Repository openethereum/openethereum, pull requests merged in 2018-03, with the labels that each got.

#8019 bump tiny-keccak
  Cargo.lock
Labels: A8-looksgood, M4-core

#7739 SecretStore: ECDSA session for cases when 2*t < N
  secret_store/src/key_server.rs
  secret_store/src/key_server_cluster/admin_sessions/key_version_negotiation_session.rs
  secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs
  secret_store/src/key_server_cluster/client_sessions/generation_session.rs
  secret_store/src/key_server_cluster/client_sessions/mod.rs
  secret_store/src/key_server_cluster/client_sessions/signing_session_ecdsa.rs
  secret_store/src/key_server_cluster/client_sessions/signing_session_schnorr.rs
  secret_store/src/key_server_cluster/cluster.rs
  secret_store/src/key_server_cluster/cluster_sessions.rs
  secret_store/src/key_server_cluster/cluster_sessions_creator.rs
  secret_store/src/key_server_cluster/io/message.rs
  secret_store/src/key_server_cluster/jobs/mod.rs
  secret_store/src/key_server_cluster/jobs/signing_job_ecdsa.rs
  secret_store/src/key_server_cluster/jobs/signing_job_schnorr.rs
  secret_store/src/key_server_cluster/math.rs
  secret_store/src/key_server_cluster/message.rs
  secret_store/src/key_server_cluster/mod.rs
  secret_store/src/listener/http_listener.rs
  secret_store/src/listener/mod.rs
  secret_store/src/traits.rs
Labels: A8-looksgood, M4-core

#7864 SecretStore: secretstore_generateDocumentKey RPC
  rpc/src/v1/helpers/secretstore.rs
  rpc/src/v1/impls/secretstore.rs
  rpc/src/v1/tests/mocked/secretstore.rs
  rpc/src/v1/traits/secretstore.rs
  rpc/src/v1/types/mod.rs
  rpc/src/v1/types/secretstore.rs
Labels: A8-looksgood, M6-rpcapi

#8024 Remove all redux dependencies from the signers
  Cargo.lock
  dapps/ui/Cargo.toml
Labels: A8-looksgood, M7-ui

#7968 CI: Fix cargo cache
  scripts/gitlab-build.sh
Labels: B0-patch, M1-ci, P5-sometimesoon

#8026 fixed ethstore sign
  ethstore/cli/src/main.rs
Labels: A8-looksgood, B0-patch, M4-core

#8031 fixed parsing ethash seals and verify_block_undordered
  ethcore/src/ethereum/ethash.rs
Labels: A8-looksgood, B0-patch, M4-core

#8022 Make 1.10 beta
  scripts/gitlab-build.sh
  util/version/Cargo.toml
Labels: A2-insubstantial, M2-installer

#8030 Drop built-in dapps for stable (binary size)
  js/package-lock.json
  js/src/Dapps/blacklist.js
  js/src/Dapps/dapps.js
  js/webpack/app.js
Labels: A8-backport, A8-looksgood, M7-ui

#8023 Make 1.9 stable
  Cargo.lock
  Cargo.toml
  mac/Parity.pkgproj
  nsis/installer.nsi
  scripts/gitlab-build.sh
  util/Cargo.toml
  util/version/Cargo.toml
  util/version/src/lib.rs
Labels: A2-insubstantial, M2-installer

#8034 Extract the hard dependency on rocksdb from the light client
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/light/src/client/mod.rs
  ethcore/light/src/client/service.rs
  ethcore/light/src/lib.rs
  ethcore/src/client/test_client.rs
  ethcore/src/lib.rs
  parity/blockchain.rs
  parity/run.rs
  sync/src/light_sync/tests/test_net.rs
Labels: A8-looksgood, M4-core

#8032 fix for verify_block_basic crashing on invalid transaction rlp
  ethcore/src/verification/verification.rs
Labels: A8-looksgood, B0-patch, M4-core

#8017 Add changelog for 1.8.11 stable and 1.9.4 beta
  CHANGELOG.md
  docs/CHANGELOG-1.8.md
Labels: A0-pleasereview, A2-insubstantial, M3-docs, P2-asap

#8035 Accept parity origin on websockets
  parity/cli/mod.rs
  parity/configuration.rs
  parity/rpc.rs
Labels: A0-pleasereview, M4-core

#8012 Fixed broken link in README
  README.md
Labels: A2-insubstantial, A8-looksgood, M3-docs, P2-asap

#8021 Bump master to 1.11.0
  Cargo.lock
  Cargo.toml
  dapps/Cargo.toml
  dapps/ui/Cargo.toml
  devtools/Cargo.toml
  ethash/Cargo.toml
  ethcore/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/node_filter/Cargo.toml
  evmjit/Cargo.toml
  hash-fetch/Cargo.toml
  hw/Cargo.toml
  ipfs/Cargo.toml
  logger/Cargo.toml
  mac/Parity.pkgproj
  mac/Parity/Info.plist
  miner/Cargo.toml
  nsis/installer.nsi
  price-info/Cargo.toml
  rpc/Cargo.toml
  scripts/gitlab-build.sh
  stratum/Cargo.toml
  sync/Cargo.toml
  transaction-pool/Cargo.toml
  updater/Cargo.toml
  util/io/Cargo.toml
  util/network/Cargo.toml
  util/version/Cargo.toml
Labels: A2-insubstantial, A8-looksgood, M2-installer, P2-asap

#8025 prelude to the block module cleanup
  ethcore/src/block.rs
  ethcore/src/miner/miner.rs
  ethcore/src/tests/helpers.rs
  ethcore/src/tests/trace.rs
Labels: A8-looksgood, M4-core

#8052 fix cache & snapcraft CI build
  .gitlab-ci.yml
Labels: A8-looksgood, B0-patch, M1-ci

#8051 Update refs to shell
  Cargo.lock
  dapps/ui/Cargo.toml
Labels: A8-looksgood, M7-ui

#8048 Abstract devp2p
  Cargo.lock
  ethcore/light/src/net/context.rs
  ethcore/light/src/net/mod.rs
  ethcore/node_filter/Cargo.toml
  ethcore/node_filter/src/lib.rs
  sync/Cargo.toml
  sync/src/api.rs
  sync/src/lib.rs
  sync/src/sync_io.rs
  util/network-devp2p/Cargo.toml
  util/network-devp2p/src/connection.rs
  util/network-devp2p/src/connection_filter.rs
  util/network-devp2p/src/discovery.rs
  util/network-devp2p/src/handshake.rs
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/ip_utils.rs
  util/network-devp2p/src/lib.rs
  util/network-devp2p/src/node_table.rs
  util/network-devp2p/src/service.rs
  util/network-devp2p/src/session.rs
  util/network-devp2p/src/stats.rs
  util/network-devp2p/tests/tests.rs
  util/network/Cargo.toml
  util/network/src/lib.rs
  whisper/src/net/mod.rs
Labels: A8-looksgood, M4-core

#8058 [Stable] Backports
  ethcore/src/ethereum/ethash.rs
  ethcore/src/verification/verification.rs
Labels: A8-backport, M4-core

#8056 make patricia-trie more idiomatic and remove redundant code
  util/patricia_trie/benches/trie.rs
  util/patricia_trie/src/node.rs
  util/patricia_trie/src/triedb.rs
  util/patricia_trie/src/triedbmut.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8054 make blockchain functions more idiomatic
  ethcore/src/blockchain/blockchain.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core

#8059 updater: apply exponential backoff after download failure
  updater/src/updater.rs
Labels: A8-looksgood, B0-patch, M4-core, P2-asap

#8067 Max code size on Kovan
  ethcore/res/ethereum/byzantium_test.json
  ethcore/res/ethereum/constantinople_test.json
  ethcore/res/ethereum/eip150_test.json
  ethcore/res/ethereum/eip161_test.json
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/mcip3_test.json
  ethcore/res/ethereum/mcip6_byz.json
  ethcore/res/ethereum/musicoin.json
  ethcore/res/ethereum/ropsten.json
  ethcore/res/ethereum/transition_test.json
  ethcore/src/machine.rs
  ethcore/src/spec/spec.rs
  json/src/spec/params.rs
Labels: A8-looksgood, B0-patch, M4-core

#8060 Limit incoming connections.
  util/network-devp2p/src/host.rs
Labels: A8-looksgood, B0-patch, M4-core

#8076 [ethkey] Unify debug/display for Address/Public/Secret
  ethkey/cli/src/main.rs
  ethkey/src/secret.rs
Labels: A8-looksgood, M4-core

#8057 Add Kovan WASM activation blocknumber
  ethcore/res/ethereum/kovan.json
Labels: A0-pleasereview, B0-patch, M4-core, P2-asap

#8042 Echo back the message hash of a ping in the pong request
  util/network-devp2p/src/discovery.rs
  util/network-devp2p/src/node_table.rs
Labels: A8-looksgood, B0-patch, M4-core

#7970 WASM libraries bump
  Cargo.lock
  ethcore/vm/src/schedule.rs
  ethcore/wasm/Cargo.toml
  ethcore/wasm/src/env.rs
  ethcore/wasm/src/lib.rs
  ethcore/wasm/src/parser.rs
  ethcore/wasm/src/runtime.rs
Labels: A8-looksgood, B0-patch, M4-core, P0-dropeverything

#8084 WASM: Add some DOS protection
  ethcore/wasm/src/runtime.rs
Labels: A0-pleasereview, B0-patch, M4-core

#8086 ethcore test helpers cleanup
  ethcore/src/block.rs
  ethcore/src/blockchain/blockchain.rs
  ethcore/src/client/client.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/basic_authority.rs
  ethcore/src/engines/instant_seal.rs
  ethcore/src/engines/tendermint/mod.rs
  ethcore/src/ethereum/ethash.rs
  ethcore/src/ethereum/mod.rs
  ethcore/src/executive.rs
  ethcore/src/externalities.rs
  ethcore/src/json_tests/executive.rs
  ethcore/src/machine.rs
  ethcore/src/service.rs
  ethcore/src/snapshot/service.rs
  ethcore/src/state/mod.rs
  ethcore/src/state_db.rs
  ethcore/src/tests/client.rs
  ethcore/src/tests/evm.rs
  ethcore/src/tests/helpers.rs
  ethcore/src/tests/trace.rs
  ethcore/src/verification/queue/mod.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core

#8089 ethcore-service
  Cargo.lock
  Cargo.toml
  ethcore/light/src/client/mod.rs
  ethcore/light/src/client/service.rs
  ethcore/service/Cargo.toml
  ethcore/service/src/lib.rs
  ethcore/service/src/service.rs
  ethcore/src/client/client.rs
  ethcore/src/client/io_message.rs
  ethcore/src/client/mod.rs
  ethcore/src/lib.rs
  ethcore/src/snapshot/service.rs
  ethcore/src/snapshot/watcher.rs
  ethcore/src/verification/queue/mod.rs
  local-store/src/lib.rs
  parity/blockchain.rs
  parity/informant.rs
  parity/light_helpers/queue_cull.rs
  parity/main.rs
  parity/run.rs
  parity/snapshot.rs
  sync/src/tests/consensus.rs
Labels: A0-pleasereview, M4-core

#7964 Additional data in EVMTestClient
  ethcore/src/client/evm_test_client.rs
  ethcore/src/json_tests/state.rs
  evmbin/src/info.rs
Labels: A8-looksgood, M4-core

#8102 Fix Cargo.lock not parsable
  Cargo.lock
Labels: A0-pleasereview

#8093 [stable] Optimize JS build
  js/package-lock.json
  js/package.json
  js/scripts/push-cargo.sh
  js/webpack/app.js
  js/webpack/shared.js
Labels: A8-looksgood, B0-patch, M7-ui

#8103 Replace std::env::temp_dir with tempdir in tests
  Cargo.lock
  ethash/Cargo.toml
  ethash/src/compute.rs
  ethash/src/lib.rs
  ethcore/node_filter/Cargo.toml
  ethcore/node_filter/src/lib.rs
  ethcore/src/engines/basic_authority.rs
  ethcore/src/ethereum/ethash.rs
  ethcore/src/json_tests/difficulty.rs
  ethcore/src/snapshot/tests/proof_of_authority.rs
  ethcore/src/spec/spec.rs
  ethcore/src/tx_filter.rs
  evmbin/Cargo.toml
  evmbin/src/info.rs
  evmbin/src/main.rs
Labels: A8-looksgood

#8101 Fix comment for gas extern in Wasm runtime
  ethcore/wasm/src/runtime.rs
Labels: A8-looksgood, M4-core

#8100 Remove the time dependency where possible
  Cargo.lock
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/light/src/cache.rs
  ethcore/light/src/client/header_chain.rs
  ethcore/light/src/client/service.rs
  ethcore/light/src/lib.rs
  ethcore/light/src/net/load_timer.rs
  ethcore/light/src/net/mod.rs
  ethcore/light/src/net/request_credits.rs
  ethcore/light/src/net/request_set.rs
  ethcore/light/src/net/tests/mod.rs
  ethcore/light/src/on_demand/request.rs
  ethcore/light/src/on_demand/tests.rs
  ethcore/src/client/client.rs
  ethcore/src/engines/tendermint/params.rs
  ethcore/src/engines/transition.rs
  ethcore/src/header.rs
  ethcore/src/lib.rs
  ethcore/src/verification/verification.rs
  parity/blockchain.rs
  parity/main.rs
  parity/run.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/tests/mocked/eth.rs
  sync/Cargo.toml
  sync/src/chain.rs
  sync/src/lib.rs
  sync/src/light_sync/tests/test_net.rs
  util/network-devp2p/Cargo.toml
  util/network-devp2p/src/discovery.rs
  util/network-devp2p/src/lib.rs
  util/network-devp2p/src/session.rs
  util/trace-time/Cargo.toml
  util/trace-time/src/lib.rs
  whisper/Cargo.toml
  whisper/src/lib.rs
  whisper/src/message.rs
Labels: A8-looksgood, M4-core

#8104 WASM: Some more dos protection
  ethcore/vm/src/schedule.rs
  ethcore/wasm/src/lib.rs
  ethcore/wasm/src/runtime.rs
  ethcore/wasm/src/tests.rs
Labels: A8-looksgood, B0-patch, M4-core

#8099 Replace reqwest with hyper
  Cargo.lock
  dapps/src/apps/fetcher/installers.rs
  dapps/src/apps/fetcher/mod.rs
  dapps/src/apps/mod.rs
  dapps/src/handlers/fetch.rs
  dapps/src/tests/helpers/fetch.rs
  dapps/src/tests/helpers/mod.rs
  dapps/src/web.rs
  ethcore/Cargo.toml
  ethcore/src/lib.rs
  ethcore/src/miner/miner.rs
  hash-fetch/Cargo.toml
  hash-fetch/src/client.rs
  hash-fetch/src/lib.rs
  parity/configuration.rs
  parity/dapps.rs
  parity/params.rs
  parity/rpc_apis.rs
  parity/run.rs
  price-info/Cargo.toml
  price-info/src/lib.rs
  rpc/src/v1/impls/light/parity_set.rs
  rpc/src/v1/impls/parity_set.rs
  rpc/src/v1/tests/helpers/fetch.rs
  rpc/src/v1/tests/mocked/parity_set.rs
  updater/src/updater.rs
  util/fetch/Cargo.toml
  util/fetch/src/client.rs
  util/fetch/src/lib.rs
Labels: A6-mustntgrumble, M4-core

#8113 Const time comparison
  Cargo.lock
  ethcrypto/Cargo.toml
  ethcrypto/src/lib.rs
  ethstore/Cargo.toml
  ethstore/src/account/crypto.rs
  ethstore/src/lib.rs
Labels: A8-looksgood

#8098 fix trace filter returning unrelated reward calls,
  ethcore/src/trace/types/filter.rs
Labels: A8-looksgood, B0-patch, M4-core

#8118 Disable link-dead-code in code coverage CI build
  scripts/cov.sh
Labels: A0-pleasereview, M1-ci

#8047 structured rlp encoding in journaldb
  util/journaldb/src/archivedb.rs
  util/journaldb/src/earlymergedb.rs
  util/journaldb/src/lib.rs
  util/journaldb/src/overlaydb.rs
  util/journaldb/src/overlayrecentdb.rs
  util/journaldb/src/refcounteddb.rs
  util/journaldb/src/util.rs
Labels: A0-pleasereview, M4-core

#8121 Trigger js build.
  js-old/scripts/test.js
  js/scripts/test.js
Labels: A2-insubstantial, M4-core

#8122 Fix comment for fn gas() in wasm/runtime
  ethcore/wasm/src/runtime.rs
Labels: A2-insubstantial, M4-core

#8125 secret_store: use `ecies::encrypt`/`ecies::decrypt`.
  secret_store/src/key_server_cluster/io/message.rs
Labels: A8-looksgood, M4-core

#8124 fix typo
  util/network/src/lib.rs
Labels: A2-insubstantial

#8126 Remove `ethcrypto::{en,de}crypt_single_message`.
  ethcrypto/src/lib.rs
Labels: A8-looksgood, M4-core

#8130 explicitly mention pruning_history uses RAM, Fixes #8129
  parity/cli/mod.rs
Labels: A8-looksgood, M4-core

#8134 Check one step deeper if we're on release track branches
  scripts/gitlab-test.sh
Labels: A0-pleasereview, B0-patch, M1-ci

#8061 network: init discovery using healthy nodes
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/node_table.rs
Labels: A8-looksgood, B0-patch, M4-core

#8140 Check one step deeper if we're on release track branches (#8134)
  scripts/gitlab-test.sh
Labels: A8-backport, M1-ci

#8109 optional dependency on secp256k1 for ethcrypto
  ethcrypto/Cargo.toml
  ethcrypto/README.md
  ethcrypto/src/lib.rs
  ethkey/src/extended.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#7886 SecretStore: ability to identify requester via Public/Address
  secret_store/src/key_server.rs
  secret_store/src/key_server_cluster/client_sessions/decryption_session.rs
  secret_store/src/key_server_cluster/client_sessions/encryption_session.rs
  secret_store/src/key_server_cluster/client_sessions/signing_session_ecdsa.rs
  secret_store/src/key_server_cluster/client_sessions/signing_session_schnorr.rs
  secret_store/src/key_server_cluster/cluster.rs
  secret_store/src/key_server_cluster/cluster_sessions.rs
  secret_store/src/key_server_cluster/cluster_sessions_creator.rs
  secret_store/src/key_server_cluster/jobs/consensus_session.rs
  secret_store/src/key_server_cluster/jobs/key_access_job.rs
  secret_store/src/key_server_cluster/message.rs
  secret_store/src/key_server_cluster/mod.rs
  secret_store/src/serialization.rs
  secret_store/src/types/all.rs
Labels: A8-looksgood, M4-core, P5-sometimesoon

#8144 [stable] Fix scripts. Force JS rebuild.
  js-old/scripts/push-precompiled.sh
  js/scripts/push-precompiled.sh
  scripts/gitlab-test.sh
Labels: A2-insubstantial, M1-ci

#8155 fix wasmi x32 builds
  ethcore/wasm/Cargo.toml
Labels: A8-looksgood, B0-patch, M1-ci

#8105 Disable UI by default.
  parity/configuration.rs
  parity/rpc.rs
  parity/run.rs
Labels: A8-looksgood, B0-patch, B1-relnotes, M4-core

#8152 [stable] Postpone Kovan hard fork (#8137)
  ethcore/res/ethereum/kovan.json
  util/version/Cargo.toml
Labels: A8-backport, M4-core

#8160 Update parity-ui dependencies
  Cargo.lock
  dapps/ui/Cargo.toml
Labels: A2-insubstantial, A8-looksgood, B0-patch, M7-ui

#8159 rename DatabaseValueView::new to from_rlp
  util/journaldb/src/earlymergedb.rs
  util/journaldb/src/refcounteddb.rs
  util/journaldb/src/util.rs
Labels: A8-looksgood

#7887 SecretStore: store key author address in db
  secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs
  secret_store/src/key_server_cluster/admin_sessions/share_add_session.rs
  secret_store/src/key_server_cluster/client_sessions/decryption_session.rs
  secret_store/src/key_server_cluster/client_sessions/encryption_session.rs
  secret_store/src/key_server_cluster/client_sessions/generation_session.rs
  secret_store/src/key_server_cluster/client_sessions/signing_session_ecdsa.rs
  secret_store/src/key_server_cluster/client_sessions/signing_session_schnorr.rs
  secret_store/src/key_server_cluster/cluster.rs
  secret_store/src/key_server_cluster/message.rs
  secret_store/src/key_server_cluster/mod.rs
  secret_store/src/key_storage.rs
  secret_store/src/types/all.rs
Labels: A8-looksgood, M4-core, P5-sometimesoon

#8163 Some tiny modifications.
  ethcore/src/state/account.rs
  ethcore/src/state/mod.rs
  ethcore/src/state_db.rs
Labels: A2-insubstantial, A8-looksgood, M3-docs, M4-core

#8165 Update daemonize
  Cargo.lock
  Cargo.toml
Labels: A2-insubstantial, M4-core

#8167 Re-enable signer, even with no UI.
  parity/configuration.rs
  parity/rpc.rs
  parity/run.rs
  parity/signer.rs
Labels: A0-pleasereview, B0-patch, M4-core

#8168 [Beta] Backport #8167
  parity/configuration.rs
  parity/rpc.rs
  parity/run.rs
  parity/signer.rs
Labels: A8-backport, M4-core

#8171 WASM: Bump libs
  Cargo.lock
  ethcore/wasm/Cargo.toml
Labels: A2-insubstantial, B0-patch, M4-core

#8166 Handle rlp decoding Result in patricia trie
  util/patricia_trie/src/lookup.rs
  util/patricia_trie/src/node.rs
  util/patricia_trie/src/triedb.rs
  util/patricia_trie/src/triedbmut.rs
Labels: A8-looksgood, M4-core

#8176 Avoid allocations when computing triehash.
  Cargo.lock
  util/hashdb/Cargo.toml
  util/kvdb-rocksdb/Cargo.toml
  util/kvdb/Cargo.toml
  util/memorydb/Cargo.toml
  util/patricia_trie/Cargo.toml
  util/rlp/Cargo.toml
  util/rlp_compress/Cargo.toml
  util/triehash/Cargo.toml
  util/triehash/src/lib.rs
Labels: A8-looksgood, M4-core

#8189 Ethkey-cli `USAGE` non-pub
  ethkey/cli/src/main.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core

#8199 Returns number of topcis to take fr..
  ethcore/evm/src/instructions.rs
Labels: A4-clasignoffneeded, A8-looksgood

#8175 Update Changelogs
  CHANGELOG.md
  docs/CHANGELOG-1.8.md
  docs/CHANGELOG-1.9.md
Labels: A0-pleasereview, A2-insubstantial, M3-docs

#8202 Browser UI deprecation and Parity UI introduction
  README.md
Labels: A2-insubstantial, M3-docs

#8182 Updated jsonrpc to include latest backports (1.9)
  Cargo.lock
Labels: A4-awaitingci, A8-looksgood, M6-rpcapi

#8181 Updated jsonrpc to include latest backports (beta)
  Cargo.lock
Labels: A8-looksgood, M6-rpcapi

#8164 Change name Wallet -> UI
  parity/run.rs
Labels: A2-insubstantial, A8-looksgood, B0-patch

#8203 Update hyper to 0.11.24
  Cargo.lock
Labels: A8-backport, M6-rpcapi

#8180 Updated jsonrpc to point to the 1.11 branch
  Cargo.lock
  Cargo.toml
  dapps/Cargo.toml
  ipfs/Cargo.toml
  rpc/Cargo.toml
  rpc_client/Cargo.toml
  stratum/Cargo.toml
  whisper/Cargo.toml
Labels: A8-looksgood, M6-rpcapi

#8209 Bump wasmi and parity-wasm versions
  Cargo.lock
  ethcore/wasm/Cargo.toml
  ethcore/wasm/run/src/runner.rs
  ethcore/wasm/src/lib.rs
Labels: A2-insubstantial, B0-patch, M4-core

#8219 Stable backports (WASM libraries bump)
  Cargo.lock
  ethcore/wasm/Cargo.toml
  ethcore/wasm/run/src/runner.rs
  ethcore/wasm/src/lib.rs
Labels: A8-backport, M4-core

#8220 Beta backprots (WASM libs)
  Cargo.lock
  ethcore/wasm/Cargo.toml
  ethcore/wasm/run/src/runner.rs
  ethcore/wasm/src/lib.rs
Labels: A8-backport, A8-looksgood, M4-core

#8223 Update some of the dependencies for WASM
  Cargo.lock
  ethcore/Cargo.toml
Labels: A8-looksgood, M4-core

#8075 Implement hardcoded sync in the light client
  ethcore/light/src/client/header_chain.rs
  ethcore/light/src/client/mod.rs
  ethcore/light/src/client/service.rs
  ethcore/res/ethereum/foundation.json
  ethcore/src/spec/mod.rs
  ethcore/src/spec/spec.rs
  json/src/spec/hardcoded_sync.rs
  json/src/spec/mod.rs
  json/src/spec/spec.rs
  json/src/uint.rs
  parity/blockchain.rs
  parity/cli/mod.rs
  parity/configuration.rs
  parity/export_hardcoded_sync.rs
  parity/main.rs
  parity/run.rs
Labels: A0-pleasereview, M4-core

#8231 node-filter does not use ChainNotify
  Cargo.lock
  ethcore/node_filter/Cargo.toml
  ethcore/node_filter/src/lib.rs
  parity/run.rs
Labels: A8-looksgood, M4-core

#8225 Remove network stats
  util/network-devp2p/src/connection.rs
  util/network-devp2p/src/handshake.rs
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/lib.rs
  util/network-devp2p/src/service.rs
  util/network-devp2p/src/session.rs
  util/network-devp2p/src/stats.rs
  util/network-devp2p/tests/tests.rs
Labels: A8-looksgood, M4-core

#8234 jsonrpc-apis, ws-apis and ipc-apis update
  parity/cli/mod.rs
Labels: A2-insubstantial, M1-ci

#8200 fixed ethcore tx_filter
  ethcore/src/tx_filter.rs
Labels: A0-pleasereview, M4-core

#8242 Update musicoin spec in line with gmc v2.6.2
  ethcore/res/ethereum/musicoin.json
Labels: A8-looksgood, B0-patch, M2-config

#8187 Add test for ethstore-cli, fixes #8027
  Cargo.lock
  ethstore/cli/Cargo.toml
  ethstore/cli/tests/cli.rs
  test.sh
Labels: A8-looksgood, M4-core

#8233 Replace all Rlp usages with UntrustedRlp except for ethcore views
  ethcore/light/src/client/header_chain.rs
  ethcore/light/src/net/request_credits.rs
  ethcore/light/src/net/tests/mod.rs
  ethcore/light/src/on_demand/request.rs
  ethcore/src/blockchain/blockchain.rs
  ethcore/src/client/test_client.rs
  ethcore/src/encoded.rs
  ethcore/src/engines/tendermint/message.rs
  ethcore/src/header.rs
  ethcore/src/state/account.rs
  ethcore/src/trace/types/flat.rs
  ethcore/src/trace/types/trace.rs
  ethcore/src/views/block.rs
  ethcore/src/views/body.rs
  ethcore/transaction/src/transaction.rs
  ethcore/types/src/receipt.rs
  ethcore/types/src/snapshot_manifest.rs
  sync/src/block_sync.rs
  sync/src/blocks.rs
  sync/src/chain.rs
  util/network-devp2p/src/connection.rs
  util/network-devp2p/src/discovery.rs
  util/network-devp2p/src/handshake.rs
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/node_table.rs
  util/network-devp2p/src/session.rs
Labels: A8-looksgood, M4-core

#8228 Warp-only sync with warp-barrier [blocknumber] flag.
  parity/cli/mod.rs
  parity/configuration.rs
  parity/run.rs
  sync/src/api.rs
  sync/src/chain.rs
  sync/src/tests/chain.rs
  sync/src/tests/snapshot.rs
  util/network-devp2p/src/host.rs
Labels: A0-pleasereview, B1-relnotes, M4-core

#8261 Fix warning about --no-hardcoded-sync being printed when it shouldn't
  parity/run.rs
Labels: A0-pleasereview, M4-core

#8252 Add missing license header for runtime.rs
  ethcore/wasm/src/runtime.rs
Labels: A2-insubstantial, A8-looksgood

#8268 Update `app_dirs` to 1.2.1
  Cargo.lock
  Cargo.toml
  util/dir/Cargo.toml
Labels: A8-looksgood, M4-core

#8280 eth_uninstallFilter should return false for non-existent filter
  rpc/src/v1/helpers/poll_manager.rs
  rpc/src/v1/impls/eth_filter.rs
Labels: A6-mustntgrumble, M4-core

#8283 Typo fix: Mode doc - RLP should be client
  ethcore/src/client/config.rs
Labels: A2-insubstantial, M4-core
