Repository openethereum/openethereum, pull requests merged in 2018-04, with the labels that each got.

#8278 use constant durations
  dapps/node-health/src/health.rs
  dapps/src/handlers/fetch.rs
  ethcore/light/src/net/mod.rs
  miner/src/external.rs
  parity/light_helpers/queue_cull.rs
  secret_store/src/key_server_cluster/client_sessions/generation_session.rs
  secret_store/src/key_server_cluster/cluster.rs
  secret_store/src/key_server_cluster/cluster_sessions.rs
  util/fetch/src/client.rs
  util/network-devp2p/src/discovery.rs
  util/network-devp2p/src/session.rs
  whisper/src/net/mod.rs
Labels: A7-looksgoodtestsfail, M4-core

#8281 Return null number for pending block in eth_getBlockByNumber
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/impls/light/eth.rs
  rpc/src/v1/types/block.rs
Labels: A8-looksgood, M6-rpcapi

#8256 Suppress TemporarilyInvalid verification warnings.
  ethcore/src/verification/queue/kind.rs
Labels: A8-looksgood, B0-patch, M4-core

#8257 Allow customization of max WS connections.
  parity/cli/mod.rs
  parity/configuration.rs
  parity/rpc.rs
  rpc/src/lib.rs
  rpc/src/tests/ws.rs
Labels: A8-looksgood, M4-core

#8287 Revert "ci: disable link-dead-code in coverage build (#8118)"
  scripts/cov.sh
Labels: A0-pleasereview, A2-insubstantial, M1-ci

#8292 Typo fix: todo with no content
  ethcore/src/client/test_client.rs
Labels: A2-insubstantial, M4-core

#8227 Remove RefCell from Header
  ethcore/light/src/on_demand/tests.rs
  ethcore/src/block.rs
  ethcore/src/blockchain/best_block.rs
  ethcore/src/blockchain/blockchain.rs
  ethcore/src/blockchain/update.rs
  ethcore/src/client/client.rs
  ethcore/src/client/test_client.rs
  ethcore/src/client/traits.rs
  ethcore/src/engines/validator_set/contract.rs
  ethcore/src/engines/validator_set/safe_contract.rs
  ethcore/src/header.rs
  ethcore/src/miner/miner.rs
  ethcore/src/snapshot/block.rs
  ethcore/src/snapshot/consensus/authority.rs
  ethcore/src/snapshot/consensus/work.rs
  ethcore/src/snapshot/mod.rs
  ethcore/src/tests/client.rs
  ethcore/src/verification/verification.rs
  rpc/src/v1/impls/eth.rs
  sync/src/chain.rs
Labels: A8-looksgood, M4-core

#8204 Allow unsafe js eval for Parity Wallet (v1)
  dapps/src/apps/mod.rs
  dapps/src/page/builtin.rs
Labels: A8-looksgood, B0-patch, M8-dapp

#8276 Cleanup Ellaism bootnodes
  ethcore/res/ethereum/ellaism.json
Labels: A2-insubstantial, M2-config

#8294 dapps-fetcher: calculate keccak in-flight while reading the response
  dapps/src/apps/fetcher/installers.rs
  util/hash/src/lib.rs
Labels: A7-looksgoodtestsfail, M4-core

#8078 Auto-updater improvements
  Cargo.lock
  ethcore/src/client/test_client.rs
  parity/cli/mod.rs
  parity/cli/tests/config.full.toml
  parity/configuration.rs
  updater/Cargo.toml
  updater/res/operations.json
  updater/src/lib.rs
  updater/src/updater.rs
  util/dir/src/lib.rs
Labels: A0-pleasereview, F6-refactor, M4-core

#8087 Honor --max-peers if --min-peers is not specified
  parity/cli/mod.rs
  parity/cli/usage.rs
  parity/configuration.rs
Labels: A8-looksgood, M2-config, M4-core

#8029 SecretStore: generating and retrieving decryption keys via service contract
  parity/cli/mod.rs
  parity/cli/tests/config.full.toml
  parity/configuration.rs
  parity/secretstore.rs
  secret_store/res/key_server_set.json
  secret_store/res/service.json
  secret_store/src/acl_storage.rs
  secret_store/src/key_server.rs
  secret_store/src/key_server_cluster/admin_sessions/key_version_negotiation_session.rs
  secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs
  secret_store/src/key_server_cluster/client_sessions/decryption_session.rs
  secret_store/src/key_server_cluster/client_sessions/encryption_session.rs
  secret_store/src/key_server_cluster/client_sessions/generation_session.rs
  secret_store/src/key_server_cluster/client_sessions/signing_session_ecdsa.rs
  secret_store/src/key_server_cluster/client_sessions/signing_session_schnorr.rs
  secret_store/src/key_server_cluster/cluster.rs
  secret_store/src/key_server_cluster/cluster_sessions.rs
  secret_store/src/key_server_cluster/jobs/consensus_session.rs
  secret_store/src/key_server_cluster/jobs/decryption_job.rs
  secret_store/src/key_server_cluster/jobs/job_session.rs
  secret_store/src/key_server_cluster/jobs/key_access_job.rs
  secret_store/src/key_server_cluster/message.rs
  secret_store/src/key_server_cluster/mod.rs
  secret_store/src/key_storage.rs
  secret_store/src/lib.rs
  secret_store/src/listener/http_listener.rs
  secret_store/src/listener/mod.rs
  secret_store/src/listener/service_contract.rs
  secret_store/src/listener/service_contract_aggregate.rs
  secret_store/src/listener/service_contract_listener.rs
  secret_store/src/traits.rs
  secret_store/src/types/all.rs
Labels: A8-looksgood, M4-core

#8298 build: fix updater rand dependency in Cargo.lock
  Cargo.lock
Labels: A2-insubstantial, A8-looksgood, M0-build

#8229 remove evmjit
  Cargo.lock
  Cargo.toml
  docker/hub/Dockerfile
  docker/ubuntu-jit/Dockerfile
  ethcore/Cargo.toml
  ethcore/evm/Cargo.toml
  ethcore/evm/src/factory.rs
  ethcore/evm/src/jit.rs
  ethcore/evm/src/lib.rs
  ethcore/evm/src/tests.rs
  ethcore/evm/src/vmtype.rs
  ethcore/src/executive.rs
  ethcore/src/lib.rs
  ethcore/src/tests/evm.rs
  evmjit/Cargo.toml
  evmjit/src/lib.rs
  parity/cli/mod.rs
  parity/cli/tests/config.full.toml
  parity/cli/tests/config.toml
  parity/configuration.rs
  scripts/cov.sh
  scripts/doc.sh
  scripts/hook.sh
  test.sh
Labels: A8-looksgood, M4-core

#8297 Include suicided accounts in state diff
  ethcore/src/state/mod.rs
Labels: A8-looksgood, B0-patch, M4-core

#8302 Ethcore now uses rayon 0.9 as a dependency (#8296)
  Cargo.lock
  ethcore/Cargo.toml
Labels: A0-pleasereview, M4-core

#8284 Cleaner binary shutdown system
  ethcore/src/client/client.rs
  parity/run.rs
Labels: A8-looksgood, M4-core

#8251 Upgrader `remove raw unwrap` and bump semver
  Cargo.lock
  Cargo.toml
  parity/upgrade.rs
  rpc/Cargo.toml
  sync/Cargo.toml
  updater/Cargo.toml
  util/version/Cargo.toml
Labels: A8-looksgood, M4-core

#8304 Ethcore now uses Rayon 1.0 as a dependency (#8296)
  Cargo.lock
  ethcore/Cargo.toml
Labels: A8-looksgood, M4-core

#8132 Backport #8099 to beta
  Cargo.lock
  dapps/src/apps/fetcher/installers.rs
  dapps/src/apps/fetcher/mod.rs
  dapps/src/apps/mod.rs
  dapps/src/handlers/fetch.rs
  dapps/src/tests/helpers/fetch.rs
  dapps/src/tests/helpers/mod.rs
  dapps/src/web.rs
  ethcore/Cargo.toml
  ethcore/src/lib.rs
  ethcore/src/miner/miner.rs
  hash-fetch/Cargo.toml
  hash-fetch/src/client.rs
  hash-fetch/src/lib.rs
  parity/configuration.rs
  parity/dapps.rs
  parity/params.rs
  parity/rpc_apis.rs
  parity/run.rs
  price-info/Cargo.toml
  price-info/src/lib.rs
  rpc/src/v1/impls/light/parity_set.rs
  rpc/src/v1/impls/parity_set.rs
  rpc/src/v1/tests/helpers/fetch.rs
  rpc/src/v1/tests/mocked/parity_set.rs
  updater/src/updater.rs
  util/fetch/Cargo.toml
  util/fetch/src/client.rs
  util/fetch/src/lib.rs
Labels: A8-backport, M4-core

#8249 Addressing grumbles in PrivateTransactions
  Cargo.lock
  dapps/src/handlers/fetch.rs
  ethcore/Cargo.toml
  ethcore/private-tx/src/encryptor.rs
  ethcore/private-tx/src/lib.rs
  ethcore/private-tx/src/private_transactions.rs
  ethcore/src/client/chain_notify.rs
  ethcore/src/client/client.rs
  ethcore/src/test_helpers.rs
  hash-fetch/src/client.rs
  parity/run.rs
  price-info/src/lib.rs
  rpc/src/v1/impls/light/parity_set.rs
  rpc/src/v1/impls/parity_set.rs
  rpc/src/v1/impls/private.rs
  sync/src/api.rs
  sync/src/tests/helpers.rs
  util/fetch/src/client.rs
Labels: A8-looksgood, M4-core

#8285 Update some dependencies
  Cargo.lock
Labels: A8-looksgood, M4-core

#8295 Add Easthub in chain config
  ethcore/res/ethereum/easthub.json
  ethcore/src/ethereum/mod.rs
  parity/cli/mod.rs
  parity/params.rs
Labels: A8-looksgood, M2-config

#8307 Validate if gas limit is not zero
  ethcore/src/machine.rs
  json/src/spec/genesis.rs
Labels: A8-looksgood, M4-core

#8205 [beta] Change name Wallet -> UI (#8164)
  parity/run.rs
Labels: A2-insubstantial, A8-backport, A8-looksgood

#8305 Decouple timestamp open-block-assignment/verification to Engine
  ethcore/src/block.rs
  ethcore/src/client/test_client.rs
  ethcore/src/engines/instant_seal.rs
  ethcore/src/engines/mod.rs
  ethcore/src/header.rs
  ethcore/src/verification/verification.rs
Labels: A8-looksgood, M4-core

#8310 bump proc macro deps
  Cargo.lock
  util/rlp_derive/Cargo.toml
Labels: A8-looksgood, M4-core, M5-dependencies

#8300 Remove InvalidParentHash in favor of assert!
  ethcore/src/error.rs
  ethcore/src/verification/verification.rs
Labels: A8-looksgood, M4-core

#8308 Use associated type M::Error instead of Error
  ethcore/src/engines/mod.rs
Labels: A8-looksgood, M4-core

#8036 Tweaks and add a Dockerfile to compile for Android
  Cargo.lock
  Cargo.toml
  docker/android/Dockerfile
  docker/android/cargo-config.toml
  docker/android/libudev.patch
  ethcore/wasm/Cargo.toml
  parity/url.rs
  util/network-devp2p/src/ip_utils.rs
Labels: A0-pleasereview, A3-inprogress, M4-core

#8309 Read registry_address from block with REQUEST_CONFIRMATIONS_REQUIRED
  secret_store/src/helpers.rs
  secret_store/src/key_server_set.rs
  secret_store/src/lib.rs
  secret_store/src/listener/service_contract.rs
Labels: A8-looksgood, M4-core

#8326 Fix the JSONRPC API not running with the light client
  parity/run.rs
Labels: A8-looksgood, M4-core, M6-rpcapi, P2-asap

#8334 remove the clone operation of code_cache
  ethcore/src/state/account.rs
Labels: A8-looksgood, M4-core

#8318 final private tx pr
  parity/cli/mod.rs
  parity/cli/tests/config.full.toml
  parity/configuration.rs
  parity/run.rs
  sync/src/private_tx.rs
Labels: A8-looksgood, M4-core

#8324 replace_home for password_files, reserved_peers and log_file
  parity/configuration.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#8201 Whisper cli
  Cargo.lock
  Cargo.toml
  whisper/cli/Cargo.toml
  whisper/cli/src/main.rs
  whisper/src/rpc/filter.rs
Labels: A8-looksgood, M4-core

#8173 SecretStore: get rid of engine.signer dependency
  Cargo.lock
  parity/run.rs
  parity/secretstore.rs
  secret_store/Cargo.toml
  secret_store/src/acl_storage.rs
  secret_store/src/key_server_cluster/client_sessions/generation_session.rs
  secret_store/src/key_server_cluster/client_sessions/signing_session_schnorr.rs
  secret_store/src/key_server_cluster/cluster.rs
  secret_store/src/key_server_set.rs
  secret_store/src/lib.rs
  secret_store/src/listener/service_contract.rs
  secret_store/src/listener/service_contract_listener.rs
  secret_store/src/trusted_client.rs
Labels: A8-looksgood, M4-core

#8338 ethcore-stratum crate moved to ethcore directory
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/stratum/Cargo.toml
  ethcore/stratum/src/lib.rs
  ethcore/stratum/src/traits.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8341 rpc, eth_filter: return error if the filter id does not exist
  rpc/src/v1/helpers/errors.rs
  rpc/src/v1/impls/eth_filter.rs
Labels: A0-pleasereview, M6-rpcapi

#8346 [beta] Backports
  Cargo.lock
  dapps/Cargo.toml
  dapps/src/apps/mod.rs
  dapps/src/lib.rs
  dapps/src/page/builtin.rs
  dapps/src/router.rs
  dapps/src/tests/helpers/mod.rs
  dapps/ui-deprecation/Cargo.toml
  dapps/ui-deprecation/build.rs
  dapps/ui-deprecation/build/index.html
  dapps/ui-deprecation/src/lib.rs
  dapps/ui-deprecation/src/lib.rs.in
  ethcore/res/ethereum/musicoin.json
  ethcore/src/state/mod.rs
  ethcore/src/verification/queue/kind.rs
  parity/cli/mod.rs
  parity/configuration.rs
  parity/dapps.rs
  parity/rpc.rs
  parity/run.rs
  sync/src/api.rs
  sync/src/chain.rs
  sync/src/tests/chain.rs
  sync/src/tests/snapshot.rs
  util/network/src/host.rs
Labels: A8-backport, M4-core

#8352 [stable] Backports
  ethcore/res/ethereum/musicoin.json
  ethcore/src/state/mod.rs
  ethcore/src/verification/queue/kind.rs
  parity/configuration.rs
  util/version/Cargo.toml
Labels: A8-backport, M4-core

#8335 Use hyper 0.11 in ethcore-miner and improvements in parity-reactor
  Cargo.lock
  dapps/node-health/src/health.rs
  dapps/src/tests/helpers/fetch.rs
  ethcore/private-tx/Cargo.toml
  ethcore/private-tx/src/encryptor.rs
  ethcore/private-tx/src/lib.rs
  ethcore/src/miner/miner.rs
  hash-fetch/src/client.rs
  miner/Cargo.toml
  miner/src/work_notify.rs
  parity/configuration.rs
  parity/light_helpers/queue_cull.rs
  parity/run.rs
  price-info/src/lib.rs
  rpc/src/v1/tests/eth.rs
  rpc/src/v1/tests/helpers/fetch.rs
  util/fetch/Cargo.toml
  util/fetch/src/client.rs
  util/fetch/src/lib.rs
  util/reactor/src/lib.rs
Labels: A8-looksgood, M4-core, M5-dependencies

#8151 SecretStore: having <t+1 nodes with key shares now does not abort ServersSetChangeSession
  secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs
  secret_store/src/key_server_cluster/admin_sessions/share_change_session.rs
Labels: A8-looksgood, M4-core

#8340 ethcrypto renamed to ethcore-crypto and moved to ethcore dir
  Cargo.lock
  ethcore/crypto/Cargo.toml
  ethcore/crypto/README.md
  ethcore/crypto/src/lib.rs
  ethcore/private-tx/Cargo.toml
  ethcore/private-tx/src/encryptor.rs
  ethcore/private-tx/src/lib.rs
  ethstore/Cargo.toml
  ethstore/src/lib.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  secret_store/Cargo.toml
  secret_store/src/key_server.rs
  secret_store/src/key_server_cluster/client_sessions/decryption_session.rs
  secret_store/src/key_server_cluster/io/handshake.rs
  secret_store/src/key_server_cluster/io/message.rs
  secret_store/src/key_server_cluster/jobs/decryption_job.rs
  secret_store/src/key_server_cluster/mod.rs
  secret_store/src/lib.rs
  secret_store/src/node_key_pair.rs
  util/network-devp2p/Cargo.toml
  util/network-devp2p/src/lib.rs
  util/network/Cargo.toml
  util/network/src/lib.rs
  whisper/Cargo.toml
  whisper/src/lib.rs
  whisper/src/rpc/crypto.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8355 bump app_dirs, fixes #8315
  Cargo.lock
Labels: A0-pleasereview, A8-backport

#8262 Enable UI by default, but only display deprecation notice
  Cargo.lock
  dapps/Cargo.toml
  dapps/src/apps/mod.rs
  dapps/src/lib.rs
  dapps/src/router.rs
  dapps/src/tests/helpers/mod.rs
  dapps/ui-deprecation/Cargo.toml
  dapps/ui-deprecation/build.rs
  dapps/ui-deprecation/build/index.html
  dapps/ui-deprecation/src/lib.rs
  dapps/ui-deprecation/src/lib.rs.in
  parity/configuration.rs
  parity/dapps.rs
  parity/rpc.rs
  parity/run.rs
Labels: A0-pleasereview, B0-patchthis, M4-core, M7-ui

#8359 Use async hyper server in secret_store and upgrade igd
  Cargo.lock
  secret_store/Cargo.toml
  secret_store/src/lib.rs
  secret_store/src/listener/http_listener.rs
  secret_store/src/types/all.rs
  util/network-devp2p/Cargo.toml
Labels: A8-looksgood, M4-core, M5-dependencies

#8364 bump snappy and ring, use single rayon version
  Cargo.lock
Labels: A0-pleasereview, A2-insubstantial, M4-core

#8363 util `fake-fetch`
  Cargo.lock
  Cargo.toml
  hash-fetch/Cargo.toml
  hash-fetch/src/client.rs
  hash-fetch/src/lib.rs
  price-info/Cargo.toml
  price-info/src/lib.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  rpc/src/v1/tests/helpers/mod.rs
  rpc/src/v1/tests/mocked/parity_set.rs
  util/fake-fetch/Cargo.toml
  util/fake-fetch/src/lib.rs
Labels: A3-inprogress, A8-looksgood, M4-core

#8362 Dev chain - increase gasLimit to 8'000'000
  ethcore/res/instant_seal.json
Labels: B1-releasenotes, F8-enhancement, M2-config, P7-nicetohave, Q0-trivial

#8365 use atty instead of isatty
  Cargo.lock
  Cargo.toml
  logger/Cargo.toml
  logger/src/lib.rs
  parity/informant.rs
  parity/main.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core

#8356 Add `util/mem` to zero out memory on drop.
  Cargo.lock
  Cargo.toml
  ethcore/src/snapshot/tests/proof_of_authority.rs
  ethcore/transaction/src/transaction.rs
  ethkey/Cargo.toml
  ethkey/src/extended.rs
  ethkey/src/lib.rs
  ethkey/src/secret.rs
  rpc/src/v1/tests/mocked/eth.rs
  rpc/src/v1/tests/mocked/signing.rs
  secret_store/src/key_server.rs
  secret_store/src/key_server_cluster/client_sessions/decryption_session.rs
  secret_store/src/key_server_cluster/math.rs
  util/mem/Cargo.toml
  util/mem/src/lib.rs
  whisper/Cargo.toml
  whisper/src/lib.rs
  whisper/src/rpc/crypto.rs
  whisper/src/rpc/key_store.rs
  whisper/src/rpc/mod.rs
Labels: A5-grumble, A8-looksgood, M4-core

#8368 No hardcoded client name
  rpc/src/v1/impls/web3.rs
  rpc/src/v1/tests/mocked/web3.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8380 Fix config test by adding no-hardcodec-sync
  parity/cli/tests/config.full.toml
Labels: A2-insubstantial, A8-looksgood, M4-core

#8382 ci: fix change detection in master builds
  scripts/gitlab-test.sh
Labels: A2-insubstantial, M1-ci

#8385 handle queue import errors a bit more gracefully
  ethcore/sync/src/light_sync/mod.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#8350 Bump beta to 1.10.1
  Cargo.lock
  Cargo.toml
  mac/Parity.pkgproj
  nsis/installer.nsi
  util/version/Cargo.toml
Labels: A8-backport, M2-installer, M4-core

#8402 Readme `Clarify that Windows need perl and yasm`
  README.md
Labels: A2-insubstantial, M3-docs

#8371 Unify and limit rocksdb dependency places
  Cargo.lock
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/migrations/Cargo.toml
  ethcore/src/lib.rs
  ethcore/src/snapshot/service.rs
  ethcore/src/snapshot/tests/service.rs
  ethcore/src/test_helpers.rs
  ethcore/src/test_helpers_internal.rs
  parity/blockchain.rs
  parity/db/mod.rs
  parity/db/rocksdb/helpers.rs
  parity/db/rocksdb/migration.rs
  parity/db/rocksdb/mod.rs
  parity/export_hardcoded_sync.rs
  parity/helpers.rs
  parity/main.rs
  parity/run.rs
  parity/secretstore.rs
  parity/snapshot.rs
  secret_store/Cargo.toml
  secret_store/src/key_storage.rs
  secret_store/src/lib.rs
  secret_store/src/types/all.rs
  util/migration-rocksdb/Cargo.toml
  util/migration-rocksdb/src/lib.rs
  util/migration-rocksdb/tests/tests.rs
Labels: A8-looksgood, F6-refactor, M4-core

#8373 Use tokio::spawn in secret_store listener and fix Uri
  secret_store/src/listener/http_listener.rs
Labels: A8-looksgood, M4-core

#8367 remove Tendermint extra_info due to seal inconsistencies
  ethcore/src/engines/tendermint/mod.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#8322 More code refactoring to integrate Duration
  dapps/src/tests/helpers/fetch.rs
  ethcore/light/src/net/load_timer.rs
  ethcore/light/src/net/mod.rs
  ethcore/light/src/net/request_credits.rs
  ethcore/service/src/service.rs
  ethcore/src/account_provider/mod.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/transition.rs
  ethcore/src/error.rs
  ethcore/src/verification/verification.rs
  ethcore/sync/src/api.rs
  ethcore/sync/src/chain.rs
  ethcore/sync/src/light_sync/mod.rs
  local-store/src/lib.rs
  parity/informant.rs
  parity/light_helpers/queue_cull.rs
  rpc/src/v1/impls/personal.rs
  util/io/src/lib.rs
  util/io/src/service.rs
  util/network-devp2p/src/connection.rs
  util/network-devp2p/src/handshake.rs
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/lib.rs
  util/network-devp2p/src/session.rs
  util/network-devp2p/tests/tests.rs
  util/network/src/lib.rs
  util/unexpected/src/lib.rs
  whisper/src/net/mod.rs
Labels: A0-pleasereview, F6-refactor, M4-core

#8408 tokio-core v0.1.16 -> v0.1.17
  Cargo.lock
Labels: A8-looksgood, M5-dependencies

#8413 Fix an obsolete TODO where `miner` is alias of `author`
  rpc/src/v1/types/block.rs
Labels: A2-insubstantial, M4-core

#8381 update zip to 0.3
  Cargo.lock
  dapps/Cargo.toml
Labels: A8-looksgood, M4-core, M5-dependencies

#8414 Fix receipts stripping.
  ethcore/src/block.rs
  ethcore/src/client/client.rs
Labels: A8-looksgood, M4-core

#8411 Changelogs for 1.9.6 and 1.10.1
  CHANGELOG.md
  docs/CHANGELOG-1.9.md
Labels: A0-pleasereview, A2-insubstantial, M3-docs

#8386 Move ethcore::Error to error_chain
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/light/src/client/header_chain.rs
  ethcore/light/src/lib.rs
  ethcore/src/client/client.rs
  ethcore/src/client/mod.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/mod.rs
  ethcore/src/engines/tendermint/mod.rs
  ethcore/src/error.rs
  ethcore/src/ethereum/ethash.rs
  ethcore/src/executed.rs
  ethcore/src/lib.rs
  ethcore/src/miner/miner.rs
  ethcore/src/snapshot/tests/proof_of_work.rs
  ethcore/src/snapshot/tests/state.rs
  ethcore/src/verification/queue/kind.rs
  ethcore/src/verification/queue/mod.rs
  ethcore/src/verification/verification.rs
  ethcore/sync/src/block_sync.rs
  ethcore/sync/src/chain.rs
  ethcore/sync/src/light_sync/mod.rs
  ethcore/transaction/src/error.rs
  ethkey/src/error.rs
  parity/blockchain.rs
  rpc/src/v1/helpers/errors.rs
Labels: A8-looksgood, F6-refactor, M4-core

#8390 remove From::from.
  ethcore/src/executive.rs
Labels: A8-looksgood, M4-core

#8438 Use forked app_dirs crate for reverted Windows dir behavior
  Cargo.lock
  Cargo.toml
  parity/main.rs
  util/dir/Cargo.toml
Labels: A8-looksgood, M4-core

#8419 Block reward contract
  Cargo.lock
  ethcore/res/authority_round_block_reward_contract.json
  ethcore/res/contracts/block_reward.json
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/block_reward.rs
  ethcore/src/engines/mod.rs
  ethcore/src/engines/validator_set/mod.rs
  ethcore/src/spec/spec.rs
  json/src/spec/authority_round.rs
Labels: A8-looksgood, M4-core

#8439 Improve VM executor stack size estimation rules
  ethcore/src/executive.rs
Labels: A8-looksgood, M4-core

#8431 Private transactions processing error handling
  Cargo.lock
  ethcore/private-tx/src/lib.rs
  ethcore/sync/Cargo.toml
  ethcore/sync/src/lib.rs
  ethcore/sync/src/res/private_spec.json
  ethcore/sync/src/tests/consensus.rs
  ethcore/sync/src/tests/helpers.rs
  ethcore/sync/src/tests/mod.rs
  ethcore/sync/src/tests/private.rs
Labels: A6-mustntgrumble, M4-core

#8447 Update Cargo hidapi-rs dependency
  Cargo.lock
Labels: A0-pleasereview, M5-dependencies

#8454 Allow 32 bit pipelines to fail
  .gitlab-ci.yml
Labels: A2-insubstantial, B0-patchthis, M1-ci

#8452 Update wasmi
  Cargo.lock
  ethcore/wasm/Cargo.toml
Labels: A8-looksgood, B0-patchthis, M5-dependencies

#8448 Return error in case eth_call returns VM errors
  rpc/src/v1/helpers/errors.rs
  rpc/src/v1/impls/eth.rs
Labels: A8-looksgood, B1-releasenotes, M6-rpcapi

#8377 ParityShell::open `Return result`
  parity/main.rs
  parity/run.rs
  parity/url.rs
Labels: A8-looksgood, M4-core

#8456 Update Parity stable to 1.9.7 + Backports
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/wasm/Cargo.toml
  mac/Parity.pkgproj
  nsis/installer.nsi
  util/Cargo.toml
  util/version/Cargo.toml
Labels: A8-backport, M2-installer, M5-dependencies

#8455 Update Parity beta to 1.10.2 + Backports
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/wasm/Cargo.toml
  mac/Parity.pkgproj
  nsis/installer.nsi
  util/version/Cargo.toml
Labels: A8-backport, M2-installer, M5-dependencies

#8462 fix docker build
  docker/hub/Dockerfile
Labels: A2-insubstantial, B0-patchthis, M0-build, M1-ci

#8460 Add changelog for 1.9.7 and 1.10.2
  CHANGELOG.md
  docs/CHANGELOG-1.9.md
Labels: A2-insubstantial, A8-looksgood, M3-docs

#8446 Small fixes
  json/src/vm/vm.rs
Labels: A2-insubstantial, M3-docs

#8471 Use rename_all for RichBlock and RichHeader serialization
  rpc/src/v1/types/block.rs
Labels: A2-insubstantial, A8-looksgood, M6-rpcapi

#8481 Don't require write lock when fetching status.
  ethcore/sync/src/api.rs
Labels: A8-looksgood, M4-core

#8477 Bump master to 1.12
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  dapps/Cargo.toml
  dapps/ui/Cargo.toml
  devtools/Cargo.toml
  ethash/Cargo.toml
  ethcore/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/node_filter/Cargo.toml
  ethcore/stratum/Cargo.toml
  ethcore/sync/Cargo.toml
  hash-fetch/Cargo.toml
  hw/Cargo.toml
  ipfs/Cargo.toml
  logger/Cargo.toml
  mac/Parity.pkgproj
  mac/Parity/Info.plist
  miner/Cargo.toml
  nsis/installer.nsi
  price-info/Cargo.toml
  rpc/Cargo.toml
  scripts/gitlab-build.sh
  transaction-pool/Cargo.toml
  updater/Cargo.toml
  util/io/Cargo.toml
  util/network-devp2p/Cargo.toml
  util/network/Cargo.toml
  util/version/Cargo.toml
Labels: A2-insubstantial, M2-installer, M5-dependencies

#8483 Fix snap builds
  scripts/gitlab-build.sh
Labels: A2-insubstantial, B0-patchthis, M1-ci

#8489 Update hardcodedSync for Ethereum, Kovan, and Ropsten
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/ropsten.json
Labels: A2-insubstantial, B0-patchthis, M2-config

#8475 Betalize 1.11 :)
  .gitlab-ci.yml
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/ropsten.json
  scripts/gitlab-build.sh
  util/version/Cargo.toml
Labels: A2-insubstantial, A8-backport, M2-installer

#8493 Update wasmi and pwasm-utils
  Cargo.lock
  ethcore/wasm/Cargo.toml
Labels: A8-looksgood, B0-patchthis, M5-dependencies

#8497 Remove three old warp boot nodes.
  ethcore/res/ethereum/foundation.json
Labels: A2-insubstantial, M2-config

#8473 Return error if RLP size of transaction exceeds the limit
  Cargo.lock
  ethcore/src/client/client.rs
  ethcore/src/engines/mod.rs
  ethcore/src/machine.rs
  ethcore/src/miner/pool_client.rs
  ethcore/src/spec/spec.rs
  ethcore/sync/src/chain.rs
  ethcore/transaction/src/error.rs
  json/src/spec/params.rs
  miner/Cargo.toml
  miner/src/lib.rs
  miner/src/pool/client.rs
  miner/src/pool/res/big_transaction.data
  miner/src/pool/tests/client.rs
  miner/src/pool/tests/mod.rs
  miner/src/pool/tests/tx.rs
  miner/src/pool/verifier.rs
  rpc/src/v1/helpers/errors.rs
Labels: A0-pleasereview, B1-releasenotes, M4-core, M6-rpcapi

#8457 `duration_ns: u64 -> duration: Duration`
  ethcore/private-tx/src/lib.rs
  ethcore/src/client/chain_notify.rs
  ethcore/src/client/client.rs
  ethcore/src/snapshot/watcher.rs
  ethcore/sync/src/api.rs
  ethcore/sync/src/tests/helpers.rs
  parity/informant.rs
  rpc/src/v1/impls/eth_pubsub.rs
  rpc/src/v1/tests/mocked/eth_pubsub.rs
  secret_store/src/acl_storage.rs
  secret_store/src/key_server_set.rs
  secret_store/src/listener/service_contract_listener.rs
  updater/src/updater.rs
Labels: A6-mustntgrumble, M4-core

#8474 Stabilize 1.10.3
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  docker/hub/Dockerfile
  mac/Parity.pkgproj
  nsis/installer.nsi
  scripts/gitlab-build.sh
  util/version/Cargo.toml
Labels: A2-insubstantial, A8-backport, M2-installer

#8505 Remove unused dependency `bigint`
  Cargo.lock
  rpc_cli/Cargo.toml
  util/memorydb/Cargo.toml
Labels: A8-looksgood, M4-core
