Repository openethereum/openethereum, pull requests merged in 2018-09, with the labels that each got.

#9441 use kvdb-* and parity-snappy crates from crates.io
  Cargo.lock
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/node_filter/Cargo.toml
  ethcore/service/Cargo.toml
  ethcore/src/lib.rs
  ethcore/sync/Cargo.toml
  local-store/Cargo.toml
  rpc/Cargo.toml
  secret_store/Cargo.toml
  util/journaldb/Cargo.toml
  util/migration-rocksdb/Cargo.toml
  util/network-devp2p/Cargo.toml
  util/network-devp2p/src/lib.rs
  util/network/Cargo.toml
  util/network/src/lib.rs
Labels: A8-looksgood, M4-core

#9458 evmbin: escape newlines in json errors
  evmbin/src/display/json.rs
  evmbin/src/display/mod.rs
  evmbin/src/display/std_json.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9457 Fix a bug in evmbin initial_gas display
  evmbin/src/info.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9462 fix typo in bash script
  scripts/gitlab/push.sh
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M1-ci 🙉

#9385 Fix light client deadlock
  ethcore/sync/src/light_sync/mod.rs
  parity/informant.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#9467 Fixed typo
  util/io/src/service_mio.rs
Labels: A8-looksgood 🦄, M3-docs 📑

#9346 Add a Java interface
  Cargo.lock
  parity-clib/Cargo.toml
  parity-clib/Parity.java
  parity-clib/src/lib.rs
Labels: A8-looksgood 🦄, M0-build 🏗

#9383 [light/jsonrpc] Provide the actual account for `eth_coinbase` RPC and unify error handeling for light and full client
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/impls/light/eth.rs
  rpc/src/v1/tests/mocked/eth.rs
Labels: A8-looksgood 🦄, B0-patchthis 🕷, B1-releasenotes 📜, M4-core ⛓, M6-rpcapi 📣

#9470 ethcore: don't validate difficulty when ignoring seal check
  ethcore/src/engines/mod.rs
  ethcore/src/verification/queue/kind.rs
  ethcore/src/verification/queue/mod.rs
  ethcore/src/verification/verification.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9469 Support millisecond timestamp for instant seal engine
  ethcore/res/instant_seal.json
  ethcore/src/engines/instant_seal.rs
  ethcore/src/spec/spec.rs
  ethcore/sync/src/res/private_spec.json
  json/src/spec/engine.rs
  json/src/spec/instant_seal.rs
  json/src/spec/mod.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9435 aura: don't report skipped primaries when empty steps are enabled
  ethcore/src/engines/authority_round/mod.rs
Labels: A8-looksgood 🦄, B0-patchthis 🕷, M4-core ⛓

#9473 Light `clippy(fy)`
  ethcore/light/src/cache.rs
  ethcore/light/src/cht.rs
  ethcore/light/src/client/header_chain.rs
  ethcore/light/src/client/mod.rs
  ethcore/light/src/client/service.rs
  ethcore/light/src/net/context.rs
  ethcore/light/src/net/load_timer.rs
  ethcore/light/src/net/mod.rs
  ethcore/light/src/net/request_credits.rs
  ethcore/light/src/net/request_set.rs
  ethcore/light/src/net/status.rs
  ethcore/light/src/net/tests/mod.rs
  ethcore/light/src/on_demand/mod.rs
  ethcore/light/src/on_demand/request.rs
  ethcore/light/src/provider.rs
  ethcore/light/src/transaction_queue.rs
  ethcore/light/src/types/request/mod.rs
  ethcore/sync/src/api.rs
  ethcore/sync/src/light_sync/sync_round.rs
  ethcore/sync/src/light_sync/tests/test_net.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/impls/light/eth.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9319 EIP 1283: Net gas metering for SSTORE without dirty maps
  ethcore/evm/src/interpreter/gasometer.rs
  ethcore/evm/src/interpreter/mod.rs
  ethcore/evm/src/tests.rs
  ethcore/res/ethereum/constantinople_test.json
  ethcore/src/executive.rs
  ethcore/src/externalities.rs
  ethcore/src/json_tests/executive.rs
  ethcore/src/spec/spec.rs
  ethcore/src/state/account.rs
  ethcore/src/state/mod.rs
  ethcore/src/state/substate.rs
  ethcore/vm/src/ext.rs
  ethcore/vm/src/schedule.rs
  ethcore/vm/src/tests.rs
  ethcore/wasm/src/runtime.rs
  json/src/spec/params.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#9502 rpc(debug_getBadBlocks): fix test
  rpc/src/v1/tests/mocked/debug.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, M4-core ⛓

#9480 Generalized blockReward and difficultyBombDelays config
  ethcore/res/ethereum/byzantium_test.json
  ethcore/res/ethereum/constantinople_test.json
  ethcore/res/ethereum/expanse.json
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/mcip3_test.json
  ethcore/res/ethereum/mcip6_byz.json
  ethcore/res/ethereum/musicoin.json
  ethcore/res/ethereum/ropsten.json
  ethcore/res/ethereum/transition_test.json
  ethcore/src/ethereum/ethash.rs
  json/src/spec/ethash.rs
  json/src/spec/mod.rs
Labels: A8-looksgood 🦄, B1-releasenotes 📜, B9-blocker 🚧, M4-core ⛓

#9501 parity: print correct keys path on startup
  parity/run.rs
  util/dir/src/lib.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, B0-patchthis 🕷, M2-config 📂, M4-core ⛓

#9448 light: give free credits for reserved peers
  ethcore/light/src/net/context.rs
  ethcore/light/src/net/mod.rs
  ethcore/light/src/net/tests/mod.rs
  ethcore/sync/src/light_sync/tests/test_net.rs
  util/network-devp2p/src/host.rs
  util/network/src/lib.rs
Labels: A7-looksgoodcantmerge 🙄, B1-releasenotes 📜, M4-core ⛓

#9492 Don't error when Snapshot is aborted
  ethcore/src/snapshot/service.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9479 upload will fail if a file with the same hash is already up
  .gitlab-ci.yml
Labels: A8-looksgood 🦄, B9-blocker 🚧, M1-ci 🙉

#9484 Only check warp syncing for eth_getWorks
  rpc/src/v1/impls/eth.rs
Labels: A8-looksgood 🦄, B0-patchthis 🕷, B9-blocker 🚧, M6-rpcapi 📣

#9443 Stable backports 1.11.11
  Cargo.lock
  Cargo.toml
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/ropsten.json
  ethcore/res/ethereum/tobalaba.json
  mac/Parity.pkgproj
  nsis/installer.nsi
  parity/run.rs
  rpc/src/v1/impls/eth.rs
  util/dir/src/lib.rs
  util/version/Cargo.toml
Labels: A0-pleasereview 🤓, A8-backport 🕸, M2-config 📂

#9452 Beta backports to 2.0.4
  Cargo.lock
  Cargo.toml
  ethcore/src/blockchain/blockchain.rs
  ethcore/src/client/client.rs
  ethcore/src/engines/authority_round/mod.rs
  parity/run.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/impls/light/eth.rs
  rpc/src/v1/tests/mocked/eth.rs
  util/blooms-db/src/db.rs
  util/blooms-db/src/lib.rs
  util/dir/src/lib.rs
  util/version/Cargo.toml
Labels: A0-pleasereview 🤓, A8-backport 🕸, M2-config 📂

#9515 ci: fix rpc docs generation
  scripts/gitlab/rpc-docs.sh
Labels: A8-looksgood 🦄, B0-patchthis 🕷, B9-blocker 🚧, M0-build 🏗

#9514 Fix checkpointing when creating contract failed
  ethcore/src/state/mod.rs
Labels: A8-looksgood 🦄, B0-patchthis 🕷, B9-blocker 🚧, M4-core ⛓

#9516 fix typo in version string
  .gitlab-ci.yml
Labels: A2-insubstantial 👶, B0-patchthis 🕷, M1-ci 🙉

#9489 Replace hardcoded JSON with serde json! macro
  Cargo.lock
  evmbin/Cargo.toml
  evmbin/src/display/json.rs
  evmbin/src/display/mod.rs
  evmbin/src/display/std_json.rs
  evmbin/src/info.rs
  evmbin/src/main.rs
Labels: A8-looksgood 🦄, M4-core ⛓, M5-dependencies 🖇

#9525 Update patricia trie to 0.2.2
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/private-tx/Cargo.toml
  ethcore/vm/Cargo.toml
  rpc/Cargo.toml
  util/patricia-trie-ethereum/Cargo.toml
Labels: A2-insubstantial 👶, A8-looksgood 🦄, B0-patchthis 🕷

#9522 Fix a panic on create2 new opcode
  ethcore/evm/src/interpreter/gasometer.rs
Labels: A8-looksgood 🦄, B0-patchthis 🕷, B9-blocker 🚧, M4-core ⛓

#9417 [light] Validate `account balance` before importing transactions
  rpc/src/v1/helpers/dispatch.rs
Labels: A8-looksgood 🦄, M4-core ⛓, M6-rpcapi 📣

#9530 Update snapcraft for stable
  snap/snapcraft.yaml
Labels: A8-looksgood 🦄, M1-ci 🙉

#9517 Bump master to 2.2.0
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  scripts/gitlab/package-snap.sh
  scripts/gitlab/publish-docker.sh
  scripts/gitlab/publish-snap.sh
  scripts/gitlab/push.sh
  util/version/Cargo.toml
Labels: A8-looksgood 🦄, M2-config 📂

#9532 state: test when contract creation fails, old storage values should re-appear
  ethcore/src/state/mod.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#9543 correct before_script for nightly build versions
  .gitlab-ci.yml
Labels: A8-looksgood 🦄, B0-patchthis 🕷, M1-ci 🙉

#9544 net_version caches network_id to avoid redundant aquire of sync read lock
  rpc/src/v1/impls/net.rs
Labels: A6-mustntgrumble 💦, B0-patchthis 🕷, M4-core ⛓, M6-rpcapi 📣

#9545 Remove initial token for WS
  rpc/src/authcodes.rs
  rpc/src/tests/ws.rs
Labels: A8-looksgood 🦄, B0-patchthis 🕷, B9-blocker 🚧, M6-rpcapi 📣

#9511 new ethabi
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/node_filter/Cargo.toml
  ethcore/node_filter/src/lib.rs
  ethcore/private-tx/Cargo.toml
  ethcore/private-tx/src/lib.rs
  ethcore/src/client/client.rs
  ethcore/src/engines/block_reward.rs
  ethcore/src/engines/validator_set/contract.rs
  ethcore/src/engines/validator_set/safe_contract.rs
  ethcore/src/miner/service_transaction_checker.rs
  ethcore/src/snapshot/tests/proof_of_authority.rs
  ethcore/src/tx_filter.rs
  hash-fetch/Cargo.toml
  hash-fetch/src/urlhint.rs
  registrar/Cargo.toml
  registrar/src/registrar.rs
  secret_store/Cargo.toml
  secret_store/src/acl_storage.rs
  secret_store/src/key_server_set.rs
  secret_store/src/listener/service_contract.rs
  updater/Cargo.toml
  updater/src/updater.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9239 Multithreaded snapshot creation
  Cargo.lock
  ethcore/src/client/client.rs
  ethcore/src/client/config.rs
  ethcore/src/snapshot/consensus/authority.rs
  ethcore/src/snapshot/consensus/mod.rs
  ethcore/src/snapshot/consensus/work.rs
  ethcore/src/snapshot/mod.rs
  ethcore/src/snapshot/tests/state.rs
  parity/cli/mod.rs
  parity/configuration.rs
  parity/run.rs
  parity/snapshot.rs
Labels: A8-looksgood 🦄, B0-patchthis 🕷, B1-releasenotes 📜, B9-blocker 🚧, M4-core ⛓

#9537 ci: always run build pipelines for win, mac, linux, and android
  .gitlab-ci.yml
  scripts/gitlab/test.sh
Labels: A8-looksgood 🦄, M1-ci 🙉

#9550 ci: fix rpc docs generation, take 2
  scripts/gitlab/rpc-docs.sh
Labels: A8-looksgood 🦄, B0-patchthis 🕷, M0-build 🏗, M1-ci 🙉

#9553 update ethabi-derive, syn && quote
  Cargo.lock
  util/rlp_derive/Cargo.toml
  util/rlp_derive/src/de.rs
  util/rlp_derive/src/en.rs
  util/rlp_derive/src/lib.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#9557 Simultaneous platform tests WIP
  .gitlab-ci.yml
  scripts/gitlab/test.sh
Labels: A8-looksgood 🦄, M1-ci 🙉

#9560 move dockerfile for android build container to scripts repo
  docker/android/Dockerfile
  docker/android/cargo-config.toml
  docker/android/libudev.patch
Labels: A8-looksgood 🦄, M1-ci 🙉

#9526 Improve P2P discovery
  ethcore/sync/src/chain/propagator.rs
  util/network-devp2p/src/discovery.rs
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/node_table.rs
Labels: A8-looksgood 🦄, B0-patchthis 🕷, B9-blocker 🚧, M4-core ⛓

#9563 while working on the platform tests make them non-breaking
  .gitlab-ci.yml
Labels: A0-pleasereview 🤓, M1-ci 🙉

#9564 Increase Gas-floor-target and Gas Cap
  parity/cli/mod.rs
  parity/cli/tests/config.full.toml
  parity/params.rs
Labels: A2-insubstantial 👶, B0-patchthis 🕷, B1-releasenotes 📜, M2-config 📂

#9569 Added ropsten bootnodes
  ethcore/res/ethereum/ropsten.json
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M2-config 📂

#9519 Backports for 2.0.5 stable
  Cargo.lock
  Cargo.toml
  ethcore/sync/src/chain/propagator.rs
  parity/cli/mod.rs
  parity/cli/tests/config.full.toml
  parity/params.rs
  rpc/src/authcodes.rs
  rpc/src/tests/ws.rs
  rpc/src/v1/impls/net.rs
  util/network-devp2p/src/discovery.rs
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/node_table.rs
  util/version/Cargo.toml
Labels: A8-backport 🕸, A8-looksgood 🦄, M2-config 📂, M4-core ⛓

#9571 Fix evm's evm-debug informant compile
  ethcore/evm/src/instructions.rs
  ethcore/evm/src/interpreter/informant.rs
  ethcore/evm/src/interpreter/mod.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9574 Fix typo for jsonrpc-threads flag
  parity/cli/mod.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M2-config 📂

#9578 docs(rpc): push the branch along with tags
  scripts/gitlab-rpc-docs.sh
  scripts/gitlab/rpc-docs.sh
Labels: A2-insubstantial 👶, B0-patchthis 🕷, M0-build 🏗

#9584 add snapcraft package image (master)
  .gitlab-ci.yml
Labels: A8-looksgood 🦄, M1-ci 🙉

#9583 add snapcraft package image
  .gitlab-ci.yml
  scripts/gitlab/package-snap.sh
Labels: A8-looksgood 🦄, M1-ci 🙉

#9585 Remove snapcraft clean
  scripts/gitlab/package-snap.sh
Labels: A8-looksgood 🦄, M1-ci 🙉

#9587 ci: disable build cache for json-rpc-docs
  .gitlab-ci.yml
  scripts/gitlab-rpc-docs.sh
Labels: A8-looksgood 🦄, M1-ci 🙉

#9597 ci: fix regex 🙄
  .gitlab-ci.yml
Labels: A8-looksgood 🦄, A9-buythatmanabeer 🍻, B0-patchthis 🕷, M1-ci 🙉, P2-asap 🌊

#9600 Backports to 2.0.6 stable
  Cargo.lock
  Cargo.toml
  util/version/Cargo.toml
Labels: A8-backport 🕸, M1-ci 🙉, M2-config 📂, P2-asap 🌊

#9599 Backports for 2.1.1 beta
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  scripts/gitlab/rpc-docs.sh
  util/version/Cargo.toml
Labels: A8-backport 🕸, M1-ci 🙉, M2-config 📂, P2-asap 🌊

#9554 docs: add changelogs for 1.11.10, 1.11.11, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.1.0, and 2.1.1
  CHANGELOG.md
  README.md
  docs/CHANGELOG-1.11.md
  docs/CHANGELOG-2.0.md
  scripts/gitlab/test.sh
Labels: A0-pleasereview 🤓, M1-ci 🙉, M3-docs 📑

#9609 beta: rpc-docs set github token
  scripts/gitlab/rpc-docs.sh
Labels: A8-looksgood 🦄, M1-ci 🙉

#9610 master: rpc-docs set github token
  scripts/gitlab/rpc-docs.sh
Labels: A8-looksgood 🦄, M1-ci 🙉

#9611 rpc-docs should push the branch
  scripts/gitlab-rpc-docs.sh
Labels: A8-looksgood 🦄, M1-ci 🙉

#9612 rpc-docs should push the branch
  scripts/gitlab-rpc-docs.sh
Labels: A8-looksgood 🦄, M1-ci 🙉

#9613 stable(rpc-docs): avoid recursive copy
  scripts/gitlab-rpc-docs.sh
Labels: A8-looksgood 🦄, M1-ci 🙉

#9621 fix windows compilation, replaces #9561
  Cargo.lock
Labels: A8-looksgood 🦄, M4-core ⛓

#9593 simplify ethcore errors by removing BlockImportError
  ethcore/light/src/client/header_chain.rs
  ethcore/light/src/client/mod.rs
  ethcore/src/client/client.rs
  ethcore/src/client/mod.rs
  ethcore/src/client/test_client.rs
  ethcore/src/client/traits.rs
  ethcore/src/error.rs
  ethcore/src/verification/queue/mod.rs
  ethcore/sync/src/block_sync.rs
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/light_sync/mod.rs
  parity/blockchain.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#9602 Update ropsten bootnodes
  ethcore/res/ethereum/ropsten.json
Labels: A2-insubstantial 👶, A7-looksgoodtestsfail 🤖, M2-config 📂

#9633 fix failing node-table tests on mac os
  util/network-devp2p/src/node_table.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9608 fix(network): don't disconnect reserved peers
  util/network-devp2p/src/host.rs
Labels: A7-looksgoodtestsfail 🤖, B0-patchthis 🕷, M4-core ⛓

#9603 Use static call and apparent value transfer for block reward contract code
  ethcore/src/engines/mod.rs
  ethcore/src/machine.rs
Labels: A7-looksgoodtestsfail 🤖, M4-core ⛓

#9638 fix bad-block reporting no reason
  ethcore/src/client/client.rs
  ethcore/src/verification/queue/mod.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9615 ethcore: handle vm exception when estimating gas
  ethcore/src/client/client.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9639 ignore key_server_cluster randomly failing tests
  secret_store/src/key_server_cluster/cluster.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#9589 Remove unused dependencies in `ethcore-sync`
  Cargo.lock
  ethcore/sync/Cargo.toml
  ethcore/sync/src/lib.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓, M5-dependencies 🖇

#9527 RPC: parity_getBlockReceipts
  ethcore/light/src/provider.rs
  ethcore/src/blockchain/blockchain.rs
  ethcore/src/client/client.rs
  ethcore/src/client/test_client.rs
  ethcore/src/client/traits.rs
  ethcore/src/miner/miner.rs
  ethcore/src/miner/mod.rs
  ethcore/src/views/body.rs
  ethcore/sync/src/chain/supplier.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/impls/light/eth.rs
  rpc/src/v1/impls/light/parity.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/tests/helpers/miner_service.rs
  rpc/src/v1/tests/mocked/parity.rs
  rpc/src/v1/traits/parity.rs
  rpc/src/v1/types/block_number.rs
  rpc/src/v1/types/mod.rs
Labels: A8-looksgood 🦄, M6-rpcapi 📣

#9620 ethcore/VerificationQueue don't spawn up extra `worker-threads` when explictly specified not to
  ethcore/src/verification/queue/mod.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9547 ethereum libfuzzer integration small change
  ethcore/src/client/evm_test_client.rs
  ethcore/src/lib.rs
  ethcore/src/pod_account.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, M4-core ⛓

#9658 Test fix for windows cache name...
  .gitlab-ci.yml
Labels: A8-looksgood 🦄, B0-patchthis 🕷, M1-ci 🙉

#9673 Calculate sha3 instead of sha256 for push-release.
  scripts/gitlab/build-unix.sh
  scripts/gitlab/build-windows.sh
  scripts/gitlab/push.sh
Labels: A8-looksgood 🦄, B0-patchthis 🕷, B9-blocker 🚧, M1-ci 🙉, P2-asap 🌊

#9562 Hardfork the testnets
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/ropsten.json
  ethcore/src/json_tests/difficulty.rs
Labels: A8-looksgood 🦄, B0-patchthis 🕷, B9-blocker 🚧, M2-config 📂, P2-asap 🌊
