Repository openethereum/openethereum, pull requests merged in 2018-05, with the labels that each got.

#8517 Show imported messages for light client
  ethcore/light/src/client/service.rs
  parity/informant.rs
  parity/run.rs
Labels: A8-looksgood, M4-core

#8504 Directly return None if tracing is disabled
  ethcore/src/client/client.rs
Labels: A8-looksgood, M4-core

#8071 Hardware Wallet trait
  hw/src/ledger.rs
  hw/src/lib.rs
  hw/src/trezor.rs
Labels: A8-looksgood, M4-core

#8357 SecretStore: merge two types of errors into single one + Error::is_non_fatal
  secret_store/src/acl_storage.rs
  secret_store/src/key_server.rs
  secret_store/src/key_server_cluster/admin_sessions/key_version_negotiation_session.rs
  secret_store/src/key_server_cluster/admin_sessions/mod.rs
  secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs
  secret_store/src/key_server_cluster/admin_sessions/share_add_session.rs
  secret_store/src/key_server_cluster/client_sessions/decryption_session.rs
  secret_store/src/key_server_cluster/client_sessions/encryption_session.rs
  secret_store/src/key_server_cluster/client_sessions/generation_session.rs
  secret_store/src/key_server_cluster/client_sessions/signing_session_ecdsa.rs
  secret_store/src/key_server_cluster/client_sessions/signing_session_schnorr.rs
  secret_store/src/key_server_cluster/cluster.rs
  secret_store/src/key_server_cluster/cluster_sessions.rs
  secret_store/src/key_server_cluster/cluster_sessions_creator.rs
  secret_store/src/key_server_cluster/connection_trigger.rs
  secret_store/src/key_server_cluster/connection_trigger_with_migration.rs
  secret_store/src/key_server_cluster/jobs/consensus_session.rs
  secret_store/src/key_server_cluster/jobs/decryption_job.rs
  secret_store/src/key_server_cluster/jobs/job_session.rs
  secret_store/src/key_server_cluster/jobs/signing_job_ecdsa.rs
  secret_store/src/key_server_cluster/jobs/signing_job_schnorr.rs
  secret_store/src/key_server_cluster/message.rs
  secret_store/src/key_server_cluster/mod.rs
  secret_store/src/key_server_set.rs
  secret_store/src/key_storage.rs
  secret_store/src/lib.rs
  secret_store/src/listener/http_listener.rs
  secret_store/src/listener/mod.rs
  secret_store/src/listener/service_contract_listener.rs
  secret_store/src/serialization.rs
  secret_store/src/traits.rs
  secret_store/src/types/all.rs
  secret_store/src/types/error.rs
  secret_store/src/types/mod.rs
Labels: A8-looksgood, M4-core

#8520 Enable WebAssembly and Byzantium for Ellaism
  ethcore/res/ethereum/ellaism.json
Labels: A2-insubstantial, A8-looksgood, B0-patchthis, M2-config

#8470 Transaction Pool improvements
  miner/src/pool/mod.rs
  miner/src/pool/queue.rs
  miner/src/pool/ready.rs
  miner/src/pool/scoring.rs
  transaction-pool/Cargo.toml
  transaction-pool/src/error.rs
  transaction-pool/src/lib.rs
  transaction-pool/src/pool.rs
  transaction-pool/src/ready.rs
  transaction-pool/src/scoring.rs
  transaction-pool/src/tests/helpers.rs
  transaction-pool/src/tests/mod.rs
  transaction-pool/src/tests/tx_builder.rs
  transaction-pool/src/transactions.rs
Labels: A8-looksgood, M4-core

#8463 Fetching logs by hash in blockchain database
  ethcore/src/blockchain/blockchain.rs
  ethcore/src/client/client.rs
  ethcore/src/verification/verification.rs
Labels: A0-pleasereview, B0-patchthis, M4-core, P2-asap

#8491 Pass on storage keys tracing to handle the case when it is not modified
  ethcore/src/state/mod.rs
Labels: A8-looksgood, B0-patchthis, M4-core, P2-asap

#8522 Don't panic in import_block if invalid rlp
  ethcore/src/client/client.rs
  ethcore/src/error.rs
  ethcore/src/tests/client.rs
  ethcore/src/verification/queue/kind.rs
  ethcore/src/verification/queue/mod.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#8536 Remove expect
  util/patricia_trie/src/lib.rs
  util/patricia_trie/src/lookup.rs
  util/patricia_trie/src/triedb.rs
  util/rlp/src/error.rs
Labels: A0-pleasereview

#8490 Refactor block reward application and tracing
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/block_reward.rs
  ethcore/src/engines/mod.rs
  ethcore/src/engines/null_engine.rs
  ethcore/src/engines/tendermint/mod.rs
  ethcore/src/ethereum/ethash.rs
  ethcore/src/machine.rs
  ethcore/src/trace/types/trace.rs
  machine/src/lib.rs
  rpc/src/v1/types/trace.rs
Labels: A8-looksgood, F6-refactor, M4-core

#8524 Keep all enacted blocks notify in order
  ethcore/private-tx/src/lib.rs
  ethcore/src/blockchain/import_route.rs
  ethcore/src/client/chain_notify.rs
  ethcore/src/client/client.rs
  ethcore/src/client/mod.rs
  ethcore/src/snapshot/watcher.rs
  ethcore/sync/src/api.rs
  ethcore/sync/src/tests/helpers.rs
  parity/informant.rs
  rpc/src/v1/impls/eth_pubsub.rs
  rpc/src/v1/tests/mocked/eth_pubsub.rs
  secret_store/src/acl_storage.rs
  secret_store/src/key_server_set.rs
  secret_store/src/listener/service_contract_listener.rs
  updater/src/updater.rs
Labels: A8-looksgood, M4-core

#8541 Node table sorting according to last contact data
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/node_table.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#8557 [stable] Backports
  Cargo.lock
  ethcore/res/ethereum/ellaism.json
  ethcore/src/blockchain/blockchain.rs
  ethcore/src/client/client.rs
  ethcore/src/state/mod.rs
  ethcore/src/verification/verification.rs
  ethcore/wasm/Cargo.toml
Labels: A8-backport, M4-core

#8558 [beta] Backports
  Cargo.lock
  ethcore/light/src/client/service.rs
  ethcore/res/ethereum/ellaism.json
  ethcore/src/blockchain/blockchain.rs
  ethcore/src/client/client.rs
  ethcore/src/error.rs
  ethcore/src/state/mod.rs
  ethcore/src/tests/client.rs
  ethcore/src/verification/queue/kind.rs
  ethcore/src/verification/queue/mod.rs
  ethcore/src/verification/verification.rs
  ethcore/wasm/Cargo.toml
  parity/informant.rs
  parity/run.rs
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/node_table.rs
Labels: A8-backport, M4-core

#8412 Parity as a library
  Cargo.lock
  Cargo.toml
  parity-clib-example/CMakeLists.txt
  parity-clib-example/main.cpp
  parity-clib/Cargo.toml
  parity-clib/parity.h
  parity-clib/src/lib.rs
  parity/blockchain.rs
  parity/cli/usage.rs
  parity/configuration.rs
  parity/lib.rs
  parity/main.rs
  parity/run.rs
  parity/snapshot.rs
  parity/url.rs
  test.sh
Labels: A8-looksgood, M4-core

#8486 Trace precompiled contracts when the transfer value is not zero
  ethcore/src/executive.rs
Labels: A6-mustntgrumble, B0-patchthis, B1-releasenotes, M4-core, P2-asap

#8530 Don't block sync when importing old blocks
  Cargo.lock
  ethcore/private-tx/src/lib.rs
  ethcore/private-tx/tests/private_contract.rs
  ethcore/service/Cargo.toml
  ethcore/service/src/lib.rs
  ethcore/service/src/service.rs
  ethcore/src/client/ancient_import.rs
  ethcore/src/client/client.rs
  ethcore/src/client/io_message.rs
  ethcore/src/client/mod.rs
  ethcore/src/client/test_client.rs
  ethcore/src/client/traits.rs
  ethcore/src/views/block.rs
  ethcore/sync/Cargo.toml
  ethcore/sync/src/api.rs
  ethcore/sync/src/block_sync.rs
  ethcore/sync/src/chain.rs
  ethcore/sync/src/lib.rs
  ethcore/sync/src/tests/helpers.rs
  ethcore/sync/src/tests/private.rs
  util/io/src/lib.rs
  util/io/src/service.rs
  util/io/src/worker.rs
Labels: A8-looksgood, B0-patchthis, M4-core, P2-asap

#8568 Make trace-time & transaction-pool publishable
  transaction-pool/Cargo.toml
  util/trace-time/Cargo.toml
Labels: A2-insubstantial, A8-looksgood, M4-core

#8569 Remove State::replace_backend
  ethcore/src/state/mod.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8543 Refactoring `ethcore-sync` - Fixing warp-sync barrier
  ethcore/sync/src/chain.rs
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/propagator.rs
  ethcore/sync/src/chain/requester.rs
  ethcore/sync/src/chain/supplier.rs
  ethcore/sync/src/tests/snapshot.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#8556 Update CHANGELOG for 1.9, 1.10, and 1.11
  CHANGELOG.md
  docs/CHANGELOG-1.10.md
  docs/CHANGELOG-1.9.md
Labels: A0-pleasereview, M3-docs, P5-sometimesoon

#8545 Handle socket address parsing errors
  Cargo.lock
  util/network-devp2p/Cargo.toml
  util/network-devp2p/src/lib.rs
  util/network-devp2p/src/node_table.rs
  util/network/src/error.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#8579 Rename `whisper-cli binary` to `whisper`
  whisper/cli/Cargo.toml
  whisper/cli/src/main.rs
Labels: A2-insubstantial, B0-patchthis, M5-binaries

#8578 Add whisper CLI to the pipelines
  scripts/gitlab-build.sh
Labels: A2-insubstantial, B0-patchthis, M1-ci

#8587 Added Dockerfile for alpine linux
  docker/alpine/Dockerfile
Labels: A8-looksgood, M1-ci

#8591 Changelog and Readme
  README.md
Labels: A2-insubstantial, M3-docs

#8584 Attempt to fix intermittent test failures
  miner/src/pool/tests/mod.rs
Labels: A8-looksgood, M4-core

#8537 Make mio optional in ethcore-io
  Cargo.lock
  ethcore/sync/Cargo.toml
  test.sh
  util/io/Cargo.toml
  util/io/src/lib.rs
  util/io/src/service_mio.rs
  util/io/src/service_non_mio.rs
  util/io/src/worker.rs
  util/network-devp2p/Cargo.toml
Labels: A6-mustntgrumble, M4-core

#8600 Fix Parity UI link
  README.md
Labels: A8-looksgood

#8586 Block::decode() returns Result
  ethcore/src/encoded.rs
  ethcore/src/snapshot/consensus/authority.rs
Labels: A8-looksgood, M4-core

#8581 block_header can fail so return Result
  rpc/src/v1/impls/light/parity.rs
  util/journaldb/src/earlymergedb.rs
  util/journaldb/src/refcounteddb.rs
Labels: A8-looksgood, M4-core

#8539 Remove inject.js server-side injection for dapps
  dapps/src/page/handler.rs
  dapps/src/tests/home.rs
Labels: A8-looksgood, M8-dapp

#8602 Fix the mio test again
  util/io/src/lib.rs
Labels: A8-looksgood, M4-core

#8601 2 tiny modification on snapshot
  ethcore/src/snapshot/consensus/work.rs
  ethcore/src/snapshot/service.rs
Labels: A8-looksgood

#8610 typo: wrong indentation in kovan config
  ethcore/res/ethereum/kovan.json
Labels: A2-insubstantial, A8-looksgood, M2-config

#8595 Whisper-cli `remove manually added text to the errors`
  whisper/cli/src/main.rs
Labels: A2-insubstantial, A8-looksgood, M5-binaries

#8573 Gitlab test script fixes
  scripts/gitlab-test.sh
Labels: A0-pleasereview, B0-patchthis, M1-ci

#8626 Bump stable to 1.10.4
  Cargo.lock
  Cargo.toml
  mac/Parity.pkgproj
  nsis/installer.nsi
  util/version/Cargo.toml
Labels: A8-backport, M2-installer

#8623 [stable] Backports
  ethcore/src/executive.rs
  parity/account.rs
  scripts/gitlab-test.sh
Labels: A8-backport, M4-core

#8627 Bump beta to 1.11.1
  Cargo.lock
  Cargo.toml
  mac/Parity.pkgproj
  nsis/installer.nsi
  util/version/Cargo.toml
Labels: A8-backport, M2-installer

#8611 Fix BlockReward contract "arithmetic operation overflow"
  ethcore/src/machine.rs
Labels: A0-pleasereview, B0-patchthis, M4-core

#8629 ´main.rs´ typo
  parity/main.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core

#8621 Store morden db and keys in "path/to/parity/data/Morden" (ropsten uses "test", like before)
  .gitignore
  ethcore/res/ethereum/morden.json
  util/dir/src/lib.rs
Labels: A2-insubstantial, A8-looksgood, B1-releasenotes, M2-config, M4-core

#8528 Fix light sync with initial validator-set contract
  ethcore/src/spec/spec.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#8625 Remove NetworkContext::io_channel()
  util/network-devp2p/src/host.rs
  util/network/src/lib.rs
Labels: A8-looksgood, M4-core

#8538 Check that the Android build doesn't dep on c++_shared
  .gitlab-ci.yml
Labels: A0-pleasereview, M1-ci

#8640 More typos
  parity/main.rs
  secret_store/src/acl_storage.rs
  secret_store/src/key_server_set.rs
  secret_store/src/key_storage.rs
  secret_store/src/serialization.rs
  secret_store/src/traits.rs
  secret_store/src/types/all.rs
  secret_store/src/types/error.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core

#8637 Changelog for 1.10.4-stable and 1.11.1-beta
  CHANGELOG.md
  docs/CHANGELOG-1.10.md
Labels: A0-pleasereview, M3-docs

#8641 Don't open Browser post-install on Mac, fixes #8194
  mac/post-install.sh
Labels: A8-looksgood, B0-patchthis, B1-releasenotes, M2-installer

#8544 Resumable warp-sync / Seed downloaded snapshots
  ethcore/src/snapshot/service.rs
  ethcore/src/snapshot/tests/service.rs
  ethcore/src/snapshot/traits.rs
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/supplier.rs
  ethcore/sync/src/snapshot.rs
  ethcore/sync/src/tests/snapshot.rs
  ethcore/types/src/restoration_status.rs
  parity/informant.rs
  parity/snapshot.rs
  rpc/src/v1/tests/helpers/snapshot_service.rs
Labels: A8-looksgood, B1-releasenotes, M4-core

#8642 Fix ancient blocks not downloading
  ethcore/src/client/client.rs
  ethcore/sync/src/blocks.rs
Labels: A8-looksgood, B0-patchthis, M4-core, P5-sometimesoon

#8644 Remove HostInfo::next_nonce
  util/network-devp2p/src/host.rs
  util/network/src/lib.rs
Labels: A8-looksgood, M4-core

#8657 Remove the Keccak C library and use the pure Rust impl
  Cargo.lock
  ethash/src/keccak.rs
  util/hash/Cargo.toml
  util/hash/benches/keccak_256.rs
  util/hash/build.rs
  util/hash/src/lib.rs
  util/hash/src/tinykeccak.c
Labels: A8-looksgood, M5-dependencies

#8669 updated tiny-keccak to 1.4.2
  Cargo.lock
Labels: A8-looksgood, M5-dependencies

#8665 parity: improve cli help and logging
  parity/cli/mod.rs
  parity/informant.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8677 Remove HostInfo::client_version() and secret()
  util/network-devp2p/src/handshake.rs
  util/network-devp2p/src/host.rs
  util/network/src/lib.rs
Labels: A0-pleasereview, M4-core

#8674 Move connection_filter to the network crate
  Cargo.lock
  ethcore/node_filter/Cargo.toml
  ethcore/node_filter/src/lib.rs
  ethcore/sync/src/api.rs
  ethcore/sync/src/lib.rs
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/lib.rs
  util/network-devp2p/src/service.rs
  util/network/src/connection_filter.rs
  util/network/src/lib.rs
Labels: A0-pleasereview, M4-core

#8671 Remove the error when stopping the network
  ethcore/sync/src/api.rs
  util/io/src/service_mio.rs
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/service.rs
  util/network-devp2p/tests/tests.rs
Labels: A8-looksgood, M4-core

#8588 Allow making direct RPC queries from the C API
  parity-clib-example/main.cpp
  parity-clib/parity.h
  parity-clib/src/lib.rs
  parity/rpc.rs
  parity/run.rs
  rpc/src/v1/types/provenance.rs
Labels: A8-looksgood, M4-core

#8682 Fix cli signer
  Cargo.lock
  rpc/Cargo.toml
  rpc/src/v1/types/uint.rs
Labels: A0-pleasereview, B0-patchthis, M4-core

#8628 Use impl Future in the light client RPC helpers
  rpc/src/v1/helpers/light_fetch.rs
  rpc/src/v1/impls/eth_pubsub.rs
  rpc/src/v1/impls/light/eth.rs
Labels: A8-looksgood, M4-core

#8695 Update mod.rs
  parity/cli/mod.rs
Labels: A2-insubstantial, A8-looksgood, M2-config, M3-docs

#8705 Remove empty file
  ethstore/tests/cli.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8683 Set the request index to that of the current request
  rpc/src/v1/helpers/light_fetch.rs
  rpc/src/v1/tests/eth.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#8692 parity: trim whitespace when parsing duration strings
  parity/helpers.rs
Labels: A2-insubstantial, F3-annoyance, M4-core

#8697 Implement recursive fmt::Debug for patrica_trie::TrieDB to print Node trees
  util/patricia_trie/src/triedb.rs
Labels: A8-looksgood, M4-core

#8722 Remove unused imports
  util/network/src/lib.rs
  util/patricia_trie/src/triedb.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8713 Add a test for decoding corrupt data
  util/patricia_trie/src/triedb.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8707 Fix compilation error on nightly rust
  util/network-devp2p/src/service.rs
Labels: A8-looksgood, M4-core

#8686 network-devp2p: handle UselessPeer disconnect
  util/network-devp2p/src/host.rs
Labels: A8-looksgood, F2-bug, M4-core

#8691 Fix local transactions policy.
  miner/src/pool/scoring.rs
  miner/src/pool/tests/mod.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#8727 Add a deadlock detection thread
  Cargo.lock
  Cargo.toml
  parity/lib.rs
Labels: A8-looksgood, M4-core

#8735 Remove unused function new_pow_test_spec
  ethcore/src/spec/spec.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8699 Allow users to specify interface to listen to via CLI
  parity/cli/mod.rs
  parity/configuration.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8731 Fix some nits using clippy
  util/network-devp2p/src/handshake.rs
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/ip_utils.rs
  util/network-devp2p/src/node_table.rs
  util/network-devp2p/src/service.rs
  util/network-devp2p/src/session.rs
  whisper/cli/src/main.rs
Labels: A8-looksgood, M4-core, M5-binaries

#8736 Remove a couple of unnecessary `transmute()`
  ethash/src/compute.rs
  util/plain_hasher/src/lib.rs
Labels: A8-looksgood, M4-core

#8728 bump tiny-keccak to 1.4
  ethcore/crypto/Cargo.toml
  ethcore/private-tx/Cargo.toml
  ethkey/Cargo.toml
  ethstore/Cargo.toml
  rpc/Cargo.toml
  secret_store/Cargo.toml
  util/network-devp2p/Cargo.toml
  whisper/Cargo.toml
Labels: A2-insubstantial, A8-looksgood

#8726 Ease tiny-keccak version requirements (1.4.1 -> 1.4)
  util/hash/Cargo.toml
Labels: A2-insubstantial, M5-dependencies

#8719 Remove -k/--insecure option from curl installer
  README.md
Labels: A8-looksgood, M3-docs

#8656 Fix PoW blockchains sealing notifications in chain_new_blocks
  ethcore/src/client/client.rs
Labels: A8-looksgood, B0-patchthis, B9-blocker, M4-core, P5-sometimesoon
