Repository openethereum/openethereum, pull requests merged in 2018-11, with the labels that each got.

#9842 chore(bump regex)
  Cargo.lock
  Cargo.toml
  logger/Cargo.toml
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓, M5-dependencies 🖇

#9788 ci: remove failing tests for android, windows, and macos
  .gitlab-ci.yml
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#9767 Support MIX.
  ethcore/res/ethereum/mix.json
  ethcore/src/ethereum/mod.rs
  parity/cli/mod.rs
  parity/params.rs
Labels: A0-pleasereview 🤓, B7-releasenotes 📜, M2-config 📂, M4-core ⛓

#9828 Classic.json Bootnode Update
  ethcore/res/ethereum/classic.json
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#9821 version: mark 2.1.5 stable
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/res/ethereum/classic.json
  ethcore/src/verification/verification.rs
  util/version/Cargo.toml
Labels: A2-insubstantial 👶, A8-backport 🕸, M2-installer 📲

#9848 Option to disable keep alive for JSON-RPC http transport
  Cargo.lock
  parity/cli/mod.rs
  parity/configuration.rs
  parity/rpc.rs
  rpc/src/lib.rs
  rpc/src/tests/rpc.rs
  rpc/src/v1/extractors.rs
  rpc/src/v1/informant.rs
Labels: A8-looksgood 🦄, M6-rpcapi 📣

#9811 Update Callisto block reward code to support HF1
  ethcore/res/ethereum/callisto.json
Labels: A2-insubstantial 👶, A3-inprogress ⏳, A3-stale 🍃, A8-looksgood 🦄, M2-config 📂

#9839 Clean up existing benchmarks
  Cargo.lock
  ethash/Cargo.toml
  ethash/benches/basic.rs
  ethash/src/lib.rs
  ethcore/Cargo.toml
  ethcore/benches/builtin.rs
  ethcore/evm/Cargo.toml
  ethcore/evm/benches/basic.rs
  ethcore/evm/src/benches/mod.rs
  ethcore/evm/src/lib.rs
  ethcore/src/lib.rs
  ethcore/src/state/mod.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9854 Fix docker script
  scripts/docker/hub/Dockerfile
Labels: A0-pleasereview 🤓, B1-patch-beta 🕷🕷, M1-ci 🙉, P2-asap 🌊

#9876 Allow to seal work on latest block
  ethcore/src/miner/miner.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9873 Fix json tracer overflow
  evmbin/src/display/json.rs
Labels: A8-looksgood 🦄, B1-patch-beta 🕷🕷, M4-core ⛓

#9884 Remove unused code
  ethcore/evm/src/interpreter/memory.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9855 ci: nuke the gitlab caches
  .gitlab-ci.yml
Labels: A3-inprogress ⏳, A4-awaitingci 🤖, M1-ci 🙉

#9886 Fix Parity not closing on Ctrl-C
  rpc/src/v1/impls/pubsub.rs
Labels: A8-looksgood 🦄, B1-patch-beta 🕷🕷, M4-core ⛓

#9883 Use expect
  ethcore/evm/src/interpreter/stack.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9889 chore(bump docopt): 0.8 -> 1.0
  Cargo.lock
  Cargo.toml
  ethkey/cli/Cargo.toml
  ethstore/cli/Cargo.toml
  evmbin/Cargo.toml
  whisper/cli/Cargo.toml
Labels: A8-looksgood 🦄, M4-core ⛓

#9896 chore(rpc-tests): remove unused rand
  rpc/src/tests/ws.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, M4-core ⛓

#9900 ethcore: use Machine::verify_transaction on parent block
  ethcore/src/machine.rs
  ethcore/src/verification/verification.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#9907 Update hardcoded headers
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/ropsten.json
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#9908 fix(logger): `reqwest` no longer a dependency
  logger/src/lib.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#9701 EIP 191
  rpc/src/v1/helpers/dispatch.rs
  rpc/src/v1/helpers/eip191.rs
  rpc/src/v1/helpers/mod.rs
  rpc/src/v1/helpers/requests.rs
  rpc/src/v1/impls/personal.rs
  rpc/src/v1/impls/signer.rs
  rpc/src/v1/tests/mocked/personal.rs
  rpc/src/v1/traits/personal.rs
  rpc/src/v1/types/confirmations.rs
  rpc/src/v1/types/eip191.rs
  rpc/src/v1/types/mod.rs
  util/EIP-712/src/encode.rs
Labels: A0-pleasereview 🤓, M6-rpcapi 📣

#9824 light-fetch: Differentiate between out-of-gas/manual throw and use required gas from response on failure
  rpc/src/v1/helpers/light_fetch.rs
Labels: A6-mustntgrumble 💦, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#9918 simplify cargo audit
  scripts/gitlab/cargo-audit.sh
Labels: A8-looksgood 🦄, M1-ci 🙉

#9914 Fix performance issue importing Kovan blocks
  ethcore/src/client/client.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/mod.rs
Labels: A8-looksgood 🦄, B1-patch-beta 🕷🕷, M4-core ⛓

#9904 Backport Stable 2.1.6
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/ropsten.json
  ethcore/src/machine.rs
  ethcore/src/verification/verification.rs
  rpc/src/tests/ws.rs
  rpc/src/v1/helpers/light_fetch.rs
  rust-toolchain
  scripts/gitlab/build-unix.sh
  scripts/gitlab/build-windows.sh
  scripts/gitlab/cargo-audit.sh
  util/version/Cargo.toml
Labels: A8-backport 🕸, A8-looksgood 🦄, M2-config 📂, M4-core ⛓

#9923 docs(require rust 1.30)
  README.md
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M3-docs 📑

#9922 Clarify poll lifetime
  parity/cli/mod.rs
  parity/rpc_apis.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/tests/mocked/eth.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9928 Add experimental RPCs flag
  parity/cli/mod.rs
  parity/configuration.rs
  parity/rpc_apis.rs
  parity/run.rs
  rpc/src/v1/helpers/errors.rs
  rpc/src/v1/impls/personal.rs
  rpc/src/v1/tests/mocked/personal.rs
Labels: A8-looksgood 🦄, B1-patch-beta 🕷🕷, M6-rpcapi 📣

#8643 Keep existing blocks when restoring a Snapshot
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/light/src/provider.rs
  ethcore/service/src/service.rs
  ethcore/src/blockchain/blockchain.rs
  ethcore/src/client/client.rs
  ethcore/src/client/test_client.rs
  ethcore/src/client/traits.rs
  ethcore/src/lib.rs
  ethcore/src/snapshot/error.rs
  ethcore/src/snapshot/mod.rs
  ethcore/src/snapshot/service.rs
  ethcore/src/snapshot/tests/service.rs
  ethcore/src/test_helpers.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/supplier.rs
  rpc/src/v1/impls/parity.rs
Labels: A8-looksgood 🦄, B7-releasenotes 📜, B9-blocker 🚧, M4-core ⛓

#9934 Unbreak parity-rpc build on rust -stable
  rpc/src/v1/helpers/light_fetch.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, M4-core ⛓

#9935 Update eth-secp256k1 to include fix for BSDs
  Cargo.lock
Labels: A8-looksgood 🦄, M4-core ⛓

#9944 allow rust-nightly builds fail in nightly builds
  .gitlab-ci.yml
Labels: A8-looksgood 🦄, M1-ci 🙉

#9947 Missing blocks in filter_changes RPC
  rpc/src/v1/helpers/poll_filter.rs
  rpc/src/v1/impls/eth_filter.rs
  rpc/src/v1/tests/mocked/eth.rs
Labels: A8-looksgood 🦄, M6-rpcapi 📣

#9001 EIP-1186: add `eth_getProof` RPC-Method
  parity/rpc_apis.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/impls/light/eth.rs
  rpc/src/v1/tests/eth.rs
  rpc/src/v1/traits/eth.rs
  rpc/src/v1/types/account_info.rs
  rpc/src/v1/types/mod.rs
Labels: A6-mustntgrumble 💦, M6-rpcapi 📣

#9925 Adjust requests costs for light client
  ethcore/light/src/net/mod.rs
  ethcore/light/src/net/tests/mod.rs
  ethcore/sync/src/api.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#9939 Fix empty steps
  ethcore/src/client/client.rs
  ethcore/src/engines/authority_round/mod.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#9946 prevent silent errors in daemon mode
  parity/run.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#9834 Do not use the home directory as the working dir in docker
  scripts/docker/hub/Dockerfile
Labels: A8-looksgood 🦄, M1-ci 🙉

#9958 chore(eip712): remove unused `failure-derive`
  Cargo.lock
  util/EIP-712/Cargo.toml
  util/EIP-712/src/lib.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓, M5-dependencies 🖇

#9952 Fix a deadlock
  ethcore/src/blockchain/blockchain.rs
  parity/informant.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9888 Remove runtime from secret_store.
  Cargo.lock
  parity/run.rs
  parity/secretstore.rs
  secret_store/Cargo.toml
  secret_store/src/key_server.rs
  secret_store/src/key_server_cluster/client_sessions/generation_session.rs
  secret_store/src/key_server_cluster/cluster.rs
  secret_store/src/key_server_cluster/cluster_sessions.rs
  secret_store/src/lib.rs
  secret_store/src/listener/http_listener.rs
  secret_store/src/types/all.rs
  util/runtime/src/lib.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9955 Disable EIP-98 transition by default
  ethcore/res/ethereum/byzantium_test.json
  ethcore/res/ethereum/callisto.json
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/constantinople_test.json
  ethcore/res/ethereum/easthub.json
  ethcore/res/ethereum/eip150_test.json
  ethcore/res/ethereum/eip161_test.json
  ethcore/res/ethereum/eip210_test.json
  ethcore/res/ethereum/ellaism.json
  ethcore/res/ethereum/expanse.json
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/frontier_like_test.json
  ethcore/res/ethereum/frontier_test.json
  ethcore/res/ethereum/homestead_test.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/kovan_wasm_test.json
  ethcore/res/ethereum/mcip3_test.json
  ethcore/res/ethereum/mix.json
  ethcore/res/ethereum/morden.json
  ethcore/res/ethereum/musicoin.json
  ethcore/res/ethereum/ropsten.json
  ethcore/res/ethereum/social.json
  ethcore/res/ethereum/tobalaba.json
  ethcore/src/spec/spec.rs
Labels: A8-looksgood 🦄, B7-releasenotes 📜, M2-config 📂

#9706 Add a optional json dump state to evm-bin
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/src/client/evm_test_client.rs
  ethcore/src/json_tests/state.rs
  ethcore/src/lib.rs
  ethcore/src/pod_account.rs
  ethcore/src/pod_state.rs
  ethcore/src/state/account.rs
  ethcore/src/state/mod.rs
  ethcore/src/trace/mod.rs
  ethcore/wasm/run/src/runner.rs
  evmbin/Cargo.toml
  evmbin/README.md
  evmbin/src/display/json.rs
  evmbin/src/display/simple.rs
  evmbin/src/display/std_json.rs
  evmbin/src/info.rs
  evmbin/src/main.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9932 Fix light client informant while syncing
  ethcore/sync/src/light_sync/mod.rs
  parity/informant.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#9881 Make CALLCODE to trace value to be the code address
  ethcore/src/state/mod.rs
  ethcore/src/trace/types/trace.rs
Labels: A8-looksgood 🦄, B7-releasenotes 📜, M4-core ⛓

#9475 Add Error message when sync is still in progress.
  parity/cli/mod.rs
  parity/cli/tests/config.full.toml
  parity/configuration.rs
  parity/rpc_apis.rs
  parity/run.rs
  rpc/src/v1/helpers/errors.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/tests/eth.rs
Labels: A8-looksgood 🦄, B7-releasenotes 📜, M4-core ⛓, M6-rpcapi 📣

#9963 Add changelogs for 2.0.9, 2.1.4, 2.1.6, and 2.2.1
  CHANGELOG.md
  docs/CHANGELOG-2.0.md
  docs/CHANGELOG-2.1.md
Labels: A8-looksgood 🦄, M3-docs 📑

#9970 ci: rearrange pipeline by logic
  .gitlab-ci.yml
  scripts/gitlab/publish-docs.sh
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#9971 fix docker build
  scripts/docker/hub/Dockerfile
Labels: A2-insubstantial 👶, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#9972 Deny unknown fields for chainspec
  Cargo.lock
  chainspec/Cargo.toml
  chainspec/src/main.rs
  json/src/spec/account.rs
  json/src/spec/authority_round.rs
  json/src/spec/basic_authority.rs
  json/src/spec/builtin.rs
  json/src/spec/engine.rs
  json/src/spec/ethash.rs
  json/src/spec/genesis.rs
  json/src/spec/hardcoded_sync.rs
  json/src/spec/instant_seal.rs
  json/src/spec/null_engine.rs
  json/src/spec/params.rs
  json/src/spec/seal.rs
  json/src/spec/spec.rs
  json/src/spec/state.rs
  json/src/spec/tendermint.rs
  json/src/spec/validator_set.rs
  rpc/src/v1/tests/eth.rs
Labels: A8-looksgood 🦄, B1-patch-beta 🕷🕷, B7-releasenotes 📜, M2-config 📂

#9967 Fix unstable peers and slowness in sync
  ethcore/sync/src/api.rs
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/tests/helpers.rs
Labels: A8-looksgood 🦄, B1-patch-beta 🕷🕷, M4-core ⛓

#9840 Calculate gas for deployment transaction
  ethcore/private-tx/src/lib.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9975 Backports for stable 2.1.7
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/light/src/net/mod.rs
  ethcore/light/src/net/tests/mod.rs
  ethcore/src/client/client.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/sync/Cargo.toml
  ethcore/sync/src/api.rs
  ethcore/sync/src/blocks.rs
  ethcore/sync/src/lib.rs
  ethcore/sync/src/light_sync/mod.rs
  ethstore/Cargo.toml
  miner/src/pool/tests/mod.rs
  parity/informant.rs
  parity/run.rs
  scripts/docker/hub/Dockerfile
  scripts/docker/hub/check_sync.sh
  scripts/gitlab/publish-docs.sh
  util/version/Cargo.toml
  whisper/Cargo.toml
Labels: A0-pleasereview 🤓, A8-backport 🕸, M1-ci 🙉, M2-config 📂, M4-core ⛓

#9980 Remove tendermint engine support
  ethcore/res/tendermint.json
  ethcore/src/engines/mod.rs
  ethcore/src/engines/signer.rs
  ethcore/src/engines/tendermint/message.rs
  ethcore/src/engines/tendermint/mod.rs
  ethcore/src/engines/tendermint/params.rs
  ethcore/src/engines/transition.rs
  ethcore/src/engines/vote_collector.rs
  ethcore/src/spec/spec.rs
  ethcore/sync/src/tests/consensus.rs
  json/src/spec/engine.rs
  json/src/spec/mod.rs
  json/src/spec/tendermint.rs
Labels: A8-looksgood 🦄, B7-releasenotes 📜, M4-core ⛓

#9992 Fix Bloom migration
  parity/db/rocksdb/blooms.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10000 Fix daemonize
  Cargo.lock
  Cargo.toml
  parity/run.rs
Labels: A1-onice 🌨, A6-revertrevert 💀, A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓, M5-dependencies 🖇

#9990 docs: update changelogs
  CHANGELOG.md
  docs/CHANGELOG-2.1.md
Labels: A8-looksgood 🦄, M3-docs 📑

#10003 move daemonize before creating account provider
  parity/run.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷

#10001 Stable patch release 2.1.8
  Cargo.lock
  Cargo.toml
  parity/db/rocksdb/blooms.rs
  parity/run.rs
  util/version/Cargo.toml
Labels: A8-backport 🕸, A8-looksgood 🦄, M4-core ⛓

#10002 Beta patch release 2.2.3
  Cargo.lock
  Cargo.toml
  parity/db/rocksdb/blooms.rs
  parity/run.rs
  util/version/Cargo.toml
Labels: A8-backport 🕸, A8-looksgood 🦄, M4-core ⛓
