Repository openethereum/openethereum, pull requests merged in 2018-06, with the labels that each got.

#8711 Print warnings when fetching pending blocks
  ethcore/src/miner/miner.rs
  rpc/src/v1/impls/eth.rs
Labels: A8-looksgood, M4-core

#8589 Fix XOR distance calculation in discovery Kademlia impl
  util/network-devp2p/src/discovery.rs
Labels: A0-pleasereview, M4-core

#8653 Remove NetworkService::config()
  ethcore/sync/src/api.rs
  parity/informant.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/tests/mocked/manage_network.rs
  util/network-devp2p/src/service.rs
  whisper/cli/src/main.rs
Labels: A8-looksgood, M4-core

#8745 CI: Fixes for Android Pipeline
  .gitlab-ci.yml
Labels: A0-pleasereview, A2-insubstantial, B0-patchthis, M1-ci

#8744 Custom Error Messages on ENFILE and EMFILE IO Errors
  Cargo.lock
  util/network/Cargo.toml
  util/network/src/error.rs
  util/network/src/lib.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#8750 parity-version: bump beta to 1.11.2
  Cargo.toml
  mac/Parity.pkgproj
  nsis/installer.nsi
  util/version/Cargo.toml
Labels: A2-insubstantial, A8-looksgood, M2-installer

#8758 Remove public node settings from cli
  parity/cli/mod.rs
  parity/configuration.rs
  parity/rpc_apis.rs
  parity/run.rs
  rpc/src/v1/helpers/accounts.rs
  rpc/src/v1/helpers/errors.rs
  rpc/src/v1/helpers/mod.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/impls/parity_accounts.rs
  rpc/src/v1/impls/personal.rs
  rpc/src/v1/impls/private.rs
  rpc/src/v1/impls/secretstore.rs
  rpc/src/v1/impls/signer.rs
  rpc/src/v1/impls/signing.rs
  rpc/src/v1/impls/signing_unsafe.rs
  rpc/src/v1/tests/eth.rs
  rpc/src/v1/tests/mocked/eth.rs
  rpc/src/v1/tests/mocked/parity.rs
  rpc/src/v1/tests/mocked/parity_accounts.rs
  rpc/src/v1/tests/mocked/personal.rs
  rpc/src/v1/tests/mocked/secretstore.rs
  rpc/src/v1/tests/mocked/signer.rs
  rpc/src/v1/tests/mocked/signing.rs
Labels: A7-looksgoodtestsfail, M5-binaries

#8710 ethcore-sync: fix connection to peers behind chain fork block
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/chain/mod.rs
Labels: A8-looksgood, B0-patchthis, B9-blocker, M4-core

#8681 Remove HostTrait altogether
  ethcore/light/src/net/mod.rs
  ethcore/sync/src/api.rs
  util/network-devp2p/src/handshake.rs
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/lib.rs
  util/network-devp2p/src/session.rs
  util/network-devp2p/tests/tests.rs
  util/network/src/lib.rs
  whisper/src/net/mod.rs
Labels: A8-looksgood, M4-core

#8763 Remove Result wrapper from AccountProvider in RPC impls
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/impls/parity_accounts.rs
  rpc/src/v1/impls/personal.rs
  rpc/src/v1/impls/secretstore.rs
  rpc/src/v1/impls/signer.rs
  rpc/src/v1/impls/signing.rs
  rpc/src/v1/impls/signing_unsafe.rs
  rpc/src/v1/tests/mocked/parity.rs
  rpc/src/v1/tests/mocked/personal.rs
  rpc/src/v1/tests/mocked/signer.rs
  rpc/src/v1/tests/mocked/signing.rs
Labels: A0-pleasereview, M4-core

#8749 parity: bump stable version to 1.10.5
  Cargo.lock
  Cargo.toml
  mac/Parity.pkgproj
  nsis/installer.nsi
  util/journaldb/src/earlymergedb.rs
  util/journaldb/src/refcounteddb.rs
  util/version/Cargo.toml
Labels: A2-insubstantial, A8-backport, A8-looksgood, M2-installer

#8743 Conditionally compile ethcore public test helpers
  ethcore/Cargo.toml
  ethcore/private-tx/Cargo.toml
  ethcore/src/client/mod.rs
  ethcore/src/lib.rs
  ethcore/src/spec/spec.rs
  ethcore/sync/Cargo.toml
Labels: A8-looksgood, F6-refactor, M4-core

#8782 [stable] Backports
  ethcore/src/spec/spec.rs
  mac/post-install.sh
  rpc/src/v1/helpers/light_fetch.rs
  rpc/src/v1/tests/eth.rs
  rpc/src/v1/types/uint.rs
  util/network/src/host.rs
  util/network/src/node_table.rs
Labels: A8-backport, M4-core

#8785 [beta] Backports
  .gitlab-ci.yml
  Cargo.lock
  ethcore/service/src/service.rs
  ethcore/src/client/client.rs
  ethcore/src/snapshot/service.rs
  ethcore/src/snapshot/tests/service.rs
  ethcore/src/snapshot/traits.rs
  ethcore/src/spec/spec.rs
  ethcore/sync/src/blocks.rs
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/supplier.rs
  ethcore/sync/src/snapshot.rs
  ethcore/sync/src/tests/snapshot.rs
  ethcore/types/src/restoration_status.rs
  mac/post-install.sh
  miner/src/pool/scoring.rs
  miner/src/pool/tests/mod.rs
  parity/informant.rs
  parity/run.rs
  parity/snapshot.rs
  rpc/Cargo.toml
  rpc/src/v1/helpers/light_fetch.rs
  rpc/src/v1/tests/eth.rs
  rpc/src/v1/tests/helpers/snapshot_service.rs
  rpc/src/v1/types/uint.rs
  util/network-devp2p/src/host.rs
  util/network/Cargo.toml
  util/network/src/error.rs
  util/network/src/lib.rs
Labels: A8-backport, M4-core

#8786 rpc: fix address formatting in TransactionRequest Display
  rpc/src/v1/types/transaction_request.rs
Labels: A2-insubstantial, A8-looksgood, M6-rpcapi, M7-signer

#8791 Have space between feature cfg flag
  dapps/js-glue/src/js.rs
  ethcore/evm/src/lib.rs
  ethcore/src/client/mod.rs
  ethcore/src/lib.rs
  ethcore/src/spec/spec.rs
  parity/lib.rs
  parity/secretstore.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8795 Fix evmbin compilation
  evmbin/Cargo.toml
Labels: A8-looksgood, M4-core

#8802 Disallow unsigned transactions in case EIP-86 is disabled
  ethcore/src/ethereum/mod.rs
  ethcore/src/machine.rs
  ethcore/src/verification/verification.rs
  ethcore/transaction/src/transaction.rs
Labels: A0-pleasereview, B0-patchthis, B9-blocker, M4-core

#8751 Fix ancient blocks queue deadlock
  ethcore/src/client/client.rs
  miner/src/pool/queue.rs
Labels: A0-pleasereview, B0-patchthis, B9-blocker, M4-core, P2-asap

#8807 [Backports] old stable 1.8
  ethcore/src/transaction.rs
Labels: A8-backport

#8808 [Backports] old stable 1.9
  ethcore/src/transaction.rs
Labels: A8-backport, M4-core

#8809 [Backports] old stable 1.7
  ethcore/src/transaction.rs
Labels: A8-backport, M4-core

#8806 parity-version: bump beta to 1.11.3
  Cargo.lock
  Cargo.toml
  ethcore/src/client/client.rs
  ethcore/src/ethereum/mod.rs
  ethcore/src/machine.rs
  ethcore/src/verification/verification.rs
  ethcore/transaction/src/transaction.rs
  mac/Parity.pkgproj
  miner/src/pool/queue.rs
  nsis/installer.nsi
  util/version/Cargo.toml
Labels: A8-backport, M2-installer, M4-core

#8805 parity-version: bump stable to 1.10.6
  Cargo.lock
  Cargo.toml
  ethcore/src/ethereum/mod.rs
  ethcore/src/machine.rs
  ethcore/src/verification/verification.rs
  ethcore/transaction/src/transaction.rs
  mac/Parity.pkgproj
  nsis/installer.nsi
  util/version/Cargo.toml
Labels: A8-backport, M2-installer, M4-core

#8810 docs: add changelogs for 1.10.6 and 1.11.3
  CHANGELOG.md
  docs/CHANGELOG-1.10.md
Labels: A2-insubstantial, A8-looksgood, M3-docs

#8778 Remove windows tray and installer
  .gitlab-ci.yml
  Cargo.lock
  nsis/installer.nsi
  nsis/logo.ico
  scripts/gitlab-build.sh
  windows/ptray/ptray.cpp
  windows/ptray/ptray.ico
  windows/ptray/ptray.rc
  windows/ptray/ptray.vcxproj
  windows/ptray/resource.h
  windows/ptray/targetver.h
Labels: A8-looksgood, B1-releasenotes, M2-installer, P2-asap

#8783 Remove UI related settings from CLI
  Cargo.lock
  Cargo.toml
  dapps/Cargo.toml
  dapps/src/apps/fetcher/installers.rs
  dapps/src/apps/fetcher/mod.rs
  dapps/src/apps/fs.rs
  dapps/src/apps/mod.rs
  dapps/src/apps/ui.rs
  dapps/src/error_tpl.html
  dapps/src/handlers/content.rs
  dapps/src/handlers/echo.rs
  dapps/src/handlers/errors.rs
  dapps/src/handlers/fetch.rs
  dapps/src/handlers/mod.rs
  dapps/src/handlers/streaming.rs
  dapps/src/lib.rs
  dapps/src/page/builtin.rs
  dapps/src/page/handler.rs
  dapps/src/page/local.rs
  dapps/src/proxypac.rs
  dapps/src/router.rs
  dapps/src/tests/fetch.rs
  dapps/src/tests/helpers/mod.rs
  dapps/src/tests/home.rs
  dapps/src/tests/mod.rs
  dapps/src/tests/redirection.rs
  dapps/src/tests/validation.rs
  dapps/src/web.rs
  dapps/ui-deprecation/Cargo.toml
  dapps/ui-deprecation/build.rs
  dapps/ui-deprecation/build/index.html
  dapps/ui-deprecation/src/lib.rs
  dapps/ui-deprecation/src/lib.rs.in
  dapps/ui/Cargo.toml
  dapps/ui/src/lib.rs
  parity/cli/mod.rs
  parity/configuration.rs
  parity/dapps.rs
  parity/lib.rs
  parity/rpc.rs
  parity/run.rs
  parity/signer.rs
Labels: A8-looksgood, M7-ui

#8819 Removed obsolete IpcMode enum
  ethcore/src/client/client.rs
  ethcore/src/client/config.rs
  ethcore/src/client/test_client.rs
  ethcore/src/client/traits.rs
  ethcore/types/src/lib.rs
  ethcore/types/src/mode.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/impls/parity_set.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8794 parity: fix indentation in sync logging
  parity/informant.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8822 CI: Fix docker tags
  .gitlab-ci.yml
Labels: A2-insubstantial, A8-looksgood, B0-patchthis, M1-ci

#8832 ethcore: fix ancient block import error handling
  ethcore/src/client/client.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#8756 added from and to to Receipt
  ethcore/src/client/client.rs
  ethcore/types/src/receipt.rs
  rpc/src/v1/tests/mocked/eth.rs
  rpc/src/v1/types/receipt.rs
Labels: A8-looksgood, M6-rpcapi

#8831 Use system allocator when profiling memory
  Cargo.toml
  parity/lib.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8824 Fix `deadlock_detection` feature branch compilation
  parity/lib.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8821 Specify critical release flag per network
  util/version/Cargo.toml
Labels: A8-looksgood, M4-core

#8803 Fixed AuthorityRound deadlock on shutdown
  ethcore/src/engines/authority_round/mod.rs
Labels: A0-pleasereview, B0-patchthis, M4-core

#8790 devp2p: Move UDP socket handling from Discovery to Host.
  util/network-devp2p/src/discovery.rs
  util/network-devp2p/src/host.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#8834 Disable parallel verification and skip verifiying already imported txs.
  Cargo.lock
  miner/Cargo.toml
  miner/src/lib.rs
  miner/src/pool/queue.rs
  miner/src/pool/tests/client.rs
  miner/src/pool/tests/mod.rs
  miner/src/pool/verifier.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#8828 Clearing up the reason behind "Ethereum Signed Message"
  rpc/src/v1/helpers/dispatch.rs
Labels: A2-insubstantial, A8-looksgood, M3-docs

#8784 network-devp2p: downgrade logging to debug, add target
  util/network-devp2p/src/discovery.rs
Labels: A2-insubstantial, M4-core

#8863 Fix CLI return code on --help for ethkey, ethstore & whisper
  ethkey/cli/src/main.rs
  ethstore/cli/src/main.rs
  whisper/cli/src/main.rs
Labels: A0-pleasereview, M4-core

#8856 parity-version: beta release 1.11.4
  Cargo.lock
  Cargo.toml
  mac/Parity.pkgproj
  nsis/installer.nsi
  util/version/Cargo.toml
Labels: A8-backport, A8-looksgood, M2-installer

#8867 Don't allocate in expect_valid_rlp unless necessary
  ethcore/src/views/view_rlp.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#8844 Use sealing.enabled to emit eth_mining information
  ethcore/src/miner/miner.rs
Labels: A8-looksgood, M4-core

#8777 Limit the number of transactions in pending set
  Cargo.lock
  ethcore/light/src/net/mod.rs
  ethcore/light/src/net/tests/mod.rs
  ethcore/light/src/provider.rs
  ethcore/src/client/client.rs
  ethcore/src/client/test_client.rs
  ethcore/src/client/traits.rs
  ethcore/src/miner/miner.rs
  ethcore/src/miner/mod.rs
  ethcore/src/tests/client.rs
  ethcore/sync/src/api.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/propagator.rs
  miner/src/lib.rs
  miner/src/pool/mod.rs
  miner/src/pool/queue.rs
  miner/src/pool/tests/mod.rs
  parity/rpc_apis.rs
  rpc/Cargo.toml
  rpc/src/v1/impls/eth_filter.rs
  rpc/src/v1/impls/eth_pubsub.rs
  rpc/src/v1/impls/light/parity.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/tests/helpers/miner_service.rs
  rpc/src/v1/tests/mocked/eth_pubsub.rs
  rpc/src/v1/traits/parity.rs
  transaction-pool/Cargo.toml
  transaction-pool/src/pool.rs
  transaction-pool/src/tests/mod.rs
Labels: A8-looksgood, M4-core

#8400 Tx permission contract improvement
  ethcore/res/contracts/tx_acl.json
  ethcore/res/contracts/tx_acl_deprecated.json
  ethcore/res/tx_permission_tests/contract_ver_2_genesis.json
  ethcore/res/tx_permission_tests/deprecated_contract_genesis.json
  ethcore/src/tx_filter.rs
Labels: A0-pleasereview, M4-core

#8854 Fix concurrent access to signer queue
  rpc/src/v1/helpers/mod.rs
  rpc/src/v1/helpers/signing_queue.rs
  rpc/src/v1/impls/signer.rs
  rpc/src/v1/tests/mocked/signing.rs
Labels: A8-looksgood, B0-patchthis, M6-rpcapi

#8864 README.md: update the list of dependencies
  README.md
Labels: A8-looksgood, M3-docs, M5-dependencies

#8875 Remove mac os installers etc
  mac/Parity Ethereum.xcodeproj/project.pbxproj
  mac/Parity Ethereum.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  mac/Parity.pkgproj
  mac/Parity/AppDelegate.swift
  mac/Parity/Assets.xcassets/AppIcon.appiconset/Contents.json
  mac/Parity/Assets.xcassets/AppIcon.appiconset/Parity.png
  mac/Parity/Assets.xcassets/Contents.json
  mac/Parity/Assets.xcassets/statusIcon.imageset/Contents.json
  mac/Parity/Assets.xcassets/statusIcon.imageset/Parity-1.png
  mac/Parity/Assets.xcassets/statusIcon.imageset/Parity-2.png
  mac/Parity/Assets.xcassets/statusIcon.imageset/Parity.png
  mac/Parity/Base.lproj/MainMenu.xib
  mac/Parity/GetBSDProcessList.swift
  mac/Parity/Info.plist
  mac/install-licence.txt
  mac/install-readme.txt
  mac/post-install.sh
  mac/uninstall-parity.sh
  scripts/gitlab-build.sh
Labels: A8-looksgood, M2-installer

#8878 docker: Fix alpine build
  docker/alpine/Dockerfile
Labels: A2-insubstantial, M1-ci

#8853 Check whether we need resealing in miner and unwrap has_account in account_provider
  ethcore/src/account_provider/mod.rs
  ethcore/src/miner/miner.rs
  ethcore/src/miner/pool_client.rs
  ethcore/src/snapshot/tests/proof_of_authority.rs
  parity/run.rs
  parity/secretstore.rs
Labels: A8-looksgood, M4-core

#8868 hardware_wallet/Ledger `Sign messages` + some refactoring
  Cargo.lock
  ethcore/src/account_provider/mod.rs
  hw/Cargo.toml
  hw/src/ledger.rs
  hw/src/lib.rs
  hw/src/trezor.rs
  rpc/src/v1/helpers/dispatch.rs
Labels: A8-looksgood, M4-core

#8876 update jsonrpc libs, fixed ipc leak
  Cargo.lock
Labels: A8-looksgood, B0-patchthis, M4-core, M6-rpcapi

#8796 Handle removed logs in filter changes and add geth compatibility field
  rpc/src/v1/helpers/poll_filter.rs
  rpc/src/v1/impls/eth_filter.rs
  rpc/src/v1/impls/eth_pubsub.rs
  rpc/src/v1/impls/light/eth.rs
  rpc/src/v1/tests/mocked/eth.rs
  rpc/src/v1/tests/mocked/eth_pubsub.rs
  rpc/src/v1/types/log.rs
  rpc/src/v1/types/receipt.rs
Labels: A8-looksgood, B0-patchthis, M6-rpcapi

#8435 SecretStore: service pack 1
  parity/cli/mod.rs
  parity/cli/tests/config.full.toml
  parity/configuration.rs
  parity/secretstore.rs
  secret_store/src/acl_storage.rs
  secret_store/src/key_server.rs
  secret_store/src/key_server_cluster/admin_sessions/key_version_negotiation_session.rs
  secret_store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs
  secret_store/src/key_server_cluster/admin_sessions/share_add_session.rs
  secret_store/src/key_server_cluster/admin_sessions/share_change_session.rs
  secret_store/src/key_server_cluster/client_sessions/decryption_session.rs
  secret_store/src/key_server_cluster/cluster.rs
  secret_store/src/key_server_cluster/cluster_sessions.rs
  secret_store/src/key_server_cluster/cluster_sessions_creator.rs
  secret_store/src/key_server_cluster/connection_trigger.rs
  secret_store/src/key_server_cluster/jobs/key_access_job.rs
  secret_store/src/key_server_cluster/message.rs
  secret_store/src/key_server_set.rs
  secret_store/src/key_storage.rs
  secret_store/src/lib.rs
  secret_store/src/listener/service_contract.rs
  secret_store/src/listener/service_contract_listener.rs
  secret_store/src/trusted_client.rs
  secret_store/src/types/all.rs
Labels: A8-looksgood, M4-core

#8886 Add new ovh bootnodes and fix port for foundation bootnode 3.2
  ethcore/res/ethereum/foundation.json
Labels: A8-looksgood, M2-config

#8889 Fix some warns on nightly
  ethcore/src/engines/authority_round/mod.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8870 Add support for --chain tobalaba
  ethcore/res/ethereum/tobalaba.json
  ethcore/src/ethereum/mod.rs
  parity/cli/mod.rs
  parity/params.rs
Labels: A8-looksgood, M2-config

#8892 Add ETC Cooperative-run load balanced parity-based bootnode
  ethcore/res/ethereum/classic.json
Labels: A8-looksgood, M2-config

#8896 Atomic create new files with permissions to owner in ethstore
  ethstore/src/accounts_dir/disk.rs
Labels: A8-looksgood, M4-core

#8901 fixed osx create file permissions
  ethstore/src/accounts_dir/disk.rs
Labels: A8-looksgood, M4-core

#8891 Block 0 is valid in queries
  ethcore/src/client/client.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#8906 Minor fix in chain supplier and light provider
  ethcore/light/src/provider.rs
  ethcore/sync/src/chain/supplier.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#8913 Remove a weird emoji in new_social docs
  ethcore/src/ethereum/mod.rs
Labels: A2-insubstantial, M2-config

#8887 Remove debian/.deb and centos/.rpm packaging scripts
  .gitlab-ci.yml
  scripts/deb-build.sh
  scripts/gitlab-build.sh
  test.sh
Labels: A8-looksgood, M1-ci, M5-binaries

#8890 Hardware-wallets `Clean up things I missed in the latest PR`
  hw/src/ledger.rs
  hw/src/lib.rs
  hw/src/trezor.rs
Labels: A8-looksgood, M4-core

#8915 cleanup nibbleslice
  util/patricia_trie/src/nibbleslice.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8885 Allow Poll Lifetime to be configured via CLI
  parity/cli/mod.rs
  parity/configuration.rs
  parity/rpc_apis.rs
  parity/run.rs
  rpc/src/v1/helpers/poll_manager.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/impls/eth_filter.rs
  rpc/src/v1/impls/light/eth.rs
  rpc/src/v1/tests/mocked/eth.rs
Labels: A8-looksgood, M6-rpcapi

#8882 Allow disabling local-by-default for transactions with new config entry
  ethcore/src/miner/miner.rs
  ethcore/src/miner/mod.rs
  parity/cli/mod.rs
  parity/cli/tests/config.full.toml
  parity/configuration.rs
  rpc/src/v1/helpers/dispatch.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/tests/helpers/miner_service.rs
Labels: A8-looksgood, B1-releasenotes, B9-blocker, M4-core

#8830 Include node identity in the P2P advertised client version.
  parity/configuration.rs
Labels: A8-looksgood, M4-core

#8919 [stable] Backports
  .gitlab-ci.yml
  Cargo.lock
  ethcore/light/src/provider.rs
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/foundation.json
  ethcore/src/client/client.rs
  ethcore/src/engines/authority_round/mod.rs
  rpc/src/v1/helpers/mod.rs
  rpc/src/v1/helpers/signing_queue.rs
  rpc/src/v1/impls/signer.rs
  rpc/src/v1/tests/mocked/signing.rs
  sync/src/chain.rs
Labels: A8-backport, M4-core

#8916 [beta] Backports
  .gitlab-ci.yml
  Cargo.lock
  ethcore/light/src/provider.rs
  ethcore/private-tx/src/lib.rs
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/foundation.json
  ethcore/src/account_provider/mod.rs
  ethcore/src/blockchain/import_route.rs
  ethcore/src/client/chain_notify.rs
  ethcore/src/client/client.rs
  ethcore/src/client/mod.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/miner/miner.rs
  ethcore/src/miner/mod.rs
  ethcore/src/miner/pool_client.rs
  ethcore/src/snapshot/tests/proof_of_authority.rs
  ethcore/src/snapshot/watcher.rs
  ethcore/src/views/view_rlp.rs
  ethcore/sync/src/api.rs
  ethcore/sync/src/chain/supplier.rs
  ethcore/sync/src/tests/helpers.rs
  miner/Cargo.toml
  miner/src/lib.rs
  miner/src/pool/queue.rs
  miner/src/pool/tests/client.rs
  miner/src/pool/tests/mod.rs
  miner/src/pool/verifier.rs
  parity/cli/mod.rs
  parity/cli/tests/config.full.toml
  parity/configuration.rs
  parity/informant.rs
  parity/run.rs
  parity/secretstore.rs
  rpc/src/v1/helpers/dispatch.rs
  rpc/src/v1/helpers/mod.rs
  rpc/src/v1/helpers/poll_filter.rs
  rpc/src/v1/helpers/signing_queue.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/impls/eth_filter.rs
  rpc/src/v1/impls/eth_pubsub.rs
  rpc/src/v1/impls/light/eth.rs
  rpc/src/v1/impls/signer.rs
  rpc/src/v1/tests/helpers/miner_service.rs
  rpc/src/v1/tests/mocked/eth.rs
  rpc/src/v1/tests/mocked/eth_pubsub.rs
  rpc/src/v1/tests/mocked/signing.rs
  rpc/src/v1/types/log.rs
  rpc/src/v1/types/receipt.rs
  secret_store/src/acl_storage.rs
  secret_store/src/key_server_set.rs
  secret_store/src/listener/service_contract_listener.rs
  updater/src/updater.rs
Labels: A8-backport, M4-core

#8926 Update Ropsten forkblock at 3383558
  ethcore/res/ethereum/ropsten.json
Labels: A0-pleasereview, A2-insubstantial, B0-patchthis, M2-config

#8910 ethstore: retry deduplication of wallet file names until success
  ethstore/src/accounts_dir/disk.rs
Labels: A8-looksgood, M4-core

#8925 Update hardcoded headers
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/ropsten.json
Labels: A8-looksgood, B0-patchthis, M2-config

#8941 Fixed blooms dir creation
  ethcore/src/test_helpers.rs
  parity/db/rocksdb/mod.rs
Labels: A8-looksgood, M4-core

#8936 ethcore: fix compilation when using slow-blocks or evm-debug features
  ethcore/Cargo.toml
  ethcore/evm/src/interpreter/informant.rs
  ethcore/src/block.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8931 docs: update changelogs
  CHANGELOG.md
  docs/CHANGELOG-1.10.md
Labels: A8-looksgood, M3-docs

#8943 rpc: cap gas limit of local calls
  rpc/src/v1/helpers/fake_sign.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#8930 scripts: minor improvements
  .gitlab-ci.yml
  scripts/gitlab-build.sh
Labels: A8-looksgood, B0-patchthis, M1-ci

#8949 Print public key of the SS node on start
  parity/secretstore.rs
Labels: A8-looksgood, M4-core

#8932 Restrict vault.json permssion to owner and using random suffix for temp vault.json file
  ethstore/src/accounts_dir/disk.rs
  ethstore/src/accounts_dir/vault.rs
Labels: A0-pleasereview, M4-core

#8879 Eliminate some more `transmute()`
  ethash/src/compute.rs
  util/network-devp2p/src/ip_utils.rs
Labels: A8-looksgood, M4-core

#8953 deps: bump fs-swap
  Cargo.lock
Labels: A2-insubstantial, A8-looksgood, M5-dependencies

#8952 scripts: fix docker build tag on latest using master
  scripts/docker-build.sh
Labels: A0-pleasereview, B0-patchthis, M1-ci

#8951 Bump stable to 1.10.8
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/res/ethereum/ropsten.json
  mac/Parity.pkgproj
  nsis/installer.nsi
  rpc/src/v1/helpers/fake_sign.rs
  scripts/docker-build.sh
  scripts/gitlab-build.sh
  util/version/Cargo.toml
Labels: A8-backport, M1-ci, M2-config, M6-rpcapi

#8967 parity: hide legacy options from cli --help
  parity/cli/mod.rs
  parity/cli/usage.rs
Labels: A2-insubstantial, A8-looksgood, B1-releasenotes, M2-config

#8972 Bump error-chain and quick_error versions
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/crypto/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/private-tx/Cargo.toml
  ethcore/service/Cargo.toml
  ethkey/Cargo.toml
  miner/Cargo.toml
  transaction-pool/Cargo.toml
  util/error/Cargo.toml
  util/kvdb/Cargo.toml
  util/migration-rocksdb/Cargo.toml
  util/network-devp2p/Cargo.toml
  util/network/Cargo.toml
Labels: A0-pleasereview, M4-core

#8464 Disable hardware-wallets on platforms that don't support `libusb`
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/src/account_provider/mod.rs
  ethcore/src/lib.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  rpc/src/v1/helpers/dispatch.rs
  rpc/src/v1/impls/light/parity.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/impls/parity_accounts.rs
  util/fake-hardware-wallet/Cargo.toml
  util/fake-hardware-wallet/src/lib.rs
Labels: A8-looksgood, M4-core, M5-dependencies

#8962 parity: omit redundant last imported block number in light sync informant
  parity/informant.rs
Labels: A8-looksgood, M4-core

#8983 Use local parity-dapps-glue instead of crate published at crates.io
  Cargo.lock
  Cargo.toml
  dapps/Cargo.toml
Labels: A8-looksgood, M5-dependencies, M8-dapp, P2-asap

#8984 snap: downgrade rust to revision 1.26.2, ref snapcraft/+bug/1778530
  snap/snapcraft.yaml
Labels: A8-looksgood, B0-patchthis, M1-ci

#8977 Fix deadlock in blockchain.
  ethcore/src/blockchain/blockchain.rs
Labels: A7-looksgoodtestsfail, B0-patchthis, M4-core

#8914 Refactor evm Instruction to be a c-like enum
  ethcore/evm/src/instructions.rs
  ethcore/evm/src/interpreter/gasometer.rs
  ethcore/evm/src/interpreter/mod.rs
  ethcore/evm/src/interpreter/shared_cache.rs
  ethcore/evm/src/lib.rs
  evmbin/src/display/json.rs
  evmbin/src/display/std_json.rs
Labels: A8-looksgood, F6-refactor, M4-core

#8980 Improve should_replace on NonceAndGasPrice
  miner/src/pool/mod.rs
  miner/src/pool/scoring.rs
  miner/src/pool/tests/tx.rs
Labels: A8-looksgood, M4-core

#8995 Preserve the current abort behavior
  util/panic_hook/src/lib.rs
Labels: A8-looksgood, M4-core

#9003 Fix Android build on beta
  parity/url.rs
Labels: A0-pleasereview, A8-backport, M4-core

#8986 Stable: Backports
  Cargo.lock
  Cargo.toml
  ethcore/src/blockchain/blockchain.rs
  snap/snapcraft.yaml
Labels: A8-backport, M1-ci, M4-core, M5-dependencies

#8955 Bump beta to 1.11.5 / Backports
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/ropsten.json
  ethcore/src/blockchain/blockchain.rs
  mac/Parity.pkgproj
  nsis/installer.nsi
  parity/url.rs
  rpc/src/v1/helpers/fake_sign.rs
  scripts/docker-build.sh
  scripts/gitlab-build.sh
  snap/snapcraft.yaml
  util/version/Cargo.toml
Labels: A8-backport, M1-ci, M2-config, M6-rpcapi

#8934 Minimal effective gas price in the queue
  miner/src/pool/queue.rs
  miner/src/pool/scoring.rs
  miner/src/pool/tests/mod.rs
  miner/src/pool/verifier.rs
  transaction-pool/src/pool.rs
  transaction-pool/src/tests/mod.rs
Labels: A8-looksgood, B0-patchthis, M4-core
