Repository openethereum/openethereum, pull requests merged in 2018-12, with the labels that each got.

#9979 Add tokio runtime to ethcore io worker
  Cargo.lock
  util/io/Cargo.toml
  util/io/src/lib.rs
  util/io/src/worker.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9761 Version and notification for private contract wrapper added
  ethcore/private-tx/res/private.evm
  ethcore/private-tx/res/private.json
  ethcore/private-tx/src/lib.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9988 LenCachingMutex
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/src/lib.rs
  ethcore/src/verification/queue/mod.rs
  util/len-caching-mutex/Cargo.toml
  util/len-caching-mutex/src/lib.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#9790 light client : failsafe crate (circuit breaker)
  Cargo.lock
  ethcore/light/Cargo.toml
  ethcore/light/src/lib.rs
  ethcore/light/src/on_demand/mod.rs
  ethcore/light/src/on_demand/request_guard.rs
  ethcore/light/src/on_demand/response_guard.rs
  ethcore/light/src/on_demand/tests.rs
  parity/cli/mod.rs
  parity/cli/tests/config.full.toml
  parity/cli/tests/config.toml
  parity/configuration.rs
  parity/run.rs
  rpc/src/v1/helpers/errors.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10016 light(on_demand): decrease default time window to 10 secs
  ethcore/light/src/on_demand/mod.rs
  parity/cli/mod.rs
  parity/cli/tests/config.full.toml
  parity/cli/tests/config.toml
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, M4-core ⛓

#10017 ci: move future releases to ethereum subdir on s3
  scripts/gitlab/publish-awss3.sh
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉, P2-asap 🌊

#10020 patch beta release pipeline
  Cargo.lock
  Cargo.toml
  ethcore/src/state/mod.rs
  scripts/gitlab/publish-awss3.sh
  util/version/Cargo.toml
Labels: A0-pleasereview 🤓, A8-backport 🕸, M1-ci 🙉

#10019 Fix test: corpus_inaccessible (panic)
  ethcore/light/src/cache.rs
Labels: A8-looksgood 🦄, B1-patch-beta 🕷🕷, M4-core ⛓

#10018 Sort the storage for the private state
  ethcore/private-tx/src/lib.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10024 Change test miner max memory to support malloc allocator
  miner/src/pool/tests/mod.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10034 Center the Subtitle, use some CAPS
  README.md
Labels: A2-insubstantial 👶, M3-docs 📑

#10041 Strict empty steps validation
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/validator_set/test.rs
  json/src/spec/authority_round.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, B7-releasenotes 📜, M4-core ⛓

#10031 ethcore: enable constantinople on ethereum
  ethcore/res/ethereum/foundation.json
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#10048 Bump crossbeam.
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/src/executive.rs
  ethcore/src/snapshot/mod.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10050 Update parking_lot to 0.7
  Cargo.lock
  Cargo.toml
  ethash/Cargo.toml
  ethcore/Cargo.toml
  ethcore/evm/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/node_filter/Cargo.toml
  ethcore/private-tx/Cargo.toml
  ethcore/stratum/Cargo.toml
  ethcore/sync/Cargo.toml
  ethstore/Cargo.toml
  ethstore/cli/Cargo.toml
  hash-fetch/Cargo.toml
  hw/Cargo.toml
  logger/Cargo.toml
  miner/Cargo.toml
  price-info/Cargo.toml
  rpc/Cargo.toml
  rpc_client/Cargo.toml
  secret_store/Cargo.toml
  updater/Cargo.toml
  util/blooms-db/Cargo.toml
  util/io/Cargo.toml
  util/journaldb/Cargo.toml
  util/len-caching-mutex/Cargo.toml
  util/network-devp2p/Cargo.toml
  whisper/Cargo.toml
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10047 Backports for beta 2.2.5
  Cargo.lock
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/light/src/cache.rs
  ethcore/res/ethereum/foundation.json
  ethcore/src/client/client.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/validator_set/test.rs
  ethcore/src/executive.rs
  ethcore/src/snapshot/mod.rs
  json/src/spec/authority_round.rs
  miner/src/pool/tests/mod.rs
  util/version/Cargo.toml
Labels: A0-pleasereview 🤓, A8-backport 🕸, M4-core ⛓

#10032 Implement len caching for parking_lot RwLock
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/src/lib.rs
  ethcore/src/verification/queue/mod.rs
  util/len-caching-lock/Cargo.toml
  util/len-caching-lock/src/lib.rs
  util/len-caching-lock/src/mutex.rs
  util/len-caching-lock/src/rwlock.rs
Labels: M4-core ⛓

#10064 Update changelog update for 2.2.5-beta and 2.1.10-stable
  CHANGELOG.md
  docs/CHANGELOG-2.1.md
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M3-docs 📑

#9938 Fill transaction hash on ethGetLog of light client.
  rpc/src/v1/helpers/light_fetch.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/impls/light/parity.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/traits/parity.rs
Labels: A8-looksgood 🦄, B1-patch-beta 🕷🕷, M4-core ⛓, M6-rpcapi 📣

#10081 Add --frozen when running cargo
  test.sh
Labels: A2-insubstantial 👶, M0-build 🏗, M1-ci 🙉

#10105 Revert "Add --frozen when running cargo (#10081)"
  test.sh
Labels: A0-pleasereview 🤓, M0-build 🏗

#10106 Move EIP-712 crate back to parity-ethereum
  Cargo.lock
  rpc/Cargo.toml
  rpc/src/lib.rs
  rpc/src/v1/helpers/eip191.rs
  rpc/src/v1/impls/personal.rs
  rpc/src/v1/traits/personal.rs
  util/EIP-712/Cargo.toml
  util/EIP-712/README.md
  util/EIP-712/src/eip712.rs
  util/EIP-712/src/encode.rs
  util/EIP-712/src/lib.rs
  util/EIP-712/src/parser.rs
Labels: A2-insubstantial 👶, M4-core ⛓

#10107 Follow-up to #10105
  test.sh
Labels: A8-looksgood 🦄, M1-ci 🙉
