Repository openethereum/openethereum, pull requests merged in 2018-07, with the labels that each got.

#9021 Removed duplicate dependency
  rpc/Cargo.toml
Labels: A8-looksgood, M5-dependencies

#8924 simplify kvdb error types
  Cargo.lock
  ethcore/light/src/client/header_chain.rs
  ethcore/src/blockchain/blockchain.rs
  ethcore/src/client/client.rs
  ethcore/src/client/error.rs
  ethcore/src/client/evm_test_client.rs
  ethcore/src/error.rs
  ethcore/src/test_helpers.rs
  local-store/src/lib.rs
  parity/db/rocksdb/migration.rs
  parity/db/rocksdb/mod.rs
  secret_store/src/types/error.rs
  util/error/Cargo.toml
  util/error/src/lib.rs
  util/kvdb-memorydb/src/lib.rs
  util/kvdb-rocksdb/src/lib.rs
  util/kvdb/Cargo.toml
  util/kvdb/src/lib.rs
  util/migration-rocksdb/Cargo.toml
  util/migration-rocksdb/src/lib.rs
  util/migration-rocksdb/tests/tests.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#8999 Attempt to graceful shutdown in case of panics
  ethkey/cli/src/main.rs
  ethstore/cli/src/main.rs
  evmbin/src/main.rs
  parity/main.rs
  util/panic_hook/src/lib.rs
  whisper/cli/src/main.rs
Labels: A8-looksgood, M4-core

#9012 Update Changelogs for 1.10.8 and 1.11.5
  CHANGELOG.md
  docs/CHANGELOG-1.10.md
Labels: A2-insubstantial, A8-looksgood, M3-docs

#9025 Only return error log for rustls
  logger/src/lib.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#9005 Recently rejected cache for transaction queue
  ethcore/src/client/client.rs
  ethcore/src/client/config.rs
  ethcore/src/verification/mod.rs
  ethcore/sync/src/chain/mod.rs
  miner/src/pool/queue.rs
  miner/src/pool/tests/mod.rs
  parity/blockchain.rs
  parity/run.rs
  parity/snapshot.rs
  parity/user_defaults.rs
  util/journaldb/src/lib.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#9027 Precise HTTP or WebSockets for JSON-RPC options
  parity/cli/mod.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#9002 Never drop local transactions from different senders.
  miner/src/pool/scoring.rs
  miner/src/pool/tests/mod.rs
  transaction-pool/src/pool.rs
  transaction-pool/src/scoring.rs
  transaction-pool/src/tests/helpers.rs
  transaction-pool/src/tests/mod.rs
Labels: A8-looksgood, B0-patchthis, B1-releasenotes, M4-core

#9013 bump parking_lot to 0.6
  Cargo.lock
  Cargo.toml
  dapps/Cargo.toml
  dapps/node-health/Cargo.toml
  ethash/Cargo.toml
  ethcore/Cargo.toml
  ethcore/evm/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/node_filter/Cargo.toml
  ethcore/private-tx/Cargo.toml
  ethcore/stratum/Cargo.toml
  ethcore/sync/Cargo.toml
  ethcore/wasm/Cargo.toml
  ethcore/wasm/src/parser.rs
  ethstore/Cargo.toml
  ethstore/cli/Cargo.toml
  hash-fetch/Cargo.toml
  hw/Cargo.toml
  logger/Cargo.toml
  miner/Cargo.toml
  price-info/Cargo.toml
  rpc/Cargo.toml
  rpc_client/Cargo.toml
  secret_store/Cargo.toml
  updater/Cargo.toml
  util/blooms-db/Cargo.toml
  util/io/Cargo.toml
  util/journaldb/Cargo.toml
  util/kvdb-memorydb/Cargo.toml
  util/kvdb-rocksdb/Cargo.toml
  util/network-devp2p/Cargo.toml
  whisper/Cargo.toml
Labels: A8-looksgood, M5-dependencies

#9032 Move the C/C++ example to another directory
  .gitignore
  parity-clib-examples/cpp/CMakeLists.txt
  parity-clib-examples/cpp/main.cpp
  test.sh
Labels: A6-mustntgrumble, M3-docs, M4-core

#9044 eip160/eip161 spec: u64 -> BlockNumber
  ethcore/src/spec/spec.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#9026 Optimize pending transactions filter
  ethcore/src/miner/miner.rs
  ethcore/src/miner/mod.rs
  miner/src/pool/queue.rs
  miner/src/pool/ready.rs
  rpc/src/v1/helpers/mod.rs
  rpc/src/v1/helpers/poll_filter.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/impls/eth_filter.rs
  rpc/src/v1/impls/light/eth.rs
  rpc/src/v1/tests/helpers/miner_service.rs
Labels: A0-pleasereview, B0-patchthis, B1-releasenotes, M4-core

#9038 Update ETSC bootnodes
  ethcore/res/ethereum/social.json
Labels: A2-insubstantial, A8-looksgood, M2-config

#9020 Introduce more optional features in ethcore
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/src/lib.rs
  ethcore/src/miner/miner.rs
  ethcore/src/miner/mod.rs
  ethcore/src/miner/stratum.rs
  miner/Cargo.toml
  miner/src/gas_price_calibrator.rs
  miner/src/gas_pricer.rs
  miner/src/lib.rs
  parity/params.rs
  parity/run.rs
Labels: A6-mustntgrumble, M0-build, M4-core, M5-dependencies

#9050 bump fs-swap to 0.2.3 so it is compatible with osx 10.11 again
  Cargo.lock
Labels: A0-pleasereview, B9-blocker, M4-core, P2-asap

#9043 reduce number of constraints for triedb types
  Cargo.lock
  util/hashdb/src/lib.rs
  util/patricia_trie/Cargo.toml
  util/patricia_trie/src/lib.rs
  util/patricia_trie/src/triedbmut.rs
Labels: A0-pleasereview, M4-core

#8998 Fixes for misbehavior reporting in AuthorityRound
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/validator_set/mod.rs
  ethcore/src/engines/validator_set/simple_list.rs
Labels: A8-looksgood, B0-patchthis, B9-blocker, M4-core, P2-asap

#9054 remove util-error
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/src/client/client.rs
  ethcore/src/client/config.rs
  ethcore/src/client/error.rs
  ethcore/src/error.rs
  ethcore/src/lib.rs
  ethcore/src/snapshot/service.rs
  ethcore/src/state_db.rs
  util/error/Cargo.toml
  util/error/src/lib.rs
  util/journaldb/Cargo.toml
  util/journaldb/src/archivedb.rs
  util/journaldb/src/earlymergedb.rs
  util/journaldb/src/lib.rs
  util/journaldb/src/overlaydb.rs
  util/journaldb/src/overlayrecentdb.rs
  util/journaldb/src/refcounteddb.rs
  util/journaldb/src/traits.rs
Labels: A8-looksgood, M4-core

#9016 Stable: 1.10.9 backports
  Cargo.lock
  Cargo.toml
  ethcore/res/ethereum/tobalaba.json
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/validator_set/mod.rs
  ethcore/src/engines/validator_set/simple_list.rs
  ethcore/src/ethereum/mod.rs
  logger/src/lib.rs
  mac/Parity.pkgproj
  nsis/installer.nsi
  parity/cli/mod.rs
  parity/params.rs
  scripts/gitlab-build.sh
  util/version/Cargo.toml
Labels: A0-pleasereview, A8-backport, M1-ci, M4-core

#9015 Beta: 1.11.6 backports
  Cargo.lock
  Cargo.toml
  ethcore/private-tx/src/lib.rs
  ethcore/res/ethereum/tobalaba.json
  ethcore/src/client/client.rs
  ethcore/src/client/config.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/validator_set/mod.rs
  ethcore/src/engines/validator_set/simple_list.rs
  ethcore/src/ethereum/mod.rs
  ethcore/src/miner/miner.rs
  ethcore/src/miner/mod.rs
  ethcore/src/miner/pool_client.rs
  ethcore/src/verification/mod.rs
  ethcore/sync/src/api.rs
  ethcore/sync/src/chain/mod.rs
  logger/src/lib.rs
  mac/Parity.pkgproj
  miner/src/lib.rs
  miner/src/pool/mod.rs
  miner/src/pool/queue.rs
  miner/src/pool/ready.rs
  miner/src/pool/scoring.rs
  miner/src/pool/tests/mod.rs
  miner/src/pool/tests/tx.rs
  miner/src/pool/verifier.rs
  nsis/installer.nsi
  parity/blockchain.rs
  parity/cli/mod.rs
  parity/params.rs
  parity/run.rs
  parity/snapshot.rs
  parity/user_defaults.rs
  rpc/src/v1/helpers/mod.rs
  rpc/src/v1/helpers/poll_filter.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/impls/eth_filter.rs
  rpc/src/v1/impls/light/eth.rs
  rpc/src/v1/tests/helpers/miner_service.rs
  scripts/gitlab-build.sh
  transaction-pool/Cargo.toml
  transaction-pool/src/error.rs
  transaction-pool/src/lib.rs
  transaction-pool/src/pool.rs
  transaction-pool/src/ready.rs
  transaction-pool/src/scoring.rs
  transaction-pool/src/tests/helpers.rs
  transaction-pool/src/tests/mod.rs
  transaction-pool/src/tests/tx_builder.rs
  transaction-pool/src/transactions.rs
  util/journaldb/src/lib.rs
  util/version/Cargo.toml
Labels: A0-pleasereview, A8-backport, M1-ci, M4-core, M6-rpcapi

#9066 fetch: replace futures-timer with tokio-timer
  Cargo.lock
  scripts/cov.sh
  util/fetch/Cargo.toml
  util/fetch/src/client.rs
  util/fetch/src/lib.rs
Labels: A0-pleasereview, M4-core

#9072 Enable test in `miner/pool/test`
  miner/src/pool/tests/mod.rs
Labels: A0-pleasereview, A2-insubstantial, M4-core

#9069 docs: add changelog for 1.10.9 stable and 1.11.6 beta
  CHANGELOG.md
  docs/CHANGELOG-1.10.md
Labels: A0-pleasereview, A2-insubstantial, M3-docs

#9055 remove trait bounds from several structs
  ethcore/src/cache_manager.rs
  ethcore/src/executive.rs
  ethcore/src/externalities.rs
  ethcore/src/state/mod.rs
  ethcore/types/src/account_diff.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#9063 SeedHashCompute remove needless `new` implementation
  ethash/src/cache.rs
  ethash/src/seed_compute.rs
  ethcore/src/miner/stratum.rs
  miner/src/work_notify.rs
  rpc/src/v1/impls/eth.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#9074 secret-store `fix warning in tests`
  secret_store/src/key_server_cluster/math.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#9077 Replace `std::env::home_dir` with `dirs::home_dir`
  Cargo.lock
  parity/upgrade.rs
  util/dir/Cargo.toml
  util/dir/src/helpers.rs
  util/dir/src/lib.rs
  util/path/Cargo.toml
  util/path/src/lib.rs
Labels: A8-looksgood, M4-core

#9036 Clean up deprecated options and add CHECK macro
  parity/cli/mod.rs
  parity/cli/usage.rs
  parity/deprecated.rs
Labels: A8-looksgood, M4-core, P5-sometimesoon

#9045 Some work towards iOS build
  Cargo.lock
  parity/url.rs
Labels: A8-looksgood, M4-core

#9060 Phrasing, precisions and typos in CLI help
  parity/cli/mod.rs
Labels: A2-insubstantial, A8-looksgood, M3-docs

#8787 Updater verification
  Cargo.toml
  ethcore/src/client/client.rs
  parity/configuration.rs
  parity/main.rs
  parity/run.rs
  updater/Cargo.toml
  updater/src/lib.rs
  updater/src/service.rs
  updater/src/types/version_info.rs
  updater/src/updater.rs
Labels: A8-looksgood, M4-core

#8883 Transactions hashes missing in trace_replayBlockTransactions method result #8725
  ethcore/src/client/client.rs
  ethcore/src/client/test_client.rs
  ethcore/src/client/traits.rs
  rpc/src/v1/impls/light/trace.rs
  rpc/src/v1/impls/traces.rs
  rpc/src/v1/tests/mocked/traces.rs
  rpc/src/v1/traits/traces.rs
  rpc/src/v1/types/mod.rs
  rpc/src/v1/types/trace.rs
Labels: A8-looksgood, M6-rpcapi

#8963 db: remove wal disabling / fast-and-loose option.
  Cargo.lock
  ethcore/service/src/service.rs
  ethcore/src/client/config.rs
  parity/blockchain.rs
  parity/cli/mod.rs
  parity/cli/tests/config.full.toml
  parity/configuration.rs
  parity/db/rocksdb/helpers.rs
  parity/db/rocksdb/migration.rs
  parity/db/rocksdb/mod.rs
  parity/deprecated.rs
  parity/export_hardcoded_sync.rs
  parity/helpers.rs
  parity/run.rs
  parity/snapshot.rs
  util/migration-rocksdb/src/lib.rs
Labels: A8-looksgood, M2-config

#9080 Fix nightly warnings
  parity/lib.rs
  rpc/src/v1/helpers/light_fetch.rs
Labels: A0-pleasereview, A1-onice, A2-insubstantial, M4-core

#9088 Fix OOM when restoring a Snapshot
  ethcore/sync/src/snapshot.rs
Labels: A8-looksgood, B0-patchthis, M4-core, P5-sometimesoon

#9052 Parity Ethereum 2.0.0
  Cargo.lock
  Cargo.toml
  ethcore/sync/src/chain/propagator.rs
  parity-clib/Cargo.toml
  parity-clib/src/lib.rs
  parity/configuration.rs
  parity/main.rs
  rpc/src/v1/tests/helpers/sync_provider.rs
  rpc/src/v1/tests/mocked/parity.rs
  util/version/Cargo.toml
  util/version/src/lib.rs
Labels: A8-looksgood, B9-blocker, M4-core, P2-asap

#9064 Add separate database directory for light client (#8927)
  parity/configuration.rs
  util/dir/src/lib.rs
Labels: A0-pleasereview, M4-core

#8771 Multiple improvements to discovery ping handling
  util/network-devp2p/src/discovery.rs
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/node_table.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#9097 Revert "Replace `std::env::home_dir` with `dirs::home_dir` (#9077)"
  Cargo.lock
  parity/upgrade.rs
  util/dir/Cargo.toml
  util/dir/src/helpers.rs
  util/dir/src/lib.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#9084 Update README.md
  README.md
Labels: A2-insubstantial, A8-looksgood, M3-docs

#9108 Update hidapi
  Cargo.lock
Labels: A0-pleasereview, B0-patchthis, M4-core

#9111 docker: add cmake dependency
  docker/alpine/Dockerfile
  docker/centos/Dockerfile
  docker/hub/Dockerfile
  docker/ubuntu-aarch64/Dockerfile
  docker/ubuntu-arm/Dockerfile
  docker/ubuntu/Dockerfile
Labels: A8-looksgood, B0-patchthis, M0-build

#9104 Fix work-notify.
  Cargo.toml
  ethcore/Cargo.toml
  parity/run.rs
Labels: A8-looksgood, B0-patchthis, B9-blocker, M4-core

#9095 parity-version: bump nightly version to 2.1
  Cargo.lock
  Cargo.toml
  util/version/Cargo.toml
Labels: A2-insubstantial, A8-looksgood, M2-installer

#9098 Update light client hardcoded headers
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/ropsten.json
Labels: A2-insubstantial, A8-looksgood, B0-patchthis, M4-core

#9115 Make sure to create full pending blocks
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/src/ethereum/ethash.rs
  ethcore/src/miner/miner.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#9121 Insert ETC (classic) hardcoded headers until block #6170625
  ethcore/res/ethereum/classic.json
Labels: A2-insubstantial, M2-config

#9096 Removed redundant struct bounds and unnecessary data copying
  ethcore/src/block.rs
  ethcore/src/client/client.rs
  ethcore/src/test_helpers.rs
  ethcore/src/tests/trace.rs
  util/using_queue/src/lib.rs
Labels: A6-mustntgrumble, M4-core

#9107 Completely remove all dapps struct from rpc
  parity/rpc_apis.rs
  rpc/src/lib.rs
  rpc/src/v1/helpers/dapps.rs
  rpc/src/v1/helpers/errors.rs
  rpc/src/v1/helpers/mod.rs
  rpc/src/v1/impls/light/parity.rs
  rpc/src/v1/impls/light/parity_set.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/impls/parity_set.rs
  rpc/src/v1/mod.rs
  rpc/src/v1/tests/mocked/parity.rs
  rpc/src/v1/tests/mocked/parity_set.rs
  rpc/src/v1/traits/parity.rs
  rpc/src/v1/traits/parity_set.rs
  rpc/src/v1/types/dapps.rs
  rpc/src/v1/types/mod.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#9086 ethcore: Minor cleanup in Receipt constructor
  ethcore/types/src/receipt.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#9085 Unify engine error to reject blocks
  ethcore/src/block.rs
  ethcore/src/client/client.rs
  ethcore/src/client/test_client.rs
  ethcore/src/client/traits.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/basic_authority.rs
  ethcore/src/engines/block_reward.rs
  ethcore/src/engines/instant_seal.rs
  ethcore/src/engines/tendermint/mod.rs
  ethcore/src/ethereum/ethash.rs
  ethcore/src/miner/miner.rs
  ethcore/src/test_helpers.rs
  ethcore/src/tests/client.rs
  ethcore/src/tests/trace.rs
  rpc/src/v1/tests/helpers/miner_service.rs
Labels: A8-looksgood, B1-releasenotes, M4-core

#9135 fix verification in ethcore-sync collect_blocks
  ethcore/sync/src/block_sync.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#9132 add cmake to snap build stage
  snap/snapcraft.yaml
Labels: A8-looksgood, B0-patchthis, M0-build, M1-ci

#9134 `evm bench` fix broken dependencies
  ethcore/benches/evm.rs
Labels: A8-looksgood, M0-build, M5-dependencies

#9093 Backports to 1.11.7-stable
  Cargo.lock
  Cargo.toml
  docker/alpine/Dockerfile
  docker/centos/Dockerfile
  docker/hub/Dockerfile
  docker/ubuntu-aarch64/Dockerfile
  docker/ubuntu-arm/Dockerfile
  docker/ubuntu/Dockerfile
  ethcore/Cargo.toml
  ethcore/benches/evm.rs
  ethcore/light/src/net/mod.rs
  ethcore/light/src/net/tests/mod.rs
  ethcore/light/src/provider.rs
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/ropsten.json
  ethcore/service/src/service.rs
  ethcore/src/client/client.rs
  ethcore/src/client/test_client.rs
  ethcore/src/client/traits.rs
  ethcore/src/ethereum/ethash.rs
  ethcore/src/miner/miner.rs
  ethcore/src/miner/mod.rs
  ethcore/src/miner/pool_client.rs
  ethcore/src/tests/client.rs
  ethcore/sync/src/api.rs
  ethcore/sync/src/block_sync.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/propagator.rs
  ethcore/sync/src/snapshot.rs
  mac/Parity.pkgproj
  miner/src/lib.rs
  miner/src/pool/mod.rs
  miner/src/pool/queue.rs
  miner/src/pool/tests/mod.rs
  nsis/installer.nsi
  parity/rpc_apis.rs
  parity/run.rs
  rpc/src/v1/impls/eth_pubsub.rs
  rpc/src/v1/impls/light/parity.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/tests/helpers/miner_service.rs
  rpc/src/v1/tests/mocked/eth_pubsub.rs
  rpc/src/v1/traits/parity.rs
  transaction-pool/src/pool.rs
  transaction-pool/src/tests/mod.rs
  util/version/Cargo.toml
Labels: A8-backport, M2-installer

#9094 Backports to 2.0.0-beta
  Cargo.lock
  Cargo.toml
  docker/alpine/Dockerfile
  docker/centos/Dockerfile
  docker/hub/Dockerfile
  docker/ubuntu-aarch64/Dockerfile
  docker/ubuntu-arm/Dockerfile
  docker/ubuntu/Dockerfile
  ethcore/Cargo.toml
  ethcore/benches/evm.rs
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/ropsten.json
  ethcore/service/src/service.rs
  ethcore/src/client/client.rs
  ethcore/src/ethereum/ethash.rs
  ethcore/src/miner/miner.rs
  ethcore/src/miner/pool_client.rs
  ethcore/sync/src/block_sync.rs
  parity/configuration.rs
  parity/rpc_apis.rs
  parity/run.rs
  parity/upgrade.rs
  rpc/src/lib.rs
  rpc/src/v1/helpers/dapps.rs
  rpc/src/v1/helpers/errors.rs
  rpc/src/v1/helpers/mod.rs
  rpc/src/v1/impls/light/parity.rs
  rpc/src/v1/impls/light/parity_set.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/impls/parity_set.rs
  rpc/src/v1/mod.rs
  rpc/src/v1/tests/mocked/parity.rs
  rpc/src/v1/tests/mocked/parity_set.rs
  rpc/src/v1/traits/parity.rs
  rpc/src/v1/traits/parity_set.rs
  rpc/src/v1/types/dapps.rs
  rpc/src/v1/types/mod.rs
  snap/snapcraft.yaml
  util/dir/Cargo.toml
  util/dir/src/helpers.rs
  util/dir/src/lib.rs
  util/network-devp2p/src/discovery.rs
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/node_table.rs
  util/version/Cargo.toml
Labels: A8-backport, M2-installer, M4-core

#9146 Receipt constructor `Allocate less stack for blooms`
  ethcore/types/src/receipt.rs
Labels: A2-insubstantial, A8-looksgood

#9149 Be more specific for `-l` CLI arguments
  parity/cli/mod.rs
Labels: A2-insubstantial, F8-enhancement, M3-docs

#9154 parity: fix logging cli parameter example
  parity/cli/mod.rs
Labels: A2-insubstantial, M4-core

#9148 Disable per-sender limit for local transactions.
  miner/src/pool/scoring.rs
  miner/src/pool/tests/mod.rs
  transaction-pool/src/pool.rs
  transaction-pool/src/scoring.rs
  transaction-pool/src/tests/helpers.rs
  transaction-pool/src/tests/mod.rs
  transaction-pool/src/transactions.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#9153 Remove unused tx_queue_gas parameter.
  parity/cli/mod.rs
  parity/cli/tests/config.full.toml
  parity/cli/tests/config.toml
Labels: A8-looksgood, B1-releasenotes, M4-core

#9151 handle SyncHandler errors properly
  ethcore/sync/src/block_sync.rs
  ethcore/sync/src/blocks.rs
  ethcore/sync/src/chain/handler.rs
Labels: A8-looksgood, M4-core

#9164 Be more graceful on Aura difficulty validation
  ethcore/src/engines/authority_round/mod.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#9138 Fix bugfix hard fork logic
  ethcore/src/miner/miner.rs
  ethcore/src/spec/spec.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#9170 ethcore: add missing builtins benchmarks
  ethcore/benches/evm.rs
  ethcore/src/builtin.rs
  ethcore/src/lib.rs
Labels: A8-looksgood, M4-core

#9160 ci: update version strings for snaps
  scripts/gitlab-build.sh
Labels: A0-pleasereview, A2-insubstantial, M1-ci

#9173 docker: update hub dockerfile
  docker/hub/Dockerfile
Labels: A2-insubstantial, M1-ci

#9191 Update "This is a bug. Please report it at:" link
  util/panic_hook/src/lib.rs
Labels: A8-looksgood, M4-core

#9189 parity: fix UserDefaults json parser
  Cargo.lock
  parity/params.rs
  parity/run.rs
  parity/user_defaults.rs
Labels: A8-looksgood, M4-core

#9112 rpc: fix is_major_importing sync state condition
  parity/informant.rs
  rpc/src/lib.rs
  rpc/src/v1/helpers/block_import.rs
Labels: A2-insubstantial, A8-looksgood, B0-patchthis, M4-core

#9179 ethcore: add builtin benchmarks based on geth
  ethcore/benches/builtin.rs
  ethcore/benches/evm.rs
Labels: A8-looksgood, M4-core

#9190 Avoid schedule copying in nested call/create
  ethcore/private-tx/src/lib.rs
  ethcore/src/client/client.rs
  ethcore/src/client/evm_test_client.rs
  ethcore/src/executive.rs
  ethcore/src/externalities.rs
  ethcore/src/factory.rs
  ethcore/src/json_tests/executive.rs
  ethcore/src/machine.rs
  ethcore/src/spec/spec.rs
  ethcore/src/state/mod.rs
  ethcore/src/tests/client.rs
  ethcore/src/tests/evm.rs
Labels: A8-looksgood, M4-core

#9143 Added --tx-queue-no-early-reject flag to disable early tx queue rejects
  ethcore/private-tx/src/private_transactions.rs
  ethcore/src/miner/miner.rs
  miner/src/pool/queue.rs
  miner/src/pool/tests/mod.rs
  miner/src/pool/verifier.rs
  parity/cli/mod.rs
  parity/cli/tests/config.full.toml
  parity/configuration.rs
  rpc/src/v1/tests/helpers/miner_service.rs
Labels: A8-looksgood, M6-rpcapi

#9215 Simple build instruction fix
  README.md
Labels: A2-insubstantial, A8-looksgood, M3-docs

#9144 Backports to 1.11.8-stable
  Cargo.lock
  Cargo.toml
  docker/hub/Dockerfile
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/miner/miner.rs
  ethcore/src/spec/spec.rs
  ethcore/wasm/Cargo.toml
  ethcore/wasm/src/parser.rs
  mac/Parity.pkgproj
  miner/src/pool/scoring.rs
  miner/src/pool/tests/mod.rs
  nsis/installer.nsi
  parity/informant.rs
  parity/params.rs
  parity/run.rs
  parity/user_defaults.rs
  rpc/src/lib.rs
  rpc/src/v1/helpers/block_import.rs
  scripts/gitlab-build.sh
  transaction-pool/src/pool.rs
  transaction-pool/src/scoring.rs
  transaction-pool/src/tests/helpers.rs
  transaction-pool/src/tests/mod.rs
  transaction-pool/src/transactions.rs
  util/version/Cargo.toml
Labels: A8-backport, M2-installer, M4-core

#9161 deserialize block only once during verification
  ethcore/src/client/client.rs
  ethcore/src/verification/mod.rs
  ethcore/src/verification/queue/kind.rs
  ethcore/src/verification/verification.rs
  ethcore/transaction/src/transaction.rs
Labels: A8-looksgood, M4-core

#9217 ethcore: update bn version
  Cargo.lock
Labels: A2-insubstantial, A8-looksgood, M4-core

#9174 Update bootnodes for multiple chains
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/ellaism.json
  ethcore/res/ethereum/expanse.json
  ethcore/res/ethereum/morden.json
  ethcore/res/ethereum/musicoin.json
Labels: A8-looksgood, M2-config

#9141 Insert PROOF messages for some cases in blockchain
  ethcore/src/blockchain/blockchain.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#9195 remove ssl from dockerfiles
  docker/android/Dockerfile
  docker/hub/Dockerfile
  docker/ubuntu/Dockerfile
Labels: A0-pleasereview, A2-insubstantial, B0-patchthis, M0-build

#9145 Backports to 2.0.1-beta
  Cargo.lock
  Cargo.toml
  docker/hub/Dockerfile
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/miner/miner.rs
  ethcore/src/spec/spec.rs
  miner/src/pool/scoring.rs
  miner/src/pool/tests/mod.rs
  node-health/Cargo.toml
  node-health/src/health.rs
  node-health/src/lib.rs
  node-health/src/time.rs
  node-health/src/types.rs
  parity/cli/mod.rs
  parity/cli/tests/config.toml
  parity/configuration.rs
  parity/deprecated.rs
  parity/informant.rs
  parity/lib.rs
  parity/params.rs
  parity/rpc_apis.rs
  parity/run.rs
  parity/user_defaults.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  rpc/src/v1/helpers/block_import.rs
  rpc/src/v1/impls/light/parity.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/tests/mocked/parity.rs
  rpc/src/v1/traits/parity.rs
  scripts/gitlab-build.sh
  transaction-pool/src/pool.rs
  transaction-pool/src/scoring.rs
  transaction-pool/src/tests/helpers.rs
  transaction-pool/src/tests/mod.rs
  transaction-pool/src/transactions.rs
  util/version/Cargo.toml
Labels: A8-backport, M2-installer, M4-core

#9222 snap: remove ssl dependencies from snapcraft definition
  snap/snapcraft.yaml
Labels: A2-insubstantial, A8-looksgood, B0-patchthis, M0-build

#9220 Removes duplicate libudev-dev from Dockerfile
  docker/hub/Dockerfile
Labels: A8-looksgood, M1-ci

#9226 Allow download of old blocks from peers with equal or lower difficulty
  ethcore/sync/src/chain/mod.rs
Labels: A0-pleasereview, B0-patchthis, M4-core

#9221 Fix potential as_usize overflow when casting from U256 in miner
  ethcore/src/miner/miner.rs
Labels: A8-looksgood, B0-patchthis, M4-core

#9232 fix typo
  util/network-devp2p/src/host.rs
Labels: A8-looksgood, M4-core

#9230 add changelog for 1.11.8 stable and 2.0.1 beta
  CHANGELOG.md
  docs/CHANGELOG-1.11.md
Labels: A0-pleasereview, M3-docs

#9203 Double up the number of possible sessions.
  util/network-devp2p/src/host.rs
Labels: A8-looksgood, M4-core

#9117 block cleanup
  ethcore/src/block.rs
  ethcore/src/blockchain/blockchain.rs
  ethcore/src/blockchain/extras.rs
  ethcore/src/blockchain/generator.rs
  ethcore/src/blockchain/update.rs
  ethcore/src/client/client.rs
  ethcore/src/encoded.rs
  ethcore/src/header.rs
  ethcore/src/snapshot/consensus/authority.rs
  ethcore/src/snapshot/consensus/work.rs
  ethcore/src/snapshot/tests/proof_of_work.rs
  ethcore/src/test_helpers.rs
  ethcore/src/verification/verification.rs
  machine/src/lib.rs
Labels: A8-looksgood, M4-core

#9237 Improve Tracer documentation
  ethcore/src/trace/mod.rs
Labels: A8-looksgood, M3-docs

#9234 Implement EIP-1052 (EXTCODEHASH) and fix several issues in state account cache
  ethcore/evm/src/instructions.rs
  ethcore/evm/src/interpreter/gasometer.rs
  ethcore/evm/src/interpreter/mod.rs
  ethcore/src/client/client.rs
  ethcore/src/executive.rs
  ethcore/src/externalities.rs
  ethcore/src/json_tests/executive.rs
  ethcore/src/machine.rs
  ethcore/src/spec/spec.rs
  ethcore/src/state/account.rs
  ethcore/src/state/mod.rs
  ethcore/vm/src/ext.rs
  ethcore/vm/src/schedule.rs
  ethcore/vm/src/tests.rs
  json/src/spec/params.rs
Labels: A8-looksgood, M4-core

#9253 removed client error
  ethcore/src/client/client.rs
  ethcore/src/client/error.rs
  ethcore/src/client/mod.rs
  ethcore/src/error.rs
Labels: A2-insubstantial, A8-looksgood, M4-core

#9210 Check if synced when using eth_getWork (#9193)
  rpc/src/v1/impls/eth.rs
Labels: A0-pleasereview, B0-patchthis, M6-rpcapi
