Repository openethereum/openethereum, pull requests merged in 2019-08, with the labels that each got.

#10940 Change the return type of step_inner function.
  ethcore/evm/src/interpreter/mod.rs
Labels: A8-looksgood 🦄, B1-patch-beta 🕷🕷, F7-optimisation 💊

#10939 Updated security@parity.io key
  SECURITY.md
Labels: A2-insubstantial 👶

#10941 Fix some warnings and typos.
  ethcore/src/json_tests/executive.rs
  ethcore/src/lib.rs
  ethcore/src/miner/miner.rs
  ethcore/wasm/src/runtime.rs
Labels: A2-insubstantial 👶

#10938 Enable sealing when engine is ready
  ethcore/src/miner/miner.rs
Labels: A8-looksgood 🦄, B1-patch-beta 🕷🕷, M4-core ⛓

#10932 Allow default block parameter to be blockHash
  ethcore/src/client/client.rs
  ethcore/src/client/test_client.rs
  ethcore/src/client/traits.rs
  rpc/src/v1/helpers/errors.rs
  rpc/src/v1/helpers/light_fetch.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/impls/traces.rs
  rpc/src/v1/types/block_number.rs
  rpc/src/v1/types/filter.rs
  rpc/src/v1/types/trace_filter.rs
Labels: A8-looksgood 🦄, M6-rpcapi 📣

#10929 journaldb changes
  ethcore/account-state/src/backend.rs
  util/journaldb/Cargo.toml
  util/journaldb/src/archivedb.rs
  util/journaldb/src/as_hash_db_impls.rs
  util/journaldb/src/earlymergedb.rs
  util/journaldb/src/lib.rs
  util/journaldb/src/overlaydb.rs
  util/journaldb/src/overlayrecentdb.rs
  util/journaldb/src/refcounteddb.rs
  util/journaldb/src/traits.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10742 refactor: Refactor evmbin CLI
  ethcore/src/client/evm_test_client.rs
  ethcore/src/json_tests/chain.rs
  ethcore/src/json_tests/state.rs
  ethcore/src/json_tests/transaction.rs
  ethcore/types/src/transaction/transaction.rs
  evmbin/Cargo.toml
  evmbin/README.md
  evmbin/res/create2callPrecompiles.json
  evmbin/res/teststate.json
  evmbin/src/display/json.rs
  evmbin/src/display/mod.rs
  evmbin/src/display/simple.rs
  evmbin/src/display/std_json.rs
  evmbin/src/info.rs
  evmbin/src/main.rs
Labels: A4-gotissues 💥

#10953 Fix compiler warnings in util/io and upgrade to edition 2018 Upgrade mio to latest
  Cargo.lock
  util/io/Cargo.toml
  util/io/src/lib.rs
  util/io/src/service_mio.rs
  util/io/src/service_non_mio.rs
  util/io/src/worker.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10956 [evmbin] add more tests to main.rs
  evmbin/src/display/std_json.rs
  evmbin/src/info.rs
  evmbin/src/main.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶

#10957 Add support for Energy Web Foundation's new chains
  ethcore/res/ethereum/ewc.json
  ethcore/res/ethereum/tobalaba.json
  ethcore/res/ethereum/volta.json
  ethcore/src/spec/chain.rs
  parity/cli/mod.rs
  parity/params.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#10955 removed redundant state_root function from spec
  ethcore/src/spec/chain.rs
  ethcore/src/spec/spec.rs
  evmbin/src/main.rs
  parity/params.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10961 V2.5.6 stable
  .github/CONTRIBUTING.md
  .gitlab-ci.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  accounts/Cargo.toml
  accounts/ethkey/Cargo.toml
  accounts/ethkey/README.md
  accounts/ethkey/cli/Cargo.toml
  accounts/ethkey/src/extended.rs
  accounts/ethkey/src/lib.rs
  accounts/ethstore/Cargo.toml
  accounts/ethstore/cli/Cargo.toml
  chainspec/Cargo.toml
  cli-signer/Cargo.toml
  cli-signer/rpc-client/Cargo.toml
  docs/CHANGELOG-2.4.md
  ethash/Cargo.toml
  ethcore/Cargo.toml
  ethcore/blockchain/Cargo.toml
  ethcore/call-contract/Cargo.toml
  ethcore/evm/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/node-filter/Cargo.toml
  ethcore/private-tx/src/encryptor.rs
  ethcore/res/ethereum/ewc.json
  ethcore/res/ethereum/ropsten.json
  ethcore/res/ethereum/tobalaba.json
  ethcore/res/ethereum/volta.json
  ethcore/service/Cargo.toml
  ethcore/src/client/client.rs
  ethcore/src/ethereum/mod.rs
  ethcore/src/executive.rs
  ethcore/src/lib.rs
  ethcore/src/snapshot/mod.rs
  ethcore/sync/Cargo.toml
  ethcore/sync/src/chain/mod.rs
  ethcore/types/Cargo.toml
  ethcore/types/src/restoration_status.rs
  ethcore/vm/Cargo.toml
  ethcore/wasm/Cargo.toml
  ethcore/wasm/run/Cargo.toml
  evmbin/Cargo.toml
  ipfs/Cargo.toml
  json/Cargo.toml
  miner/Cargo.toml
  parity/cli/mod.rs
  parity/configuration.rs
  parity/logger/Cargo.toml
  parity/params.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  rpc/src/v1/helpers/engine_signer.rs
  scripts/gitlab/publish-av-whitelists.sh
  secret-store/Cargo.toml
  util/version/Cargo.toml
  whisper/Cargo.toml
Labels: A8-backport 🕸

#10926 Disable unsyncable expanse chain
  parity/cli/mod.rs
  parity/params.rs
Labels: A0-pleasereview 🤓, M2-config 📂

#10901 tx-pool: accept local tx with higher gas price when pool full
  miner/src/pool/replace.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10964 Fix ethcore/benches build.
  ethcore/benches/builtin.rs
Labels: A8-looksgood 🦄

#10973 2.6.1-beta
  .gitlab-ci.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  docs/CHANGELOG-2.4.md
  ethcore/Cargo.toml
  ethcore/blockchain/Cargo.toml
  ethcore/evm/src/interpreter/mod.rs
  ethcore/res/ethereum/ewc.json
  ethcore/res/ethereum/tobalaba.json
  ethcore/res/ethereum/volta.json
  ethcore/src/ethereum/mod.rs
  ethcore/src/executive.rs
  ethcore/src/lib.rs
  ethcore/src/miner/miner.rs
  ethcore/src/snapshot/mod.rs
  miner/src/pool/replace.rs
  parity/cli/mod.rs
  parity/params.rs
  scripts/gitlab/publish-av-whitelists.sh
  util/version/Cargo.toml
Labels: A8-backport 🕸

#10974 [blooms-db] Fix benchmarks
  util/blooms-db/benches/blooms.rs
  util/blooms-db/src/db.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#10972 Update to latest trie version.
  Cargo.lock
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/account-db/Cargo.toml
  ethcore/account-state/Cargo.toml
  ethcore/blockchain/Cargo.toml
  ethcore/db/Cargo.toml
  ethcore/evm/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/pod/Cargo.toml
  ethcore/pod/src/account.rs
  ethcore/private-tx/Cargo.toml
  ethcore/src/client/client.rs
  ethcore/src/client/evm_test_client.rs
  ethcore/src/executive_state.rs
  ethcore/src/json_tests/trie.rs
  ethcore/state-db/Cargo.toml
  ethcore/sync/Cargo.toml
  ethcore/trace/Cargo.toml
  ethcore/trie-vm-factories/Cargo.toml
  ethcore/trie-vm-factories/src/lib.rs
  ethcore/types/Cargo.toml
  miner/Cargo.toml
  util/journaldb/Cargo.toml
  util/journaldb/src/earlymergedb.rs
  util/keccak-hasher/Cargo.toml
  util/memory-cache/Cargo.toml
  util/patricia-trie-ethereum/Cargo.toml
  util/patricia-trie-ethereum/src/lib.rs
  util/patricia-trie-ethereum/src/rlp_node_codec.rs
  util/triehash-ethereum/Cargo.toml
Labels: A8-looksgood 🦄, M4-core ⛓

#10976 [evmbin] fix compilation
  Cargo.lock
  ethcore/Cargo.toml
  evmbin/Cargo.toml
  evmbin/README.md
  evmbin/src/display/json.rs
  evmbin/src/display/simple.rs
  evmbin/src/display/std_json.rs
  evmbin/src/info.rs
  evmbin/src/main.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓, M5-binaries 📦

#10954 Verify transaction against its block during import
  ethcore/src/miner/miner.rs
  ethcore/src/miner/pool_client.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10965 [.gitlab.yml] cargo check ethcore benches
  .gitlab-ci.yml
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M1-ci 🙉

#10931 Better error message for rpc gas price errors
  ethcore/types/src/transaction/error.rs
  miner/src/pool/queue.rs
  miner/src/pool/tests/mod.rs
  miner/src/pool/verifier.rs
  rpc/src/v1/helpers/errors.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M6-rpcapi 📣

#10977 manual publish jobs for releases, no changes for nightlies
  .gitlab-ci.yml
Labels: A0-pleasereview 🤓, A8-backport 🕸, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#10748 Private contract migration and offchain state sync
  Cargo.lock
  ethcore/db/src/db.rs
  ethcore/private-tx/Cargo.toml
  ethcore/private-tx/src/error.rs
  ethcore/private-tx/src/lib.rs
  ethcore/private-tx/src/log.rs
  ethcore/private-tx/src/private_state_db.rs
  ethcore/private-tx/src/state_store.rs
  ethcore/private-tx/tests/private_contract.rs
  ethcore/service/src/service.rs
  ethcore/src/client/chain_notify.rs
  ethcore/src/test_helpers.rs
  ethcore/sync/Cargo.toml
  ethcore/sync/src/api.rs
  ethcore/sync/src/block_sync.rs
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/propagator.rs
  ethcore/sync/src/chain/requester.rs
  ethcore/sync/src/chain/supplier.rs
  ethcore/sync/src/chain/sync_packet.rs
  ethcore/sync/src/lib.rs
  ethcore/sync/src/private_tx.rs
  ethcore/sync/src/sync_io.rs
  ethcore/sync/src/tests/helpers.rs
  ethcore/sync/src/tests/private.rs
  parity/cli/mod.rs
  parity/configuration.rs
  parity/db/rocksdb/migration.rs
  parity/modules.rs
  parity/run.rs
  rpc/src/v1/types/private_log.rs
Labels: B7-releasenotes 📜, M4-core ⛓

#10980 Fix rlp decode for inline trie nodes.
  util/patricia-trie-ethereum/src/lib.rs
  util/patricia-trie-ethereum/src/rlp_node_codec.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10909 Add a 2/3 quorum option to Authority Round.
  ethcore/src/engines/authority_round/finality.rs
  ethcore/src/engines/authority_round/mod.rs
  json/src/spec/authority_round.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10875 Configuration map of block reward contract addresses
  ethcore/src/engines/authority_round/mod.rs
  json/src/spec/authority_round.rs
Labels: A8-looksgood 🦄, B7-releasenotes 📜, F8-enhancement 🎊

#10987 EIP 2028: transaction gas lowered from 68 to 16
  ethcore/evm/src/tests.rs
  ethcore/types/src/engines/params.rs
  ethcore/vm/src/schedule.rs
  ethcore/vm/src/tests.rs
  json/src/spec/params.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10979 [ipfs] Convert to edition 2018
  ipfs/Cargo.toml
  ipfs/src/error.rs
  ipfs/src/lib.rs
  ipfs/src/route.rs
Labels: A8-looksgood 🦄, M5-dependencies 🖇

#10991 Fix compilation on recent nightlies
  ipfs/Cargo.toml
  ipfs/src/lib.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M5-dependencies 🖇

#10996 bump spin to 0.5.2
  Cargo.lock
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10981 Make ClientIoMessage generic over the Client
  Cargo.lock
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/client-traits/src/lib.rs
  ethcore/light/Cargo.toml
  ethcore/light/src/client/mod.rs
  ethcore/light/src/client/service.rs
  ethcore/light/src/lib.rs
  ethcore/private-tx/src/lib.rs
  ethcore/service/Cargo.toml
  ethcore/service/src/lib.rs
  ethcore/service/src/service.rs
  ethcore/src/client/client.rs
  ethcore/src/client/mod.rs
  ethcore/src/client/test_client.rs
  ethcore/src/json_tests/chain.rs
  ethcore/src/lib.rs
  ethcore/src/miner/miner.rs
  ethcore/src/miner/pool_client.rs
  ethcore/src/snapshot/io.rs
  ethcore/src/snapshot/mod.rs
  ethcore/src/snapshot/service.rs
  ethcore/src/snapshot/tests/helpers.rs
  ethcore/src/snapshot/tests/proof_of_work.rs
  ethcore/src/snapshot/tests/service.rs
  ethcore/src/snapshot/tests/state.rs
  ethcore/src/snapshot/watcher.rs
  ethcore/src/test_helpers.rs
  ethcore/src/tests/client.rs
  ethcore/src/tests/trace.rs
  ethcore/sync/src/tests/consensus.rs
  ethcore/sync/src/tests/helpers.rs
  ethcore/sync/src/tests/private.rs
  ethcore/types/src/client_types.rs
  ethcore/types/src/io_message.rs
  ethcore/types/src/lib.rs
  ethcore/verification/Cargo.toml
  ethcore/verification/src/canon_verifier.rs
  ethcore/verification/src/lib.rs
  ethcore/verification/src/noop_verifier.rs
  ethcore/verification/src/queue/kind.rs
  ethcore/verification/src/queue/mod.rs
  ethcore/verification/src/verification.rs
  ethcore/verification/src/verifier.rs
  parity/blockchain.rs
  parity/configuration.rs
  parity/informant.rs
  parity/lib.rs
  parity/run.rs
  parity/snapshot.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  rpc/src/v1/tests/eth.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10983 EIP-1344 Add CHAINID op-code
  Cargo.lock
  ethcore/engines/validator-set/src/safe_contract.rs
  ethcore/evm/Cargo.toml
  ethcore/evm/src/factory.rs
  ethcore/evm/src/instructions.rs
  ethcore/evm/src/interpreter/mod.rs
  ethcore/evm/src/lib.rs
  ethcore/evm/src/tests.rs
  ethcore/machine/src/externalities.rs
  ethcore/src/json_tests/executive.rs
  ethcore/types/src/engines/params.rs
  ethcore/vm/src/env_info.rs
  ethcore/vm/src/ext.rs
  ethcore/vm/src/schedule.rs
  ethcore/vm/src/tests.rs
  json/src/spec/params.rs
  parity/informant.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#11002 check mem diff
  ethcore/trace/src/executive_tracer.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, B0-patch-stable 🕷, B1-patch-beta 🕷🕷

#10989 xDai chain support and nodes list update
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/poacore.json
  ethcore/res/ethereum/poasokol.json
  ethcore/res/ethereum/xdai.json
  ethcore/spec/src/chain.rs
  parity/cli/mod.rs
  parity/params.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, B7-releasenotes 📜, M2-config 📂

#11006 v2.5.7 stable
  Cargo.lock
  Cargo.toml
  ethcore/src/trace/executive_tracer.rs
  util/version/Cargo.toml
Labels: A8-backport 🕸

#11007 v2.6.2 beta
  Cargo.lock
  Cargo.toml
  ethcore/src/trace/executive_tracer.rs
  util/version/Cargo.toml
Labels: A8-backport 🕸

#10992 EIP 1884 Re-pricing of trie-size dependent operations
  ethcore/evm/src/evm.rs
  ethcore/evm/src/instructions.rs
  ethcore/evm/src/interpreter/mod.rs
  ethcore/evm/src/tests.rs
  ethcore/types/src/engines/params.rs
  ethcore/vm/src/ext.rs
  ethcore/vm/src/return_data.rs
  ethcore/vm/src/schedule.rs
  json/src/spec/params.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#10191 Implement EIP-1283 reenable transition, EIP-1706 and EIP-2200
  ethcore/evm/src/interpreter/gasometer.rs
  ethcore/types/src/engines/params.rs
  ethcore/vm/src/schedule.rs
  json/src/spec/params.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓
