Repository openethereum/openethereum, pull requests merged in 2019-02, with the labels that each got.

#10007 prevent silent errors in daemon mode
  Cargo.lock
  Cargo.toml
  parity-clib/Parity.java
  parity-clib/examples/cpp/main.cpp
  parity-clib/examples/java/Main.java
  parity-clib/parity.h
  parity-clib/src/java.rs
  parity-clib/src/lib.rs
  parity/configuration.rs
  parity/lib.rs
  parity/logger/src/lib.rs
  parity/main.rs
  parity/run.rs
Labels: A6-mustntgrumble 💦, M4-core ⛓

#10281 Additional tests for uint deserialization.
  rpc/src/v1/types/bytes.rs
  rpc/src/v1/types/hash.rs
  rpc/src/v1/types/uint.rs
Labels: A0-pleasereview 🤓, A8-backport 🕸, M6-rpcapi 📣

#10282 version: bump stable to 2.2.9
  Cargo.lock
  Cargo.toml
  util/version/Cargo.toml
Labels: A8-looksgood 🦄, M2-config 📂

#10283 version: bump beta to 2.3.2
  Cargo.lock
  Cargo.toml
  util/version/Cargo.toml
Labels: A8-looksgood 🦄, M2-config 📂

#10280 Additional tests for uint deserialization.
  rpc/src/v1/types/bytes.rs
  rpc/src/v1/types/hash.rs
  rpc/src/v1/types/uint.rs
Labels: A8-backport 🕸, M6-rpcapi 📣

#10284 Fix Windows build
  Cargo.toml
Labels: A2-insubstantial 👶, B1-patch-beta 🕷🕷, M5-dependencies 🖇

#10286 Backport #10285 to beta
  test.sh
Labels: A8-backport 🕸, M1-ci 🙉

#10300 Update to jsonrpc-derive 10.0.2, fixes aliases bug
  Cargo.lock
  rpc/Cargo.toml
  whisper/Cargo.toml
Labels: A2-insubstantial 👶, M5-dependencies 🖇

#10301 fix(secret-store): deprecation warning
  secret-store/src/listener/http_listener.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#10262 update ring to 0.14
  Cargo.lock
  Cargo.toml
  accounts/ethkey/Cargo.toml
  accounts/ethstore/Cargo.toml
  accounts/ethstore/src/account/crypto.rs
  accounts/ethstore/src/account/kdf.rs
  accounts/ethstore/src/account/safe_account.rs
  accounts/ethstore/src/accounts_dir/disk.rs
  accounts/ethstore/src/accounts_dir/mod.rs
  accounts/ethstore/src/accounts_dir/vault.rs
  accounts/ethstore/src/ethstore.rs
  accounts/ethstore/src/json/kdf.rs
  accounts/ethstore/src/json/vault_file.rs
  accounts/ethstore/src/json/vault_key_file.rs
  accounts/ethstore/src/lib.rs
  accounts/ethstore/src/presale.rs
  ethcore/Cargo.toml
  ethcore/private-tx/Cargo.toml
  parity/account.rs
  parity/configuration.rs
  parity/lib.rs
  parity/params.rs
  parity/presale.rs
  rpc/Cargo.toml
  secret-store/Cargo.toml
  util/fetch/Cargo.toml
  util/network-devp2p/Cargo.toml
  util/network/Cargo.toml
  whisper/Cargo.toml
Labels: A8-looksgood 🦄, M5-dependencies 🖇

#10086 Call private contract methods from another private contract (read-only)
  ethcore/private-tx/res/keys_acl.json
  ethcore/private-tx/src/encryptor.rs
  ethcore/private-tx/src/key_server_keys.rs
  ethcore/private-tx/src/lib.rs
  ethcore/private-tx/tests/private_contract.rs
  ethcore/service/src/service.rs
  ethcore/sync/src/tests/private.rs
  parity/blockchain.rs
  parity/run.rs
  parity/snapshot.rs
  rpc/src/v1/impls/private.rs
  rpc/src/v1/types/private_receipt.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10175 Add missing step for Using `systemd` service file
  README.md
Labels: A2-insubstantial 👶, M3-docs 📑

#10291 fix(osx and windows builds): bump parity-daemonize
  Cargo.lock
  Cargo.toml
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M0-build 🏗

#10015 Properly handle check_epoch_end_signal errors
  ethcore/src/client/client.rs
  ethcore/src/engines/mod.rs
  ethcore/src/state/mod.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10247 Increase number of requested block bodies in chain sync
  Cargo.lock
  ethcore/sync/src/api.rs
  ethcore/sync/src/block_sync.rs
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/propagator.rs
  ethcore/sync/src/chain/requester.rs
  ethcore/sync/src/chain/supplier.rs
  ethcore/sync/src/sync_io.rs
  ethcore/sync/src/tests/helpers.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  rpc/src/v1/tests/helpers/sync_provider.rs
  rpc/src/v1/tests/mocked/parity.rs
  rpc/src/v1/types/sync.rs
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/session.rs
  util/network-devp2p/tests/tests.rs
  util/network/Cargo.toml
  util/network/src/client_version.rs
  util/network/src/lib.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10297 CI optimizations
  .gitlab-ci.yml
  scripts/gitlab/build-unix.sh
  scripts/gitlab/cargo-audit.sh
  scripts/gitlab/publish-onnet-update.sh
  scripts/gitlab/test-all.sh
  test.sh
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#10313 fix: parity-clib/examples/cpp/CMakeLists.txt
  parity-clib/examples/cpp/CMakeLists.txt
Labels: A8-looksgood 🦄

#10295 Make specification of protocol in SyncRequester::send_request explicit
  ethcore/sync/src/api.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/propagator.rs
  ethcore/sync/src/chain/requester.rs
  ethcore/sync/src/sync_io.rs
  ethcore/sync/src/tests/helpers.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10246 Secure WS-RPC: grant access to all apis
  parity/rpc.rs
  parity/rpc_apis.rs
Labels: A8-looksgood 🦄, M7-signer 🔏

#10238 fix(light-rpc): Make `light_sync` generic
  Cargo.lock
  ethcore/sync/src/api.rs
  parity/light_helpers/epoch_fetch.rs
  parity/light_helpers/queue_cull.rs
  rpc/src/v1/helpers/dispatch/light.rs
  rpc/src/v1/helpers/light_fetch.rs
  rpc/src/v1/impls/eth_pubsub.rs
  rpc/src/v1/impls/light/eth.rs
  rpc/src/v1/impls/light/parity.rs
Labels: A8-looksgood 🦄, M4-core ⛓, M6-rpcapi 📣

#10294 Revive parity_setMinGasPrice RPC call
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/src/lib.rs
  ethcore/src/miner/miner.rs
  ethcore/src/miner/mod.rs
  miner/src/gas_pricer.rs
  rpc/src/v1/impls/parity_set.rs
  rpc/src/v1/tests/helpers/miner_service.rs
  rpc/src/v1/tests/mocked/parity_set.rs
Labels: A7-looksgoodtestsfail 🤖, M6-rpcapi 📣

#10327 Additional error for invalid gas
  ethcore/evm/src/interpreter/mod.rs
  ethcore/light/src/transaction_queue.rs
  ethcore/src/executive.rs
  ethcore/src/state/account.rs
  ethcore/src/state/mod.rs
  miner/src/pool/queue.rs
  miner/src/pool/ready.rs
  miner/src/pool/verifier.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10328 Backport #10327 to beta
  ethcore/evm/src/interpreter/mod.rs
  ethcore/light/src/transaction_queue.rs
  ethcore/src/executive.rs
  ethcore/src/state/account.rs
  ethcore/src/state/mod.rs
  miner/src/pool/queue.rs
  miner/src/pool/ready.rs
  miner/src/pool/verifier.rs
Labels: A8-backport 🕸, A8-looksgood 🦄

#10329 Backport #10327 to stable
  ethcore/evm/src/interpreter/mod.rs
  ethcore/light/src/transaction_queue.rs
  ethcore/src/executive.rs
  ethcore/src/state/account.rs
  ethcore/src/state/mod.rs
  miner/src/pool/queue.rs
  miner/src/pool/ready.rs
  miner/src/pool/verifier.rs
Labels: A8-backport 🕸, A8-looksgood 🦄

#10330 fix(add helper for timestamp overflows)
  ethcore/src/error.rs
  ethcore/src/verification/verification.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10168 snap: official image / test
  .gitlab-ci.yml
  scripts/gitlab/publish-snap.sh
  scripts/snap/snapcraft.template.yaml
Labels: A3-stale 🍃, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#10059 fix(docker): fix not receives SIGINT
  scripts/docker/hub/Dockerfile
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#10305 Don't add discovery initiators to the node table
  Cargo.lock
  util/network-devp2p/Cargo.toml
  util/network-devp2p/src/discovery.rs
  util/network-devp2p/src/lib.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10336 change docker image based on debian instead of ubuntu due to the chan…
  scripts/docker/hub/Dockerfile
Labels: B0-patch-stable 🕷, B1-patch-beta 🕷🕷

#10315 Bundle protocol and packet_id together in chain sync
  Cargo.lock
  ethcore/sync/Cargo.toml
  ethcore/sync/src/api.rs
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/propagator.rs
  ethcore/sync/src/chain/requester.rs
  ethcore/sync/src/chain/supplier.rs
  ethcore/sync/src/chain/sync_packet.rs
  ethcore/sync/src/lib.rs
  ethcore/sync/src/sync_io.rs
  ethcore/sync/src/tests/helpers.rs
Labels: A6-mustntgrumble 💦, M4-core ⛓

#10343 snap: prefix version and populate candidate channel
  scripts/gitlab/publish-snap.sh
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#10351 Fixed misstype
  ethcore/private-tx/src/error.rs
  ethcore/private-tx/src/lib.rs
  miner/src/pool/tests/mod.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#10345 no volumes are needed, just run -v volume:/path/in/the/container
  scripts/docker/hub/Dockerfile
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#10353 Stable Backports
  Cargo.lock
  Cargo.toml
  scripts/docker/hub/Dockerfile
  scripts/gitlab/publish-snap.sh
  util/version/Cargo.toml
Labels: A8-backport 🕸, M1-ci 🙉

#10354 Beta Backports
  Cargo.lock
  Cargo.toml
  scripts/docker/hub/Dockerfile
  scripts/gitlab/publish-snap.sh
  util/version/Cargo.toml
Labels: A8-backport 🕸, M1-ci 🙉

#10346 fix(compilation warns): `no-default-features`
  parity/account.rs
  parity/account_utils.rs
  parity/upgrade.rs
  rpc/src/v1/helpers/dispatch/mod.rs
  rpc/src/v1/helpers/errors.rs
  rpc/src/v1/helpers/mod.rs
  rpc/src/v1/types/derivation.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#10357 snap: release untagged versions from branches to the candidate snap c…
  scripts/gitlab/publish-snap.sh
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#10362 Add fields to `memzero`'s Cargo.toml
  util/memzero/Cargo.toml
Labels: A8-looksgood 🦄, M3-docs 📑

#9850 SecretStore: use in-memory transport in cluster tests
  secret-store/src/key_server.rs
  secret-store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs
  secret-store/src/key_server_cluster/admin_sessions/share_add_session.rs
  secret-store/src/key_server_cluster/client_sessions/generation_session.rs
  secret-store/src/key_server_cluster/client_sessions/signing_session_ecdsa.rs
  secret-store/src/key_server_cluster/client_sessions/signing_session_schnorr.rs
  secret-store/src/key_server_cluster/cluster.rs
  secret-store/src/key_server_cluster/cluster_connections.rs
  secret-store/src/key_server_cluster/cluster_connections_net.rs
  secret-store/src/key_server_cluster/cluster_message_processor.rs
  secret-store/src/key_server_cluster/cluster_sessions.rs
  secret-store/src/key_server_cluster/connection_trigger.rs
  secret-store/src/key_server_cluster/connection_trigger_with_migration.rs
  secret-store/src/key_server_cluster/mod.rs
  secret-store/src/node_key_pair.rs
  secret_store/src/key_server_cluster/cluster_connections.rs
  secret_store/src/key_server_cluster/cluster_connections_net.rs
  secret_store/src/key_server_cluster/cluster_message_processor.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10359 chore(bump parity-daemonize): require rust >= 1.31
  Cargo.lock
  Cargo.toml
  parity/main.rs
Labels: A8-looksgood 🦄, M4-core ⛓, M5-dependencies 🖇

#10324 Add message to IO errors
  parity/upgrade.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10377 snap: add the removable-media plug
  scripts/snap/snapcraft.template.yaml
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#9762 ethash: implement Progpow
  Cargo.lock
  Cargo.toml
  ethash/Cargo.toml
  ethash/benches/basic.rs
  ethash/benches/progpow.rs
  ethash/res/progpow_testvectors.json
  ethash/src/cache.rs
  ethash/src/compute.rs
  ethash/src/lib.rs
  ethash/src/progpow.rs
  ethcore/Cargo.toml
  ethcore/src/ethereum/ethash.rs
  ethcore/src/json_tests/skip.rs
  json/src/spec/ethash.rs
  test.sh
Labels: A8-looksgood 🦄, B7-releasenotes 📜, M4-core ⛓

#10309 exchanged old(azure) bootnodes with new(ovh) ones
  ethcore/res/ethereum/kovan.json
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#10384 fix(trace_main! macro): don't export
  parity/main.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10373 beta: snap: release untagged versions from branches to the candidate (#10357)
  ethcore/res/ethereum/kovan.json
  scripts/gitlab/publish-snap.sh
  scripts/snap/snapcraft.template.yaml
Labels: A8-backport 🕸, M1-ci 🙉

#10372 stable: snap: release untagged versions from branches to the candidate (#10357)
  ethcore/res/ethereum/kovan.json
  scripts/gitlab/publish-snap.sh
  scripts/snap/snapcraft.template.yaml
Labels: A8-backport 🕸, M1-ci 🙉

#10375 tx pool: always accept local transactions
  miner/src/pool/scoring.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10314 Update to latest mem-db, hash-db and trie-db.
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/light/src/cht.rs
  ethcore/light/src/lib.rs
  ethcore/light/src/on_demand/request.rs
  ethcore/private-tx/Cargo.toml
  ethcore/private-tx/src/lib.rs
  ethcore/src/account_db.rs
  ethcore/src/client/client.rs
  ethcore/src/json_tests/trie.rs
  ethcore/src/lib.rs
  ethcore/src/pod_account.rs
  ethcore/src/snapshot/account.rs
  ethcore/src/snapshot/mod.rs
  ethcore/src/snapshot/tests/helpers.rs
  ethcore/src/snapshot/tests/service.rs
  ethcore/src/snapshot/tests/state.rs
  ethcore/src/spec/spec.rs
  ethcore/src/state/account.rs
  ethcore/src/state/backend.rs
  ethcore/src/state/mod.rs
  ethcore/src/state_db.rs
  ethcore/sync/Cargo.toml
  ethcore/vm/Cargo.toml
  ethcore/vm/src/lib.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  util/journaldb/Cargo.toml
  util/journaldb/src/archivedb.rs
  util/journaldb/src/as_hash_db_impls.rs
  util/journaldb/src/earlymergedb.rs
  util/journaldb/src/lib.rs
  util/journaldb/src/overlaydb.rs
  util/journaldb/src/overlayrecentdb.rs
  util/journaldb/src/refcounteddb.rs
  util/journaldb/src/traits.rs
  util/keccak-hasher/Cargo.toml
  util/keccak-hasher/src/lib.rs
  util/patricia-trie-ethereum/Cargo.toml
  util/patricia-trie-ethereum/src/lib.rs
  util/patricia-trie-ethereum/src/rlp_node_codec.rs
  util/triehash-ethereum/Cargo.toml
Labels: A8-looksgood 🦄, M5-dependencies 🖇

#10396 chore(bump ethereum-types 0.4.2)
  Cargo.lock
Labels: A8-looksgood 🦄, M5-dependencies 🖇

#10394 fix(jni): bump to jni to 0.11 & remove unsafe impl
  Cargo.lock
  parity-clib/Cargo.toml
  parity-clib/src/java.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M5-dependencies 🖇

#10393 no-git for publish jobs, empty artifacts dir
  .gitlab-ci.yml
  scripts/gitlab/build-unix.sh
  scripts/gitlab/publish-onchain.sh
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#10392 version: bump nightly to 2.5
  Cargo.lock
  Cargo.toml
  util/version/Cargo.toml
Labels: A8-looksgood 🦄, M2-installer 📲

#10368 Fix to_pod storage trie value decoding
  ethcore/src/state/mod.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10391 set correct nonce when node creates a public transaction wrapping a private transaction
  ethcore/private-tx/src/lib.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10386 snap: reenable i386, arm64, armhf architecture publishing
  .gitlab-ci.yml
  scripts/gitlab/build-unix.sh
  scripts/gitlab/publish-snap.sh
  scripts/snap/snapcraft.template.yaml
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, B9-blocker 🚧, M1-ci 🙉

#10414 Backports for Stable 2.3.5
  .gitlab-ci.yml
  ethcore/src/state/mod.rs
  miner/src/pool/scoring.rs
  scripts/gitlab/build-unix.sh
  scripts/gitlab/publish-onchain.sh
  scripts/gitlab/publish-snap.sh
  scripts/snap/snapcraft.template.yaml
Labels: A8-backport 🕸, M1-ci 🙉, M4-core ⛓

#10416 Backports for Beta 2.4.0
  .gitlab-ci.yml
  ethcore/src/state/mod.rs
  scripts/gitlab/build-unix.sh
  scripts/gitlab/publish-onchain.sh
  scripts/gitlab/publish-snap.sh
  scripts/snap/snapcraft.template.yaml
Labels: A8-backport 🕸, M1-ci 🙉, M4-core ⛓

#10422 10000 > 5000
  parity/cli/mod.rs
Labels: A2-insubstantial 👶, B0-patch-stable 🕷, B1-patch-beta 🕷🕷

#10366 Refactor ethcore::client::TransactResult to use it inside std::result::Result
  ethcore/src/client/evm_test_client.rs
  ethcore/src/client/mod.rs
  ethcore/src/json_tests/state.rs
  evmbin/src/info.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10424 fix panic when logging directory does not exist
  parity/main.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10427 parity/main.rs uses eprintln instead of raw stderr interface
  parity/main.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10385 Remove duplicate test cases
  ethcore/src/state/account.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10425 remove redundant macro println_stderr from parity/cli/usage.rs
  parity/cli/usage.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10423 fix underflow in pip
  ethcore/light/src/net/mod.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10429 ci: clean up gitlab-ci.yml leftovers from previous merge
  .gitlab-ci.yml
Labels: A2-insubstantial 👶, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#10426 panic_hook module uses eprintln instead of raw stderr interface
  util/panic-hook/src/lib.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10417 Update hardcoded headers for Foundation, Ropsten, Kovan and Classic
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/ropsten.json
Labels: A2-insubstantial 👶, B0-patch-stable 🕷, B1-patch-beta 🕷🕷

#10430 More Backports for Stable 2.3.5
  .gitlab-ci.yml
  ethcore/light/src/net/mod.rs
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/ropsten.json
  parity/cli/mod.rs
  parity/configuration.rs
  parity/main.rs
Labels: A8-backport 🕸, M1-ci 🙉, M3-docs 📑, M4-core ⛓

#10431 More Backports for Beta 2.4.0
  .gitlab-ci.yml
  ethcore/light/src/net/mod.rs
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/ropsten.json
  parity/cli/mod.rs
  parity/main.rs
Labels: A8-backport 🕸, M1-ci 🙉, M3-docs 📑, M4-core ⛓
