Repository openethereum/openethereum, pull requests merged in 2019-04, with the labels that each got.

#10526 tx-pool: check transaction readiness before replacing
  Cargo.lock
  ethcore/private-tx/Cargo.toml
  ethcore/private-tx/src/error.rs
  ethcore/private-tx/src/private_transactions.rs
  miner/Cargo.toml
  miner/src/pool/listener.rs
  miner/src/pool/local_transactions.rs
  miner/src/pool/mod.rs
  miner/src/pool/queue.rs
  miner/src/pool/replace.rs
  miner/src/pool/scoring.rs
  rpc/Cargo.toml
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10532 2.3.9 stable backports
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/easthub.json
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/morden.json
  ethcore/res/ethereum/ropsten.json
  ethcore/res/ethereum/social.json
  ethcore/src/ethereum/mod.rs
  parity/cli/mod.rs
  parity/params.rs
  rpc/src/v1/helpers/fake_sign.rs
  scripts/gitlab/build-linux.sh
  scripts/gitlab/build-windows.sh
  scripts/gitlab/test-cpp.sh
  util/version/Cargo.toml
Labels: A8-backport 🕸, M1-ci 🙉

#10533 2.4.4 beta backports
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/easthub.json
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/morden.json
  ethcore/res/ethereum/ropsten.json
  ethcore/res/ethereum/social.json
  ethcore/src/ethereum/mod.rs
  parity/cli/mod.rs
  parity/params.rs
  rpc/src/v1/helpers/fake_sign.rs
  scripts/gitlab/build-linux.sh
  scripts/gitlab/build-windows.sh
  scripts/gitlab/test-cpp.sh
  util/version/Cargo.toml
Labels: A8-backport 🕸, M1-ci 🙉

#10560 version: bump master to 2.6
  Cargo.lock
  Cargo.toml
  util/version/Cargo.toml
Labels: A2-insubstantial 👶, M5-dependencies 🖇

#10521 Explicitly enable or disable Stratum in config file (Issue 9785)
  parity/cli/mod.rs
  parity/cli/tests/config.stratum_disabled.toml
  parity/cli/tests/config.stratum_enabled.toml
  parity/cli/tests/config.stratum_missing_field.toml
  parity/cli/tests/config.stratum_missing_section.toml
Labels: A8-looksgood 🦄, B7-releasenotes 📜, M2-config 📂, M4-core ⛓

#10311 RPC: Implements eth_subscribe("syncing")
  Cargo.lock
  ethcore/light/src/client/mod.rs
  ethcore/src/client/client.rs
  ethcore/src/client/test_client.rs
  ethcore/src/client/traits.rs
  ethcore/sync/Cargo.toml
  ethcore/sync/src/api.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/lib.rs
  ethcore/sync/src/light_sync/mod.rs
  parity/informant.rs
  parity/modules.rs
  parity/rpc_apis.rs
  parity/run.rs
  rpc/src/lib.rs
  rpc/src/v1/helpers/block_import.rs
  rpc/src/v1/helpers/light_fetch.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/impls/eth_pubsub.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/mod.rs
  rpc/src/v1/tests/helpers/sync_provider.rs
  rpc/src/v1/tests/mocked/eth_pubsub.rs
  rpc/src/v1/types/pubsub.rs
  secret-store/src/trusted_client.rs
  updater/src/updater.rs
Labels: A6-mustntgrumble 💦, A7-looksgoodcantmerge 🙄, B7-releasenotes 📜, M4-core ⛓, M6-rpcapi 📣

#10562 Update Issue Template to direct security issue to email
  .github/ISSUE_TEMPLATE.md
Labels: A2-insubstantial 👶, M3-docs 📑

#10559 fix(light cull): poll light cull instead of timer
  Cargo.lock
  parity/light_helpers/mod.rs
  parity/light_helpers/queue_cull.rs
  parity/run.rs
  rpc/src/v1/helpers/light_fetch.rs
  rpc/src/v1/impls/light/eth.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10288 Node table limiting and cache for node filter
  ethcore/node-filter/src/lib.rs
  parity/run.rs
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/lib.rs
  util/network-devp2p/src/node_table.rs
Labels: A8-looksgood 🦄, M2-config 📂, M4-core ⛓

#10561 2.4.5 stable backports
  .gitlab-ci.yml
Labels: A8-backport 🕸, M1-ci 🙉

#10574 ethcore: improve timestamp handling
  ethcore/types/src/header.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10576 beta backports
  ethcore/types/src/header.rs
  parity/light_helpers/mod.rs
  parity/light_helpers/queue_cull.rs
  parity/run.rs
  rpc/src/v1/helpers/light_fetch.rs
  rpc/src/v1/impls/light/eth.rs
Labels: A8-backport 🕸, M4-core ⛓

#10575 stable backports
  ethcore/types/src/header.rs
Labels: A8-backport 🕸, M4-core ⛓

#10586 fix(evmbin): make benches compile again
  evmbin/benches/mod.rs
Labels: A8-looksgood 🦄

#10558 Watch transactions pool
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/light/src/lib.rs
  ethcore/light/src/transaction_queue.rs
  ethcore/src/lib.rs
  ethcore/src/miner/miner.rs
  miner/Cargo.toml
  miner/src/lib.rs
  miner/src/pool/listener.rs
  miner/src/pool/mod.rs
  miner/src/pool/queue.rs
  parity/cli/mod.rs
  parity/rpc_apis.rs
  rpc/src/v1/impls/mod.rs
  rpc/src/v1/impls/transactions_pool.rs
  rpc/src/v1/traits/mod.rs
  rpc/src/v1/traits/transactions_pool.rs
Labels: A8-looksgood 🦄, M6-rpcapi 📣

#10579 CI improvements
  .gitlab-ci.yml
  parity-clib/examples/cpp/CMakeLists.txt
  scripts/gitlab/build-linux.sh
  scripts/gitlab/build-windows.sh
  scripts/gitlab/test-linux.sh
  scripts/gitlab/validate-chainspecs.sh
Labels: M1-ci 🙉

#10587 fix(whisper): change expiry `unix_time + ttl + work`
  whisper/src/message.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷

#10596 sccache logs to stdout
  .gitlab-ci.yml
Labels: M1-ci 🙉

#10584 Allow CORS requests in Secret Store API
  Cargo.lock
  parity/cli/mod.rs
  parity/cli/tests/config.full.toml
  parity/configuration.rs
  parity/secretstore.rs
  secret-store/Cargo.toml
  secret-store/src/lib.rs
  secret-store/src/listener/http_listener.rs
  secret-store/src/types/all.rs
Labels: A8-looksgood 🦄

#10608 adds rpc error message for --no-ancient-blocks
  parity/rpc_apis.rs
  parity/run.rs
  rpc/src/v1/helpers/errors.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/tests/eth.rs
Labels: A8-looksgood 🦄, M6-rpcapi 📣

#10606 Constantinople HF on POA Core
  ethcore/res/ethereum/poacore.json
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M2-config 📂

#10605 Clique: zero-fill extradata when the supplied value is less than 32 bytes in length
  ethcore/src/engines/clique/mod.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10600 evm: add some mulmod benches
  Cargo.lock
  ethcore/evm/Cargo.toml
  ethcore/evm/benches/basic.rs
  ethcore/evm/src/interpreter/mod.rs
  ethcore/evm/src/lib.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10615 Remove unused import
  ethcore/src/engines/clique/mod.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄
