Repository openethereum/openethereum, pull requests merged in 2019-03, with the labels that each got.

#10440 Use correct name for documentation field in Memzero's Cargo.toml
  util/memzero/Cargo.toml
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10438 Silence Error::cause deprecations for upcoming Rust 1.33
  ethcore/light/src/on_demand/mod.rs
  ethcore/private-tx/src/error.rs
  ethcore/service/src/error.rs
  ethcore/src/error.rs
  util/network/src/error.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10446 CI publish to aws
  .gitlab-ci.yml
  scripts/gitlab/publish-aws.sh
Labels: A0-pleasereview 🤓, M1-ci 🙉

#10312 Implement parity_versionInfo & parity_setChain on LC; fix parity_setChain
  ethcore/light/src/client/mod.rs
  ethcore/src/client/client.rs
  ethcore/src/client/test_client.rs
  ethcore/src/client/traits.rs
  parity/rpc_apis.rs
  parity/run.rs
  rpc/src/v1/helpers/errors.rs
  rpc/src/v1/impls/light/parity.rs
  rpc/src/v1/impls/light/parity_set.rs
  rpc/src/v1/impls/parity_set.rs
Labels: A8-looksgood 🦄, B1-patch-beta 🕷🕷, M6-rpcapi 📣

#10451 CI aws git checkout
  .gitlab-ci.yml
  scripts/gitlab/publish-aws.sh
Labels: A0-pleasereview 🤓, M1-ci 🙉

#10456 Revert "CI aws git checkout (#10451)"
  .gitlab-ci.yml
  scripts/gitlab/publish-aws.sh
Labels: A0-pleasereview 🤓, M1-ci 🙉

#10389 docs: update changelogs for 2.2.{8,9,10,11}, 2.3.{1,2,3,4,5}, and 2.4.0
  CHANGELOG.md
  docs/CHANGELOG-2.2.md
  docs/CHANGELOG-2.3.md
Labels: A8-looksgood 🦄, M3-docs 📑

#10454 simplify ethcore machine by removing redundant traits
  ethcore/src/engines/instant_seal.rs
  ethcore/src/engines/mod.rs
  ethcore/src/engines/null_engine.rs
  ethcore/src/machine.rs
  ethcore/types/src/header.rs
  machine/src/lib.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10464 docs(spec): remove link to obsolete issue
  ethcore/src/spec/spec.rs
Labels: A2-insubstantial 👶, M4-core ⛓

#10452 Tests parallelized
  .gitlab-ci.yml
  scripts/gitlab/build-linux.sh
  scripts/gitlab/rust-changes.sh
  scripts/gitlab/test-cpp.sh
  scripts/gitlab/test-linux.sh
  scripts/gitlab/validate-chainspecs.sh
  test.sh
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, F4-tests 💻, M1-ci 🙉

#10467 Ensure static validator set changes are recognized
  ethcore/src/engines/authority_round/mod.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10469 simplify parity machine
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/src/block.rs
  ethcore/src/engines/block_reward.rs
  ethcore/src/engines/instant_seal.rs
  ethcore/src/engines/mod.rs
  ethcore/src/engines/null_engine.rs
  ethcore/src/ethereum/ethash.rs
  ethcore/src/lib.rs
  ethcore/src/machine/impls.rs
  ethcore/src/machine/mod.rs
  ethcore/src/machine/traits.rs
  ethcore/src/trace/types/trace.rs
  ethcore/types/Cargo.toml
  ethcore/types/src/engines/epoch.rs
  ethcore/types/src/header.rs
  ethcore/types/src/lib.rs
  machine/Cargo.toml
Labels: A8-looksgood 🦄, M4-core ⛓

#10472 further simplify machine
  ethcore/src/engines/mod.rs
  ethcore/src/machine/impls.rs
  ethcore/src/machine/traits.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10475 remove unused Engine::is_proposal
  ethcore/src/client/client.rs
  ethcore/src/engines/mod.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10476 remove unused Engine::maximum_uncle_age
  ethcore/src/client/client.rs
  ethcore/src/engines/mod.rs
  ethcore/src/verification/verification.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10479 simplify block module and usage
  ethcore/src/block.rs
  ethcore/src/client/client.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/basic_authority.rs
  ethcore/src/engines/instant_seal.rs
  ethcore/src/ethereum/ethash.rs
  ethcore/src/machine/impls.rs
  ethcore/src/miner/miner.rs
  ethcore/src/tests/client.rs
  rpc/src/v1/tests/helpers/miner_service.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10480 OpenBlock::new take IntoIterator instead of mutable ref to Iterator
  ethcore/src/block.rs
  ethcore/src/client/client.rs
  ethcore/src/client/test_client.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/basic_authority.rs
  ethcore/src/engines/instant_seal.rs
  ethcore/src/ethereum/ethash.rs
  ethcore/src/test_helpers.rs
  ethcore/src/tests/trace.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10477 Сaching through docker volume
  .gitlab-ci.yml
Labels: A3-inprogress ⏳, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#10470 2.3.6 stable backports
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/json_tests/skip.rs
  scripts/gitlab/build-linux.sh
  scripts/gitlab/rust-changes.sh
  scripts/gitlab/test-cpp.sh
  scripts/gitlab/test-linux.sh
  scripts/gitlab/validate-chainspecs.sh
  test.sh
  util/version/Cargo.toml
Labels: A8-backport 🕸, M1-ci 🙉, M4-core ⛓

#10471 2.4.1 beta backports
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/light/src/client/mod.rs
  ethcore/src/client/client.rs
  ethcore/src/client/test_client.rs
  ethcore/src/client/traits.rs
  ethcore/src/engines/authority_round/mod.rs
  parity/rpc_apis.rs
  parity/run.rs
  rpc/src/v1/helpers/errors.rs
  rpc/src/v1/impls/light/parity.rs
  rpc/src/v1/impls/light/parity_set.rs
  rpc/src/v1/impls/parity_set.rs
  scripts/gitlab/build-linux.sh
  scripts/gitlab/rust-changes.sh
  scripts/gitlab/test-cpp.sh
  scripts/gitlab/test-linux.sh
  scripts/gitlab/validate-chainspecs.sh
  test.sh
  util/version/Cargo.toml
Labels: A8-backport 🕸, M1-ci 🙉, M4-core ⛓

#10486 fix win&mac build
  .gitlab-ci.yml
Labels: A4-awaitingci 🤖, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#10489 fix(rpc): add lint `unused_extern_crates` + fix warns
  Cargo.lock
  rpc/Cargo.toml
  rpc/src/lib.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓, M5-dependencies 🖇

#10383 fix(extract `timestamp_checked_add` as lib)
  Cargo.lock
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/lib.rs
  ethcore/src/verification/verification.rs
  util/time-utils/Cargo.toml
  util/time-utils/src/lib.rs
  whisper/Cargo.toml
  whisper/src/lib.rs
  whisper/src/message.rs
  whisper/src/net/mod.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10488 2.4.2 beta backports
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/lib.rs
  ethcore/src/verification/verification.rs
  util/time-utils/Cargo.toml
  util/time-utils/src/lib.rs
  util/version/Cargo.toml
  whisper/Cargo.toml
  whisper/src/lib.rs
  whisper/src/message.rs
  whisper/src/net/mod.rs
Labels: A8-backport 🕸, M1-ci 🙉

#10487 2.3.7 stable backports
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/lib.rs
  ethcore/src/verification/verification.rs
  util/time-utils/Cargo.toml
  util/time-utils/src/lib.rs
  util/version/Cargo.toml
  whisper/Cargo.toml
  whisper/src/lib.rs
  whisper/src/message.rs
  whisper/src/net/mod.rs
Labels: A8-backport 🕸, M1-ci 🙉

#10497 fix(time-utils): add missing license
  util/time-utils/src/lib.rs
Labels: A2-insubstantial 👶, M3-docs 📑

#10057 whisper/cli: add p2p port and ip parameters
  Cargo.lock
  whisper/README.md
  whisper/cli/Cargo.toml
  whisper/cli/src/main.rs
Labels: A8-looksgood 🦄, M2-config 📂

#10503 Add additional request tests
  ethcore/light/src/types/request/batch.rs
  ethcore/light/src/types/request/mod.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷

#10507 2.3.8 stable backports
  Cargo.lock
  Cargo.toml
  ethcore/light/src/types/request/batch.rs
  ethcore/light/src/types/request/mod.rs
  util/version/Cargo.toml
Labels: A8-backport 🕸, M4-core ⛓

#10508 2.4.3 beta backports
  Cargo.lock
  Cargo.toml
  ethcore/light/src/types/request/batch.rs
  ethcore/light/src/types/request/mod.rs
  util/version/Cargo.toml
Labels: A8-backport 🕸, M4-core ⛓

#10509 fix Sha3/keccak256 hash calculation for binaries
  scripts/gitlab/build-linux.sh
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉, P2-asap 🌊

#10493 fix(rpc): fix a bunch of clippy lints
  parity/rpc_apis.rs
  rpc/src/authcodes.rs
  rpc/src/http_common.rs
  rpc/src/lib.rs
  rpc/src/tests/helpers.rs
  rpc/src/tests/http_client.rs
  rpc/src/tests/ws.rs
  rpc/src/v1/extractors.rs
  rpc/src/v1/helpers/deprecated.rs
  rpc/src/v1/helpers/dispatch/light.rs
  rpc/src/v1/helpers/dispatch/mod.rs
  rpc/src/v1/helpers/external_signer/mod.rs
  rpc/src/v1/helpers/external_signer/oneshot.rs
  rpc/src/v1/helpers/external_signer/signing_queue.rs
  rpc/src/v1/helpers/fake_sign.rs
  rpc/src/v1/helpers/ipfs.rs
  rpc/src/v1/helpers/light_fetch.rs
  rpc/src/v1/helpers/signature.rs
  rpc/src/v1/helpers/subscription_manager.rs
  rpc/src/v1/helpers/work.rs
  rpc/src/v1/impls/debug.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/impls/eth_filter.rs
  rpc/src/v1/impls/eth_pubsub.rs
  rpc/src/v1/impls/light/eth.rs
  rpc/src/v1/impls/light/net.rs
  rpc/src/v1/impls/light/parity.rs
  rpc/src/v1/impls/light/parity_set.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/impls/parity_set.rs
  rpc/src/v1/impls/private.rs
  rpc/src/v1/impls/pubsub.rs
  rpc/src/v1/impls/rpc.rs
  rpc/src/v1/impls/signer.rs
  rpc/src/v1/impls/signing.rs
  rpc/src/v1/impls/signing_unsafe.rs
  rpc/src/v1/impls/traces.rs
  rpc/src/v1/impls/web3.rs
  rpc/src/v1/informant.rs
  rpc/src/v1/tests/mocked/web3.rs
  rpc/src/v1/types/block.rs
  rpc/src/v1/types/block_number.rs
  rpc/src/v1/types/confirmations.rs
  rpc/src/v1/types/consensus_status.rs
  rpc/src/v1/types/filter.rs
  rpc/src/v1/types/log.rs
  rpc/src/v1/types/private_receipt.rs
  rpc/src/v1/types/pubsub.rs
  rpc/src/v1/types/receipt.rs
  rpc/src/v1/types/sync.rs
  rpc/src/v1/types/trace.rs
  rpc/src/v1/types/transaction.rs
  rpc/src/v1/types/transaction_request.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10494 docs: add changelogs for 2.3.{6,7,8} and 2.4.{1,2,3}
  CHANGELOG.md
  docs/CHANGELOG-2.3.md
Labels: A8-looksgood 🦄, M3-docs 📑

#10511 Add a more realistic Batch test
  ethcore/light/src/types/request/batch.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#10524 verbose flag for cpp tests
  scripts/gitlab/test-cpp.sh
Labels: A1-onice 🌨, M1-ci 🙉

#9981 ethcore: add clique engine
  ethcore/Cargo.toml
  ethcore/res/ethereum/goerli.json
  ethcore/res/ethereum/kotti.json
  ethcore/res/ethereum/rinkeby.json
  ethcore/src/block.rs
  ethcore/src/client/client.rs
  ethcore/src/engines/clique/block_state.rs
  ethcore/src/engines/clique/mod.rs
  ethcore/src/engines/clique/params.rs
  ethcore/src/engines/clique/step_service.rs
  ethcore/src/engines/clique/tests.rs
  ethcore/src/engines/clique/util.rs
  ethcore/src/engines/mod.rs
  ethcore/src/ethereum/mod.rs
  ethcore/src/miner/miner.rs
  ethcore/src/spec/spec.rs
  json/src/spec/clique.rs
  json/src/spec/engine.rs
  json/src/spec/mod.rs
  parity/cli/mod.rs
  parity/params.rs
  util/version/Cargo.toml
Labels: A8-looksgood 🦄, B7-releasenotes 📜, M4-core ⛓, Q3-bounty 💸

#10519 Add trace information to eth_estimateGas
  ethcore/src/client/client.rs
  ethcore/src/executed.rs
  rpc/src/v1/helpers/errors.rs
Labels: A6-mustntgrumble 💦, F8-enhancement 🎊, M6-rpcapi 📣

#10510 private-tx: replace error_chain
  Cargo.lock
  ethcore/private-tx/Cargo.toml
  ethcore/private-tx/src/encryptor.rs
  ethcore/private-tx/src/error.rs
  ethcore/private-tx/src/lib.rs
  ethcore/private-tx/src/private_transactions.rs
  ethcore/service/src/error.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10520 Initial support sccache for windows build
  .gitlab-ci.yml
  scripts/gitlab/build-windows.sh
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M0-build 🏗, M1-ci 🙉

#10531 ethcore: remove eth social and easthub chain configs
  ethcore/res/ethereum/easthub.json
  ethcore/res/ethereum/social.json
  ethcore/src/ethereum/mod.rs
  parity/cli/mod.rs
  parity/params.rs
Labels: A2-insubstantial 👶, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, B7-releasenotes 📜, M2-config 📂

#10537 Fix max_gas
  rpc/src/v1/helpers/fake_sign.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷

#10540 fix(bump dependencies)
  Cargo.lock
Labels: A8-looksgood 🦄, M5-dependencies 🖇

#10543 separate docker image to build docs
  .gitlab-ci.yml
Labels: M1-ci 🙉

#10542 updated lru-cache to 0.1.2
  Cargo.lock
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M5-dependencies 🖇

#10551 clique: make state backfill time measurement more accurate
  ethcore/src/engines/clique/mod.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#10546 build android with cache, win fixes
  .gitlab-ci.yml
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#10088 Implement caching for service transactions checker
  ethcore/private-tx/src/lib.rs
  ethcore/src/client/client.rs
  ethcore/src/miner/miner.rs
  ethcore/src/miner/pool_client.rs
  miner/src/service_transaction_checker.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10535 fix(light eth_gasPrice): ask network if not in cache
  rpc/src/v1/helpers/light_fetch.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/impls/light/eth.rs
  rpc/src/v1/traits/eth.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓, M6-rpcapi 📣

#10547 Update light client harcoded headers
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/morden.json
  ethcore/res/ethereum/ropsten.json
Labels: A2-insubstantial 👶, A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷

#10545 fix(light account response): update `tx_queue` on every account request/response
  rpc/src/v1/helpers/light_fetch.rs
  rpc/src/v1/impls/light/eth.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓
