Repository openethereum/openethereum, pull requests merged in 2019-07, with the labels that each got.

#10827 Beta 2.5.4
  Cargo.lock
  Cargo.toml
  util/version/Cargo.toml
Labels: A8-backport 🕸

#10826 Stable 2.4.9
  Cargo.lock
  Cargo.toml
  util/version/Cargo.toml
Labels: A8-backport 🕸

#10796 Better logging when backfilling ancient blocks fail
  ethcore/blockchain/src/best_block.rs
  ethcore/blockchain/src/blockchain.rs
  ethcore/db/src/keys.rs
  ethcore/src/snapshot/consensus/authority.rs
  ethcore/src/snapshot/consensus/mod.rs
  ethcore/src/snapshot/consensus/work.rs
  ethcore/src/snapshot/error.rs
  ethcore/src/snapshot/service.rs
  ethcore/src/snapshot/tests/helpers.rs
  ethcore/src/snapshot/tests/proof_of_work.rs
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/types/src/restoration_status.rs
  parity/informant.rs
  parity/snapshot.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#10829 ethcore does not use byteorder
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/src/builtin.rs
  ethcore/src/lib.rs
  ethcore/src/state_db.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10828 Fix typo in README.md
  README.md
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M3-docs 📑

#10831 Remove excessive warning
  rpc/src/v1/helpers/engine_signer.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#10814 When updating the client or when called from RPC, sleep should mean sleep
  ethcore/src/client/client.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10830 Allow --nat extip:your.host.here.org
  parity/configuration.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10834 idiomatic changes to PodState
  ethcore/src/pod_account.rs
  ethcore/src/pod_state.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶

#10657 refactor: Related #9459 - evmbin: replace untyped json! macro with fully typed serde serialization using Rust structs
  accounts/ethstore/src/json/crypto.rs
  evmbin/src/display/json.rs
  evmbin/src/display/std_json.rs
  evmbin/src/info.rs
Labels: A0-pleasereview 🤓

#10833 Break circular dependency between Client and Engine (part 1)
  ethcore/src/block.rs
  ethcore/src/client/client.rs
  ethcore/src/client/test_client.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/basic_authority.rs
  ethcore/src/engines/clique/mod.rs
  ethcore/src/engines/clique/tests.rs
  ethcore/src/engines/instant_seal.rs
  ethcore/src/engines/mod.rs
  ethcore/src/engines/null_engine.rs
  ethcore/src/ethereum/ethash.rs
  ethcore/src/miner/miner.rs
  ethcore/src/test_helpers.rs
  ethcore/src/tests/client.rs
  ethcore/src/tests/trace.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10812 refactor: whisper: Add type aliases and update rustdocs in message.rs
  whisper/src/message.rs
  whisper/src/rpc/filter.rs
  whisper/src/rpc/mod.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10817 Improve logging when remote peer is unknown
  util/network-devp2p/src/connection.rs
Labels: A0-pleasereview 🤓, A8-looksgood 🦄

#10838 Extricate PodAccount and state Account to own crates
  Cargo.lock
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/pod-account/Cargo.toml
  ethcore/pod-account/src/lib.rs
  ethcore/src/account_db.rs
  ethcore/src/lib.rs
  ethcore/src/snapshot/account.rs
  ethcore/src/state/mod.rs
  ethcore/state-account/Cargo.toml
  ethcore/state-account/src/lib.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10811 test: whisper/cli `add invalid pool size test depending on processor`
  whisper/cli/src/main.rs
Labels: A7-looksgoodtestsfail 🤖, M5-binaries 📦

#10839 Extract AccountDB to account-db
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/account-db/Cargo.toml
  ethcore/account-db/src/lib.rs
  ethcore/src/lib.rs
  ethcore/src/snapshot/account.rs
  ethcore/state-account/Cargo.toml
  ethcore/state-account/src/lib.rs
Labels: A2-insubstantial 👶, A7-looksgoodtestsfail 🤖

#10745 Improve logging and cleanup in miner around block sealing
  ethcore/blockchain/src/blockchain.rs
  ethcore/src/block.rs
  ethcore/src/client/client.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/mod.rs
  ethcore/src/engines/validator_set/contract.rs
  ethcore/src/engines/validator_set/safe_contract.rs
  ethcore/src/engines/validator_set/test.rs
  ethcore/src/miner/miner.rs
  ethcore/src/state/mod.rs
  ethcore/sync/src/block_sync.rs
  miner/using-queue/src/lib.rs
  util/journaldb/src/traits.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10841 update jsonrpc to 12.0
  Cargo.lock
  Cargo.toml
  cli-signer/rpc-client/Cargo.toml
  ipfs/Cargo.toml
  miner/stratum/Cargo.toml
  parity/configuration.rs
  parity/rpc.rs
  rpc/Cargo.toml
  rpc/src/v1/traits/debug.rs
  rpc/src/v1/traits/eth.rs
  rpc/src/v1/traits/eth_pubsub.rs
  rpc/src/v1/traits/eth_signing.rs
  rpc/src/v1/traits/net.rs
  rpc/src/v1/traits/parity.rs
  rpc/src/v1/traits/parity_accounts.rs
  rpc/src/v1/traits/parity_set.rs
  rpc/src/v1/traits/parity_signing.rs
  rpc/src/v1/traits/personal.rs
  rpc/src/v1/traits/private.rs
  rpc/src/v1/traits/pubsub.rs
  rpc/src/v1/traits/rpc.rs
  rpc/src/v1/traits/secretstore.rs
  rpc/src/v1/traits/signer.rs
  rpc/src/v1/traits/traces.rs
  rpc/src/v1/traits/transactions_pool.rs
  rpc/src/v1/traits/web3.rs
  secret-store/Cargo.toml
  whisper/Cargo.toml
  whisper/cli/Cargo.toml
  whisper/src/lib.rs
  whisper/src/rpc/mod.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M5-dependencies 🖇

#10846 Update version to 2.7.0
  Cargo.lock
  Cargo.toml
  util/version/Cargo.toml
Labels: A8-looksgood 🦄

#10845 update parking-lot to 0.8
  Cargo.lock
  Cargo.toml
  accounts/Cargo.toml
  accounts/ethstore/Cargo.toml
  accounts/ethstore/cli/Cargo.toml
  cli-signer/rpc-client/Cargo.toml
  ethash/Cargo.toml
  ethcore/Cargo.toml
  ethcore/blockchain/Cargo.toml
  ethcore/db/Cargo.toml
  ethcore/evm/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/node-filter/Cargo.toml
  ethcore/private-tx/Cargo.toml
  ethcore/sync/Cargo.toml
  miner/Cargo.toml
  miner/stratum/Cargo.toml
  parity/logger/Cargo.toml
  rpc/Cargo.toml
  secret-store/Cargo.toml
  updater/Cargo.toml
  updater/hash-fetch/Cargo.toml
  util/blooms-db/Cargo.toml
  util/io/Cargo.toml
  util/journaldb/Cargo.toml
  util/len-caching-lock/Cargo.toml
  util/network-devp2p/Cargo.toml
  whisper/Cargo.toml
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10843 make fn submit_seal more idiomatic
  ethcore/src/miner/miner.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10847 removed unused trait PrivateNotify and unused Error types
  ethcore/src/client/mod.rs
  ethcore/src/client/private_notify.rs
  ethcore/src/error.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10848 bump crossbeam
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/src/executive.rs
  ethcore/src/lib.rs
  ethcore/src/snapshot/mod.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10851 removed unused macros
  util/macros/Cargo.toml
  util/macros/src/lib.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10852 remove QueueError
  ethcore/src/client/client.rs
  ethcore/src/error.rs
  ethcore/sync/src/block_sync.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10850 ethcore-builtin
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/builtin/Cargo.toml
  ethcore/builtin/src/lib.rs
  ethcore/src/executive.rs
  ethcore/src/lib.rs
Labels: A2-insubstantial 👶, A6-mustntgrumble 💦

#10771 EIP-1702: Generalized Account Versioning Scheme
  ethcore/evm/src/interpreter/mod.rs
  ethcore/light/src/on_demand/request.rs
  ethcore/pod-account/src/lib.rs
  ethcore/src/executive.rs
  ethcore/src/externalities.rs
  ethcore/src/factory.rs
  ethcore/src/json_tests/executive.rs
  ethcore/src/machine.rs
  ethcore/src/pod_state.rs
  ethcore/src/snapshot/account.rs
  ethcore/src/spec/spec.rs
  ethcore/src/state/mod.rs
  ethcore/src/tests/evm.rs
  ethcore/state-account/src/lib.rs
  ethcore/types/src/basic_account.rs
  ethcore/vm/src/action_params.rs
  ethcore/vm/src/ext.rs
  ethcore/vm/src/lib.rs
  ethcore/vm/src/schedule.rs
  ethcore/vm/src/tests.rs
  ethcore/wasm/src/lib.rs
  ethcore/wasm/src/runtime.rs
  json/src/blockchain/account.rs
  json/src/spec/account.rs
  json/src/spec/params.rs
  json/src/vm/transaction.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10860 [ethash] use static_assertions crate
  Cargo.lock
  ethash/Cargo.toml
  ethash/src/lib.rs
  ethash/src/shared.rs
Labels: A2-insubstantial 👶

#10865 Remove compiler warning
  rpc/src/v1/helpers/engine_signer.rs
Labels: A2-insubstantial 👶, M4-core ⛓

#10837 Fix fork choice
  Cargo.lock
  ethcore/blockchain/Cargo.toml
  ethcore/blockchain/src/blockchain.rs
  ethcore/blockchain/src/generator.rs
  ethcore/private-tx/src/lib.rs
  ethcore/src/machine.rs
Labels: A7-looksgoodcantmerge 🙄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10858 Extract state-db from ethcore
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/private-tx/Cargo.toml
  ethcore/private-tx/src/lib.rs
  ethcore/service/src/service.rs
  ethcore/src/lib.rs
  ethcore/src/machine.rs
  ethcore/src/spec/spec.rs
  ethcore/state-db/Cargo.toml
  ethcore/state-db/src/lib.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10849 removed redundant fork choice abstraction
  ethcore/src/client/client.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/basic_authority.rs
  ethcore/src/engines/clique/mod.rs
  ethcore/src/engines/instant_seal.rs
  ethcore/src/engines/mod.rs
  ethcore/src/engines/null_engine.rs
  ethcore/src/ethereum/ethash.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10769 refactor: Move run_transaction params into fields of a TxInput struct and make doc comments of its fields
  ethcore/src/client/evm_test_client.rs
  ethcore/src/json_tests/chain.rs
  ethcore/src/json_tests/state.rs
  ethcore/src/json_tests/transaction.rs
  ethcore/types/src/transaction/transaction.rs
  evmbin/README.md
  evmbin/src/info.rs
  evmbin/src/main.rs
Labels: A0-pleasereview 🤓

#10854 Run cargo fix on a few of the worst offenders
  ethcore/db/src/db.rs
  ethcore/evm/src/factory.rs
  ethcore/evm/src/interpreter/gasometer.rs
  ethcore/evm/src/interpreter/memory.rs
  ethcore/evm/src/interpreter/mod.rs
  ethcore/evm/src/tests.rs
  ethcore/light/src/cht.rs
  ethcore/light/src/client/fetch.rs
  ethcore/light/src/client/header_chain.rs
  ethcore/light/src/client/mod.rs
  ethcore/light/src/client/service.rs
  ethcore/light/src/net/context.rs
  ethcore/light/src/net/load_timer.rs
  ethcore/light/src/net/mod.rs
  ethcore/light/src/on_demand/mod.rs
  ethcore/light/src/on_demand/request.rs
  ethcore/light/src/on_demand/tests.rs
  ethcore/sync/src/api.rs
  ethcore/sync/src/block_sync.rs
  ethcore/sync/src/blocks.rs
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/propagator.rs
  ethcore/sync/src/chain/requester.rs
  ethcore/sync/src/chain/supplier.rs
  ethcore/sync/src/light_sync/mod.rs
  ethcore/sync/src/snapshot.rs
  ethcore/sync/src/sync_io.rs
  ethcore/sync/src/tests/consensus.rs
  ethcore/sync/src/tests/helpers.rs
  ethcore/sync/src/tests/private.rs
  ethcore/types/src/lib.rs
  ethcore/types/src/restoration_status.rs
  ethcore/vm/src/error.rs
  ethcore/vm/src/lib.rs
  ethcore/wasm/src/lib.rs
  ethcore/wasm/src/runtime.rs
  ethcore/wasm/src/tests.rs
  util/journaldb/src/archivedb.rs
  util/journaldb/src/as_hash_db_impls.rs
  util/journaldb/src/earlymergedb.rs
  util/journaldb/src/lib.rs
  util/journaldb/src/overlaydb.rs
  util/journaldb/src/overlayrecentdb.rs
  util/journaldb/src/refcounteddb.rs
  util/journaldb/src/traits.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#10867 Move the substate module into ethcore/executive
  Cargo.lock
  ethcore/account-state/Cargo.toml
  ethcore/account-state/src/lib.rs
  ethcore/account-state/src/state.rs
  ethcore/src/client/evm_test_client.rs
  ethcore/src/executive.rs
  ethcore/src/externalities.rs
  ethcore/src/json_tests/executive.rs
  ethcore/src/lib.rs
  ethcore/src/machine.rs
  ethcore/src/spec/spec.rs
  ethcore/src/substate.rs
  ethcore/src/tests/evm.rs
  evmbin/src/info.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  rpc/src/v1/tests/helpers/miner_service.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10863 Docker images renaming
  .gitlab-ci.yml
Labels: A8-backport 🕸, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#10861 [ethash] remove mem::uninitialized
  ethash/benches/basic.rs
  ethash/src/compute.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#10855 whisper is no longer a part of parity-ethereum repo
  Cargo.lock
  Cargo.toml
  README.md
  accounts/ethkey/README.md
  accounts/ethstore/README.md
  ethcore/sync/src/api.rs
  evmbin/README.md
  parity/cli/mod.rs
  parity/configuration.rs
  parity/deprecated.rs
  parity/lib.rs
  parity/modules.rs
  parity/rpc_apis.rs
  parity/run.rs
  parity/whisper.rs
  scripts/gitlab/build-linux.sh
  scripts/gitlab/build-windows.sh
  scripts/snap/snapcraft.template.yaml
  whisper/Cargo.toml
  whisper/README.md
  whisper/cli/Cargo.toml
  whisper/cli/src/main.rs
  whisper/src/aes_gcm/mod.rs
  whisper/src/lib.rs
  whisper/src/message.rs
  whisper/src/net/mod.rs
  whisper/src/net/tests.rs
  whisper/src/rpc/crypto.rs
  whisper/src/rpc/filter.rs
  whisper/src/rpc/key_store.rs
  whisper/src/rpc/mod.rs
  whisper/src/rpc/payload.rs
  whisper/src/rpc/types.rs
Labels: A8-looksgood 🦄, B7-releasenotes 📜, M4-core ⛓

#10866 Update README.md and Changelogs
  CHANGELOG.md
  README.md
  docs/CHANGELOG-2.4.md
  docs/CHANGELOG-2.5.md
Labels: A0-pleasereview 🤓, M3-docs 📑

#10868 Move DatabaseExtras back to trace
  Cargo.lock
  ethcore/blockchain/src/database_extras.rs
  ethcore/blockchain/src/lib.rs
  ethcore/src/client/client.rs
  ethcore/trace/Cargo.toml
  ethcore/trace/src/db.rs
  ethcore/trace/src/import.rs
  ethcore/trace/src/lib.rs
  ethcore/trace/src/types/localized.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#10890 simplify create_address_scheme
  Cargo.lock
  ethcore/private-tx/Cargo.toml
  ethcore/private-tx/src/lib.rs
  ethcore/src/client/client.rs
  ethcore/src/client/evm_test_client.rs
  ethcore/src/engines/mod.rs
  ethcore/src/executive.rs
  ethcore/src/machine.rs
  ethcore/src/miner/miner.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10888 rename is_pruned to is_prunable
  ethcore/src/client/client.rs
  ethcore/state-db/src/lib.rs
  util/journaldb/src/archivedb.rs
  util/journaldb/src/traits.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10889 TransactionQueue::import accepts iterator
  ethcore/src/miner/miner.rs
  miner/src/pool/queue.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10892 return block nonce when engine is clique
  ethcore/src/engines/clique/mod.rs
Labels: A8-looksgood 🦄, M4-core ⛓, M6-rpcapi 📣

#10899 cleanup ethcore ethereum module
  ethcore/src/ethereum.rs
  ethcore/types/Cargo.toml
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10900 Avast whitelist script
  .gitlab-ci.yml
  scripts/gitlab/publish-av-whitelists.sh
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷

#10891 remove verify_transaction_unordered from engine
  ethcore/src/engines/mod.rs
  ethcore/src/json_tests/transaction.rs
  ethcore/src/machine.rs
  ethcore/src/miner/pool_client.rs
  ethcore/src/verification/verification.rs
  ethcore/types/src/transaction/transaction.rs
Labels: A7-looksgoodcantmerge 🙄, M4-core ⛓

#10911 Add file path to DiskMap write/read warnings
  accounts/src/stores.rs
Labels: A8-looksgood 🦄

#10913 Fixes incorrect comment.
  miner/src/pool/scoring.rs
Labels: A2-insubstantial 👶, F5-documentation 📑

#10921 Fix cargo audit
  Cargo.lock
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, M5-dependencies 🖇

#10916 Additional arithmetic EVM opcode benchmarks
  ethcore/evm/benches/basic.rs
Labels: A8-looksgood 🦄

#10919 Kaspersky AV whitelisting
  .gitlab-ci.yml
  scripts/gitlab/publish-av-whitelists.sh
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷

#10906 simplify BlockReward::reward implementation
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/block_reward.rs
  ethcore/src/engines/ethash.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10904 get rid of hidden mutability of Spec
  ethcore/pod/src/state.rs
  ethcore/src/json_tests/chain.rs
  ethcore/src/spec/spec.rs
  json/src/bytes.rs
  json/src/spec/hardcoded_sync.rs
  parity/export_hardcoded_sync.rs
  rpc/src/v1/tests/eth.rs
Labels: A8-looksgood 🦄, M4-core ⛓
