Repository openethereum/openethereum, pull requests merged in 2019-01, with the labels that each got.

#10119 Fix broken links in all README.md files
  README.md
  accounts/ethkey/README.md
  accounts/ethstore/README.md
  evmbin/README.md
  whisper/README.md
Labels: A2-insubstantial 👶, M3-docs 📑

#10077 HF in POA Sokol (2019-01-04)
  ethcore/res/ethereum/poacore.json
  ethcore/res/ethereum/poasokol.json
Labels: A8-looksgood 🦄, B7-releasenotes 📜, M2-config 📂

#9644 refactor (hardware wallet) : reduce the number of threads
  accounts/hw/src/ledger.rs
  accounts/hw/src/lib.rs
  accounts/hw/src/trezor.rs
Labels: A6-mustntgrumble 💦, M4-core ⛓

#9920 parity-clib: `async C bindings to RPC requests` + `subscribe/unsubscribe to websocket events`
  Cargo.lock
  parity-clib/Cargo.toml
  parity-clib/Parity.java
  parity-clib/examples/cpp/CMakeLists.txt
  parity-clib/examples/cpp/main.cpp
  parity-clib/examples/java/Main.java
  parity-clib/examples/java/README.md
  parity-clib/examples/java/run.sh
  parity-clib/parity.h
  parity-clib/src/java.rs
  parity-clib/src/lib.rs
  parity/lib.rs
  parity/run.rs
  rpc/src/lib.rs
Labels: A6-mustntgrumble 💦, A7-looksgoodcantmerge 🙄, M4-core ⛓, M6-rpcapi 📣

#10124 Bump rocksdb-sys to 0.5.5
  Cargo.lock
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M5-dependencies 🖇

#9710 Pyethereum keystore support
  Cargo.lock
  accounts/ethkey/cli/src/main.rs
  accounts/ethstore/Cargo.toml
  accounts/ethstore/cli/Cargo.toml
  accounts/ethstore/cli/src/main.rs
  accounts/ethstore/src/account/crypto.rs
  accounts/ethstore/src/account/kdf.rs
  accounts/ethstore/src/account/safe_account.rs
  accounts/ethstore/src/accounts_dir/disk.rs
  accounts/ethstore/src/ethstore.rs
  accounts/ethstore/src/import.rs
  accounts/ethstore/src/json/crypto.rs
  accounts/ethstore/src/json/kdf.rs
  accounts/ethstore/src/json/key_file.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10117 Use LenCachingMutex to optimize verification.
  ethcore/src/verification/queue/mod.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#10128 Identity fix
  ethcore/sync/src/chain/propagator.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10134 Update pwasm-utils to 0.6.1
  Cargo.lock
  ethcore/wasm/Cargo.toml
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M5-dependencies 🖇

#9999 Private tx enabled flag added into STATUS packet
  Cargo.lock
  ethcore/sync/src/api.rs
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/propagator.rs
  ethcore/sync/src/tests/helpers.rs
  parity/modules.rs
  parity/run.rs
Labels: A7-looksgoodcantmerge 🙄, M4-core ⛓

#10042 Don't try to send oversized packets
  ethcore/src/client/test_client.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/supplier.rs
  ethcore/sync/src/sync_io.rs
  ethcore/sync/src/tests/helpers.rs
  util/network-devp2p/src/connection.rs
  util/network-devp2p/src/host.rs
  util/network/src/lib.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10067 Autogen docs for the "Configuring Parity Ethereum" wiki page.
  .gitlab-ci.yml
  scripts/gitlab/publish-docs.sh
Labels: A0-pleasereview 🤓, M1-ci 🙉, M3-docs 📑

#10143 Remove caching for node permissioning check
  ethcore/node-filter/src/lib.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10054 finality: dont require chain head to be in the chain
  ethcore/src/engines/authority_round/mod.rs
Labels: A8-looksgood 🦄, B1-patch-beta 🕷🕷, M4-core ⛓

#10102 Replace ethcore-logger with env-logger.
  Cargo.lock
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/private-tx/Cargo.toml
  ethcore/private-tx/src/lib.rs
  ethcore/private-tx/tests/private_contract.rs
  ethcore/src/json_tests/chain.rs
  ethcore/src/json_tests/difficulty.rs
  ethcore/src/json_tests/state.rs
  ethcore/src/lib.rs
  ethcore/src/snapshot/tests/service.rs
  ethcore/src/spec/spec.rs
  ethcore/src/state/mod.rs
  ethcore/src/state_db.rs
  ethcore/sync/Cargo.toml
  ethcore/sync/src/lib.rs
  ethcore/wasm/Cargo.toml
  ethcore/wasm/run/Cargo.toml
  ethcore/wasm/run/src/main.rs
  ethcore/wasm/src/lib.rs
  ethcore/wasm/src/tests.rs
  miner/stratum/Cargo.toml
  miner/stratum/src/lib.rs
  parity/lib.rs
  parity/logger/Cargo.toml
  parity/logger/src/lib.rs
  parity/logger/src/rotating.rs
  rpc/Cargo.toml
  rpc/src/v1/impls/parity.rs
  secret-store/Cargo.toml
  secret-store/src/key_server.rs
  secret-store/src/key_server_cluster/cluster.rs
  secret-store/src/lib.rs
  util/journaldb/Cargo.toml
  util/journaldb/src/earlymergedb.rs
  util/journaldb/src/lib.rs
  util/journaldb/src/overlayrecentdb.rs
  util/network-devp2p/Cargo.toml
  util/network-devp2p/src/lib.rs
  util/network-devp2p/tests/tests.rs
  whisper/cli/Cargo.toml
  whisper/cli/src/main.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10152 Update EWF's tobalaba chainspec
  ethcore/res/ethereum/tobalaba.json
Labels: A8-looksgood 🦄, M2-config 📂

#10155 HF in POA Core (2019-01-18) - Constantinople
  ethcore/res/ethereum/poacore.json
Labels: A8-looksgood 🦄, B1-patch-beta 🕷🕷, M2-config 📂

#10142 ci: re-enable snap publishing
  .gitlab-ci.yml
  scripts/gitlab/publish-snap.sh
  scripts/snap/icon.png
  scripts/snap/parity.desktop
  scripts/snap/snapcraft.template.yaml
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#10138 Make sure parent block is not in importing queue when importing ancient blocks
  ethcore/src/client/client.rs
Labels: A8-looksgood 🦄, B1-patch-beta 🕷🕷, M4-core ⛓

#10113 beta backports v2.2.6
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/private-tx/src/lib.rs
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/poacore.json
  ethcore/res/ethereum/poasokol.json
  ethcore/res/ethereum/ropsten.json
  ethcore/src/client/chain_notify.rs
  ethcore/src/client/client.rs
  ethcore/src/client/mod.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/snapshot/watcher.rs
  ethcore/sync/src/api.rs
  ethcore/sync/src/chain/propagator.rs
  ethcore/sync/src/tests/helpers.rs
  ethcore/wasm/Cargo.toml
  parity/informant.rs
  rpc/src/v1/helpers/light_fetch.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/impls/eth_pubsub.rs
  rpc/src/v1/impls/light/parity.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/tests/mocked/eth_pubsub.rs
  rpc/src/v1/traits/parity.rs
  scripts/gitlab/publish-docs.sh
  scripts/gitlab/publish-snap.sh
  scripts/snap/icon.png
  scripts/snap/parity.desktop
  scripts/snap/snapcraft.template.yaml
  secret_store/src/acl_storage.rs
  secret_store/src/key_server_set.rs
  secret_store/src/listener/service_contract_listener.rs
  test.sh
  updater/src/updater.rs
  util/version/Cargo.toml
Labels: A0-pleasereview 🤓, A8-backport 🕸, M2-config 📂

#10157 snap: fix path in script
  scripts/gitlab/publish-snap.sh
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#10071 Merge Machine and WithBalances
  ethcore/src/engines/block_reward.rs
  ethcore/src/engines/null_engine.rs
  ethcore/src/machine.rs
  machine/src/lib.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10159 refactor(trim_right_matches -> trim_end_matches)
  rpc/src/v1/types/transaction_request.rs
Labels: A2-insubstantial 👶, M4-core ⛓

#10161 fix(android): remove dependency to libusb
  ethcore/Cargo.toml
  ethcore/src/lib.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
Labels: A2-insubstantial 👶, M4-core ⛓

#10167 Ping nodes from discovery
  util/network-devp2p/src/discovery.rs
Labels: A8-looksgood 🦄

#10151 Bump JSON-RPC
  Cargo.lock
  rpc/src/tests/ws.rs
  rpc/src/v1/extractors.rs
Labels: A8-looksgood 🦄, M6-rpcapi 📣

#10166 fix(whisper): correct PoW calculation
  whisper/src/message.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10144 Fix _cannot recursively call into `Core`_ issue
  Cargo.lock
  util/network-devp2p/src/ip_utils.rs
Labels: A6-mustntgrumble 💦, B1-patch-beta 🕷🕷, M4-core ⛓

#10140 [ci] Fix #9822: trace_filter does not return failed contract creation
  ethcore/src/trace/types/filter.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10170 Remove reference to ui-interface command-line option
  parity/cli/mod.rs
Labels: A2-insubstantial 👶, M3-docs 📑

#10141 Skip locking in statedb for non-canon blocks
  ethcore/src/state_db.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#10179 Fix panic on Light Client shutdown
  parity/run.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10060 Align personal_unlockAccount behaviour when permanent unlock is disabled
  rpc/src/v1/impls/personal.rs
  rpc/src/v1/tests/mocked/personal.rs
Labels: A8-looksgood 🦄, M6-rpcapi 📣

#10186 version: bump fork blocks for kovan and foundation
  util/version/Cargo.toml
Labels: A2-insubstantial 👶, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#10189 pull constantinople on ethereum network
  ethcore/res/ethereum/foundation.json
  util/version/Cargo.toml
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, B9-blocker 🚧, M2-config 📂, P0-dropeverything 🌋

#10195 Fix _cannot recursively call into `Core`_ - Part 2
  util/network-devp2p/src/ip_utils.rs
Labels: A8-looksgood 🦄, B1-patch-beta 🕷🕷, M4-core ⛓

#9782 Adds cli interface to allow reseting chain to a particular block
  ethcore/blockchain/src/blockchain.rs
  ethcore/blockchain/src/lib.rs
  ethcore/src/client/client.rs
  ethcore/src/client/mod.rs
  ethcore/src/client/traits.rs
  parity/blockchain.rs
  parity/cli/mod.rs
  parity/configuration.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10198 Cancel Constantinople HF on POA Core
  ethcore/res/ethereum/poacore.json
Labels: A0-pleasereview 🤓, M2-config 📂

#10197 Update the changelogs for 2.1.11, 2.2.6, 2.2.7, and 2.3.0
  CHANGELOG.md
  docs/CHANGELOG-2.0.md
  docs/CHANGELOG-2.1.md
  docs/CHANGELOG-2.2.md
Labels: A0-pleasereview 🤓, M3-docs 📑

#10178 Extract CallContract and RegistryInfo traits into their own crate
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/call-contract/Cargo.toml
  ethcore/call-contract/src/call_contract.rs
  ethcore/call-contract/src/lib.rs
  ethcore/src/client/client.rs
  ethcore/src/client/mod.rs
  ethcore/src/client/test_client.rs
  ethcore/src/client/traits.rs
  ethcore/src/lib.rs
  ethcore/src/miner/mod.rs
  ethcore/src/miner/pool_client.rs
  miner/Cargo.toml
  miner/res/contracts/service_transaction.json
  miner/src/lib.rs
  miner/src/service_transaction_checker.rs
Labels: A7-looksgoodcantmerge 🙄, M4-core ⛓

#10205 Remove CallContract and RegistryInfo re-exports from `ethcore/client`
  Cargo.lock
  Cargo.toml
  ethcore/private-tx/Cargo.toml
  ethcore/private-tx/src/lib.rs
  ethcore/src/client/mod.rs
  ethcore/src/engines/validator_set/contract.rs
  ethcore/src/lib.rs
  ethcore/src/machine.rs
  ethcore/src/miner/miner.rs
  ethcore/src/miner/mod.rs
  ethcore/src/miner/pool_client.rs
  ethcore/src/tx_filter.rs
  ethcore/src/verification/canon_verifier.rs
  ethcore/src/verification/mod.rs
  ethcore/src/verification/noop_verifier.rs
  ethcore/src/verification/verification.rs
  ethcore/src/verification/verifier.rs
  parity/lib.rs
  parity/run.rs
  secret-store/Cargo.toml
  secret-store/src/acl_storage.rs
  secret-store/src/key_server_set.rs
  secret-store/src/lib.rs
  secret-store/src/listener/service_contract.rs
  secret-store/src/trusted_client.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#10208 perform stripping during build
  scripts/gitlab/build-unix.sh
Labels: A0-pleasereview 🤓, M0-build 🏗, M1-ci 🙉

#10214 Add EIP-1283 disable transition
  ethcore/src/spec/spec.rs
  json/src/spec/params.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10223 Enable St-Peters-Fork ("Constantinople Fix")
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/poasokol.json
  ethcore/res/ethereum/ropsten.json
  util/version/Cargo.toml
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#10051 import rpc transactions sequentially
  rpc/src/v1/helpers/dispatch.rs
  rpc/src/v1/impls/personal.rs
Labels: A8-looksgood 🦄, M6-rpcapi 📣

#10209 fix(ManageNetwork): replace Range with RangeInclusive
  ethcore/sync/src/api.rs
  parity/informant.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/tests/mocked/manage_network.rs
  util/network-devp2p/src/service.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#10224 Stable Backports 2.2.8
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/poacore.json
  ethcore/res/ethereum/poasokol.json
  ethcore/res/ethereum/ropsten.json
  ethcore/src/spec/spec.rs
  json/src/spec/params.rs
  scripts/gitlab/build-unix.sh
  util/version/Cargo.toml
Labels: A0-pleasereview 🤓, A8-backport 🕸, M2-config 📂

#10225 Beta Backports 2.3.1
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/poacore.json
  ethcore/res/ethereum/poasokol.json
  ethcore/res/ethereum/ropsten.json
  ethcore/src/spec/spec.rs
  json/src/spec/params.rs
  scripts/gitlab/build-unix.sh
  util/network-devp2p/src/ip_utils.rs
  util/version/Cargo.toml
Labels: A0-pleasereview 🤓, A8-backport 🕸, M2-config 📂

#10229 fixed: use types::transaction::SignedTransaction; instead of transaction::SignedTransaction;
  rpc/src/v1/impls/personal.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#10233 Fix typo: CHANGELOG-2.1 -> CHANGELOG-2.2
  CHANGELOG.md
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M3-docs 📑

#10249 Update CHANGELOG.md
  CHANGELOG.md
Labels: A2-insubstantial 👶, M3-docs 📑

#10232 Take in account zero gas price certification when doing transact_contract
  ethcore/src/client/client.rs
  miner/src/service_transaction_checker.rs
  rpc/src/v1/impls/personal.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10254 Fix v2.2.7 release date in the changelog.
  docs/CHANGELOG-2.2.md
Labels: A2-insubstantial 👶, M3-docs 📑

#10258 Stable: Macos heapsize force jemalloc (#10234)
  Cargo.lock
  Cargo.toml
Labels: A8-backport 🕸, M5-dependencies 🖇

#10259 Beta: Macos heapsize force jemalloc (#10234)
  Cargo.lock
  Cargo.toml
Labels: A8-backport 🕸, M5-dependencies 🖇

#10263 Fix join-set test to be deterministic.
  parity/helpers.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓
