Repository openethereum/openethereum, pull requests merged in 2019-05, with the labels that each got.

#10616 [ethcore] remove error_chain
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/light/src/client/header_chain.rs
  ethcore/src/client/client.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/clique/mod.rs
  ethcore/src/engines/clique/tests.rs
  ethcore/src/error.rs
  ethcore/src/ethereum/ethash.rs
  ethcore/src/lib.rs
  ethcore/src/miner/miner.rs
  ethcore/src/snapshot/error.rs
  ethcore/src/snapshot/service.rs
  ethcore/src/snapshot/tests/proof_of_work.rs
  ethcore/src/snapshot/tests/state.rs
  ethcore/src/verification/queue/kind.rs
  ethcore/src/verification/queue/mod.rs
  ethcore/src/verification/verification.rs
  ethcore/sync/src/block_sync.rs
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/light_sync/mod.rs
  parity/blockchain.rs
  rpc/src/v1/helpers/errors.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10628 Update kovan.json to switch Kovan validator set to POA Consensus Contracts
  ethcore/res/ethereum/kovan.json
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#10632 Fix rinkeby petersburg fork
  ethcore/res/ethereum/rinkeby.json
Labels: A2-insubstantial 👶, A8-looksgood 🦄, B1-patch-beta 🕷🕷, M2-config 📂

#10642 stable 2.4.6
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/evm/Cargo.toml
  ethcore/evm/benches/basic.rs
  ethcore/evm/src/interpreter/mod.rs
  ethcore/evm/src/lib.rs
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/poacore.json
  util/version/Cargo.toml
  whisper/src/message.rs
Labels: A0-pleasereview 🤓, A8-backport 🕸, M2-config 📂, M4-core ⛓

#10643 beta 2.5.1
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/evm/Cargo.toml
  ethcore/evm/benches/basic.rs
  ethcore/evm/src/interpreter/mod.rs
  ethcore/evm/src/lib.rs
  ethcore/res/ethereum/goerli.json
  ethcore/res/ethereum/kotti.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/poacore.json
  ethcore/res/ethereum/rinkeby.json
  ethcore/src/engines/clique/mod.rs
  parity/rpc_apis.rs
  parity/run.rs
  rpc/src/v1/helpers/errors.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/tests/eth.rs
  util/version/Cargo.toml
  whisper/src/message.rs
Labels: A0-pleasereview 🤓, A8-backport 🕸, M2-config 📂, M4-core ⛓

#10609 Adds parity_getRawBlockByNumber, parity_submitRawBlock
  rpc/src/v1/helpers/errors.rs
  rpc/src/v1/impls/light/parity.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/traits/parity.rs
Labels: A8-looksgood 🦄, M4-core ⛓, M6-rpcapi 📣

#10647 [whisper] Move needed aes_gcm crypto in-crate
  Cargo.lock
  whisper/Cargo.toml
  whisper/src/aes_gcm/mod.rs
  whisper/src/lib.rs
  whisper/src/rpc/crypto.rs
Labels: A8-looksgood 🦄, M4-core ⛓, M5-dependencies 🖇

#10649 fix(compilation warnings)
  ethcore/src/client/client.rs
  ethcore/src/engines/clique/mod.rs
  ethcore/src/ethereum/ethash.rs
  parity/informant.rs
  rpc/src/tests/http_client.rs
  rpc/src/v1/helpers/dispatch/prospective_signer.rs
  util/network-devp2p/src/host.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#10056 Trivial journal for private transactions
  Cargo.lock
  ethcore/private-tx/Cargo.toml
  ethcore/private-tx/src/error.rs
  ethcore/private-tx/src/lib.rs
  ethcore/private-tx/src/log.rs
  ethcore/private-tx/src/private_transactions.rs
  ethcore/private-tx/tests/private_contract.rs
  ethcore/sync/src/tests/private.rs
  parity/configuration.rs
  rpc/src/v1/impls/private.rs
  rpc/src/v1/traits/private.rs
  rpc/src/v1/types/mod.rs
  rpc/src/v1/types/private_log.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10654 docs: Add PR template
  PULL_REQUEST_TEMPLATE.md
Labels: A2-insubstantial 👶

#10659 stable ci: publish docs debug (#10638)
  .gitlab-ci.yml
  scripts/gitlab/publish-docs.sh
Labels: A0-pleasereview 🤓, A8-backport 🕸, M1-ci 🙉

#10660 beta ci: publish docs debug (#10638)
  .gitlab-ci.yml
  scripts/gitlab/publish-docs.sh
Labels: A8-backport 🕸, M1-ci 🙉

#10662 stable ci: backport missing diff from master
  .gitlab-ci.yml
  scripts/gitlab/build-linux.sh
  scripts/gitlab/build-windows.sh
  scripts/gitlab/test-linux.sh
  scripts/gitlab/validate-chainspecs.sh
Labels: A8-backport 🕸, M1-ci 🙉

#10661 beta ci: backport missing diff from master
  .gitlab-ci.yml
  scripts/gitlab/build-linux.sh
  scripts/gitlab/build-windows.sh
  scripts/gitlab/test-linux.sh
  scripts/gitlab/validate-chainspecs.sh
Labels: A8-backport 🕸, M1-ci 🙉

#10663 fix: Move PR template into .github/ folder
  .github/PULL_REQUEST_TEMPLATE.md
Labels: A2-insubstantial 👶, M3-docs 📑

#10653 docs: Add ProgPoW Rust docs to ethash module
  ethash/src/progpow.rs
Labels: A0-pleasereview 🤓, M3-docs 📑

#10676 [CI] allow cargo audit to fail
  .gitlab-ci.yml
  Cargo.lock
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#10678 Remove support for hardware wallets
  Cargo.lock
  README.md
  accounts/Cargo.toml
  accounts/fake-hardware-wallet/Cargo.toml
  accounts/fake-hardware-wallet/src/lib.rs
  accounts/hw/Cargo.toml
  accounts/hw/src/ledger.rs
  accounts/hw/src/lib.rs
  accounts/hw/src/trezor.rs
  accounts/src/error.rs
  accounts/src/lib.rs
  ethcore/src/engines/signer.rs
  parity/account_utils.rs
  parity/cli/mod.rs
  parity/configuration.rs
  parity/params.rs
  rpc/src/v1/helpers/dispatch/signing.rs
  rpc/src/v1/impls/parity_accounts.rs
  rpc/src/v1/traits/parity_accounts.rs
  rpc/src/v1/types/account_info.rs
  rpc/src/v1/types/mod.rs
  scripts/docker/hub/Dockerfile
  scripts/docker/ubuntu-aarch64/Dockerfile
  scripts/docker/ubuntu-arm/Dockerfile
  scripts/snap/snapcraft.template.yaml
Labels: A8-looksgood 🦄, B7-releasenotes 📜

#10669 Reset blockchain properly
  ethcore/blockchain/src/blockchain.rs
  ethcore/src/client/client.rs
  ethcore/src/tests/client.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓, M4-io 💾

#10679 Remove annoying compiler warnings
  Cargo.lock
  accounts/Cargo.toml
  accounts/ethstore/src/accounts_dir/disk.rs
  accounts/src/lib.rs
  ethcore/node-filter/src/lib.rs
  ethcore/src/spec/spec.rs
  ethcore/sync/src/chain/sync_packet.rs
  ethcore/types/src/views/view_rlp.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶

#10658 docs: evmbin - Update Rust docs
  evmbin/benches/mod.rs
  evmbin/src/main.rs
Labels: A0-pleasereview 🤓, M3-docs 📑

#10682 Don't panic if extra_data is longer than VANITY_LENGTH
  ethcore/src/engines/clique/mod.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶

#10689 add_sync_notifier in EthPubSubClient holds on to a Client for too long
  rpc/src/v1/impls/eth_pubsub.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10683 Fix compiler warning (that will become an error)
  ethcore/src/client/client.rs
  ethcore/src/engines/clique/mod.rs
  ethcore/src/engines/clique/step_service.rs
Labels: A0-pleasereview 🤓

#10529 Add SealingState; don't prepare block when not ready.
  ethcore/src/client/client.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/basic_authority.rs
  ethcore/src/engines/clique/mod.rs
  ethcore/src/engines/instant_seal.rs
  ethcore/src/engines/mod.rs
  ethcore/src/miner/miner.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10673 new image
  .gitlab-ci.yml
Labels: A8-backport 🕸, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#10650 Upgrade to parity-crypto 0.4
  Cargo.lock
  accounts/ethkey/Cargo.toml
  accounts/ethstore/Cargo.toml
  accounts/ethstore/src/account/crypto.rs
  accounts/ethstore/src/account/kdf.rs
  accounts/ethstore/src/account/safe_account.rs
  accounts/ethstore/src/accounts_dir/disk.rs
  accounts/ethstore/src/accounts_dir/mod.rs
  accounts/ethstore/src/accounts_dir/vault.rs
  accounts/ethstore/src/ethstore.rs
  accounts/ethstore/src/json/kdf.rs
  accounts/ethstore/src/json/vault_file.rs
  accounts/ethstore/src/json/vault_key_file.rs
  accounts/ethstore/src/presale.rs
  ethcore/Cargo.toml
  ethcore/private-tx/Cargo.toml
  parity/account.rs
  parity/configuration.rs
  parity/params.rs
  parity/presale.rs
  rpc/Cargo.toml
  secret-store/Cargo.toml
  util/network-devp2p/Cargo.toml
  util/network/Cargo.toml
Labels: A8-looksgood 🦄, M4-core ⛓, M5-dependencies 🖇

#10644 Update publishing
  .gitlab-ci.yml
  scripts/docker/hub/Dockerfile
  scripts/docker/hub/publish-docker.sh
  scripts/gitlab/publish-docker.sh
  scripts/gitlab/publish-docs.sh
  scripts/gitlab/publish-onchain.sh
  scripts/gitlab/publish-snap.sh
Labels: A0-pleasereview 🤓, A8-backport 🕸, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉
