Repository openethereum/openethereum, pull requests merged in 2019-10, with the labels that each got.

#11105 use images from our registry
  .gitlab-ci.yml
Labels: M1-ci 🙉

#11111 Update to latest jsonrpc
  Cargo.lock
  Cargo.toml
  cli-signer/rpc-client/Cargo.toml
  ethcore/private-tx/Cargo.toml
  ipfs/Cargo.toml
  miner/Cargo.toml
  miner/stratum/Cargo.toml
  rpc/Cargo.toml
  secret-store/Cargo.toml
  secret-store/src/lib.rs
  secret-store/src/listener/http_listener.rs
  util/fetch/Cargo.toml
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M5-dependencies 🖇

#11108 [spec] fix rinkeby spec
  ethcore/res/ethereum/rinkeby.json
Labels: A2-insubstantial 👶, A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#11112 Fix deprecated trait objects without an explicit `dyn`
  accounts/ethstore/cli/src/main.rs
  accounts/ethstore/src/ethstore.rs
  ethcore/wasm/run/src/runner.rs
  miner/src/pool/replace.rs
  parity-clib/src/lib.rs
  secret-store/src/key_server.rs
  secret-store/src/key_server_cluster/admin_sessions/key_version_negotiation_session.rs
  secret-store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs
  secret-store/src/key_server_cluster/admin_sessions/sessions_queue.rs
  secret-store/src/key_server_cluster/admin_sessions/share_add_session.rs
  secret-store/src/key_server_cluster/admin_sessions/share_change_session.rs
  secret-store/src/key_server_cluster/client_sessions/decryption_session.rs
  secret-store/src/key_server_cluster/client_sessions/encryption_session.rs
  secret-store/src/key_server_cluster/client_sessions/generation_session.rs
  secret-store/src/key_server_cluster/client_sessions/signing_session_ecdsa.rs
  secret-store/src/key_server_cluster/client_sessions/signing_session_schnorr.rs
  secret-store/src/key_server_cluster/cluster.rs
  secret-store/src/key_server_cluster/cluster_connections.rs
  secret-store/src/key_server_cluster/cluster_connections_net.rs
  secret-store/src/key_server_cluster/cluster_message_processor.rs
  secret-store/src/key_server_cluster/cluster_sessions.rs
  secret-store/src/key_server_cluster/cluster_sessions_creator.rs
  secret-store/src/key_server_cluster/connection_trigger.rs
  secret-store/src/key_server_cluster/connection_trigger_with_migration.rs
  secret-store/src/key_server_cluster/io/deadline.rs
  secret-store/src/key_server_cluster/io/handshake.rs
  secret-store/src/key_server_cluster/jobs/key_access_job.rs
  secret-store/src/key_server_cluster/jobs/unknown_sessions_job.rs
  secret-store/src/key_server_cluster/net/accept_connection.rs
  secret-store/src/key_server_cluster/net/connect.rs
  secret-store/src/key_server_set.rs
  secret-store/src/key_storage.rs
  secret-store/src/lib.rs
  secret-store/src/listener/http_listener.rs
  secret-store/src/listener/mod.rs
  secret-store/src/listener/service_contract.rs
  secret-store/src/listener/service_contract_aggregate.rs
  secret-store/src/listener/service_contract_listener.rs
  secret-store/src/traits.rs
  secret-store/src/trusted_client.rs
  util/fetch/src/client.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11114 [stable]: backports
  .gitlab-ci.yml
  ethcore/res/ethereum/rinkeby.json
Labels: A8-backport 🕸

#11115 [beta]: backports
  .gitlab-ci.yml
  ethcore/res/ethereum/rinkeby.json
Labels: A0-pleasereview 🤓, A8-backport 🕸

#11056 SIMD Implementation for EIP-152
  Cargo.lock
  util/EIP-152/Cargo.toml
  util/EIP-152/LICENSE
  util/EIP-152/benches/bench.rs
  util/EIP-152/src/avx2.rs
  util/EIP-152/src/lib.rs
  util/EIP-152/src/portable.rs
Labels: A8-looksgood 🦄, F7-optimisation 💊, M4-core ⛓

#10971 Switching sccache from local to Redis
  .gitlab-ci.yml
  scripts/gitlab/build-linux.sh
  scripts/gitlab/test-cpp.sh
  scripts/gitlab/test-linux.sh
  scripts/gitlab/validate-chainspecs.sh
Labels: A0-pleasereview 🤓, A3-inprogress ⏳, M1-ci 🙉

#11102 Refactor return type of `BlockChainClient::code` #7098
  ethcore/client-traits/src/lib.rs
  ethcore/src/client/client.rs
  ethcore/src/test_helpers/test_client.rs
  parity/blockchain.rs
  rpc/src/v1/impls/eth.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11110 Deduplicate registrar contract & calling logic
  Cargo.lock
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/call-contract/src/call_contract.rs
  ethcore/client-traits/Cargo.toml
  ethcore/client-traits/src/lib.rs
  ethcore/private-tx/Cargo.toml
  ethcore/private-tx/src/key_server_keys.rs
  ethcore/private-tx/src/lib.rs
  ethcore/res/contracts/registrar.json
  ethcore/src/client/client.rs
  ethcore/src/lib.rs
  ethcore/src/miner/mod.rs
  ethcore/src/test_helpers/test_client.rs
  ethcore/src/tests/client.rs
  miner/Cargo.toml
  miner/src/lib.rs
  miner/src/service_transaction_checker.rs
  parity/lib.rs
  parity/run.rs
  secret-store/Cargo.toml
  secret-store/src/acl_storage.rs
  secret-store/src/key_server_set.rs
  secret-store/src/lib.rs
  secret-store/src/listener/service_contract.rs
  secret-store/src/trusted_client.rs
  updater/hash-fetch/Cargo.toml
  updater/hash-fetch/src/client.rs
  updater/hash-fetch/src/lib.rs
  updater/hash-fetch/src/urlhint.rs
  updater/src/updater.rs
  util/registrar/Cargo.toml
  util/registrar/src/lib.rs
  util/registrar/src/registrar.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#11121 Move StateResult to `common-types`
  ethcore/Cargo.toml
  ethcore/client-traits/src/lib.rs
  ethcore/src/client/client.rs
  ethcore/src/test_helpers/test_client.rs
  ethcore/types/src/client_types.rs
  parity/blockchain.rs
  rpc/src/v1/impls/eth.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11106 EIP-712: bump version in prep for publishing
  Cargo.lock
  util/EIP-712/Cargo.toml
Labels: A2-insubstantial 👶, A7-looksgoodtestsfail 🤖

#11124 Refactor parity_listStorageKeys with count parameter optional
  ethcore/client-traits/src/lib.rs
  ethcore/src/client/client.rs
  ethcore/src/test_helpers/test_client.rs
  parity/blockchain.rs
  rpc/src/v1/impls/light/parity.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/traits/parity.rs
Labels: A8-looksgood 🦄, M6-rpcapi 📣

#11128 Fix some random typos, formatting/whitespace
  ethcore/client-traits/src/lib.rs
  ethcore/machine/src/executive.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#11126 ServiceTransactionChecker::refresh_cache: allow registrar unavailable
  miner/src/service_transaction_checker.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11138 [json]: add docs to `hardfork specification`
  json/src/spec/spec.rs
Labels: A2-insubstantial 👶, M3-docs 📑

#11145 Fix sccache statistics
  .gitlab-ci.yml
  scripts/gitlab/build-linux.sh
  scripts/gitlab/test-cpp.sh
  scripts/gitlab/test-linux.sh
  scripts/gitlab/validate-chainspecs.sh
Labels: A0-pleasereview 🤓, M1-ci 🙉

#11140 Use TryFrom instead of From+panic for Builtin
  Cargo.lock
  ethcore/builtin/Cargo.toml
  ethcore/builtin/src/lib.rs
  ethcore/machine/src/test_helpers.rs
  ethcore/spec/src/spec.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10920 RPC method for clearing the engine signer
  ethcore/engine/src/engine.rs
  ethcore/engines/authority-round/src/lib.rs
  ethcore/engines/basic-authority/src/lib.rs
  ethcore/engines/clique/src/lib.rs
  ethcore/src/miner/miner.rs
  ethcore/src/miner/mod.rs
  rpc/src/v1/impls/light/parity_set.rs
  rpc/src/v1/impls/parity_set.rs
  rpc/src/v1/tests/helpers/miner_service.rs
  rpc/src/v1/traits/parity_set.rs
Labels: A8-looksgood 🦄, M6-rpcapi 📣

#11155 Secret store: fix Instant::now() related race in net_keep_alive
  secret-store/src/key_server_cluster/cluster_connections_net.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#11158 [beta]: backport #11155 (Secret store: fix Instant::now() related race in net_keep_alive)
  secret-store/src/key_server_cluster/cluster_connections_net.rs
Labels: A8-backport 🕸

#11163 [keccak-hasher]: rust 2018
  util/keccak-hasher/Cargo.toml
  util/keccak-hasher/src/lib.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, M4-core ⛓

#11161 Cleanup stratum a bit
  ethcore/src/miner/stratum.rs
  miner/stratum/src/lib.rs
  miner/stratum/src/traits.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷

#11127 Change how RPCs eth_call and eth_estimateGas handle "Pending"
  ethcore/client-traits/src/lib.rs
  ethcore/src/client/client.rs
  ethcore/src/miner/mod.rs
  ethcore/src/test_helpers/test_client.rs
  ethcore/src/tests/client.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/tests/helpers/miner_service.rs
  rpc/src/v1/tests/mocked/eth.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, B7-releasenotes 📜, M4-core ⛓

#11172 ethcore client: fix a double Read Lock bug in fn Client::logs()
  ethcore/src/client/client.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#11175 util Host: fix a double Read Lock bug in fn Host::session_readable()
  util/network-devp2p/src/host.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#11123 [ethash] chainspec validate `ecip1017EraRounds` non-zero
  ethcore/engines/ethash/src/lib.rs
  json/src/spec/ethash.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11170 TxPermissions ver 3: gas price & data
  ethcore/machine/res/tx_acl_gas_price.json
  ethcore/machine/src/tx_filter.rs
  ethcore/res/tx_permission_tests/contract_ver_3.sol
  ethcore/res/tx_permission_tests/contract_ver_3_genesis.json
Labels: A8-looksgood 🦄, B7-releasenotes 📜, M4-core ⛓

#11180 [ethcore/builtin]: do not panic in blake2pricer on short input
  ethcore/builtin/src/lib.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#11022 [dependencies] bump rand 0.7
  Cargo.lock
  accounts/ethkey/Cargo.toml
  accounts/ethkey/src/random.rs
  accounts/ethstore/Cargo.toml
  accounts/ethstore/src/random.rs
  accounts/ethstore/tests/util/transient_dir.rs
  ethcore/Cargo.toml
  ethcore/blockchain/Cargo.toml
  ethcore/engines/authority-round/Cargo.toml
  ethcore/engines/clique/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/snapshot/Cargo.toml
  ethcore/snapshot/snapshot-tests/Cargo.toml
  ethcore/snapshot/src/consensus/work.rs
  ethcore/src/client/client.rs
  ethcore/sync/Cargo.toml
  ethcore/sync/src/light_sync/mod.rs
  rpc/Cargo.toml
  rpc/src/authcodes.rs
  rpc/src/v1/helpers/secretstore.rs
  rpc/src/v1/helpers/subscribers.rs
  rpc/src/v1/helpers/subscription_manager.rs
  rpc/src/v1/tests/mocked/eth_pubsub.rs
  rpc/src/v1/tests/mocked/pubsub.rs
  updater/Cargo.toml
  updater/hash-fetch/Cargo.toml
  updater/hash-fetch/src/client.rs
  util/network-devp2p/Cargo.toml
  util/network-devp2p/src/node_table.rs
Labels: A8-looksgood 🦄, M5-dependencies 🖇

#11179 [receipt]: add `sender` & `receiver` to `RichReceipts`
  ethcore/src/miner/miner.rs
  ethcore/types/src/receipt.rs
  rpc/src/v1/tests/mocked/eth.rs
  rpc/src/v1/tests/mocked/parity.rs
  rpc/src/v1/types/receipt.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M6-rpcapi 📣

#11183 [dependencies]: jsonrpc `14.0.1`
  Cargo.lock
  Cargo.toml
  cli-signer/rpc-client/Cargo.toml
  ipfs/Cargo.toml
  miner/stratum/Cargo.toml
  rpc/Cargo.toml
  rpc/src/v1/traits/eth.rs
  rpc/src/v1/traits/eth_pubsub.rs
  rpc/src/v1/traits/eth_signing.rs
  rpc/src/v1/traits/parity.rs
  rpc/src/v1/traits/parity_accounts.rs
  rpc/src/v1/traits/parity_set.rs
  rpc/src/v1/traits/parity_signing.rs
  rpc/src/v1/traits/personal.rs
  rpc/src/v1/traits/private.rs
  rpc/src/v1/traits/pubsub.rs
  rpc/src/v1/traits/secretstore.rs
  rpc/src/v1/traits/signer.rs
  rpc/src/v1/traits/traces.rs
  rpc/src/v1/traits/transactions_pool.rs
  rpc/src/v1/traits/web3.rs
  secret-store/Cargo.toml
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M5-dependencies 🖇, M6-rpcapi 📣

#11191 Remove unused macro_use.
  secret-store/src/lib.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#11188 Made ecrecover implementation trait public
  ethcore/builtin/src/lib.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11143 [stable]: backport #10691 and #10683
  ethcore/src/client/client.rs
  ethcore/src/engines/clique/mod.rs
  ethcore/src/engines/clique/step_service.rs
  ethcore/src/engines/mod.rs
Labels: A8-backport 🕸

#11159 [stable]: backport #11155 (Secret store: fix Instant::now() related race in net_keep_alive) #11158
  secret-store/src/key_server_cluster/cluster_connections_net.rs
Labels: A8-backport 🕸

#11192 Type annotation for next_key() matching of json filter options
  README.md
  ethcore/src/miner/filter_options.rs
  rpc/src/v1/tests/mocked/parity.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M6-rpcapi 📣

#11204 [export hardcoded sync]: use debug for `H256`
  ethcore/spec/src/spec.rs
  parity/export_hardcoded_sync.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#11206 Upgrade jsonrpc to latest
  Cargo.lock
  Cargo.toml
  cli-signer/rpc-client/Cargo.toml
  ipfs/Cargo.toml
  miner/stratum/Cargo.toml
  rpc/Cargo.toml
  secret-store/Cargo.toml
Labels: A8-looksgood 🦄, M5-dependencies 🖇

#10902 Step duration map configuration parameter ported from the POA Network fork
  ethcore/engines/authority-round/src/lib.rs
  json/src/spec/authority_round.rs
  json/src/spec/mod.rs
  json/src/spec/step_duration.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#11211 [informant]: `MillisecondDuration` -> `as_millis()`
  parity/blockchain.rs
  parity/informant.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11197 Use a lock instead of atomics for snapshot Progress
  Cargo.lock
  ethcore/snapshot/snapshot-tests/src/account.rs
  ethcore/snapshot/snapshot-tests/src/helpers.rs
  ethcore/snapshot/snapshot-tests/src/proof_of_work.rs
  ethcore/snapshot/snapshot-tests/src/service.rs
  ethcore/snapshot/snapshot-tests/src/state.rs
  ethcore/snapshot/src/account.rs
  ethcore/snapshot/src/consensus/authority.rs
  ethcore/snapshot/src/consensus/work.rs
  ethcore/snapshot/src/lib.rs
  ethcore/snapshot/src/service.rs
  ethcore/snapshot/src/traits.rs
  ethcore/src/client/client.rs
  ethcore/types/Cargo.toml
  ethcore/types/src/lib.rs
  ethcore/types/src/snapshot.rs
  parity/informant.rs
  parity/snapshot_cmd.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#11209 Use provided usd-per-eth value if an endpoint is specified
  ethcore/src/miner/miner.rs
  miner/price-info/src/lib.rs
  miner/src/gas_price_calibrator.rs
  parity/configuration.rs
  parity/helpers.rs
  parity/params.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂, M4-core ⛓

#11203 Update MIX bootnodes.
  ethcore/res/ethereum/mix.json
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#11226 Fix docker centos build
  scripts/docker/README.md
  scripts/docker/centos/build.sh
Labels: A8-looksgood 🦄, M0-build 🏗, M1-ci 🙉, hacktoberfest

#11219 Snapshot restoration overhaul
  Cargo.lock
  ethcore/snapshot/src/lib.rs
  ethcore/snapshot/src/service.rs
  ethcore/snapshot/src/traits.rs
  ethcore/sync/Cargo.toml
  ethcore/sync/src/api.rs
  ethcore/sync/src/block_sync.rs
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/requester.rs
  ethcore/sync/src/chain/supplier.rs
  ethcore/sync/src/snapshot_sync.rs
  ethcore/sync/src/sync_io.rs
  ethcore/sync/src/tests/helpers.rs
  ethcore/types/src/snapshot.rs
  util/network-devp2p/src/host.rs
  util/network/src/lib.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#11225 Insert explicit warning into the panic hook
  parity/main.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#11039 [builtin]: support `multiple prices and activations` in chain spec
  Cargo.lock
  ethcore/builtin/Cargo.toml
  ethcore/builtin/src/lib.rs
  ethcore/engines/basic-authority/res/basic_authority.json
  ethcore/engines/basic-authority/src/lib.rs
  ethcore/machine/Cargo.toml
  ethcore/machine/benches/builtin_contract.rs
  ethcore/machine/src/test_helpers.rs
  ethcore/res/authority_round.json
  ethcore/res/authority_round_block_reward_contract.json
  ethcore/res/constructor.json
  ethcore/res/ethereum/builtin_multi_bench.json
  ethcore/res/ethereum/builtin_one_activation_bench.json
  ethcore/res/ethereum/byzantium_test.json
  ethcore/res/ethereum/callisto.json
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/constantinople_test.json
  ethcore/res/ethereum/eip210_test.json
  ethcore/res/ethereum/ellaism.json
  ethcore/res/ethereum/ewc.json
  ethcore/res/ethereum/expanse.json
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/goerli.json
  ethcore/res/ethereum/istanbul_test.json
  ethcore/res/ethereum/kotti.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/kovan_wasm_test.json
  ethcore/res/ethereum/mcip3_test.json
  ethcore/res/ethereum/mix.json
  ethcore/res/ethereum/morden.json
  ethcore/res/ethereum/musicoin.json
  ethcore/res/ethereum/poacore.json
  ethcore/res/ethereum/poasokol.json
  ethcore/res/ethereum/rinkeby.json
  ethcore/res/ethereum/ropsten.json
  ethcore/res/ethereum/st_peters_test.json
  ethcore/res/ethereum/transition_test.json
  ethcore/res/ethereum/volta.json
  ethcore/res/ethereum/xdai.json
  ethcore/res/instant_seal.json
  ethcore/res/null.json
  ethcore/res/spec_backward_compability.json
  ethcore/spec/src/spec.rs
  json/src/spec/account.rs
  json/src/spec/builtin.rs
  json/src/spec/spec.rs
  json/src/spec/state.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, B7-releasenotes 📜, M2-config 📂, M4-core ⛓
