Repository openethereum/openethereum, pull requests merged in 2019-11, with the labels that each got.

#11228 [chain specs]: activate `Istanbul` on mainnet
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/goerli.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/rinkeby.json
  ethcore/res/ethereum/ropsten.json
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, B7-releasenotes 📜, M2-config 📂

#11200 ethcore/res: add mordor testnet configuration
  ethcore/res/ethereum/kotti.json
  ethcore/res/ethereum/morden.json
  ethcore/res/ethereum/mordor.json
  ethcore/spec/src/chain.rs
  parity/account_utils.rs
  parity/cli/mod.rs
  parity/configuration.rs
  parity/params.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, B7-releasenotes 📜, M2-config 📂

#11236 Update list of bootnodes for xDai chain
  ethcore/res/ethereum/xdai.json
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#11234 [stable] builtin, istanbul and mordor testnet backports
  Cargo.lock
  accounts/ethkey/Cargo.toml
  ethcore/Cargo.toml
  ethcore/builtin/Cargo.toml
  ethcore/builtin/src/lib.rs
  ethcore/res/authority_round.json
  ethcore/res/authority_round_block_reward_contract.json
  ethcore/res/basic_authority.json
  ethcore/res/constructor.json
  ethcore/res/ethereum/builtin_multi_bench.json
  ethcore/res/ethereum/builtin_one_activation_bench.json
  ethcore/res/ethereum/byzantium_test.json
  ethcore/res/ethereum/callisto.json
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/constantinople_test.json
  ethcore/res/ethereum/eip210_test.json
  ethcore/res/ethereum/ellaism.json
  ethcore/res/ethereum/ewc.json
  ethcore/res/ethereum/expanse.json
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/goerli.json
  ethcore/res/ethereum/istanbul_test.json
  ethcore/res/ethereum/kotti.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/kovan_wasm_test.json
  ethcore/res/ethereum/mcip3_test.json
  ethcore/res/ethereum/mix.json
  ethcore/res/ethereum/morden.json
  ethcore/res/ethereum/mordor.json
  ethcore/res/ethereum/musicoin.json
  ethcore/res/ethereum/poacore.json
  ethcore/res/ethereum/poasokol.json
  ethcore/res/ethereum/rinkeby.json
  ethcore/res/ethereum/ropsten.json
  ethcore/res/ethereum/st_peters_test.json
  ethcore/res/ethereum/transition_test.json
  ethcore/res/ethereum/volta.json
  ethcore/res/instant_seal.json
  ethcore/res/null.json
  ethcore/res/spec_backward_compability.json
  ethcore/src/ethereum/mod.rs
  ethcore/src/executive.rs
  ethcore/src/lib.rs
  ethcore/src/spec/spec.rs
  json/Cargo.toml
  json/src/lib.rs
  json/src/spec/account.rs
  json/src/spec/builtin.rs
  json/src/spec/spec.rs
  json/src/spec/state.rs
  parity/account_utils.rs
  parity/cli/mod.rs
  parity/configuration.rs
  parity/params.rs
Labels: A8-backport 🕸

#11201 Update light client headers: ropsten #6631425 foundation #8798209
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/ropsten.json
Labels: A8-looksgood 🦄, B1-patch-beta 🕷🕷, M2-config 📂

#11212 [stable]: backport #10984
  ethcore/src/client/client.rs
  ethcore/src/client/traits.rs
  ethcore/src/tests/client.rs
  parity/blockchain.rs
Labels: A8-backport 🕸

#11186 Make InstantSeal Instant again
  Cargo.lock
  ethcore/client-traits/src/lib.rs
  ethcore/engine/src/engine.rs
  ethcore/engines/authority-round/src/lib.rs
  ethcore/engines/clique/src/lib.rs
  ethcore/engines/instant-seal/Cargo.toml
  ethcore/engines/instant-seal/src/lib.rs
  ethcore/engines/validator-set/src/multi.rs
  ethcore/engines/validator-set/src/safe_contract.rs
  ethcore/light/src/client/mod.rs
  ethcore/src/client/client.rs
  ethcore/src/miner/miner.rs
  ethcore/src/miner/mod.rs
  ethcore/src/test_helpers/test_client.rs
  miner/src/pool/listener.rs
  rpc/src/v1/tests/helpers/miner_service.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂, M4-core ⛓

#11247 Filter out some bad ropsten warp snapshots
  ethcore/res/ethereum/ropsten.json
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#11249 simplify verification
  ethcore/src/client/client.rs
  ethcore/verification/src/canon_verifier.rs
  ethcore/verification/src/lib.rs
  ethcore/verification/src/noop_verifier.rs
  ethcore/verification/src/queue/kind.rs
  ethcore/verification/src/verification.rs
  ethcore/verification/src/verifier.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11251 fix windows libusb builds
  Cargo.lock
Labels: A8-backport 🕸

#11255 Stable sccache backport
  .gitlab-ci.yml
  scripts/gitlab/build-linux.sh
Labels: A0-pleasereview 🤓, A8-backport 🕸, M1-ci 🙉

#11254 Beta sccache backport
  .gitlab-ci.yml
  scripts/gitlab/build-linux.sh
Labels: A0-pleasereview 🤓, A8-backport 🕸, M1-ci 🙉

#11258 Fix misc compile warnings
  accounts/ethstore/src/json/id.rs
  ethcore/builtin/src/lib.rs
  ethcore/machine/src/tx_filter.rs
  ethcore/src/client/client.rs
  parity/rpc_apis.rs
  util/EIP-712/src/encode.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#11185 Add a benchmark for snapshot::account::to_fat_rlps()
  Cargo.lock
  ethcore/snapshot/Cargo.toml
  ethcore/snapshot/benches/state-chunk-5279-0x2032dfb6ad93f1928dac70627a8767d2232568a1a7bf1c91ea416988000f8275.rlp
  ethcore/snapshot/benches/state-chunk-5905-0x104ff12a3fda9e0cb1aeef41fe7092982134eb116292c0eec725c32a815ef0ea.rlp
  ethcore/snapshot/benches/state-chunk-6341-0x3042ea62f982fd0cea02847ff0fd103a0beef3bb19389f5e77113c3ea355f803.rlp
  ethcore/snapshot/benches/state-chunk-6720-0x2075481dccdc2c4419112bfea2d09219a7223614656722a1a05a930baf2b0dd7.rlp
  ethcore/snapshot/benches/state-chunk-6933-0x104102770901b53230e78cfc8f6edce282eb21bfa00aa1c3543c79cb3402cf2d.rlp
  ethcore/snapshot/benches/to_fat_rlps.rs
Labels: A2-insubstantial 👶, A7-looksgoodtestsfail 🤖, F4-tests 💻

#11257 Fix registrar errors early in the chain
  miner/src/service_transaction_checker.rs
  util/registrar/src/registrar.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#11267 Ensure jsonrpc threading settings are sane
  parity/cli/mod.rs
  parity/cli/tests/config.toml
  parity/configuration.rs
  parity/deprecated.rs
  parity/lib.rs
  parity/rpc.rs
  parity/run.rs
Labels: A7-looksgoodtestsfail 🤖, M2-config 📂

#11266 removed redundant VMType enum with one variant
  ethcore/evm/src/factory.rs
  ethcore/evm/src/interpreter/mod.rs
  ethcore/evm/src/lib.rs
  ethcore/evm/src/tests.rs
  ethcore/evm/src/vmtype.rs
  ethcore/machine/src/executive.rs
  ethcore/src/client/client.rs
  ethcore/src/client/config.rs
  ethcore/src/client/mod.rs
  ethcore/src/json_tests/executive.rs
  ethcore/src/test_helpers/evm_test_client.rs
  ethcore/src/tests/evm.rs
  ethcore/trie-vm-factories/src/lib.rs
  parity/blockchain.rs
  parity/configuration.rs
  parity/helpers.rs
  parity/run.rs
  parity/snapshot_cmd.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#11269 Clarify what first_block `None` means
  ethcore/blockchain/src/blockchain.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, M3-docs 📑

#11274 Upgrade trie-db to 0.16.0.
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/account-state/Cargo.toml
  ethcore/executive-state/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/pod/Cargo.toml
  ethcore/private-tx/Cargo.toml
  ethcore/snapshot/Cargo.toml
  ethcore/snapshot/snapshot-tests/Cargo.toml
  ethcore/trie-vm-factories/Cargo.toml
  util/patricia-trie-ethereum/Cargo.toml
  util/patricia-trie-ethereum/src/rlp_node_codec.rs
Labels: A8-looksgood 🦄, M4-core ⛓, M5-dependencies 🖇

#11280 ethcore: fix rlp deprecation warnings
  ethcore/snapshot/src/account.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/propagator.rs
Labels: A2-insubstantial 👶, M4-core ⛓

#11276 fixed verify_uncles error type
  ethcore/blockchain/src/blockchain.rs
  ethcore/types/src/engines/mod.rs
  ethcore/types/src/errors/block_error.rs
  ethcore/verification/src/verification.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11270 Don't prune ancient state when instantiating a Client
  ethcore/src/client/client.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11286 [stratum]: fix typo, pusing -> pushing
  miner/stratum/src/lib.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#11227 [ethcore]: apply filter when `PendingSet::AlwaysQueue` in `ready_transactions_filtered`
  ethcore/src/miner/filter_options.rs
  ethcore/src/miner/miner.rs
  rpc/src/v1/tests/helpers/miner_service.rs
Labels: A8-looksgood 🦄, B1-patch-beta 🕷🕷, M4-core ⛓

#11288 [beta v2.6.5]: add missing PR (#10932) to CHANGELOG
  CHANGELOG.md
Labels: A2-insubstantial 👶, A8-backport 🕸, M3-docs 📑

#11282 Istanbul HF in POA Sokol (2019-12-05)
  ethcore/res/ethereum/poasokol.json
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂
