Repository openethereum/openethereum, pull requests merged in 2019-12, with the labels that each got.

#11294 interruptible test and build jobs
  .gitlab-ci.yml
Labels: M1-ci 🙉

#11293 upgrade vergen to 3.0
  Cargo.lock
  util/version/Cargo.toml
  util/version/build.rs
  util/version/src/lib.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶

#11287 Add benchmarks and tests for RlpNodeCodec decoding
  Cargo.lock
  util/patricia-trie-ethereum/Cargo.toml
  util/patricia-trie-ethereum/benches/rlp_node_codec.rs
  util/patricia-trie-ethereum/src/lib.rs
  util/patricia-trie-ethereum/src/rlp_node_codec.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, F4-tests 💻

#11289 add support for evan.network chains
  ethcore/res/ethereum/evancore.json
  ethcore/res/ethereum/evantestcore.json
  ethcore/spec/src/chain.rs
  parity/cli/mod.rs
  parity/params.rs
Labels: A8-looksgood 🦄, M2-config 📂

#11264 Treat blocks, that already downloaded, as synced
  ethcore/sync/src/block_sync.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#11248 Use upstream rocksdb
  Cargo.lock
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/service/Cargo.toml
  ethcore/service/src/service.rs
  ethcore/snapshot/Cargo.toml
  ethcore/snapshot/snapshot-tests/Cargo.toml
  ethcore/src/client/client.rs
  parity/blockchain.rs
  parity/db/mod.rs
  parity/db/rocksdb/helpers.rs
  parity/db/rocksdb/migration.rs
  parity/db/rocksdb/mod.rs
  parity/export_hardcoded_sync.rs
  parity/run.rs
  secret-store/Cargo.toml
  util/migration-rocksdb/Cargo.toml
  util/migration-rocksdb/src/lib.rs
  util/migration-rocksdb/tests/tests.rs
Labels: A8-looksgood 🦄, M4-core ⛓, M5-dependencies 🖇

#11272 only add transactions to signing-queue if it is enabled
  parity/cli/mod.rs
  parity/configuration.rs
  parity/rpc.rs
  rpc/src/v1/helpers/errors.rs
  rpc/src/v1/impls/signing.rs
  rpc/src/v1/tests/mocked/signing.rs
  rpc/src/v1/types/confirmations.rs
Labels: A5-grumble 🔥, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, B7-releasenotes 📜, M6-rpcapi 📣

#11301 [chainspec]: add `eip1344_transition` for istanbul
  ethcore/res/ethereum/foundation.json
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#11304 [backport beta]: add `eip1344_transition` for istanbul
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  ethcore/res/ethereum/foundation.json
  util/version/Cargo.toml
Labels: A8-backport 🕸

#11303 [stable backport]: add `eip1344_transition` for istanbul (#11301)
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  ethcore/res/ethereum/foundation.json
  util/version/Cargo.toml
Labels: A8-backport 🕸

#11305 validate-chainspecs: check istanbul eips are in the foundation spec
  ethcore/res/ethereum/foundation.json
  scripts/gitlab/validate-chainspecs.sh
Labels: M1-ci 🙉, M2-config 📂

#11309 Add check for deserialising hex values over U256 limit
  json/src/uint.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#11273 Adds support for ipc socket permissions
  Cargo.lock
  parity/cli/mod.rs
  parity/cli/tests/config.full.toml
  parity/configuration.rs
  parity/rpc.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
Labels: A7-looksgoodcantmerge 🙄, B7-releasenotes 📜, M4-core ⛓, M6-rpcapi 📣

#11298 Istanbul HF in POA Core (2019-12-19)
  ethcore/res/ethereum/poacore.json
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#11299 Istanbul HF in xDai (2019-12-12)
  ethcore/res/ethereum/xdai.json
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#11277 Fix atomicity violation in network-devp2p
  util/network-devp2p/src/connection.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-io 💾

#11281 Enable EIP-2384 for ice age hard fork
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/ropsten.json
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#11322 [secretstore] migrate to version 4
  parity/db/mod.rs
  parity/db/rocksdb/migration.rs
  parity/db/rocksdb/mod.rs
  parity/secretstore.rs
  secret-store/Cargo.toml
  secret-store/src/key_storage.rs
  secret-store/src/lib.rs
  secret-store/src/migration.rs
  secret-store/src/node_key_pair.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#11331 ethcore/res: activate agharta on classic 9573000
  ethcore/res/ethereum/classic.json
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, B7-releasenotes 📜, M2-config 📂

#11335 remove null signatures
  ethcore/machine/src/machine.rs
  ethcore/src/test_helpers/evm_test_client.rs
  ethcore/types/src/transaction/transaction.rs
  evmbin/Cargo.toml
  json/src/spec/builtin.rs
  json/src/uint.rs
Labels: A0-pleasereview 🤓, M4-core ⛓, M6-rpcapi 📣

#11332 tx-q: enable basic verification of local transactions
  ethcore/src/miner/miner.rs
  ethcore/src/miner/pool_client.rs
  miner/src/pool/client.rs
  miner/src/pool/tests/client.rs
  miner/src/pool/verifier.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, B7-releasenotes 📜, M4-core ⛓

#11338 ethcore/res: activate ecip-1061 on kotti and mordor
  ethcore/res/ethereum/kotti.json
  ethcore/res/ethereum/mordor.json
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#11336 V2.5.12 stable
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kotti.json
  ethcore/res/ethereum/mordor.json
  ethcore/res/ethereum/poacore.json
  ethcore/res/ethereum/poasokol.json
  ethcore/res/ethereum/ropsten.json
  ethcore/res/ethereum/xdai.json
  ethcore/src/client/evm_test_client.rs
  ethcore/src/machine/impls.rs
  ethcore/src/miner/miner.rs
  ethcore/src/miner/pool_client.rs
  ethcore/types/src/transaction/transaction.rs
  evmbin/Cargo.toml
  json/src/spec/builtin.rs
  json/src/uint.rs
  miner/src/pool/client.rs
  miner/src/pool/tests/client.rs
  miner/src/pool/verifier.rs
  util/version/Cargo.toml
Labels: A8-backport 🕸

#11337 V2.6.7 beta
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kotti.json
  ethcore/res/ethereum/mordor.json
  ethcore/res/ethereum/poacore.json
  ethcore/res/ethereum/poasokol.json
  ethcore/res/ethereum/ropsten.json
  ethcore/res/ethereum/xdai.json
  ethcore/src/client/evm_test_client.rs
  ethcore/src/machine.rs
  ethcore/src/miner/miner.rs
  ethcore/src/miner/pool_client.rs
  ethcore/types/src/transaction/transaction.rs
  evmbin/Cargo.toml
  json/src/spec/builtin.rs
  miner/src/pool/client.rs
  miner/src/pool/tests/client.rs
  miner/src/pool/verifier.rs
  parity/db/mod.rs
  parity/db/rocksdb/migration.rs
  parity/db/rocksdb/mod.rs
  parity/secretstore.rs
  secret-store/Cargo.toml
  secret-store/src/key_storage.rs
  secret-store/src/lib.rs
  secret-store/src/migration.rs
  secret-store/src/node_key_pair.rs
  util/version/Cargo.toml
Labels: A8-backport 🕸, A8-looksgood 🦄

#10946 Add randomness contract support to AuthorityRound.
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/client-traits/src/lib.rs
  ethcore/engine/src/engine.rs
  ethcore/engine/src/signer.rs
  ethcore/engine/src/test_helpers.rs
  ethcore/engines/authority-round/Cargo.toml
  ethcore/engines/authority-round/src/lib.rs
  ethcore/engines/authority-round/src/randomness.rs
  ethcore/engines/authority-round/src/util.rs
  ethcore/engines/validator-set/src/contract.rs
  ethcore/engines/validator-set/src/multi.rs
  ethcore/engines/validator-set/src/safe_contract.rs
  ethcore/res/authority_round_randomness_contract.json
  ethcore/res/contracts/authority_round_random.json
  ethcore/res/contracts/test_authority_round_random.json
  ethcore/res/contracts/test_authority_round_random.sol
  ethcore/snapshot/snapshot-tests/src/service.rs
  ethcore/spec/src/chain.rs
  ethcore/src/client/client.rs
  ethcore/src/miner/miner.rs
  ethcore/src/test_helpers/mod.rs
  ethcore/src/test_helpers/test_client.rs
  ethcore/types/src/errors/engine_error.rs
  json/src/spec/authority_round.rs
  rpc/src/v1/helpers/engine_signer.rs
Labels: A0-pleasereview 🤓, F8-enhancement 🎊, M4-core ⛓

#11210 Add Nat PMP method to P2P module
  Cargo.lock
  ethcore/sync/src/api.rs
  parity/configuration.rs
  parity/helpers.rs
  util/network-devp2p/Cargo.toml
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/ip_utils.rs
  util/network/src/lib.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#11308 update autoupdate fork blocks for nightly
  util/version/Cargo.toml
Labels: A8-looksgood 🦄

#11302 Optimization: Use more cache.
  .gitlab-ci.yml
Labels: F7-optimisation 💊, M1-ci 🙉

#11351 Update Ellaism bootnodes
  ethcore/res/ethereum/ellaism.json
Labels: A2-insubstantial 👶, A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, B7-releasenotes 📜, M2-config 📂

#11356 Make sure to not mark block header hash as invalid if only the body is wrong.
  ethcore/src/verification/queue/kind.rs
  ethcore/src/verification/queue/mod.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11348 [util/migration]: remove `static` trait bounds
  util/migration-rocksdb/src/lib.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶

#11362 update version string
  Cargo.lock
  Cargo.toml
  util/version/Cargo.toml
Labels: A8-backport 🕸
