Repository openethereum/openethereum, pull requests merged in 2019-09, with the labels that each got.

#11013 Fix deadlock in `network-devp2p`
  util/network-devp2p/src/host.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#11008 EIP 1108: Reduce alt_bn128 precompile gas costs
  ethcore/builtin/Cargo.toml
  ethcore/builtin/src/lib.rs
  ethcore/engines/basic-authority/res/basic_authority.json
  ethcore/machine/Cargo.toml
  ethcore/machine/src/executive.rs
  ethcore/res/authority_round.json
  ethcore/res/authority_round_block_reward_contract.json
  ethcore/res/constructor.json
  ethcore/res/ethereum/byzantium_test.json
  ethcore/res/ethereum/callisto.json
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/constantinople_test.json
  ethcore/res/ethereum/eip210_test.json
  ethcore/res/ethereum/ellaism.json
  ethcore/res/ethereum/ewc.json
  ethcore/res/ethereum/expanse.json
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/goerli.json
  ethcore/res/ethereum/kotti.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/kovan_wasm_test.json
  ethcore/res/ethereum/mcip3_test.json
  ethcore/res/ethereum/mix.json
  ethcore/res/ethereum/morden.json
  ethcore/res/ethereum/musicoin.json
  ethcore/res/ethereum/poacore.json
  ethcore/res/ethereum/poasokol.json
  ethcore/res/ethereum/rinkeby.json
  ethcore/res/ethereum/ropsten.json
  ethcore/res/ethereum/st_peters_test.json
  ethcore/res/ethereum/transition_test.json
  ethcore/res/ethereum/volta.json
  ethcore/res/ethereum/xdai.json
  ethcore/res/instant_seal.json
  ethcore/res/null.json
  ethcore/types/Cargo.toml
  ethcore/types/src/engines/params.rs
  json/src/spec/builtin.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#11016 Edit publish-onchain.sh to use https
  scripts/gitlab/publish-onchain.sh
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#11024 [private-tx] remove unused dependency `rand`
  Cargo.lock
  ethcore/private-tx/Cargo.toml
  ethcore/private-tx/src/lib.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#10924 cli: update usage and version headers
  parity/cli/usage_header.txt
  parity/cli/version.txt
Labels: A2-insubstantial 👶, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#11019 [trace] introduce trace failed to Ext
  ethcore/evm/src/interpreter/mod.rs
  ethcore/machine/src/externalities.rs
  ethcore/trace/src/executive_tracer.rs
  ethcore/trace/src/lib.rs
  ethcore/vm/src/ext.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#11015 Fix block detail updating
  ethcore/blockchain/src/blockchain.rs
  ethcore/db/src/db.rs
  ethcore/engines/null-engine/src/lib.rs
  ethcore/res/null_morden_with_finality.json
  ethcore/spec/src/chain.rs
  ethcore/src/client/client.rs
  json/src/spec/null_engine.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10999 Convert `std::test` benchmarks to use Criterion
  .gitlab-ci.yml
  Cargo.lock
  ethash/Cargo.toml
  ethcore/Cargo.toml
  ethcore/evm/Cargo.toml
  evmbin/Cargo.toml
  evmbin/benches/mod.rs
  util/blooms-db/Cargo.toml
  util/blooms-db/benches/blooms.rs
Labels: A8-looksgood 🦄, M1-ci 🙉

#11029 fix: remove needless use of itertools
  Cargo.lock
  ethcore/engines/authority-round/src/lib.rs
  ethcore/light/Cargo.toml
  ethcore/light/src/client/header_chain.rs
  ethcore/light/src/lib.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, M4-core ⛓

#11028 remove unused dependency `error-chain`
  Cargo.lock
  ethcore/light/Cargo.toml
  miner/Cargo.toml
  util/network-devp2p/Cargo.toml
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#10984 Add new line after writing block to hex file.
  ethcore/blockchain/src/blockchain.rs
  ethcore/client-traits/src/lib.rs
  ethcore/src/client/client.rs
  ethcore/src/tests/client.rs
  ethcore/types/src/data_format.rs
  ethcore/types/src/lib.rs
  parity/blockchain.rs
  parity/configuration.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11017 Add blake2_f precompile
  Cargo.lock
  ethcore/builtin/Cargo.toml
  ethcore/builtin/src/lib.rs
  json/src/spec/builtin.rs
  util/EIP-152/Cargo.toml
  util/EIP-152/src/lib.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#11034 [json-spec] make blake2 pricing spec more readable
  ethcore/builtin/src/lib.rs
  json/src/spec/builtin.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M2-config 📂

#11033 [spec] add istanbul test spec
  ethcore/machine/src/test_helpers.rs
  ethcore/res/ethereum/istanbul_test.json
  ethcore/spec/src/chain.rs
  ethcore/src/client/evm_test_client.rs
  evmbin/src/main.rs
  json/src/spec/spec.rs
Labels: A0-pleasereview 🤓, M2-config 📂

#11012 Move snapshot related traits to their proper place
  Cargo.lock
  ethcore/client-traits/src/lib.rs
  ethcore/service/src/service.rs
  ethcore/snapshot/Cargo.toml
  ethcore/snapshot/snapshot-tests/Cargo.toml
  ethcore/snapshot/snapshot-tests/src/abridged_block.rs
  ethcore/snapshot/snapshot-tests/src/account.rs
  ethcore/snapshot/snapshot-tests/src/helpers.rs
  ethcore/snapshot/snapshot-tests/src/io.rs
  ethcore/snapshot/snapshot-tests/src/lib.rs
  ethcore/snapshot/snapshot-tests/src/proof_of_authority.rs
  ethcore/snapshot/snapshot-tests/src/proof_of_work.rs
  ethcore/snapshot/snapshot-tests/src/service.rs
  ethcore/snapshot/snapshot-tests/src/state.rs
  ethcore/snapshot/snapshot-tests/src/test_validator_contract.json
  ethcore/snapshot/snapshot-tests/src/watcher.rs
  ethcore/snapshot/src/account.rs
  ethcore/snapshot/src/block.rs
  ethcore/snapshot/src/io.rs
  ethcore/snapshot/src/lib.rs
  ethcore/snapshot/src/service.rs
  ethcore/snapshot/src/traits.rs
  ethcore/snapshot/src/watcher.rs
  ethcore/src/client/client.rs
  parity/snapshot_cmd.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11035 Benchmarks for block verification
  .gitlab-ci.yml
  Cargo.lock
  ethcore/types/src/verification.rs
  ethcore/verification/Cargo.toml
  ethcore/verification/benches/8447675.rlp
  ethcore/verification/benches/8481474-parent-to-uncle.rlp
  ethcore/verification/benches/8481475.rlp
  ethcore/verification/benches/8481476-one-uncle.rlp
  ethcore/verification/benches/verification.rs
  ethcore/verification/src/lib.rs
  ethcore/verification/src/test_helpers.rs
  ethcore/verification/src/verification.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11036 [ethcore]: make it compile without `test-helpers` feature
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/src/lib.rs
  ethcore/src/tests/client.rs
  ethcore/src/tests/evm.rs
  ethcore/types/src/data_format.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#10995 Fix parallel transactions race-condition
  Cargo.lock
  ethcore/engines/instant-seal/src/lib.rs
  ethcore/private-tx/Cargo.toml
  ethcore/src/miner/miner.rs
  miner/Cargo.toml
  rpc/Cargo.toml
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#11045 Include test-helpers from ethjson
  evmbin/Cargo.toml
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#11047 [build]: remove `test-helper feat` from build
  ethcore/Cargo.toml
  rpc/Cargo.toml
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M0-build 🏗, M4-core ⛓

#11049 ethcore: remove `test-helper feat` from build (#11047)
  rpc/Cargo.toml
Labels: A0-pleasereview 🤓, A2-insubstantial 👶

#11048 Don't build rpc with ethcore test-helpers
  rpc/Cargo.toml
Labels: A0-pleasereview 🤓, A2-insubstantial 👶

#11052 cargo update -p eth-secp256k1
  Cargo.lock
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M5-dependencies 🖇

#11057 Update changelog
  CHANGELOG.md
Labels: A8-looksgood 🦄, M3-docs 📑

#11058 update CHANGELOG.md
  CHANGELOG.md
Labels: A8-looksgood 🦄, M3-docs 📑

#11053 Update hardcoded headers (foundation, classic, kovan, xdai, ewc, ...)
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/ewc.json
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/poacore.json
  ethcore/res/ethereum/poasokol.json
  ethcore/res/ethereum/volta.json
  ethcore/res/ethereum/xdai.json
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#11060 [evmbin] fix time formatting
  evmbin/src/display/mod.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11059 [ethcore]: reduce re-exports
  ethcore/private-tx/src/lib.rs
  ethcore/private-tx/tests/private_contract.rs
  ethcore/src/client/client.rs
  ethcore/src/client/config.rs
  ethcore/src/client/mod.rs
  ethcore/src/lib.rs
  ethcore/src/test_helpers.rs
  ethcore/sync/Cargo.toml
  ethcore/sync/src/lib.rs
  ethcore/sync/src/tests/private.rs
  evmbin/src/info.rs
  evmbin/src/main.rs
  parity/configuration.rs
  parity/helpers.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#11061 [sync]: remove unused dependencies or make dev
  Cargo.lock
  ethcore/sync/Cargo.toml
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/lib.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#11062 [ethcore]: move client test types to test-helpers
  ethcore/light/src/net/tests/mod.rs
  ethcore/light/src/on_demand/request.rs
  ethcore/light/src/provider.rs
  ethcore/src/client/mod.rs
  ethcore/src/json_tests/chain.rs
  ethcore/src/json_tests/state.rs
  ethcore/src/json_tests/transaction.rs
  ethcore/src/miner/miner.rs
  ethcore/src/test_helpers/evm_test_client.rs
  ethcore/src/test_helpers/mod.rs
  ethcore/src/test_helpers/test_client.rs
  ethcore/sync/src/block_sync.rs
  ethcore/sync/src/blocks.rs
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/propagator.rs
  ethcore/sync/src/chain/supplier.rs
  ethcore/sync/src/light_sync/tests/mod.rs
  ethcore/sync/src/light_sync/tests/test_net.rs
  ethcore/sync/src/tests/chain.rs
  ethcore/sync/src/tests/helpers.rs
  ethcore/sync/src/tests/snapshot.rs
  ethcore/verification/benches/verification.rs
  ethcore/verification/src/verification.rs
  evmbin/src/info.rs
  ipfs/src/route.rs
  rpc/src/v1/tests/helpers/miner_service.rs
  rpc/src/v1/tests/mocked/debug.rs
  rpc/src/v1/tests/mocked/eth.rs
  rpc/src/v1/tests/mocked/eth_pubsub.rs
  rpc/src/v1/tests/mocked/parity.rs
  rpc/src/v1/tests/mocked/parity_set.rs
  rpc/src/v1/tests/mocked/personal.rs
  rpc/src/v1/tests/mocked/signer.rs
  rpc/src/v1/tests/mocked/signing.rs
  rpc/src/v1/tests/mocked/signing_unsafe.rs
  rpc/src/v1/tests/mocked/traces.rs
  updater/src/updater.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11067 [sync]: rust 2018
  ethcore/sync/Cargo.toml
  ethcore/sync/src/api.rs
  ethcore/sync/src/block_sync.rs
  ethcore/sync/src/blocks.rs
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/propagator.rs
  ethcore/sync/src/chain/requester.rs
  ethcore/sync/src/chain/supplier.rs
  ethcore/sync/src/chain/sync_packet.rs
  ethcore/sync/src/lib.rs
  ethcore/sync/src/light_sync/mod.rs
  ethcore/sync/src/light_sync/response.rs
  ethcore/sync/src/light_sync/sync_round.rs
  ethcore/sync/src/light_sync/tests/mod.rs
  ethcore/sync/src/light_sync/tests/test_net.rs
  ethcore/sync/src/snapshot_sync.rs
  ethcore/sync/src/sync_io.rs
  ethcore/sync/src/tests/chain.rs
  ethcore/sync/src/tests/consensus.rs
  ethcore/sync/src/tests/helpers.rs
  ethcore/sync/src/tests/private.rs
  ethcore/sync/src/tests/snapshot.rs
  ethcore/sync/src/transactions_stats.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11068 ethcore/res: activate Istanbul on Ropsten, Görli, Rinkeby, Kovan
  ethcore/res/ethereum/goerli.json
  ethcore/res/ethereum/istanbul_test.json
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/rinkeby.json
  ethcore/res/ethereum/ropsten.json
  ethcore/res/ethereum/st_peters_test.json
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, B7-releasenotes 📜, M2-config 📂, P5-sometimesoon 🌲

#11069 [ethash] remove manual unrolling
  .gitlab-ci.yml
  Cargo.lock
  ethash/Cargo.toml
  ethash/benches/basic.rs
  ethash/src/cache.rs
  ethash/src/compute.rs
  ethash/src/lib.rs
  ethcore/verification/Cargo.toml
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, M4-core ⛓

#11088 fix(network): typo
  util/network/src/lib.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#11086 [client]: Fix for incorrectly dropped consensus messages (#11082)
  ethcore/src/client/client.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#11094 Update CHANGELOG.md and version
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  util/version/Cargo.toml
Labels: A8-backport 🕸

#11093 Update CHANGELOG.md and version
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  util/version/Cargo.toml
Labels: A8-backport 🕸

#11091 Update `kvdb`, `kvdb-rocksdb` and `h2`
  Cargo.lock
  Cargo.toml
  accounts/Cargo.toml
  accounts/ethstore/Cargo.toml
  accounts/ethstore/cli/Cargo.toml
  cli-signer/rpc-client/Cargo.toml
  ethash/Cargo.toml
  ethcore/Cargo.toml
  ethcore/account-state/Cargo.toml
  ethcore/blockchain/Cargo.toml
  ethcore/client-traits/Cargo.toml
  ethcore/db/Cargo.toml
  ethcore/engines/authority-round/Cargo.toml
  ethcore/engines/basic-authority/Cargo.toml
  ethcore/engines/clique/Cargo.toml
  ethcore/engines/validator-set/Cargo.toml
  ethcore/evm/Cargo.toml
  ethcore/executive-state/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/machine/Cargo.toml
  ethcore/node-filter/Cargo.toml
  ethcore/private-tx/Cargo.toml
  ethcore/service/Cargo.toml
  ethcore/snapshot/Cargo.toml
  ethcore/snapshot/snapshot-tests/Cargo.toml
  ethcore/spec/Cargo.toml
  ethcore/state-db/Cargo.toml
  ethcore/sync/Cargo.toml
  ethcore/trace/Cargo.toml
  ethcore/verification/Cargo.toml
  miner/Cargo.toml
  miner/local-store/Cargo.toml
  miner/stratum/Cargo.toml
  parity/logger/Cargo.toml
  rpc/Cargo.toml
  secret-store/Cargo.toml
  updater/Cargo.toml
  updater/hash-fetch/Cargo.toml
  util/blooms-db/Cargo.toml
  util/io/Cargo.toml
  util/journaldb/Cargo.toml
  util/len-caching-lock/Cargo.toml
  util/migration-rocksdb/Cargo.toml
  util/network-devp2p/Cargo.toml
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M5-dependencies 🖇

#11096 [CI] check evmbin build
  .gitlab-ci.yml
Labels: B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#11092 Correct EIP-712 encoding
  Cargo.lock
  util/EIP-712/Cargo.toml
  util/EIP-712/src/encode.rs
  util/EIP-712/src/parser.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M6-rpcapi 📣
