Repository openethereum/openethereum, pull requests merged in 2019-06, with the labels that each got.

#10710 [devp2p] Fix warnings and re-org imports
  util/network-devp2p/src/connection.rs
  util/network-devp2p/src/discovery.rs
  util/network-devp2p/src/handshake.rs
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/ip_utils.rs
  util/network-devp2p/src/lib.rs
  util/network-devp2p/src/node_table.rs
  util/network-devp2p/src/service.rs
  util/network-devp2p/src/session.rs
  util/network-devp2p/tests/tests.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10717 enable lto for release builds
  Cargo.toml
  scripts/gitlab/test-linux.sh
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M0-build 🏗

#10241 SecretStore: expose restore_key_public in HTTP API
  secret-store/src/key_server.rs
  secret-store/src/key_server_cluster/admin_sessions/key_version_negotiation_session.rs
  secret-store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs
  secret-store/src/key_server_cluster/admin_sessions/share_add_session.rs
  secret-store/src/key_server_cluster/message.rs
  secret-store/src/key_storage.rs
  secret-store/src/listener/http_listener.rs
  secret-store/src/listener/mod.rs
  secret-store/src/traits.rs
Labels: A0-pleasereview 🤓, A8-looksgood 🦄, M4-core ⛓

#10722 Removed secret_store folder
  secret_store/src/key_server_cluster/cluster_connections.rs
  secret_store/src/key_server_cluster/cluster_connections_net.rs
  secret_store/src/key_server_cluster/cluster_message_processor.rs
Labels: A2-insubstantial 👶, M4-core ⛓

#10303 SecretStore: non-blocking wait of session completion
  secret-store/src/key_server.rs
  secret-store/src/key_server_cluster/admin_sessions/key_version_negotiation_session.rs
  secret-store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs
  secret-store/src/key_server_cluster/admin_sessions/share_add_session.rs
  secret-store/src/key_server_cluster/admin_sessions/share_change_session.rs
  secret-store/src/key_server_cluster/client_sessions/decryption_session.rs
  secret-store/src/key_server_cluster/client_sessions/encryption_session.rs
  secret-store/src/key_server_cluster/client_sessions/generation_session.rs
  secret-store/src/key_server_cluster/client_sessions/signing_session_ecdsa.rs
  secret-store/src/key_server_cluster/client_sessions/signing_session_schnorr.rs
  secret-store/src/key_server_cluster/cluster.rs
  secret-store/src/key_server_cluster/cluster_message_processor.rs
  secret-store/src/key_server_cluster/cluster_sessions.rs
  secret-store/src/key_server_cluster/cluster_sessions_creator.rs
  secret-store/src/key_server_cluster/connection_trigger_with_migration.rs
  secret-store/src/key_server_cluster/mod.rs
  secret-store/src/listener/http_listener.rs
  secret-store/src/listener/mod.rs
  secret-store/src/listener/service_contract_listener.rs
  secret-store/src/traits.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10719 Use RUSTFLAGS to set the optimization level
  Cargo.toml
  scripts/gitlab/test-linux.sh
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M0-build 🏗

#10729 Stop breaking out of loop if a non-canonical hash is found
  ethcore/blockchain/src/blockchain.rs
  ethcore/src/engines/authority_round/finality.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/verification/verifier.rs
Labels: A0-pleasereview 🤓

#10731 ethcore: enable ECIP-1054 for classic
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/kotti.json
  ethcore/res/ethereum/morden.json
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#10736 backports for stable 2.4.7
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/morden.json
  scripts/docker/hub/Dockerfile
  scripts/docker/hub/publish-docker.sh
  scripts/gitlab/publish-docker.sh
  scripts/gitlab/publish-docs.sh
  scripts/gitlab/publish-onchain.sh
  scripts/gitlab/publish-snap.sh
  scripts/gitlab/test-linux.sh
  util/version/Cargo.toml
Labels: A8-backport 🕸, M1-ci 🙉, M2-config 📂

#10737 backports for beta 2.5.2
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  ethcore/blockchain/src/blockchain.rs
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/kotti.json
  ethcore/res/ethereum/morden.json
  ethcore/src/client/client.rs
  ethcore/src/tests/client.rs
  scripts/docker/hub/Dockerfile
  scripts/docker/hub/publish-docker.sh
  scripts/gitlab/publish-docker.sh
  scripts/gitlab/publish-docs.sh
  scripts/gitlab/publish-onchain.sh
  scripts/gitlab/publish-snap.sh
  scripts/gitlab/test-linux.sh
  util/version/Cargo.toml
Labels: A8-backport 🕸, M1-ci 🙉, M2-config 📂, M4-core ⛓

#10705 DevP2p: Get node IP address and udp port from Socket, if not included in PING packet
  util/network-devp2p/src/discovery.rs
  util/network-devp2p/src/node_table.rs
Labels: A8-looksgood 🦄, B1-patch-beta 🕷🕷, M4-core ⛓

#10741 fix docker tags for publishing
  scripts/docker/hub/publish-docker.sh
Labels: A8-backport 🕸, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M1-ci 🙉

#10746 Fix deprectation warnings on nightly
  ethcore/benches/builtin.rs
  ethcore/blockchain/src/blockchain.rs
  ethcore/src/account_db.rs
  ethcore/src/block.rs
  ethcore/src/builtin.rs
  ethcore/src/client/ancient_import.rs
  ethcore/src/client/client.rs
  ethcore/src/client/io_message.rs
  ethcore/src/client/test_client.rs
  ethcore/src/client/trace.rs
  ethcore/src/client/traits.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/basic_authority.rs
  ethcore/src/engines/clique/mod.rs
  ethcore/src/engines/mod.rs
  ethcore/src/engines/null_engine.rs
  ethcore/src/engines/signer.rs
  ethcore/src/engines/validator_set/contract.rs
  ethcore/src/engines/validator_set/mod.rs
  ethcore/src/engines/validator_set/multi.rs
  ethcore/src/engines/validator_set/safe_contract.rs
  ethcore/src/engines/validator_set/simple_list.rs
  ethcore/src/error.rs
  ethcore/src/ethereum/ethash.rs
  ethcore/src/executive.rs
  ethcore/src/factory.rs
  ethcore/src/lib.rs
  ethcore/src/machine/impls.rs
  ethcore/src/miner/miner.rs
  ethcore/src/miner/pool_client.rs
  ethcore/src/pod_account.rs
  ethcore/src/snapshot/account.rs
  ethcore/src/snapshot/consensus/authority.rs
  ethcore/src/snapshot/consensus/mod.rs
  ethcore/src/snapshot/consensus/work.rs
  ethcore/src/snapshot/error.rs
  ethcore/src/snapshot/mod.rs
  ethcore/src/snapshot/service.rs
  ethcore/src/snapshot/tests/helpers.rs
  ethcore/src/snapshot/watcher.rs
  ethcore/src/spec/spec.rs
  ethcore/src/state/account.rs
  ethcore/src/state/backend.rs
  ethcore/src/state/mod.rs
  ethcore/src/state_db.rs
  ethcore/src/test_helpers.rs
  ethcore/src/trace/db.rs
  ethcore/src/verification/canon_verifier.rs
  ethcore/src/verification/mod.rs
  ethcore/src/verification/noop_verifier.rs
  ethcore/src/verification/queue/kind.rs
  ethcore/src/verification/queue/mod.rs
  ethcore/src/verification/verification.rs
  ethcore/src/verification/verifier.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶

#10747 Die error_chain, die
  Cargo.lock
  ethcore/light/Cargo.toml
  ethcore/light/src/client/header_chain.rs
  ethcore/light/src/lib.rs
  ethcore/light/src/on_demand/mod.rs
  ethcore/private-tx/src/lib.rs
  ethcore/service/Cargo.toml
  ethcore/service/src/error.rs
  ethcore/service/src/lib.rs
  ethcore/service/src/service.rs
  ethcore/src/lib.rs
  ethcore/sync/src/api.rs
  ethcore/sync/src/blocks.rs
  ethcore/sync/src/lib.rs
  miner/src/lib.rs
  miner/src/pool/verifier.rs
  parity/configuration.rs
  parity/helpers.rs
  rpc/src/v1/helpers/errors.rs
  util/network-devp2p/src/connection.rs
  util/network-devp2p/src/discovery.rs
  util/network-devp2p/src/handshake.rs
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/lib.rs
  util/network-devp2p/src/node_table.rs
  util/network-devp2p/src/session.rs
  util/network/Cargo.toml
  util/network/src/error.rs
  util/network/src/lib.rs
Labels: A0-pleasereview 🤓, A8-looksgood 🦄, M4-core ⛓

#10752 Use fewer threads for snapshotting
  ethcore/src/snapshot/mod.rs
  parity/configuration.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶

#10755 updater: fix static id hashes initialization
  updater/src/updater.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#10714 [devp2p] Don't use `rust-crypto`
  util/network-devp2p/src/connection.rs
  util/network-devp2p/src/lib.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10757 SecretStore: remove support of old database formats
  secret-store/src/key_storage.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#10756 Enable aesni
  .cargo/config
  scripts/gitlab/build-linux.sh
  scripts/gitlab/build-windows.sh
  scripts/gitlab/test-linux.sh
Labels: A0-pleasereview 🤓

#10744 Add a way to signal shutdown to snapshotting threads
  ethcore/service/src/service.rs
  ethcore/src/client/client.rs
  ethcore/src/snapshot/account.rs
  ethcore/src/snapshot/error.rs
  ethcore/src/snapshot/io.rs
  ethcore/src/snapshot/mod.rs
  ethcore/src/snapshot/service.rs
  ethcore/src/snapshot/tests/service.rs
  ethcore/src/snapshot/tests/state.rs
  ethcore/src/snapshot/traits.rs
  ethcore/sync/src/tests/snapshot.rs
  parity/lib.rs
  parity/run.rs
  parity/snapshot.rs
  rpc/src/v1/tests/helpers/snapshot_service.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10716 [devp2p] Update to 2018 edition
  Cargo.lock
  util/network-devp2p/Cargo.toml
  util/network-devp2p/src/connection.rs
  util/network-devp2p/src/discovery.rs
  util/network-devp2p/src/handshake.rs
  util/network-devp2p/src/host.rs
  util/network-devp2p/src/ip_utils.rs
  util/network-devp2p/src/lib.rs
  util/network-devp2p/src/node_table.rs
  util/network-devp2p/src/service.rs
  util/network-devp2p/src/session.rs
  util/network-devp2p/tests/tests.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10762 Remove unused code
  ethcore/service/src/lib.rs
  ethcore/service/src/service.rs
  ethcore/service/src/stop_guard.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10758 Initialize private tx logger only if private tx functionality is enabled
  parity/configuration.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10720 fix: aura don't add `SystemTime::now()`
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/clique/block_state.rs
  ethcore/src/engines/clique/mod.rs
  ethcore/src/lib.rs
  ethcore/src/verification/verification.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10740 refactor: Fix indentation in ethjson
  json/src/state/test.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10766 ethcore/res: activate atlantis classic hf on block 8772000
  ethcore/res/ethereum/classic.json
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M2-config 📂

#10733 Print warnings when using dangerous settings for ValidatorSet
  ethcore/blockchain/src/blockchain.rs
  ethcore/src/engines/authority_round/finality.rs
  ethcore/src/engines/validator_set/safe_contract.rs
  ethcore/src/engines/validator_set/simple_list.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10767 Move Engine::register_client to be before other I/O handler registration
  ethcore/light/src/client/service.rs
  ethcore/service/src/service.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10652 docs: Update Readme with TOC, Contributor Guideline. Update Cargo package descriptions
  .github/CONTRIBUTING.md
  README.md
  accounts/Cargo.toml
  accounts/ethkey/Cargo.toml
  accounts/ethkey/README.md
  accounts/ethkey/cli/Cargo.toml
  accounts/ethstore/Cargo.toml
  accounts/ethstore/cli/Cargo.toml
  chainspec/Cargo.toml
  cli-signer/Cargo.toml
  cli-signer/rpc-client/Cargo.toml
  ethash/Cargo.toml
  ethcore/Cargo.toml
  ethcore/blockchain/Cargo.toml
  ethcore/call-contract/Cargo.toml
  ethcore/evm/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/node-filter/Cargo.toml
  ethcore/private-tx/src/encryptor.rs
  ethcore/service/Cargo.toml
  ethcore/sync/Cargo.toml
  ethcore/types/Cargo.toml
  ethcore/types/src/restoration_status.rs
  ethcore/vm/Cargo.toml
  ethcore/wasm/Cargo.toml
  ethcore/wasm/run/Cargo.toml
  evmbin/Cargo.toml
  ipfs/Cargo.toml
  json/Cargo.toml
  miner/Cargo.toml
  parity/logger/Cargo.toml
  rpc/Cargo.toml
  rpc/src/lib.rs
  secret-store/Cargo.toml
  whisper/Cargo.toml
Labels: A0-pleasereview 🤓, A4-gotissues 💥, M3-docs 📑

#10775 Treat empty account the same as non-exist accounts in EIP-1052
  ethcore/src/externalities.rs
Labels: A0-pleasereview 🤓, A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷

#10734 Log validator set changes in EpochManager
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/mod.rs
  ethcore/src/engines/validator_set/simple_list.rs
  ethcore/src/engines/validator_set/test.rs
Labels: A0-pleasereview 🤓

#10776 Beta 2.5.3
  Cargo.lock
  Cargo.toml
  ethcore/res/ethereum/classic.json
  ethcore/service/src/service.rs
  ethcore/src/client/client.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/clique/block_state.rs
  ethcore/src/engines/clique/mod.rs
  ethcore/src/externalities.rs
  ethcore/src/lib.rs
  ethcore/src/snapshot/account.rs
  ethcore/src/snapshot/error.rs
  ethcore/src/snapshot/io.rs
  ethcore/src/snapshot/mod.rs
  ethcore/src/snapshot/service.rs
  ethcore/src/snapshot/tests/service.rs
  ethcore/src/snapshot/tests/state.rs
  ethcore/src/snapshot/traits.rs
  ethcore/src/verification/verification.rs
  ethcore/sync/src/tests/snapshot.rs
  parity/configuration.rs
  parity/lib.rs
  parity/run.rs
  parity/snapshot.rs
  rpc/src/v1/tests/helpers/snapshot_service.rs
  scripts/docker/hub/publish-docker.sh
  util/network-devp2p/src/discovery.rs
  util/network-devp2p/src/node_table.rs
  util/version/Cargo.toml
Labels: A8-backport 🕸

#10779 Stable 2.4.8 backports
  Cargo.lock
  Cargo.toml
  ethcore/blockchain/src/blockchain.rs
  ethcore/res/ethereum/classic.json
  ethcore/service/src/service.rs
  ethcore/src/client/client.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/externalities.rs
  ethcore/src/lib.rs
  ethcore/src/snapshot/account.rs
  ethcore/src/snapshot/error.rs
  ethcore/src/snapshot/io.rs
  ethcore/src/snapshot/mod.rs
  ethcore/src/snapshot/service.rs
  ethcore/src/snapshot/tests/service.rs
  ethcore/src/snapshot/tests/state.rs
  ethcore/src/snapshot/traits.rs
  ethcore/src/tests/client.rs
  ethcore/src/verification/verification.rs
  ethcore/sync/src/tests/snapshot.rs
  parity/configuration.rs
  parity/lib.rs
  parity/rpc_apis.rs
  parity/run.rs
  parity/snapshot.rs
  rpc/src/v1/helpers/errors.rs
  rpc/src/v1/impls/eth.rs
  rpc/src/v1/tests/eth.rs
  rpc/src/v1/tests/helpers/snapshot_service.rs
  scripts/docker/hub/publish-docker.sh
  util/network-devp2p/src/discovery.rs
  util/network-devp2p/src/node_table.rs
  util/version/Cargo.toml
Labels: A8-backport 🕸

#10786 ethkey no longer uses byteorder
  Cargo.lock
  accounts/ethkey/Cargo.toml
  accounts/ethkey/src/extended.rs
  accounts/ethkey/src/lib.rs
Labels: A2-insubstantial 👶, A7-looksgoodtestsfail 🤖, B0-patch-stable 🕷, B1-patch-beta 🕷🕷

#10785 Updated blooms-db to rust 2018 and removed redundant deps
  Cargo.lock
  util/blooms-db/Cargo.toml
  util/blooms-db/src/db.rs
  util/blooms-db/src/file.rs
  util/blooms-db/src/lib.rs
Labels: A2-insubstantial 👶, A7-looksgoodtestsfail 🤖, B0-patch-stable 🕷, B1-patch-beta 🕷🕷

#10791 Removed machine abstraction from ethcore
  ethcore/benches/builtin.rs
  ethcore/light/src/client/fetch.rs
  ethcore/light/src/client/mod.rs
  ethcore/light/src/on_demand/request.rs
  ethcore/src/client/ancient_import.rs
  ethcore/src/client/client.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/basic_authority.rs
  ethcore/src/engines/block_reward.rs
  ethcore/src/engines/clique/mod.rs
  ethcore/src/engines/instant_seal.rs
  ethcore/src/engines/mod.rs
  ethcore/src/engines/null_engine.rs
  ethcore/src/engines/validator_set/contract.rs
  ethcore/src/engines/validator_set/mod.rs
  ethcore/src/engines/validator_set/multi.rs
  ethcore/src/engines/validator_set/safe_contract.rs
  ethcore/src/engines/validator_set/simple_list.rs
  ethcore/src/engines/validator_set/test.rs
  ethcore/src/ethereum/ethash.rs
  ethcore/src/ethereum/mod.rs
  ethcore/src/executive.rs
  ethcore/src/externalities.rs
  ethcore/src/json_tests/executive.rs
  ethcore/src/machine.rs
  ethcore/src/machine/mod.rs
  ethcore/src/machine/traits.rs
  ethcore/src/snapshot/consensus/authority.rs
  ethcore/src/spec/spec.rs
  ethcore/src/state/mod.rs
  ethcore/src/verification/verification.rs
  parity/light_helpers/epoch_fetch.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#10788 Removed redundant ethcore-service error type
  ethcore/service/src/error.rs
  ethcore/service/src/lib.rs
  ethcore/service/src/service.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10787 Cleanup unused vm dependencies
  Cargo.lock
  ethcore/vm/Cargo.toml
  ethcore/vm/src/lib.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, B0-patch-stable 🕷, B1-patch-beta 🕷🕷

#10800 updated parity-local-store to edition 2018
  miner/local-store/Cargo.toml
  miner/local-store/src/lib.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶

#10797 ethcore-network-devp2p uses igd 0.9
  Cargo.lock
  util/network-devp2p/Cargo.toml
  util/network-devp2p/src/ip_utils.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#10801 updated price-info to edition 2018
  Cargo.lock
  miner/price-info/Cargo.toml
  miner/price-info/src/lib.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, A7-looksgoodtestsfail 🤖

#10794 added new ropsten-bootnode and removed old one
  ethcore/res/ethereum/ropsten.json
Labels: B0-patch-stable 🕷, B1-patch-beta 🕷🕷

#10799 updated project to ansi_term 0.11
  Cargo.lock
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/blockchain/Cargo.toml
  ethcore/service/Cargo.toml
  ethcore/service/src/lib.rs
  miner/Cargo.toml
  parity/logger/Cargo.toml
  rpc/Cargo.toml
  util/network-devp2p/Cargo.toml
Labels: A0-pleasereview 🤓, A2-insubstantial 👶

#10803 Fix a few typos and unused warnings.
  ethcore/src/lib.rs
  ethcore/src/trace/types/trace.rs
  ethcore/types/src/transaction/error.rs
Labels: A8-looksgood 🦄

#10798 ethcore-light uses bincode 1.1
  Cargo.lock
  ethcore/light/Cargo.toml
  ethcore/light/src/net/load_timer.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶

#10804 ethcore-bloom-journal updated to 2018
  Cargo.lock
  util/bloom/Cargo.toml
  util/bloom/src/lib.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10772 Do not drop the peer with None difficulty
  .gitlab-ci.yml
  ethcore/sync/src/chain/mod.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10808 fix spurious test failure
  rpc/src/v1/tests/mocked/signing.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10805 removed EthEngine alias
  ethcore/light/src/client/fetch.rs
  ethcore/light/src/client/mod.rs
  ethcore/light/src/on_demand/request.rs
  ethcore/src/block.rs
  ethcore/src/client/ancient_import.rs
  ethcore/src/client/client.rs
  ethcore/src/client/test_client.rs
  ethcore/src/client/traits.rs
  ethcore/src/engines/authority_round/mod.rs
  ethcore/src/engines/mod.rs
  ethcore/src/miner/miner.rs
  ethcore/src/miner/pool_client.rs
  ethcore/src/snapshot/consensus/authority.rs
  ethcore/src/snapshot/consensus/mod.rs
  ethcore/src/snapshot/consensus/work.rs
  ethcore/src/snapshot/mod.rs
  ethcore/src/snapshot/service.rs
  ethcore/src/snapshot/tests/helpers.rs
  ethcore/src/spec/spec.rs
  ethcore/src/verification/canon_verifier.rs
  ethcore/src/verification/noop_verifier.rs
  ethcore/src/verification/queue/kind.rs
  ethcore/src/verification/queue/mod.rs
  ethcore/src/verification/verification.rs
  ethcore/src/verification/verifier.rs
  parity/light_helpers/epoch_fetch.rs
  rpc/src/v1/helpers/light_fetch.rs
  rpc/src/v1/tests/helpers/miner_service.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶

#10506 Add filtering capability to `parity_pendingTransactions` (issue 8269)
  Cargo.lock
  ethcore/Cargo.toml
  ethcore/src/lib.rs
  ethcore/src/miner/filter_options.rs
  ethcore/src/miner/miner.rs
  ethcore/src/miner/mod.rs
  ethcore/types/src/transaction/transaction.rs
  rpc/src/v1/impls/light/parity.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/tests/helpers/miner_service.rs
  rpc/src/v1/traits/parity.rs
Labels: A8-looksgood 🦄, B7-releasenotes 📜, M6-rpcapi 📣

#10807 revert temp changes to .gitlab-ci.yml
  .gitlab-ci.yml
Labels: A2-insubstantial 👶

#10806 removed redundant fmt::Display implementations
  ethcore/src/state/mod.rs
  ethcore/types/src/account_diff.rs
  ethcore/types/src/state_diff.rs
  ethcore/types/src/verification_queue_info.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10809 Add Constantinople EIPs to the dev (instant_seal) config
  ethcore/res/instant_seal.json
Labels: A0-pleasereview 🤓, M2-config 📂

#10818 removed additional_params method
  ethcore/src/client/client.rs
  ethcore/src/client/test_client.rs
  ethcore/src/client/traits.rs
  ethcore/src/engines/mod.rs
  ethcore/src/machine.rs
  ethcore/src/spec/spec.rs
  ethcore/src/tests/client.rs
  rpc/src/v1/impls/light/parity.rs
  rpc/src/v1/impls/parity.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#10813 Don't reimplement the logic from the Default impl
  parity/configuration.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#10816 replace memzero with zeroize crate
  Cargo.lock
  accounts/ethkey/Cargo.toml
  accounts/ethkey/src/lib.rs
  accounts/ethkey/src/secret.rs
  whisper/Cargo.toml
  whisper/src/lib.rs
  whisper/src/rpc/crypto.rs
  whisper/src/rpc/key_store.rs
  whisper/src/rpc/mod.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, M5-dependencies 🖇

#10822 bump `smallvec 0.6.10` to fix vulnerability
  Cargo.lock
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷
