Repository openethereum/openethereum, pull requests merged in 2020-01, with the labels that each got.

#11359 Forward-port #11356
  ethcore/verification/src/queue/kind.rs
  ethcore/verification/src/queue/mod.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11232 Encapsulate access to the client for secret store
  Cargo.lock
  Cargo.toml
  parity/lib.rs
  parity/secretstore/blockchain.rs
  parity/secretstore/mod.rs
  parity/secretstore/nodekeypair.rs
  parity/secretstore/server.rs
  secret-store/Cargo.toml
  secret-store/src/acl_storage.rs
  secret-store/src/blockchain.rs
  secret-store/src/key_server.rs
  secret-store/src/key_server_cluster/admin_sessions/servers_set_change_session.rs
  secret-store/src/key_server_cluster/admin_sessions/share_add_session.rs
  secret-store/src/key_server_cluster/cluster.rs
  secret-store/src/key_server_cluster/cluster_connections_net.rs
  secret-store/src/key_server_cluster/cluster_message_processor.rs
  secret-store/src/key_server_cluster/cluster_sessions.rs
  secret-store/src/key_server_cluster/connection_trigger.rs
  secret-store/src/key_server_cluster/connection_trigger_with_migration.rs
  secret-store/src/key_server_cluster/io/handshake.rs
  secret-store/src/key_server_cluster/mod.rs
  secret-store/src/key_server_cluster/net/accept_connection.rs
  secret-store/src/key_server_cluster/net/connect.rs
  secret-store/src/key_server_set.rs
  secret-store/src/lib.rs
  secret-store/src/listener/service_contract.rs
  secret-store/src/listener/service_contract_listener.rs
  secret-store/src/node_key_pair.rs
  secret-store/src/traits.rs
  secret-store/src/trusted_client.rs
  secret-store/src/types/all.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11346 Rip out the C and Java bindings
  .gitlab-ci.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  parity-clib/Cargo.toml
  parity-clib/Parity.java
  parity-clib/examples/cpp/CMakeLists.txt
  parity-clib/examples/cpp/main.cpp
  parity-clib/examples/java/Main.java
  parity-clib/examples/java/README.md
  parity-clib/examples/java/run.sh
  parity-clib/parity.h
  parity-clib/src/java.rs
  parity-clib/src/lib.rs
  scripts/gitlab/build-linux.sh
  scripts/gitlab/test-cpp.sh
Labels: A8-looksgood 🦄

#11292 Fix esoteric test config variable
  ethcore/res/ethereum/transition_test.json
Labels: A8-looksgood 🦄, M2-config 📂

#11378 fix cargo audit
  Cargo.lock
  util/fetch/Cargo.toml
Labels: A2-insubstantial 👶, M5-dependencies 🖇

#11311 [Trace] Distinguish between `create` and `create2`
  ethcore/engine/src/engine.rs
  ethcore/evm/src/interpreter/mod.rs
  ethcore/evm/src/lib.rs
  ethcore/executive-state/src/lib.rs
  ethcore/machine/src/executive.rs
  ethcore/machine/src/externalities.rs
  ethcore/machine/src/machine.rs
  ethcore/spec/src/spec.rs
  ethcore/src/json_tests/executive.rs
  ethcore/src/tests/evm.rs
  ethcore/trace/src/db.rs
  ethcore/trace/src/types/filter.rs
  ethcore/trace/src/types/flat.rs
  ethcore/trace/src/types/trace.rs
  ethcore/vm/src/action_params.rs
  ethcore/vm/src/action_type.rs
  ethcore/vm/src/ext.rs
  ethcore/vm/src/lib.rs
  ethcore/vm/src/tests.rs
  ethcore/wasm/src/runtime.rs
  evmbin/src/main.rs
  rpc/src/v1/tests/mocked/traces.rs
  rpc/src/v1/types/trace.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B1-patch-beta 🕷🕷, M4-core ⛓

#10928 Set the block gas limit to the value returned by a contract call
  Cargo.lock
  ethcore/block-gas-limit/Cargo.toml
  ethcore/block-gas-limit/res/block_gas_limit.json
  ethcore/block-gas-limit/src/lib.rs
  ethcore/engine/src/engine.rs
  ethcore/engines/authority-round/Cargo.toml
  ethcore/engines/authority-round/src/lib.rs
  ethcore/verification/src/verification.rs
  json/src/spec/authority_round.rs
Labels: A0-pleasereview 🤓, M2-config 📂, M4-core ⛓

#11379 authority_round: Fix next_step_time_duration.
  ethcore/engines/authority-round/src/lib.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#11347 Fix Aztlan hard fork issues
  ethcore/evm/src/interpreter/gasometer.rs
  ethcore/res/ethereum/classic.json
  ethcore/res/ethereum/kotti.json
  ethcore/res/ethereum/mordor.json
  ethcore/types/src/engines/params.rs
  ethcore/vm/src/schedule.rs
  json/src/spec/params.rs
Labels: A8-looksgood 🦄, M2-config 📂, M4-core ⛓

#11380 miner: fix deprecation warning `Error::description`
  miner/stratum/src/traits.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶

#11384 json-tests: Fix compile error
  ethcore/Cargo.toml
Labels: B0-patch-stable 🕷, B1-patch-beta 🕷🕷, F4-tests 💻

#11391 ethcore/res: fix ethereum classic chainspec blake2_f activation block…
  ethcore/res/ethereum/classic.json
Labels: A8-looksgood 🦄, M2-config 📂

#11377 Switching to stable-track
  .gitlab-ci.yml
  CHANGELOG.md
  docs/CHANGELOG-2.5.md
  docs/CHANGELOG-2.6.md
  parity/cli/mod.rs
  parity/configuration.rs
  rpc/src/v1/tests/helpers/update_service.rs
  rpc/src/v1/tests/mocked/parity.rs
  rpc/src/v1/tests/mocked/parity_set.rs
  rpc/src/v1/types/consensus_status.rs
  scripts/docker/hub/publish-docker.sh
  scripts/gitlab/publish-snap.sh
  scripts/gitlab/rust-changes.sh
  updater/src/types/release_track.rs
  updater/src/updater.rs
  util/version/Cargo.toml
  util/version/src/lib.rs
Labels: A0-pleasereview 🤓, M1-ci 🙉

#11404 engine error: remove faulty/unused `From`
  ethcore/types/src/errors/engine_error.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, M4-core ⛓

#11398 update classic testnet bootnodes
  ethcore/res/ethereum/kotti.json
  ethcore/res/ethereum/mordor.json
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, B7-releasenotes 📜

#11407 Update ProgPoW to 0.9.3
  ethash/res/progpow_testvectors.json
  ethash/src/progpow.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11400 verification: fix race same block + misc
  ethcore/light/src/client/mod.rs
  ethcore/src/client/client.rs
  ethcore/types/src/errors/ethcore_error.rs
  ethcore/verification/src/queue/kind.rs
  ethcore/verification/src/queue/mod.rs
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, M4-core ⛓

#11402 Support EtherCore
  ethcore/res/ethereum/ethercore.json
  ethcore/spec/src/chain.rs
  parity/cli/mod.rs
  parity/params.rs
Labels: A8-looksgood 🦄, M2-config 📂

#11411 Update enodes for poacore, poasokol, xdai, kovan
  ethcore/res/ethereum/kovan.json
  ethcore/res/ethereum/poacore.json
  ethcore/res/ethereum/poasokol.json
  ethcore/res/ethereum/xdai.json
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, M2-config 📂

#11408 AuthorityEngine: Minor cleanups.
  ethcore/engines/authority-round/src/lib.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11414 update hardcoded headers: mainnet and ropsten
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/ropsten.json
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, M2-config 📂

#11418 update hardcoded headers: mainnet and ropsten (#11414)
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/ropsten.json
Labels: A2-insubstantial 👶, A8-backport 🕸

#11416 fix: export hardcoded sync format
  Cargo.lock
  ethcore/spec/src/spec.rs
  ethcore/types/Cargo.toml
  ethcore/types/src/encoded.rs
  ethcore/types/src/header.rs
  ethcore/types/src/lib.rs
  ethcore/types/src/receipt.rs
  ethcore/types/src/transaction/transaction.rs
  ethcore/types/src/views/block.rs
  ethcore/types/src/views/body.rs
  ethcore/types/src/views/header.rs
  ethcore/types/src/views/transaction.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, M2-config 📂, M4-core ⛓

#11392 ethcore/res: remove morden testnet
  ethcore/engines/ethash/src/lib.rs
  ethcore/res/ethereum/morden.json
  ethcore/res/null_morden.json
  ethcore/res/null_morden_with_finality.json
  ethcore/res/null_morden_with_reward.json
  ethcore/spec/src/chain.rs
  ethcore/src/tests/client.rs
  ethcore/verification/src/verification.rs
  json/src/spec/spec.rs
  parity/account_utils.rs
  parity/cli/mod.rs
  parity/params.rs
Labels: A8-looksgood 🦄

#11427 Revert "[Trace] Distinguish between `create` and `create2` (#11311)"
  ethcore/engine/src/engine.rs
  ethcore/evm/src/interpreter/mod.rs
  ethcore/evm/src/lib.rs
  ethcore/executive-state/src/lib.rs
  ethcore/machine/src/executive.rs
  ethcore/machine/src/externalities.rs
  ethcore/machine/src/machine.rs
  ethcore/spec/src/spec.rs
  ethcore/src/json_tests/executive.rs
  ethcore/src/tests/evm.rs
  ethcore/trace/src/db.rs
  ethcore/trace/src/types/filter.rs
  ethcore/trace/src/types/flat.rs
  ethcore/trace/src/types/trace.rs
  ethcore/vm/src/action_params.rs
  ethcore/vm/src/call_type.rs
  ethcore/vm/src/ext.rs
  ethcore/vm/src/lib.rs
  ethcore/vm/src/tests.rs
  ethcore/wasm/src/runtime.rs
  evmbin/src/main.rs
  rpc/src/v1/tests/mocked/traces.rs
  rpc/src/v1/types/trace.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷

#11428 Update publish-docker.sh
  scripts/docker/hub/publish-docker.sh
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, M0-build 🏗

#11430 [release] v2.7.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  ethcore/engine/src/engine.rs
  ethcore/evm/src/interpreter/mod.rs
  ethcore/evm/src/lib.rs
  ethcore/executive-state/src/lib.rs
  ethcore/machine/src/executive.rs
  ethcore/machine/src/externalities.rs
  ethcore/machine/src/machine.rs
  ethcore/spec/src/spec.rs
  ethcore/src/json_tests/executive.rs
  ethcore/src/tests/evm.rs
  ethcore/trace/src/db.rs
  ethcore/trace/src/types/filter.rs
  ethcore/trace/src/types/flat.rs
  ethcore/trace/src/types/trace.rs
  ethcore/vm/src/action_params.rs
  ethcore/vm/src/call_type.rs
  ethcore/vm/src/ext.rs
  ethcore/vm/src/lib.rs
  ethcore/vm/src/tests.rs
  ethcore/wasm/src/runtime.rs
  evmbin/src/main.rs
  rpc/src/v1/tests/mocked/traces.rs
  rpc/src/v1/types/trace.rs
  scripts/docker/hub/publish-docker.sh
  util/version/Cargo.toml
Labels: A8-backport 🕸

#11433 goerli: replace foundation bootnode
  ethcore/res/ethereum/goerli.json
Labels: B0-patch-stable 🕷, M2-config 📂
