Repository openethereum/openethereum, pull requests merged in 2020-05, with the labels that each got.

#11682 Add deprecation warnings
  parity/run.rs
Labels: A0-pleasereview 🤓, B9-blocker 🚧

#11629 Implement Simple Subroutines for the EVM (EIP 2315)
  ethcore/evm/src/instructions.rs
  ethcore/evm/src/interpreter/mod.rs
  ethcore/evm/src/interpreter/shared_cache.rs
  ethcore/evm/src/tests.rs
  ethcore/machine/src/executive.rs
  ethcore/res/ethereum/test-specs/berlin_test.json
  ethcore/spec/src/spec.rs
  ethcore/trace/src/types/error.rs
  ethcore/types/src/engines/params.rs
  ethcore/vm/src/error.rs
  ethcore/vm/src/schedule.rs
  json/src/spec/params.rs
Labels: A6-mustntgrumble 💦, M4-core ⛓

#11711 authority-round: change sealing_state cannot sign log message to debug
  ethcore/engines/authority-round/src/lib.rs
Labels: A8-looksgood 🦄

#11716 Fix compile warnings, convert common-types to edition 2018
  accounts/ethstore/src/ethstore.rs
  ethcore/evm/src/interpreter/informant.rs
  ethcore/types/Cargo.toml
  ethcore/types/src/block.rs
  ethcore/types/src/blockchain_info.rs
  ethcore/types/src/encoded.rs
  ethcore/types/src/engines/params.rs
  ethcore/types/src/errors/block_error.rs
  ethcore/types/src/errors/ethcore_error.rs
  ethcore/types/src/errors/snapshot_error.rs
  ethcore/types/src/filter.rs
  ethcore/types/src/header.rs
  ethcore/types/src/ids.rs
  ethcore/types/src/lib.rs
  ethcore/types/src/log_entry.rs
  ethcore/types/src/receipt.rs
  ethcore/types/src/security_level.rs
  ethcore/types/src/state_diff.rs
  ethcore/types/src/trace_filter.rs
  ethcore/types/src/transaction/error.rs
  ethcore/types/src/transaction/transaction.rs
  ethcore/types/src/views/block.rs
  ethcore/types/src/views/body.rs
  ethcore/types/src/views/header.rs
  miner/src/service_transaction_checker.rs
Labels: A8-looksgood 🦄, F6-refactor 📚

#11715 Replace parity-snappy with snap
  Cargo.lock
  ethcore/snapshot/Cargo.toml
  ethcore/snapshot/snapshot-tests/Cargo.toml
  ethcore/snapshot/snapshot-tests/src/helpers.rs
  ethcore/snapshot/snapshot-tests/src/proof_of_work.rs
  ethcore/snapshot/snapshot-tests/src/state.rs
  ethcore/snapshot/src/lib.rs
  ethcore/snapshot/src/service.rs
  ethcore/types/Cargo.toml
  ethcore/types/src/errors/ethcore_error.rs
  ethcore/types/src/errors/snapshot_error.rs
  util/network-devp2p/Cargo.toml
  util/network-devp2p/src/session.rs
  util/network/Cargo.toml
  util/network/src/error.rs
  util/network/src/lib.rs
Labels: A8-looksgood 🦄, M4-io 💾

#11635 Add --sync-until=[NUM]
  ethcore/src/client/client.rs
  ethcore/src/client/config.rs
  parity/blockchain.rs
  parity/cli/mod.rs
  parity/cli/tests/config.toml
  parity/configuration.rs
  parity/helpers.rs
  parity/run.rs
  parity/snapshot_cmd.rs
Labels: A0-pleasereview 🤓

#11727 Fix compile warning
  ethcore/src/test_helpers/test_client.rs
Labels: A2-insubstantial 👶
