Repository openethereum/openethereum, pull requests merged in 2020-08, with the labels that each got.

#11827 Bump memory-db lib to 0.24.1 and add shrink_to_fit #11760
  Cargo.lock
  ethcore/account-state/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/src/client/client.rs
  util/journaldb/Cargo.toml
  util/journaldb/src/overlayrecentdb.rs
  util/patricia-trie-ethereum/Cargo.toml
Labels: A7-looksgoodtestsfail 🤖, M4-core ⛓

#11839 Update Ellaism Chainspec
  ethcore/res/ethereum/ellaism.json
Labels: A8-looksgood 🦄, M2-config 📂

#11850 cli usage update
  parity/cli/usage.rs
Labels: A8-looksgood 🦄, M4-core ⛓
