Repository openethereum/openethereum, pull requests merged in 2020-06, with the labels that each got.

#11747 Add missing forks to fork ID
  ethcore/spec/src/spec.rs
  ethcore/sync/src/chain/fork_filter.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11707 Implementation of EIP 2537
  Cargo.lock
  ethcore/builtin/Cargo.toml
  ethcore/builtin/src/lib.rs
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/test-specs/berlin_test.json
  ethcore/spec/src/chain.rs
  json/src/spec/builtin.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11761 Update secret-store reference
  Cargo.lock
Labels: A8-looksgood 🦄, M5-dependencies 🖇

#11636 Upgrade num to 0.2, use enum-primitive-derive
  Cargo.lock
  ethcore/builtin/Cargo.toml
  ethcore/sync/Cargo.toml
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/chain/supplier.rs
  ethcore/sync/src/chain/sync_packet.rs
Labels: A0-pleasereview 🤓

#11757 Add YOLO-1 testnet
  ethcore/res/ethereum/yolov1.json
  ethcore/spec/src/chain.rs
  parity/params.rs
Labels: A0-pleasereview 🤓

#11772 Use BigUint::modpow for ModExp precompile
  ethcore/builtin/src/lib.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11782 Trigger custom docker build when adding ci-build-docker to the commit
  .github/workflows/deploy-docker-custom-message.yml
Labels: A0-pleasereview 🤓, M1-ci 🙉

#11786 Feature/publish draft release ci
  .github/workflows/build.yml
Labels: A0-pleasereview 🤓, M1-ci 🙉

#11791 Update parity-crypto dependency
  Cargo.lock
  Cargo.toml
  accounts/Cargo.toml
  accounts/ethkey/Cargo.toml
  accounts/ethkey/cli/Cargo.toml
  accounts/ethstore/Cargo.toml
  accounts/ethstore/cli/Cargo.toml
  ethcore/Cargo.toml
  ethcore/blockchain/Cargo.toml
  ethcore/builtin/Cargo.toml
  ethcore/engine/Cargo.toml
  ethcore/engines/authority-round/Cargo.toml
  ethcore/engines/basic-authority/Cargo.toml
  ethcore/engines/clique/Cargo.toml
  ethcore/engines/validator-set/Cargo.toml
  ethcore/executive-state/Cargo.toml
  ethcore/machine/Cargo.toml
  ethcore/private-tx/Cargo.toml
  ethcore/snapshot/snapshot-tests/Cargo.toml
  ethcore/sync/Cargo.toml
  ethcore/types/Cargo.toml
  ethcore/verification/Cargo.toml
  ethcore/wasm/Cargo.toml
  miner/Cargo.toml
  miner/local-store/Cargo.toml
  rpc/Cargo.toml
  util/network-devp2p/Cargo.toml
  util/network/Cargo.toml
Labels: A8-looksgood 🦄, M5-dependencies 🖇

#11265 Issues during block sync
  Cargo.lock
  ethcore/client-traits/src/lib.rs
  ethcore/src/client/client.rs
  ethcore/src/test_helpers/test_client.rs
  ethcore/sync/Cargo.toml
  ethcore/sync/src/api.rs
  ethcore/sync/src/block_sync.rs
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/supplier.rs
  ethcore/verification/src/queue/mod.rs
Labels: A0-pleasereview 🤓, M4-core ⛓
