Repository openethereum/openethereum, pull requests merged in 2020-04, with the labels that each got.

#11592 Update version to v3.0.0-alpha.1
  Cargo.lock
  Cargo.toml
  util/version/Cargo.toml
Labels: A8-looksgood 🦄, F9-release 🎈

#11611 Update enodes for POA Sokol
  ethcore/res/ethereum/poasokol.json
Labels: A8-looksgood 🦄, M2-config 📂

#11606 Deduplicating crate dependencies (part 1 of n)
  Cargo.lock
  ethcore/machine/Cargo.toml
  ethcore/snapshot/Cargo.toml
  parity/logger/Cargo.toml
  util/dir/Cargo.toml
  util/io/Cargo.toml
  util/io/src/service_mio.rs
  util/io/src/service_non_mio.rs
  util/io/src/worker.rs
Labels: A8-looksgood 🦄, M5-dependencies 🖇

#11609 Activate on-chain randomness in POA Core and update bootnodes
  ethcore/res/ethereum/poacore.json
Labels: A8-looksgood 🦄, M2-config 📂

#11610 Activate POSDAO on xDai chain and update enodes
  ethcore/res/ethereum/xdai.json
Labels: A8-looksgood 🦄, M2-config 📂

#11613 Deduplicating crate dependencies (part 2 of n, `slab`)
  Cargo.lock
  util/io/Cargo.toml
  util/network-devp2p/Cargo.toml
  util/network-devp2p/src/host.rs
Labels: A8-looksgood 🦄, M5-dependencies 🖇

#11614 Deduplicating crate dependencies (part 3 of n)
  Cargo.lock
  Cargo.toml
  accounts/ethstore/Cargo.toml
  cli-signer/rpc-client/Cargo.toml
  ethcore/Cargo.toml
  ethcore/blockchain/Cargo.toml
  ethcore/engines/authority-round/Cargo.toml
  ethcore/engines/clique/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/private-tx/Cargo.toml
  ethcore/snapshot/Cargo.toml
  ethcore/snapshot/snapshot-tests/Cargo.toml
  ethcore/sync/Cargo.toml
  miner/Cargo.toml
  rpc/Cargo.toml
  rpc/src/v1/helpers/secretstore.rs
  rpc/src/v1/impls/pubsub.rs
  updater/Cargo.toml
  updater/hash-fetch/Cargo.toml
  util/fetch/Cargo.toml
  util/keccak-hasher/Cargo.toml
  util/keccak-hasher/src/lib.rs
  util/network-devp2p/Cargo.toml
  util/network-devp2p/src/connection.rs
Labels: A6-mustntgrumble 💦, M5-dependencies 🖇

#11617 deps: switch to upstream ctrlc
  Cargo.lock
  Cargo.toml
  parity/main.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, M5-dependencies 🖇

#11598 ethcore/res: activate ecip-1088 phoenix on classic
  ethcore/res/ethereum/classic.json
Labels: A0-pleasereview 🤓, M2-config 📂

#11628 Update .gitmodules
  .gitmodules
Labels: A2-insubstantial 👶

#11623 Fix ecrecover builtin
  Cargo.lock
  Cargo.toml
  accounts/Cargo.toml
  accounts/ethkey/Cargo.toml
  accounts/ethkey/cli/Cargo.toml
  accounts/ethstore/Cargo.toml
  accounts/ethstore/cli/Cargo.toml
  ethcore/Cargo.toml
  ethcore/blockchain/Cargo.toml
  ethcore/builtin/Cargo.toml
  ethcore/builtin/src/lib.rs
  ethcore/engine/Cargo.toml
  ethcore/engines/authority-round/Cargo.toml
  ethcore/engines/basic-authority/Cargo.toml
  ethcore/engines/clique/Cargo.toml
  ethcore/engines/validator-set/Cargo.toml
  ethcore/executive-state/Cargo.toml
  ethcore/machine/Cargo.toml
  ethcore/private-tx/Cargo.toml
  ethcore/snapshot/snapshot-tests/Cargo.toml
  ethcore/sync/Cargo.toml
  ethcore/types/Cargo.toml
  ethcore/verification/Cargo.toml
  miner/Cargo.toml
  miner/local-store/Cargo.toml
  rpc/Cargo.toml
  util/network-devp2p/Cargo.toml
  util/network/Cargo.toml
Labels: A8-looksgood 🦄, M4-core ⛓

#11625 validate mainnet specs against all forks
  ethcore/machine/src/test_helpers.rs
  ethcore/res/ethereum/test-specs/berlin_test.json
  ethcore/res/ethereum/test-specs/byzantium_test.json
  ethcore/res/ethereum/test-specs/constantinople_test.json
  ethcore/res/ethereum/test-specs/eip150_test.json
  ethcore/res/ethereum/test-specs/eip161_test.json
  ethcore/res/ethereum/test-specs/eip210_test.json
  ethcore/res/ethereum/test-specs/frontier_like_test.json
  ethcore/res/ethereum/test-specs/frontier_test.json
  ethcore/res/ethereum/test-specs/homestead_test.json
  ethcore/res/ethereum/test-specs/istanbul_test.json
  ethcore/res/ethereum/test-specs/kovan_wasm_test.json
  ethcore/res/ethereum/test-specs/mcip3_test.json
  ethcore/res/ethereum/test-specs/st_peters_test.json
  ethcore/res/ethereum/test-specs/transition_test.json
  ethcore/spec/src/chain.rs
  scripts/actions/validate-chainspecs.sh
Labels: A8-looksgood 🦄

#11627 Add support for non-fork side of Phoenix
  ethcore/res/ethereum/classic_no_phoenix.json
  ethcore/spec/src/chain.rs
  parity/cli/mod.rs
  parity/params.rs
Labels: A8-looksgood 🦄, M2-config 📂

#11632 Fix some compiler warnings
  ethcore/sync/src/blocks.rs
  rpc/src/v1/helpers/dispatch/light.rs
  util/network-devp2p/src/host.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#11589 Remove accounts bloom
  Cargo.lock
  ethcore/account-state/src/backend.rs
  ethcore/account-state/src/state.rs
  ethcore/db/src/db.rs
  ethcore/snapshot/Cargo.toml
  ethcore/snapshot/src/lib.rs
  ethcore/spec/src/spec.rs
  ethcore/state-db/Cargo.toml
  ethcore/state-db/src/lib.rs
  parity/db/rocksdb/migration.rs
  parity/db/rocksdb/mod.rs
  util/bloom/Cargo.toml
  util/bloom/src/lib.rs
  util/migration-rocksdb/src/lib.rs
Labels: A8-looksgood 🦄

#11644 Remove Parity bootnodes
  ethcore/res/ethereum/foundation.json
  ethcore/res/ethereum/ropsten.json
Labels: A8-looksgood 🦄

#11650 add openethereum supplementary bootnodes
  ethcore/res/ethereum/foundation.json
Labels: A2-insubstantial 👶, B9-blocker 🚧

#11482 Update EWF's chains with Istanbul transition block numbers
  ethcore/res/ethereum/ewc.json
  ethcore/res/ethereum/volta.json
Labels: A8-looksgood 🦄, M2-config 📂

#11641 New default paths
  accounts/ethstore/cli/src/main.rs
  util/dir/src/lib.rs
Labels: A6-mustntgrumble 💦, B9-blocker 🚧

#11651 Add git binary to first docker stage for generating proper log headers
  scripts/docker/alpine/Dockerfile
Labels: A0-pleasereview 🤓

#11654 Drain the transaction overlay
  ethcore/snapshot/src/lib.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#11657 rename inject to drain_transaction_overlay
  ethcore/snapshot/src/lib.rs
  util/journaldb/src/archivedb.rs
  util/journaldb/src/earlymergedb.rs
  util/journaldb/src/lib.rs
  util/journaldb/src/overlayrecentdb.rs
  util/journaldb/src/refcounteddb.rs
Labels: A7-looksgoodcantmerge 🙄

#11662 Don't delete old db after migration
  parity/db/rocksdb/migration.rs
  util/migration-rocksdb/src/lib.rs
  util/migration-rocksdb/tests/tests.rs
Labels: A0-pleasereview 🤓, F2-bug 🐞, M4-core ⛓
