Repository openethereum/openethereum, pull requests merged in 2020-02, with the labels that each got.

#11441 Remove dead bootnodes, add new geth bootnodes
  ethcore/res/ethereum/foundation.json
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, B0-patch-stable 🕷, B7-releasenotes 📜, F5-task 🎬, M2-config 📂

#11423 ethjson: impl Copy for hash type wrapper
  json/src/hash.rs
Labels: A2-insubstantial 👶, M2-config 📂, M4-core ⛓

#11396 Rough architecture diagram.
  docs/architecture-draft.png
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, M3-docs 📑

#11442 update kvdb-rocksdb to 0.4
  Cargo.lock
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/account-db/Cargo.toml
  ethcore/account-state/Cargo.toml
  ethcore/blockchain/Cargo.toml
  ethcore/client-traits/Cargo.toml
  ethcore/db/Cargo.toml
  ethcore/engines/validator-set/Cargo.toml
  ethcore/executive-state/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/node-filter/Cargo.toml
  ethcore/pod/Cargo.toml
  ethcore/private-tx/Cargo.toml
  ethcore/service/Cargo.toml
  ethcore/snapshot/Cargo.toml
  ethcore/snapshot/snapshot-tests/Cargo.toml
  ethcore/spec/Cargo.toml
  ethcore/state-db/Cargo.toml
  ethcore/sync/Cargo.toml
  ethcore/trace/Cargo.toml
  miner/local-store/Cargo.toml
  secret-store/Cargo.toml
  util/journaldb/Cargo.toml
  util/migration-rocksdb/Cargo.toml
Labels: A2-insubstantial 👶, M5-dependencies 🖇

#11432 chore: remove unused dependencies
  Cargo.lock
  ethcore/account-state/Cargo.toml
  ethcore/builtin/Cargo.toml
  ethcore/engines/validator-set/src/contract.rs
  ethcore/sync/src/light_sync/sync_round.rs
  ipfs/Cargo.toml
  util/EIP-152/Cargo.toml
Labels: A2-insubstantial 👶, M4-core ⛓

#11446 rlp_derive: cleanup
  Cargo.lock
  util/rlp-derive/Cargo.toml
  util/rlp-derive/src/de.rs
  util/rlp-derive/src/en.rs
  util/rlp-derive/src/lib.rs
  util/rlp-derive/tests/rlp.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄, B0-patch-stable 🕷, M5-dependencies 🖇

#11447 Cargo.lock: cargo update -p kvdb-rocksdb
  Cargo.lock
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, M5-dependencies 🖇

#11448 Cargo.lock: new lockfile format
  Cargo.lock
Labels: A2-insubstantial 👶, B0-patch-stable 🕷

#11451 Avoid copies
  util/journaldb/src/overlayrecentdb.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶

#11453 gcc to clang
  .gitlab-ci.yml
  scripts/gitlab/test-linux.sh
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, M1-ci 🙉

#11450 backwards compatible call_type creation_method
  ethcore/engine/src/engine.rs
  ethcore/evm/src/interpreter/mod.rs
  ethcore/evm/src/lib.rs
  ethcore/executive-state/src/lib.rs
  ethcore/machine/src/executive.rs
  ethcore/machine/src/externalities.rs
  ethcore/machine/src/machine.rs
  ethcore/spec/src/spec.rs
  ethcore/src/json_tests/executive.rs
  ethcore/src/tests/evm.rs
  ethcore/trace/src/db.rs
  ethcore/trace/src/types/filter.rs
  ethcore/trace/src/types/flat.rs
  ethcore/trace/src/types/trace.rs
  ethcore/vm/src/action_params.rs
  ethcore/vm/src/action_type.rs
  ethcore/vm/src/ext.rs
  ethcore/vm/src/lib.rs
  ethcore/vm/src/tests.rs
  ethcore/wasm/src/runtime.rs
  evmbin/src/main.rs
  rpc/src/v1/tests/mocked/traces.rs
  rpc/src/v1/types/trace.rs
  util/rlp-derive/src/de.rs
  util/rlp-derive/src/en.rs
  util/rlp-derive/src/lib.rs
  util/rlp-derive/tests/rlp.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, M4-core ⛓

#11455 remove incorrect but harmless rlp encoding for `CallType`
  ethcore/trace/src/types/trace.rs
Labels: A2-insubstantial 👶

#11458 [stable 2.7.2]: fix ETC stall
  ethcore/res/ethereum/classic.json
Labels: A8-backport 🕸

#11459 [eth classic chainspec]: remove `balance = 1` in builtin blake2_f
  ethcore/res/ethereum/classic.json
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷

#11456 Implement EIP-2124
  Cargo.lock
  Cargo.toml
  util/EIP-2124/Cargo.toml
  util/EIP-2124/src/lib.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11460 update CHANGELOG.md
  CHANGELOG.md
Labels: A2-insubstantial 👶, M3-docs 📑

#11462 update Dockerfile (#11461)
  scripts/docker/hub/Dockerfile
Labels: A8-backport 🕸

#11463 Update simple one-line installer due to switching to a single stable release track
  README.md
Labels: A8-looksgood 🦄, M3-docs 📑

#11465 Some more release track changes to README.md
  README.md
Labels: A8-looksgood 🦄, M3-docs 📑

#11466 Cleanup some code in Aura
  ethcore/engines/authority-round/src/lib.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, M4-core ⛓

#11473 sync: remove broken eth_protocol_version method
  ethcore/sync/src/sync_io.rs
  ethcore/sync/src/tests/helpers.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#11476 weak_counts has been stabilized
  parity/run.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11480 Switch from the internal runtime lib to external one from crates.io
  Cargo.lock
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/sync/Cargo.toml
  miner/Cargo.toml
  miner/price-info/Cargo.toml
  rpc/Cargo.toml
  secret-store/Cargo.toml
  updater/hash-fetch/Cargo.toml
  util/runtime/Cargo.toml
  util/runtime/src/lib.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#11489 update to published rlp-derive
  Cargo.lock
  ethcore/blockchain/Cargo.toml
  ethcore/db/Cargo.toml
  ethcore/light/Cargo.toml
  ethcore/private-tx/Cargo.toml
  ethcore/snapshot/Cargo.toml
  ethcore/trace/Cargo.toml
  ethcore/types/Cargo.toml
  util/EIP-2124/Cargo.toml
  util/rlp-derive/Cargo.toml
  util/rlp-derive/src/de.rs
  util/rlp-derive/src/en.rs
  util/rlp-derive/src/lib.rs
  util/rlp-derive/tests/rlp.rs
Labels: A2-insubstantial 👶, M5-dependencies 🖇

#11490 cargo update -p cmake
  Cargo.lock
Labels: A2-insubstantial 👶, M5-dependencies 🖇

#11475 Include the seal when populating the header for a new block
  ethcore/engines/authority-round/src/lib.rs
  ethcore/src/block.rs
  parity/run.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11491 complete null-signatures removal
  ethcore/machine/src/executive.rs
  ethcore/machine/src/externalities.rs
  ethcore/machine/src/machine.rs
  ethcore/types/src/transaction/transaction.rs
  ethcore/verification/src/verification.rs
  ethcore/vm/src/schedule.rs
Labels: A2-insubstantial 👶, M4-core ⛓

#11495 [verification]: make test-build compile standalone
  ethcore/verification/Cargo.toml
Labels: A2-insubstantial 👶, M4-core ⛓

#11496 [ci benches]: use `all-features`
  .gitlab-ci.yml
  Cargo.toml
  ethcore/verification/benches/verification.rs
  parity/lib.rs
Labels: A2-insubstantial 👶, M1-ci 🙉

#11499 OpenEthereum bootnodes are added
  ethcore/res/ethereum/foundation.json
Labels: A8-looksgood 🦄, B0-patch-stable 🕷, M2-config 📂

#11472 Implement eth/64 (EIP-2364) and drop support for eth/62
  Cargo.lock
  Cargo.toml
  ethcore/spec/Cargo.toml
  ethcore/spec/src/spec.rs
  ethcore/sync/Cargo.toml
  ethcore/sync/src/api.rs
  ethcore/sync/src/chain/fork_filter.rs
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/propagator.rs
  ethcore/sync/src/tests/helpers.rs
  parity/modules.rs
  parity/run.rs
  rpc/src/v1/tests/helpers/sync_provider.rs
  rpc/src/v1/tests/mocked/eth.rs
  rpc/src/v1/tests/mocked/parity.rs
  util/EIP-2124/Cargo.toml
  util/EIP-2124/src/lib.rs
Labels: A7-looksgoodcantmerge 🙄, A9-buythatmanabeer 🍻, M4-core ⛓

#11504 Grab bag of cleanup
  ethcore/db/src/cache_manager.rs
  ethcore/executive-state/src/lib.rs
  ethcore/src/test_helpers/evm_test_client.rs
  ethcore/trace/src/config.rs
  ethcore/trace/src/db.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#11505 Activate on-chain randomness in POA Sokol
  ethcore/res/ethereum/poasokol.json
Labels: A8-looksgood 🦄, M2-config 📂

#11506 [dependencies]: unify `rustc-hex`
  Cargo.lock
  Cargo.toml
  accounts/ethkey/cli/Cargo.toml
  accounts/ethkey/cli/src/main.rs
  accounts/ethstore/Cargo.toml
  accounts/ethstore/cli/Cargo.toml
  accounts/ethstore/src/json/bytes.rs
  accounts/ethstore/src/json/hash.rs
  accounts/ethstore/src/json/id.rs
  ethash/Cargo.toml
  ethash/benches/progpow.rs
  ethash/src/lib.rs
  ethash/src/progpow.rs
  ethcore/blockchain/Cargo.toml
  ethcore/engines/validator-set/Cargo.toml
  ethcore/evm/Cargo.toml
  ethcore/evm/benches/basic.rs
  ethcore/evm/src/interpreter/mod.rs
  ethcore/evm/src/interpreter/shared_cache.rs
  ethcore/evm/src/lib.rs
  ethcore/executive-state/Cargo.toml
  ethcore/executive-state/src/lib.rs
  ethcore/machine/Cargo.toml
  ethcore/machine/src/executive.rs
  ethcore/machine/src/machine.rs
  ethcore/pod/Cargo.toml
  ethcore/pod/src/account.rs
  ethcore/private-tx/Cargo.toml
  ethcore/private-tx/tests/private_contract.rs
  ethcore/sync/Cargo.toml
  ethcore/wasm/run/Cargo.toml
  ethcore/wasm/run/src/runner.rs
  evmbin/Cargo.toml
  evmbin/benches/mod.rs
  json/Cargo.toml
  miner/Cargo.toml
  rpc/Cargo.toml
  rpc/src/v1/helpers/errors.rs
  rpc/src/v1/tests/mocked/eth.rs
  rpc/src/v1/tests/mocked/parity_set.rs
  rpc/src/v1/tests/mocked/personal.rs
  rpc/src/v1/tests/mocked/signing.rs
  rpc/src/v1/tests/mocked/signing_unsafe.rs
  rpc/src/v1/types/bytes.rs
  rpc/src/v1/types/call_request.rs
  rpc/src/v1/types/transaction_request.rs
  updater/hash-fetch/Cargo.toml
  updater/hash-fetch/src/client.rs
  updater/hash-fetch/src/urlhint.rs
  util/network-devp2p/Cargo.toml
  util/network-devp2p/src/discovery.rs
  util/network-devp2p/src/handshake.rs
Labels: A7-looksgoodtestsfail 🤖, M4-core ⛓, M5-dependencies 🖇

#11510 Misc fixes
  ethcore/account-state/src/state.rs
  ethcore/engines/authority-round/src/lib.rs
  ethcore/pod/src/account.rs
  ethcore/src/block.rs
  ethcore/src/client/client.rs
  ethcore/src/client/config.rs
  ethcore/src/miner/miner.rs
  ethcore/src/test_helpers/mod.rs
  ethcore/src/tests/trace.rs
  parity/cache.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶

#11509 Add benchmark for transaction execution
  Cargo.lock
  ethcore/executive-state/Cargo.toml
  ethcore/executive-state/benches/8481475.rlp
  ethcore/executive-state/benches/9532543.rlp
  ethcore/executive-state/benches/execution.rs
Labels: A8-looksgood 🦄

#11507 [ethcore cleanup]: various unrelated fixes from `#11493`
  ethcore/engines/authority-round/src/lib.rs
  ethcore/engines/basic-authority/src/lib.rs
  ethcore/engines/clique/src/block_state.rs
  ethcore/engines/clique/src/lib.rs
  ethcore/engines/ethash/src/lib.rs
  ethcore/engines/validator-set/src/safe_contract.rs
  ethcore/src/block.rs
  ethcore/src/client/client.rs
  ethcore/src/miner/miner.rs
  ethcore/sync/src/block_sync.rs
  ethcore/types/src/engines/mod.rs
  ethcore/verification/src/verification.rs
Labels: A7-looksgoodcantmerge 🙄

#11522 fix compilation warnings
  ethcore/src/lib.rs
  miner/using-queue/src/lib.rs
  util/bloom/src/lib.rs
  util/len-caching-lock/Cargo.toml
  util/len-caching-lock/src/lib.rs
  util/len-caching-lock/src/mutex.rs
  util/len-caching-lock/src/rwlock.rs
  util/rlp-compress/src/common.rs
  util/stats/src/lib.rs
Labels: A2-insubstantial 👶

#11524 [EngineSigner]: don't sign message with only zeroes
  parity/account_utils.rs
  rpc/src/v1/helpers/engine_signer.rs
Labels: A0-pleasereview 🤓, B0-patch-stable 🕷, M4-core ⛓

#11514 Faster kill_garbage
  ethcore/account-state/src/state.rs
  ethcore/executive-state/src/lib.rs
  ethcore/machine/src/executive.rs
  ethcore/src/test_helpers/evm_test_client.rs
Labels: A0-pleasereview 🤓

#11530 chain-supplier: fix warning reporting for GetNodeData request
  ethcore/sync/src/chain/supplier.rs
Labels: A2-insubstantial 👶

#11532 Drop IPFS support
  Cargo.lock
  Cargo.toml
  README.md
  ipfs/Cargo.toml
  ipfs/src/error.rs
  ipfs/src/lib.rs
  ipfs/src/route.rs
  parity/cli/mod.rs
  parity/cli/presets/config.dev-insecure.toml
  parity/cli/presets/config.insecure.toml
  parity/cli/tests/config.full.toml
  parity/cli/tests/config.toml
  parity/configuration.rs
  parity/ipfs.rs
  parity/lib.rs
  parity/run.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  rpc/src/v1/helpers/ipfs.rs
  rpc/src/v1/helpers/mod.rs
  rpc/src/v1/impls/light/parity.rs
  rpc/src/v1/impls/parity.rs
  rpc/src/v1/tests/mocked/parity.rs
  rpc/src/v1/traits/parity.rs
  scripts/doc.sh
  scripts/docker/README.md
  scripts/docker/centos/Dockerfile
  scripts/hook.sh
Labels: A8-looksgood 🦄, B7-releasenotes 📜
