Repository openethereum/openethereum, pull requests merged in 2020-03, with the labels that each got.

#11525 Remove references to parity-ethereum
  .cargo/config
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  CHANGELOG.md
  README.md
  accounts/ethkey/README.md
  accounts/ethstore/README.md
  docs/CHANGELOG-1.11.md
  docs/CHANGELOG-2.0.md
  docs/CHANGELOG-2.1.md
  docs/CHANGELOG-2.2.md
  docs/CHANGELOG-2.3.md
  docs/CHANGELOG-2.4.md
  docs/CHANGELOG-2.5.md
  docs/CHANGELOG-2.6.md
  ethash/src/lib.rs
  ethcore/engines/clique/src/lib.rs
  ethcore/light/src/net/mod.rs
  ethcore/light/src/net/request_credits.rs
  ethcore/light/src/types/request/mod.rs
  ethcore/res/ethereum/tests-issues/currents.json
  ethcore/src/block.rs
  ethcore/src/json_tests/chain.rs
  ethcore/src/json_tests/state.rs
  ethcore/src/json_tests/test_common.rs
  ethcore/src/miner/miner.rs
  ethcore/src/test_helpers/evm_test_client.rs
  ethcore/sync/src/snapshot_sync.rs
  ethcore/types/src/blockchain_info.rs
  evmbin/README.md
  parity/account.rs
  parity/lib.rs
  rpc/src/v1/helpers/subscribers.rs
  rpc/src/v1/impls/net.rs
  scripts/docker/README.md
  scripts/docker/hub/Dockerfile
  scripts/gitlab/test-linux.sh
  util/EIP-152/Cargo.toml
  util/EIP-712/Cargo.toml
  util/network-devp2p/src/node_table.rs
  util/panic-hook/src/lib.rs
Labels: A3-inprogress ⏳, B0-patch-stable 🕷, M3-docs 📑

#11534 [journaldb]: remove manual clones
  util/journaldb/src/archivedb.rs
  util/journaldb/src/earlymergedb.rs
  util/journaldb/src/overlayrecentdb.rs
  util/journaldb/src/refcounteddb.rs
Labels: A2-insubstantial 👶, M4-core ⛓

#11533 Remove AuxiliaryData/AuxiliaryRequest
  ethcore/engine/src/engine.rs
  ethcore/engines/authority-round/src/lib.rs
  ethcore/engines/basic-authority/src/lib.rs
  ethcore/engines/validator-set/src/contract.rs
  ethcore/engines/validator-set/src/lib.rs
  ethcore/engines/validator-set/src/multi.rs
  ethcore/engines/validator-set/src/safe_contract.rs
  ethcore/engines/validator-set/src/simple_list.rs
  ethcore/engines/validator-set/src/test.rs
  ethcore/light/src/client/mod.rs
  ethcore/src/client/client.rs
  ethcore/types/src/engines/machine.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11528 Github Actions
  .github/workflows/audit.yml
  .github/workflows/build-test.yml
  .github/workflows/build.yml
  .github/workflows/check.yml
  scripts/actions/build-linux.sh
  scripts/actions/build-windows.sh
  scripts/actions/clean-target.sh
  scripts/actions/install-sccache.ps1
  scripts/actions/validate-chainspecs.sh
Labels: A0-pleasereview 🤓, M0-build 🏗, M1-ci 🙉

#11531 Less cloning when importing blocks
  ethcore/blockchain/src/blockchain.rs
  ethcore/engines/authority-round/src/lib.rs
  ethcore/engines/clique/src/lib.rs
  ethcore/engines/clique/src/tests.rs
  ethcore/src/block.rs
  ethcore/src/client/client.rs
  ethcore/src/test_helpers/mod.rs
  ethcore/src/tests/trace.rs
  ethcore/state-db/src/lib.rs
  ethcore/types/src/chain_notify.rs
  ethcore/types/src/client_types.rs
  util/journaldb/src/overlayrecentdb.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11546 ethcore: cleanup after #11531
  ethcore/src/client/client.rs
  ethcore/types/src/block.rs
  ethcore/verification/benches/verification.rs
  ethcore/verification/src/queue/kind.rs
  ethcore/verification/src/verification.rs
Labels: A0-pleasereview 🤓, A2-insubstantial 👶

#11550 ethcore_spec: warn if genesis constructor revert
  ethcore/spec/src/spec.rs
Labels: A8-looksgood 🦄

#11552 Code cleanup in the sync module
  ethcore/client-traits/src/lib.rs
  ethcore/src/client/client.rs
  ethcore/sync/src/block_sync.rs
  ethcore/sync/src/blocks.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#11547 [devp2p discovery]: cleanup
  util/network-devp2p/src/discovery.rs
  util/network-devp2p/src/host.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#11561 [secretstore]: don't sign secp256k1 message with only zeroes
  parity/secretstore/server.rs
Labels: A2-insubstantial 👶

#11556 Misc docs and renames …and one less clone
  ethcore/engine/src/engine.rs
  ethcore/machine/src/machine.rs
  ethcore/src/client/client.rs
  ethcore/src/test_helpers/test_client.rs
  ethcore/sync/src/chain/handler.rs
  ethcore/sync/src/chain/mod.rs
  ethcore/sync/src/chain/requester.rs
  ethcore/sync/src/chain/supplier.rs
  ethcore/types/src/io_message.rs
Labels: A2-insubstantial 👶, A8-looksgood 🦄

#11529 ethcore/res: enable ecip-1088 phoenix upgrade for kotti and mordor testnets
  ethcore/res/ethereum/kotti.json
  ethcore/res/ethereum/mordor.json
Labels: A0-pleasereview 🤓, M2-config 📂

#11570 [secretstore] create db_version file when database doesn't exist
  parity/secretstore/server.rs
Labels: A8-looksgood 🦄

#11564 [devp2p discovery]: remove `deprecated_echo_hash`
  util/network-devp2p/src/discovery.rs
Labels: A8-looksgood 🦄, M4-core ⛓

#11523 informant: display I/O stats
  Cargo.lock
  Cargo.toml
  ethcore/Cargo.toml
  ethcore/service/Cargo.toml
  ethcore/snapshot/Cargo.toml
  ethcore/snapshot/snapshot-tests/Cargo.toml
  ethcore/src/client/client.rs
  ethcore/types/src/client_types.rs
  ethcore/verification/src/queue/mod.rs
  parity/informant.rs
  util/journaldb/src/archivedb.rs
  util/journaldb/src/earlymergedb.rs
  util/journaldb/src/lib.rs
  util/journaldb/src/overlayrecentdb.rs
  util/journaldb/src/refcounteddb.rs
  util/migration-rocksdb/Cargo.toml
Labels: A0-pleasereview 🤓, M4-core ⛓

#11558 Increase the default pruning parameters
  ethcore/snapshot/src/watcher.rs
  ethcore/src/client/client.rs
  ethcore/src/client/config.rs
  parity/cli/mod.rs
  parity/configuration.rs
Labels: A0-pleasereview 🤓

#11568 ci: workaround for the cache bug on Linux
  .github/workflows/build-test.yml
  .github/workflows/build.yml
  .github/workflows/check.yml
Labels: A0-pleasereview 🤓, M1-ci 🙉

#11590 Github actions `on push tags` updated
  .github/workflows/build.yml
  .github/workflows/deploy-docker.yml
Labels: A8-looksgood 🦄, M0-build 🏗

#11584 ethcore/res: bump canon fork hash for mordor and kotti testnets
  ethcore/res/ethereum/kotti.json
  ethcore/res/ethereum/mordor.json
Labels: A8-looksgood 🦄, M2-config 📂
